src/content/guides/asset-management.md

In the Getting Started section **<script src="main.js"></script>** is written but in asset-management src is replaced with relative path which can be misleading/confusing for beginners. As both the relative path and filename will work fine, it is better to have it same across the documentation.

Removed the relative path of bundle and main

---

src/content/api/compilation-hooks.md

https://github.com/webpack/webpack/blob/v5.0.0-alpha.11/lib/Compilation.js#L152
```
"Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader"
```

normalModuleLoader will not be removed but moved

---

src/content/index.md

misc(phrasing) drop "its that simple" from homepage

---

src/components/Gitter/Gitter.scss

Gitter spacing on right was off, fixed it to stay aligned to content on mobile as well

misc(style) fix gitter right position for mobile breakpoint

---

src/content/concepts/loaders.mdx

Reading up on loaders, I noticed a broken link toward the bottom of https://webpack.js.org/concepts#loaders to an old "How to write a loader?" article. I think https://webpack.js.org/contribute/writing-a-loader is the most up to date doc on this. Updated href and link name.

Update link to new Write a Loader doc

---

src/server.jsx
webpack.prod.js

As pointed on twitter when doing `save to home screen` with our website, icon wasn't visible. This attempts to fix it

feat(icons) add tocuh icons for saving docs to homescreens, tune SW

---

src/server.jsx

- Fixes canonical from being relative

fix(seo) canonical mustn't be relative

---

README.md

Added Gitter chat img shield in README.md.
[![chat on gitter][chat]][chat-url]
[chat]: https://badges.gitter.im/webpack/webpack.svg
[chat-url]: https://gitter.im/webpack/webpack

feat(docs): adds Gitter chat in README.md

---

src/content/guides/code-splitting.md

Fix typo in code splitting documentation

---

src/components/Support/Support.jsx
src/utilities/fetch-supporters.js

- fetch supporters with Open Collective GraphQL API
- likely more reliable and future proof, ESLint and Babel recently migrated to it for similar case: 
- https://github.com/eslint/eslint.github.io/pull/564
- https://github.com/babel/website/pull/2031
- refactor path computation with `absoluteFilename`
- stop relying on `id` as it's not exposed anymore
- order supporters by totalDonations, pretty JSON format for easy troubleshooting
Expected behavior changes:
- the data is not computed the same, so it can be there is small differences with the current data. before merging we need to assess if the result is what's expected
- backers without an avatar get a default one with their initials
Todo:

Fetch supporters with Open Collective GraphQL API

---

src/content/plugins/split-chunks-plugin.md

`priority` option should belong to `cacheGroups.{cacheGroup}`, should not belong to `cacheGroups`

fix(plugins): Fix SplitChunksPlugin cacheGroup priority option

---

src/content/api/loaders.md

This adds documentation for the `mode` property of the loader context (included in the [4.32.0 release](https://github.com/webpack/webpack/releases/tag/v4.32.0)).
See webpack/webpack#9140.

Document the mode property in the loader context

---

src/content/configuration/node.md

Follow up for https://github.com/webpack/webpack.js.org/pull/1317.

docs(config/node): add `boolean` to the type

---

src/content/configuration/node.md

- only false is allowed via schema, clarifying it here.
ref: https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L2005

docs(config) node config boolean only false allowed

---

src/content/guides/build-performance.md

Since webpack v4, the CommonsChunkPlugin was removed in favor of optimization.splitChunks

Update reference to SplitChunksPlugin

---

src/content/guides/caching.md

https://github.com/johnagan/clean-webpack-plugin
It takes an options object. It looks like it cleans `dist` by default.

[DOCUMENTATION] update options argument: CleanWebpackPlugin

---

src/content/configuration/dev-server.md

Issue: https://github.com/webpack/webpack.js.org/issues/3095
- Added docs for `sockHost` option
- Fixed `sockPort` docs to specify that it is specific to connected clients of the `devServer`

docs(dev-server): document sockHost, change sockPort docs

---

src/content/guides/caching.md

There is an error in the punctuation of the following compound/complex sentence:
`This allows sites to load faster with less unnecessary network traffic, however it can also cause headaches when you need new code to be picked up.` I propose the grammar changes in `caching.md`. The following sentence would also be correct. 
`This allows sites to load faster with less unnecessary network traffic; however, it can also cause headaches when you need new code to be picked up.`
Edited for accuracy.

fix(guides): Update caching.md

---

src/content/configuration/index.mdx

Grammar: 'an extensions' -> 'an extension'

Updated index.mdx

---

src/content/guides/caching.md

1. use `new CleanWebpackPlugin()` instead of `new CleanWebpackPlugin(['dist'])`
2. use `hash` instead of `contenthash `

fix errors in caching.md

---

src/content/plugins/split-chunks-plugin.md

This is a small update to the docs for the SplitChunksPlugin's name option. I found using this function to be really esoteric, and would love to clarify even more than I have here. The problem with that is that the `module` and `chunks` arguments provided are esoteric themselves, meaning that documenting the arguments would likely lead to more confusion than help.
The docs I'm sending helped me accomplish my goal with the function, and have helped [other people][3] who are confused as well. I believe it to be sufficient for most use cases for this function.
Quick edit: also takes part of #3116. I also just signed the CLA so that should be all set now.
[3]: …

docs(plugins): clarify function provided to splitChunks.name

---

src/content/contribute/index.md

docs(contribute) fix broken link

---

src/content/plugins/split-chunks-plugin.md

docs(plugins) improve splitChunks name function doc

---

src/components/Markdown/Markdown.scss

It has been reported on twitter that headings are invisible for mobile resolutions when heading is long enough.
We can break words for such headings. It looks like this now:
Or we can allow horizontal scroll for such headings so that user can scroll them (as we do for code blocks):

ui(mobile) fix headings being cut off screen

---

src/content/configuration/target.md

This PR adds the `electron-preload` target option to the configuration/target page.
See https://github.com/webpack/webpack/pull/9188

docs(configuration): add electron-preload as available target

---

src/content/guides/code-splitting.md

Added link to bundle-stats.
Webpack plugin source - https://github.com/bundle-stats/bundle-stats/blob/master/packages/bundle-stats/src/webpack-plugin.js

docs(guides): add bundle-stats link to code-splitting

---

src/content/guides/development.md

In ["Development" guide](https://webpack.js.org/guides/development/#using-source-maps):
**Was**: "...JavaScript offers source maps, which _maps_ compiled code back to..."
**Now**: "...JavaScript offers source maps, which _map_ compiled code back to..."

docs(guides): correct verb (3rd person singular -> plural)

---

src/content/configuration/index.mdx

Fixes a typo that I came across while reading docs for plugin configuration.

Fix typo "promted" -> "prompted"

---

src/content/plugins/module-concatenation-plugin.md

I ran across a case where I wanted to disable the default `concatenateModules: true` in production mode, read these docs and came to the conclusion there wasn't an available option. Maybe it's obvious in retrospect, but figured it might be helpful for someone else to find the reference in the  module-concatenation-plugin docs here.

docs(plugins): Refer to optimization configuration

---

src/content/concepts/index.md

The forward slash in between the two regex examples is hard to spot when the examples are using a few slashes as well.

Made easier to read the two test examples provided

---

src/content/api/node.mdx

The docs currently state that the callback passed to the `MultiCompiler` is executed after each configuration in the options array has been compiled.
This is not the case. The callback is executed once, after all compilations have finished.

Fix inaccurate description of callback in MultiCompiler

---

src/content/plugins/eval-source-map-dev-tool-plugin.md

The documentation was introduced in https://github.com/webpack/webpack.js.org/pull/1776 and referenced a `sourceURLTemplate` that would be introduced in https://github.com/webpack/webpack/pull/6272 but that PR was never merged.
I'm running into a number of errors trying to run `master` locally so I haven't been able to test the changes, but since it's only removing some content I'm guessing it would be fine.

docs(plugins): removes inexistent sourceURLTemplate option from EvalSourceMapDevToolPlugin

---

src/content/configuration/output.md

Wanted to just quick fix the type on `output.filename` function option, but found many inconsistencies

docs(config) Fix types and info on output section of config docs

---

src/content/guides/tree-shaking.md

Based on https://github.com/webpack/webpack/issues/9337
Formatted, corrected grammar, amended the text style to be consistent with the docs, added links to resources.

docs(guides) add clarifying tree shaking and sideEffects section

---

src/content/guides/getting-started.md

Made a minor clarification to getting started. I'm new to webpack and missed the step to move the `index.html` to the `dist` directory. I'm hoping that asking the user to tweak as follows makes this more obivious..

docs(guides) clarify getting started directory structure tweak

---

src/content/configuration/module.mdx

This is the missing configuration i mentioned on the #3197 
Although to completely close the issue we need to figure our where to add the documentation on the `getResolve` resolver method. Currently its not on webpack.js.org and not on https://github.com/webpack/enhanced-resolve
I guess i could be tracked in #3197 and future prs

docs(config) document Rule.resolve

---

src/content/api/parser.md

Fixed a typo: Paramaeters -> Parameters

Fixed typo in parser.md

---

src/content/contribute/writing-a-plugin.md

While looking at #3148 i noticed a very good point on missing linking to existing docs

docs(plugins) link compiler and compilation from writing a plugin page

---

src/content/plugins/dll-plugin.md

I'm just assuming this definition. I just discovered Webpack DLL, and find this terminology a little awkward. DLLs are traditionally binary files linked at run time, not build time (or maybe both, I can't remember). In any case, when I discovered Webpack DLL I couldn't find a definition for "Dll."

Update docs to explain what I assume "Dll" means

---

src/content/configuration/other-options.md
src/content/configuration/stats.md

This is on master, review asap pls
Takes off configuration part from #3205

docs(config) document logging feature

---

src/content/plugins/module-concatenation-plugin.md

I wanted to read something about the ModuleConcatenationPlugin and realized that the URL to the Babel modules configuration is leading to the old 2015 preset.
Just Updating this with the new https://babeljs.io/docs/en/babel-preset-env#modules.
This PR is only updating the modules Url for the Babel reference.

Updating with new babel-present-env modules link

---

src/content/concepts/entry-points.md

Added a missing space in "entrypoint" and changed the verb "increase" to "increases" since the subject is "the number of entry points".

docs(concepts): fix typos in the Entry Points section

---

src/content/configuration/externals.md

I changed the description of the array syntax for `externals` and added an example. I just spent 1 hour digging through the source code to find out what exactly this does. The result being that a) this doesn't do what I thought when I read "parent child construct" and b) I actually have no clue at all what this would be useful for. It seems to me to be a leftover from commonjs days? If someone could give me an example how this is useful, maybe adding another sentence here would be nice.
As an aside, what I first thought this would allow me to do is that when I have 
```
a.js
– c.js
b.js
– c.js
```
that I could specify that c.js shall be bundled only when imported by a.js, but not in b.js, like `{'c.js': ['a.js', 'c.js']}` (parent a, child c)

Clarify array syntax of externals

---

src/content/api/compiler-hooks.md

Continuing to work towards documenting bunch of changes from #3205
Taken care of __Plugins__ task from the list which is around documenting `Compiler.hooks.infrastructureLog` and` Compilation.hooks.log` hooks

 docs(api) document infrastructureLog and log compiler hooks 

---

src/components/Navigation/Navigation.jsx
src/components/Navigation/Navigation.scss

Fixes the auto zoom when user focuses on search input. IOS zooms on any input which has font size < 16px;
To reproduce, open https://webpack.js.org/ and use search input, screen will zoom in
To test the fix, go to preview and repeat steps

ui(search) fix mobile auto zoom on search input

---

src/components/Navigation/Search.scss
src/components/NotificationBar/NotificationBar.scss

Search feels terrible on mobile right now... So i took a shot on trying to not create our own docsearch.css but to add a few overrides, most of them are to inline style therefore hold the !important flag. If we'd get rid of this would mean to clone and compile our own docsearch.css.
- Make sure search box fits screen
- Use full width for screens under docsearch's max-width of search box (600px;)
- Different offset for case with notification and without.
- Fix notification's close button, it is covered with text now :(
Search before:
Search after: (notice how it now fits the screen, try more on preview)
And notification bar, close button.
Before:
After:
Might actually close #3052 but not sure

ui(search) improve mobile search ux/ui; close button on notification

---

src/content/configuration/stats.md

Change spelling of 'moduleSort' to 'modulesSort'.

Fix spelling of 'moduleSort'

---

src/content/configuration/mode.md

`optimization.removeAvailableModules` is now disabled in `mode` `'development'`
See: https://github.com/webpack/webpack/releases/tag/v4.38.0

docs(config) removeAvailableModules are now disabled in mode development

---

src/content/configuration/optimization.md

#3216
update documentation for https://github.com/webpack/webpack/releases/tag/v4.38.0
> optimization.removeAvailableModules is now disabled in development mode by default

docs: update optimization.removeAvailableModules

---

src/content/guides/hot-module-replacement.md

Add link to Svelte-loader github page

docs(hot-module-replacement): Add Svelte HMR link

---

src/content/configuration/output.md

Adds note for escaping path variables to the `configuration/output` section of the docs.
Related PR: https://github.com/webpack/webpack/pull/9454
Closes: #3219

docs(config) add note for escaping path variables

---

src/content/configuration/optimization.md

A follow up to #3218
Corrects the text accordingly to new default. Remove redundant statements.
Closes #3216

docs(config) correct optimization.removeAvailableModules

---

src/content/api/compiler-hooks.md

As per title, this hook was added in webpack 4.39.0

docs(api) document assetEmitted hook

---

src/content/api/logging.md

The last pull request in sequence to add logger api and close #3205 when all the linked PRs are also merged.
Applying Plugins to runtime logger doesnt have tests or examples in webpack repo, so its example to be added later

docs(api) document runtime logger usage

---

src/content/api/logging.md

- document status method
- closes #3222

docs(api) logger status method

---

src/content/guides/hot-module-replacement.md

In the [*Hot Module Replacement*](https://webpack.js.org/guides/hot-module-replacement/) guide,
- Added a missing semicolon.
- Added a missing comma.
- Added a missing pronoun.

docs(guides): fix typos in HMR guide

---

src/content/guides/index.md

Intro in the guides section can be improved, right now we were linking the installation guides which didnt have logical next steps and also is not close to be first in the list of guides. Now we are lining getting started guide which offers next steps and has installation guide as a dependency.
more and more is redundant, so that sentence was simplified.

docs(guides) correct guides intro

---

src/content/guides/development.md

In the [*Development*](https://webpack.js.org/guides/development/) guide,
- Replaced "lets" with "let's" when it was meant to be a contraction of "let us".
- Added a missing comma.
- Changed the capitalization of an anchor link's text so it's consistent with the title of the section that is being pointed to.
- Replaced "find the bundle files in different path" with a more appropriate "find the bundle files on a different path".
- Added backticks around `webpack-dev-middleware` where missing.
- ~~Fixed the link to the next guide, which is "Code Splitting" and not "Hot Module Replacement".~~ See https://github.com/webpack/webpack.js.org/pull/3245#pullrequestreview-273809991.
- Fixed the hash in the link to `devServer.publicPath`, which had an extra `-` (`#devserver-publicpath-` --> …

docs(guides): fix typos and a link hash

---

yarn.lock

Dependabot cannot sign CLA for technical reasons, duplicating #3249 to resolve security vulnerability.

chore(deps): bump lodash.template from 4.4.0 to 4.5.0

---

src/content/contribute/writers-guide.md

It's been a while since i've started introducing types to the arguments, but usually it wasnt really clear what is right and what is wrong.
When we defined the current typing we did not consider some of the options:
- function return types
- defaults combined with enums
- objects and their prop types and their defaults if present
This should fix all the issues to date

docs(contrib) Kick off types generalization work

---

src/components/SidebarMobile/SidebarMobile.jsx
src/components/SidebarMobile/SidebarMobile.scss

On mobile, body click wasn't closing the SidebarMobile as mobile doesn't trigger `mousedown` event when you touch

docs(ui) make mobile menu close button fixed for convenience

---

src/content/api/loaders.md
src/content/api/logging.md
src/content/api/plugins.md
src/content/configuration/other-options.md
src/content/configuration/stats.md

Finally got my hands into refactoring the non accessible version of the stats config. Now all the options are properly documented (based on the available info and somewhere enhanced) and have new type system as a demonstration. If we decide to change the types notation i will update this PR.
- stats options have types and defaults in a common format
- stats options can now be linked to
- some of the stats options are now explained better 
- provided direct links to stats.logging\]
P.S. Sorry for the big diff but dont see how i'd split that work.

docs(config) refactor stats options, update links, update info

---

src/content/configuration/module.mdx

Resolves https://github.com/webpack/webpack.js.org/issues/3195
Changed in https://github.com/webpack/webpack/pull/9415.

docs(module): update module.type naming change

---

src/content/configuration/other-options.md

Remove `cache.loglevel` originally added in https://github.com/webpack/webpack.js.org/pull/2606.
This was removed in https://github.com/webpack/webpack/pull/9563/files.
Resolves https://github.com/webpack/webpack.js.org/issues/3246.

docs(cache): remove cache.loglevel

---

src/components/Support/Support.scss

Some sponsors on the homepage have stretched logos. This PR fixes this by using `max-height` instead of `height`. Images are also aligned in the middle for a more natural look. I've also limited the width of platinum & gold members, this has no effect at the moment but is just a fix just in case someone has a superwide logo in the future.
The difference is most noticeable in the **intracto** and **TEKHATTAN** logos (Bronze sponsors).

Fix aspect ratio open collective sponsors

---

src/content/api/stats.mdx

Document asset info added in webpack v4..40.0
Closes #3280

docs(api) document stats asset info object props

---

src/content/concepts/index.md

As noted by my friend on twitter, entry config could be linked to improve the reading of concepts section of the `entry`.
- make link lead to entry config
- small reword to make link self descriptive for seo

docs(concepts) improve linking from concepts entry to config entry

---

src/content/concepts/module-resolution.md

We usually use `e.g.` across the docs and it seems pretty off here

docs(concepts) fix e.g. spelling

---

src/content/guides/build-performance.md

Hello, I've recently discovered that Progress plugin tend to slow down build time and therefore wanted to note that in the docs.
In my tests by removing `progress-plugin` I was able to shave off 15~30 seconds from a production build time. At our compony prod build usually takes about 5 minutes so the change may reduce the build time from 5 to 10%. Also since prod builds tend to happen remotely on a server or a CI system I think it is a good idea to keep the log files leaner.
I am not too sure about the wording and would love to get any feedback. Thank you for the awesome docs.

Build performance: progress plugin

---

src/content/api/cli.md

Only one change: optimise to optimize

docs(api) change optimise to optimize (prefer U.S. spelling)

---

src/content/configuration/dev-server.md

Tell users of `DevServer.writeToDisk` where to find the output that gets written to disk.
fixes #3304

docs(DevServer): document writeToDisk output dir

---

src/content/concepts/loaders.mdx

npm install command wasnt running without `&&` notation so it makes sense to merge it.
The loaders ecosystem empowerment phrase was not backed up nor it wasn't straightforward, reworded it

docs(concepts) loaders command fix and message re-worked

---

src/content/concepts/loaders.mdx
src/content/guides/getting-started.md
src/content/guides/installation.md

docs(misc) correct and enhance npm install snippets

---

src/content/concepts/entry-points.md
src/content/contribute/writers-guide.md

- add the missing `<>` syntax for computed object props to the writers guide
- change recently updated example accordingly
Reference of current usage: https://webpack.js.org/configuration/entry-context/#entry

docs(types) mention computed object key syntax and correct existing case

---

src/content/configuration/dev-server.md

Changed documentation of `devServer.openPage` based on **unreleased** changes discussed here:
https://github.com/webpack/webpack-dev-server/pull/2266
> DO NOT MERGE until the aforementioned PR is integrated.

docs(DevServer): expand on `devServer.openPage` usage

---

src/content/api/cli.md

- The `-o` tag was missing in the multiple-entry CLI command

docs(cli): fix multiple-entry cli command

---

src/content/configuration/stats.md

Just added a info screen to add that the stats should be in the webpack-dev-middleware options when using webpack-dev-middleware.

webpack-dev-middleware options

---

src/content/configuration/dev-server.md

onListening was added in 3.5.0
https://github.com/webpack/webpack-dev-server/pull/1760
compiler arg for after and before functions was added in 3.3.0
https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#features-4

docs(configuration): add onListening, update after and before in devServer

---

package.json
src/content/api/hot-module-replacement.md
src/content/api/loaders.md
src/content/api/module-methods.md
src/content/api/node.mdx
src/content/api/stats.mdx
src/content/configuration/module.mdx
src/content/configuration/output.md
src/content/glossary.md

Hyperlink 4.4.0 has a new feature that will detect broken fragment links of the form `/page#fragment` where `/page` is actually a redirect to `/page/` because it's a directory with an index file. In this case the server redirect will strip the fragment, thus breaking the intended link.
See errors in the current `master` branch here: https://travis-ci.org/webpack/webpack.js.org/jobs/604644796#L2041-L2159
The following commit fixes all those errors.
Relates to https://github.com/webpack/webpack.js.org/pull/3332

Upgrade to hyperlink 4.4.0

---

package.json

These badges seem to time out a lot, and unnecessarily block pull requests: https://travis-ci.org/webpack/webpack.js.org/jobs/608516515#L2040-L2134

Skip link checking david-dm badges

---

src/content/configuration/other-options.md

This will make it clearer that this is `false` by default.
https://github.com/webpack/webpack/blob/408a4ae77eb3f7441d6dd2dc011f23e491e8fbfb/lib/Compilation.js#L501

Add `: false` to `bail` documentation

---

src/content/configuration/stats.md

While configuring the stats to display, without using the entrypoints option, I found out the entrypoints were appearing to the log, even when in the documentation was shown with a default value of `false`. I checked in the [file where defaults are defined](https://github.com/webpack/webpack/blob/beec753201763fa3724bd965a93106126d13b271/lib/stats/DefaultStatsPresetPlugin.js), and in line 112 it implicitly appears the default value is `true`, so I've edited the documentation to reflect it.

Correct `stats.entrypoints` default value

---

src/content/api/loaders.md

`html-loader` doesnt uses `addDependency` method, _Might be outdated with the changes_
I changed the example with `sass-loader` and `less-loader` which does use it
Follow up of https://github.com/webpack/webpack.js.org/pull/3353
_I messed up the reverting and somehow I couldnt reopen that PR even though this branch is ahead of master so had to make a new one_

Fix: corrected the mentioned loader api adddependency

---

src/content/configuration/index.mdx
src/content/plugins/commons-chunk-plugin.md

Removing very old references.
Another question i have is should we remove LoaderOptionsPlugin and its references too or should we update its description.

docs(multiple) remove webpack 1-2 notes as webpack 5 is closing in

---

.github/CONTRIBUTING.md

currently as per the contribution docs, running `start` script will not work when running the website in the browser as it required some of the fetched files like for the `_supporter.json`.
So `fetch` command need to be called beforehand in order to make it consistent.

chore: updated the start script to fetch at first

---

src/content/configuration/stats.md

There is no description  of `stats.preset`. Because of this there is no entry in the left menu.

Add description of the option `stats.preset`

---

src/content/configuration/module.mdx
src/content/guides/asset-modules.md

- add sort to fix the page
- refactor types, wording and structure of the configuration options
- tidy up the guide and re-link to new paragraph

docs(guides,config) asset module follow up

---

src/content/guides/build-performance.md
src/content/guides/entry-advanced.md
src/content/guides/integrations.md
src/content/guides/production.md
src/content/guides/tree-shaking.md

Just found a few cases where we let misformatting in, fixed:
https://webpack.js.org/contribute/writers-guide/#typesetting

docs(format) recent contributions violated writers guide fixed

---

src/content/configuration/module.mdx

This change explains better the relationship between `Rule.rules` and `Rule.oneOf`.
It also makes the two more connected, by pointing to the Nested rules section, which is motivated by both [webpack-chain](https://github.com/neutrinojs/webpack-chain/pull/220) and [vue-loader](https://github.com/vuejs/vue-loader/blob/cf00a45cde52f3961b36b37265761b0d92affb0c/lib/plugin-webpack4.js#L149) developers having missed the existence of `Rule.rules`
EDIT: ~~Just realized I forgot to pull master before adding my changes. Fixing it right now.~~ Done. :+1:

docs(module): add more information about nested rules

---

src/content/configuration/other-options.md

Part of #2774
Adds documentations for:
1. `cache.idleTimeout` option
2. `cache.idleTimeoutForInitialStore` option

docs(webpack5): add new cache options

---

src/content/guides/author-libraries.md

================= Was =================
================= Now =================

docs(guides) authoring libraries: source maps revamp

---

src/content/configuration/optimization.md

The respective relative links where kinda outdated eventhough they got resolved to the updated resource. Made them link up to the intended resource for the sake of consistency.

docs(configuration): fixed outdated reference to production mode resource

---

src/content/contribute/debugging.md

The warning statement about using the `--inspect` interface is missing the word `free`. Fixed it.

docs(contribute): fix incomplete warning

---

src/content/api/module-methods.md

- single quotes for js (including strings and their example/possible values)

docs(api) minor formatting fixes, use singlequotes for js strings

---

src/content/contribute/writing-a-plugin.md

Added [`schema-utils`](https://github.com/webpack/schema-utils) in `writing-a-plugin` page for schema validation,
**screenshot**

docs(writing-a-plugin): added details about schema-utils

---

src/content/configuration/module.mdx

[https://webpack.js.org/configuration/module/#ruleresolve](https://webpack.js.org/configuration/module/#ruleresolve)
The config Rule.resolve in module would cause a syntax error.

docs(configuration): config Rule.resolve with an object in module

---

src/content/contribute/writing-a-loader.md

memory-fs is depreciated and its recommended to migrate to memfs

docs(writing-a-loader): changed the depreciated memory-fs in example

---

src/content/migrate/5.md

- Closes #2393 
- mention that internals changes are listed just for information but not necessarily valuable for common users

docs(migrate) mention internal changes in migration guide

---

src/content/concepts/why-webpack.md

Document "Automatic dependency collection" in Why Webpack
In reviewing a [blogpost of mine](https://www.swyx.io/writing/jobs-of-js-build-tools), @TheLarkInn said that dependency collection ought to have much higher priority as people don't appreciate how this departs from older tools. So I proposed adding it to the docs.

Document "Automatic dependency collection" in Why Webpack

---

src/content/configuration/module.mdx
src/content/guides/asset-modules.md

Added some info about overriding `output.assetModuleFilename` after merging https://github.com/webpack/webpack/pull/10291

Overriding `output.assetModuleFilename`

---

src/content/api/cli.md

It about https://github.com/webpack/webpack-cli/pull/1195

Add info about passing cli args to nodejs

---

src/content/configuration/other-options.md
src/content/configuration/output.md
src/content/configuration/watch.md

Some definitions of accepted/default config values didn't adhere to the writer's guide - I fixed them.

docs(config): cleanup default values

---

src/content/configuration/optimization.md
src/content/migrate/5.md

Fix #3510 - enable optimization.sideEffects, innerGraph and usedExports by default

Fix 3510 - enable optimization.sideEffects, innerGraph and usedExports by default

---

src/content/api/logging.md

The path to webpack logger in the docs is fixed with the correct path

fix: corrected the path of the logger from webpack

---

src/components/Page/Page.jsx
src/content/concepts/index.md

I faced a problem when I was reading the docs which is if I was at the bottom of the page and moved to another section from the sidebar it will stay at the bottom of the page, so I added a scroll to top when I change the topic from the sidebar.
**Problem**
**Solution**

scroll to top when change topic from the sidebar

---

src/content/contribute/writers-guide.md

We didn't have this in the guide, only on certain pages of the docs. Now its more obvious how to treat such lists
ref #3520

docs(comntrib) typed shortlists

---

src/content/configuration/dev-server.md

Add `contentBasePublicPath` option description in dev-server configuration section.
https://webpack.js.org/configuration/dev-server/

docs(config): add contentBasePublicPath option

---

src/content/configuration/dev-server.md

https://github.com/webpack/webpack-dev-server/pull/2150

docs(dev-server): fix `contentBasePublicPath` example

---

src/content/contribute/plugin-patterns.md

The docs confused me when developing a plugin in 4.41.6. This PR updates the Plugin Patterns page to reference the correct data types for `fileDependencies` (a `Set` not an `Array`) and `fileTimestamps` (a `Map` not an `Object`). It also updates the example code accordingly.

docs: use correct data types

---

src/content/contribute/writing-a-loader.md

`Jade-loader` has been depreciated and `pug-loader` support complete `.jade` files
[Refer-this](https://github.com/pugjs/pug-loader#legacy-jade-files)

changed the depreciated jade loader to pug loader

---

src/server.jsx

`og:image` is url, not path.
https://ogp.me/

chore: og:image

---

src/content/configuration/resolve.md

Refer https://github.com/webpack/changelog-v5/pull/25

chore: added deprecated note for null-loader

---

src/content/api/node.mdx
src/content/contribute/writing-a-loader.md

Follow up of #3545 
`createFsFromVolume()` is a function and should be invoked directly.

docs(api): remove redundant new keyword

---

src/content/configuration/configuration-languages.md

Since there is no default export in path and webpack definitions, we need to import modules this way.

Fix import in typescript files

---

src/content/configuration/devtool.md

fixes the wrong `cheap-eval-source-map` to `eval-cheap-source-map` 
Reporting source : https://twitter.com/rossipedia/status/1230913226000330753

fix: changed the wrong cheap-eval-source-map to eval-cheap-source-map

---

src/content/api/hot-module-replacement.md
src/content/api/loaders.md
src/content/api/module-variables.md

While reviewing recent PR i spotted mis- formatting on api pages, just cleared the occurrences and found another grammar improvement

docs(format) single quotes in js spotted, minor grammar

---

src/content/concepts/under-the-hood.md

gramma fix
Sorry github was degradating and I did not mention this problem in original PR..

minor grammatical fix

---

src/content/configuration/output.md

Fixes a simple typo in the docs for `output.globalObject`.

docs: typo for output.globalObject

---

src/content/concepts/under-the-hood.md
src/content/configuration/output.md

- a follow up to do small grammar fixes
- added a link to template strings in output
- fix name of SplitChunksPlugin
- shortened info in `initial` and `non-initial`, use consistently

docs(concepts) a follow up on page creation

---

src/content/guides/asset-management.md

'group' itself is explanatory. No need to mention 'together' explicitly.

docs: Remove redundant word

---

src/components/Markdown/Markdown.scss
src/components/NotificationBar/NotificationBar.jsx

Fix #3540
It isn't *perfect* because it doesn't cover all the possible heights the topbar can be in (mobile: 56px, mobile with banner: 56px + 58px, desktop: 56px + 27.3px, desktop with banner: 56px + 27.3px + 56px). 
I've tried to optimize for (probably) the most common use case desktop (56px + 27.3px)
Here is what it looks like on desktop now:
<br>
On desktop with banner (heading is covered):
<br>
On mobile (space at the top is a bit larger):

fix: #3540 (Links don't scroll to correct position)

---

src/content/concepts/under-the-hood.md

This PR fixes a typo in 'under the hood' page of the docs.

Fix typo in 'Under the hood' page

---

src/content/configuration/resolve.md

In every example in resolve docs table, `abc` is the (assumed) name of the project. Making this path `/abc` consistent since a couple of examples were `/abs` even though the result was `/abc`.

docs(config/resolve): Fixing a typo

---

README.md

fixes: #3605
hyperlinking #3366 in the readme file 

docs(readme): hyperlinking versioning issue in readme

---

src/components/Markdown/Markdown.scss

Made a Little change with the styling of `markdown` component

chore: refactored the styling for markdown tables

---

src/content/configuration/dev-server.md
src/content/configuration/index.mdx
src/utilities/process-readme.js

:writing_hand: **Fix typos across webpack.js.org repo**
**Files that have typos**
```
webpack.js.org/src/content/configuration/dev-server.md:778:20: "supress" is a misspelling of "suppress"
webpack.js.org/src/content/configuration/index.mdx:284:9: "properites" is a misspelling of "properties"
webpack.js.org/src/utilities/process-readme.js:40:23: "documenation" is a misspelling of "documentation"
```
**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart: 
Making the world a better place :innocent:

Fix typos across webpack.js.org repo

---

src/content/api/compilation-hooks.md

Removed hooks which had warning for V5

Docs(api) : Removed hooks which had warning for v5

---

src/content/plugins/ignore-plugin.md

“Deprecated” means “it works but will be deleted soon”, which is not the case in webpack 5. Webpack 5 drop support for the old approach completely.

Docs: IgnorePlugin: Clarify the “deprecated” usage

---

src/components/Footer/Footer.scss

Fix style bugs in `Footer` component which caused body's max width wider than screen width in mobile phone browser.
Before style change:
After style change:

fix(component): fix style bugs in Footer component

---

src/content/glossary.md

Updated the glossary list to include information regarding `webpack scaffolding`.

docs(glossary): Added scaffolding to the list

---

src/content/api/loaders.md

Fixes  #3644
Removed `this.resolveSync`  from the depreciated list as it has been really removed.

docs(loader): remove resolveSync()

---

yarn.lock

We have some accessibility problems with buttons in navigation bar:
I submitted a [pull request](https://github.com/skipjack/react-banner/pull/17) on react-banner repository yesterday, and now it's published under 1.0.3.
This pull request updated its version in yarn.lock.
And here's the audit result for home page after updated:

chore(deps): update react-banner to improve accessibility

---

src/content/configuration/optimization.md

Fixes #3420 
`deterministic` value is implemented in webpack 5. but it is not mentioned anywhere hence clarifying its reference.

docs(optimization): clarify deterministic value for moduleIds

---

src/content/configuration/dev-server.md
src/content/configuration/entry-context.md
src/content/configuration/module.mdx
src/content/configuration/other-options.md
src/content/configuration/output.md
src/content/configuration/resolve.md
src/content/contribute/writing-a-loader.md
src/content/guides/build-performance.md
src/content/plugins/dll-plugin.md
src/content/plugins/provide-plugin.md

In order to make all of our examples accessible i've added the missing require call to `path` as we already had it in almost all examples using `path` directly

docs(examples) fix examples missing a require

---

src/content/plugins/dll-plugin.md

adds `format` for dll plugin and `extentions` for DllReferencePlugin
https://github.com/webpack/webpack/blob/d00e65529a4c5a4e91843f2d4178c66eff3784ae/schemas/plugins/DllPlugin.json#L15
https://github.com/webpack/webpack/blob/d00e65529a4c5a4e91843f2d4178c66eff3784ae/schemas/plugins/DllReferencePlugin.json#L109

docs(dllPlugin): add missing options

---

src/content/configuration/dev-server.md

Fixes #3668 
added type array for contentBasePublicPath option.

docs(devServer): add type array for contentBasePublicPath option

---

src/content/contribute/writing-a-plugin.md

schema-utils api has change the third param to type below
```ts
export type ValidationErrorConfiguration = {
name?: string | undefined;
baseDataPath?: string | undefined;
postFormatter?: PostFormatter | undefined;
};
```
see: [https://github.com/webpack/schema-utils/pull/41](https://github.com/webpack/schema-utils/pull/41)
from the guide, the developer may use the latest version of schema-utils that not matched the version that webpack used.
So I add a notice to warning this.

Docs(plugin): schema-utils api changed

---

src/content/configuration/output.md

This [option](https://github.com/webpack/webpack.js.org/pull/3650#pullrequestreview-381794370) is no more there in webpack 5

Docs(config) : Remove futureEmitAssets

---

src/components/Markdown/Markdown.scss

Headings look weird currently, take this heading on page https://webpack.js.org/migrate/3/#automatic--loader-module-name-extension-removed for example:
Applying `flex-wrap: wrap` will make it look better:

Break flex items into multiple lines

---

src/components/Navigation/Navigation.jsx

Currently there's error related to react-banner in `development` mode when we input anything in the search box:
It exists in `production` too:
It is caused by https://github.com/skipjack/react-banner/blob/master/src/banner/banner-search.jsx#L55 calling `onSearch` prop which we do not provide.
This pull request set `onSearch` to an empty function to fix it.

chore(app): Fix warning for react-banner

---

src/content/configuration/target.md

Calling `apply` on Tappable is marked deprecated.

docs(configuration): fix deprecated apply usage

---

src/components/Navigation/Search.scss

Search results on mobile are almost unstyled, this pull request would improve it:
And here's a preview https://webpack-7gmqohurp.now.sh/

fix(site): update search result style on mobile

---

src/components/Navigation/Search.scss

This pull request contains two commits, first commit would fix issue https://github.com/webpack/webpack.js.org/issues/3686
While second commit adding borders would visually group suggestions together, 
I'm not quite sure about the second one which is why I break it into another commit. I can squash them if anyone think it's a good idea to merge it.

fix(site): fix style for search result

---

src/content/guides/shimming.md

The index.js and globals.js are in the src directory, so the `require.resolve('index.js')` should be `require.resolve('./src/index.js')`, or else it will throw `error: Cannot find module 'index.js'` when built, and so does globals.js.

Guides(Shimming): Correct the resolve file path of rule test

---

src/content/configuration/optimization.md

Refer :
There is chunkIds: "named" as default in dev mode which is better 
https://github.com/webpack/webpack/pull/8432#issuecomment-447661876
https://github.com/webpack/webpack/blob/b0cdbf87b02685cd21dc7726eb7227872e142f5d/lib/config/defaults.js#L523

docs(config): different default based on enviornment

---

src/content/configuration/watch.md

I followed the same value while writing the docs but the default value is 200 and not 300 
https://github.com/webpack/webpack/blob/2346f6b245a92f317535018129260d7c015734c9/lib/Watching.js#L46

Docs(config) : Change default value of watchOptions.aggregateTimeout

---

src/content/configuration/externals.md

This PR adds more details and examples to the *Function* section of the *Externals* documentation. In particular, the callback that is used in the external function has a lot of variations that are not documented and for which examples are hard to find.

Update function section of Externals docs.

---

src/content/configuration/watch.md
src/content/guides/caching.md

Update the polling link and cache link to the wikipedia ones since the currently linked articles are behind a subscription wall

Update links behind subscription wall

---

src/components/Vote/Vote.jsx
src/components/Vote/Vote.scss

Noticed markdown styles squeezing vote layout, fixed.
Before
After

ui(vote) fix markdown styles squeezing vote layout

---

src/content/glossary.md

Updated the glossary list to include information regarding `shimming`.

docs(glossary): Add shimming to the list

---

src/content/configuration/index.mdx

Entry point only has `src/index`, when it should be `src/index.js`

small typo fix for default entry point

---

src/content/api/node.mdx

I've submitted a pull request here https://github.com/webpack/webpack.js.org/pull/3537 two months ago which is unfortunately wrong as I found today.
According to webpack changelog https://github.com/webpack/changelog-v5#minor-changes:
> Stats json errors and warnings no longer contain strings but objects with information splitted into properties.
> MIGRATION: Access the information on the properties. i. e. message
Then `example2.json` is for webpack 5 while `example1.json` is for webpack 4.

docs(api): update example link for webpack 5

---

src/content/plugins/internal-plugins.md

I couldn't find this in webpack internals Hence I am not sure we should document this

Docs(plugin): Remove NoHotModuleReplacementPlugin from internal-plugin

---

src/content/plugins/hot-module-replacement-plugin.md

The `requestTimeout` option was removed in this commit https://github.com/webpack/webpack/commit/9d918615922f8e7fb8ab1c9712135908cf1cadd7#diff-8941681d920ac4feda44f522b986c2d0L99. There're only `multiStep` and `fullBuildTimeout` left as we can see here https://github.com/webpack/webpack/blob/master/types.d.ts#L2599

docs(plugins): clean option

---

src/content/configuration/devtool.md

The used value "cheap-module-eval-source-map" doesn't exist (maybe anymore) and "eval-cheap-module-source-map" should be used instead
https://webpack.js.org/configuration/devtool/

Fix name of dev-tool name in description

---

src/content/configuration/output.md
src/content/plugins/split-chunks-plugin.md

Not an issue at all, but I think would be an improvement if we can use the same name as types defined for typescript https://github.com/webpack/webpack/blob/082fce5000a5bdf0fbef99acc604d1c57eef511d/declarations/WebpackOptions.d.ts#L61

docs: update argument name

---

src/components/NotificationBar/NotificationBar.scss

Notification bar is not vertically aligned on desktop:

fix(site): vertically align notification bar

---

src/content/configuration/module.mdx

This PR mirrors #3714 for the v4 documentation.
It addresses the following issues:
- #2539
- webpack/webpack#10771

Docs(config) : add module.unsafeCache to v4 docs

---

src/content/guides/development.md

Removing the `devServer` config property from watch mode snippet under Documentation > Guides > Development > Using Watch Mode.

docs(guides): Update watch mode snippet in development guide

---

src/content/contribute/writing-a-loader.md

The `Testing` part is kind of outdated and broken. And here's repo I set up in case anyone review it wanna double check https://github.com/chenxsan/testing-loader

docs(contribute): update writing-a-loader.md

---

package.json

Could be related: https://github.com/siddharthkp/bundlesize/issues/93
Master doesn't get deployed, until we figure out proper fix lets just disable it
ref: https://travis-ci.org/github/webpack/webpack.js.org/jobs/694100391
```
$ bundlesize && npm run sitemap
ERROR  Could not add github status.
401: Bad credentials 
```

feat(optimize) disable bundlesize to fix prod deploy

---

src/components/Markdown/Markdown.scss

On smaller devices headings do not wrap correctly:
After setting `word-break: break-word`:

UI: Fix word-break on headings

---

src/content/api/compilation-hooks.md

Adding deprecation warnings to avoid future usages now that [those compilation hooks were deprecated](https://github.com/webpack/webpack/blob/253cf465df3f1d577a6da25c554c5c0a7e64bf0b/lib/Compilation.js#L503) since webpack 5 beta 17.
It only includes those with warnings showed in console:
Preview url: https://webpack-js-org-git-fork-chenxsan-feature-add-deprecation-83caf4.webpack-docs.vercel.app/api/compilation-hooks/#additionalchunkassets

docs(api): add deprecation warnings

---

src/content/api/stats.mdx

It's a follow-up to https://github.com/webpack/webpack.js.org/pull/3704, the error object was copied from [example2.json](https://raw.githubusercontent.com/webpack/analyse/master/app/pages/upload/example2.json).
Preview url: https://webpack-js-org-git-fork-chenxsan-bugfix-update-stats.webpack-docs.now.sh/api/stats/#errors-and-warnings

docs(api): update stats.mdx for webpack 5

---

src/content/api/module-methods.md

Document `webpackExports` introduced in [webpack v5.0.0-beta.18](https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.18).
Preview url https://webpack-js-org-git-fork-chenxsan-feature-add-new-magic-comments.webpack-docs.vercel.app/api/module-methods/#magic-comments

docs(api): add new magic comment

---

src/content/configuration/resolve.md

Document `resolve.restrictions` introduced in [webpack v5.0.0-beta.18](https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.18)
Preview url: https://webpack-js-org-git-fork-chenxsan-feature-add-resolve-dot-8423d9.webpack-docs.vercel.app/configuration/resolve/#resolverestrictions

docs(configuration): add resolve.restrictions

---

src/content/glossary.md

I think the `is` is missing here.

docs(glossary): fix grammar

---

.travis.yml

`cypress:ci` would start the server with `yarn start` script which would remove `dist` folder causing `Post-build` stage to fail.

move build script after cypress

---

src/content/guides/installation.md

1. `webpack` beta was [published under tag `next`](https://www.npmjs.com/package/webpack?activeTab=versions).
2. We would like users to install `webpack` under `devDependencies` instead of `dependencies`.

docs(guides): use tag `next`

---

src/content/configuration/node.md

This PR fixes the documented node defaults.
See https://github.com/webpack/webpack/blob/v5.0.0-beta.20/lib/config/defaults.js#L478-L510 for the actual node default configs.
* Node defaults were restored in PR https://github.com/webpack/webpack/pull/8602
* Documentation was updated accordingly in https://github.com/webpack/webpack.js.org/pull/2753
* Node defaults were changed for targets  `node`, `async-node` and `electron-main` in https://github.com/webpack/webpack/pull/9172
* Documentation was wrongly updated for the non-default targets `node`, `async-node` and `electron-main`, but should reflect the default target `web` https://github.com/webpack/webpack.js.org/pull/3602
Relates to https://github.com/webpack/webpack/pull/11054.
I would much prefer to disable node for all targets, but …

Fix node defaults

---

src/content/configuration/configuration-types.md

according to https://webpack.js.org/configuration/devtool the "devtool" option should be source-map (it was source-maps in the file).

changing source-maps to source-map

---

.babelrc
src/components/Page/AdjacentPages.jsx
src/components/Page/AdjacentPages.scss
src/components/Page/Page.jsx
src/components/Sidebar/Sidebar.jsx
src/components/Site/Site.jsx
src/utilities/get-adjacent-pages/index.js
src/utilities/get-adjacent-pages/index.test.js

Sometimes I would read document on mobile phone and navigating between pages are not an easy task when you have to open sidebar menu first. This pull request adds links at the bottom of page for navigating to previous/next page, and I think it would improve users' experience.
Screenshot:

add links to navigate between pages

---

src/content/configuration/output.md

Follow up #3818 
`jsonpScriptType` was renamed to `scriptType`.

docs(config): remove output.jsonpScriptType references

---

src/content/configuration/externals.md

https://github.com/webpack/webpack/blob/f4b5555691cef31127e7ab9d7a998ad4f547368a/declarations/WebpackOptions.d.ts#L134
> * Specifies the default type of externals ('amd*', 'umd*', 'system' and 'jsonp' depend on output.libraryTarget set to the same value).

docs(configuration): mention jsonp

---

src/content/guides/build-performance.md

This PR removes experimentalWatchApi from the suggested code to improve ts-loader performance.  The reasons are:
- At the time of writing, experimentalWatchApi is not fully functional.
- This option and transpileOnly are mutually exclusive so cannot be applied together as previously shown.
See the discussion under ts-loader issue [#1124](https://github.com/TypeStrong/ts-loader/issues/1124#issuecomment-657266185).
When the new watchApi is working I will update the docs again to reflect how it should be used.

docs(build-performance): update ts-loader section

---

src/components/Page/Page.jsx

I was using Safari on iOS 12.4.3 to browse the document when I found the [scroll to top function](https://github.com/webpack/webpack.js.org/pull/3513/files#diff-215153bef266b7d16040d598cdf95b25R37) won't work as expected (Unfortunately I didn't notice it when I created https://github.com/webpack/webpack.js.org/pull/3656), you can see it from the video below if you don't have safari on iOS 12.4.3 to test:
https://imgur.com/mjRsGT3
But it did work on Safari on iOS 13.1.3 which mean it would be a [compatibility problem](https://stackoverflow.com/questions/58693386/why-does-scrolltop-position-not-work-on-mobile-safari):
Replacing it with `window.scrollTo` should hopefully support more browsers according to https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo#Browser_Compatibility …

fix(ux) Fix scroll to top bug on Safari iOS 12.4.3

---

src/content/guides/code-splitting.md

In the Dynamic Imports section inside Code-Splitting Guide,
`output.publicPath` option isn't always required to use `output.chunkFilename`.

docs(guides): Removed unnecessary publicPath option

---

src/content/configuration/watch.md

`watchOptions` as a `number` has been removed in webpack@4 and webpack@5:
https://github.com/webpack/webpack/blob/webpack-4/schemas/WebpackOptions.json#L2245
https://github.com/webpack/webpack/blob/034cd232093db8391afca4d10f4c6910fe3ef811/schemas/WebpackOptions.json#L3130

fix(watch): remove watchOptions number docs

---

src/content/guides/getting-started.md

As there is another `index.html` in the project root, and another one in `dist`, and in the document, we ask the user to open `index.html` after running the `npx webpack`, so we want the user to open the `index.html` which is inside `dist` directory. This just clarify which `index.html` do we mean to open

clearify which 'index.html' do we mean here

---

src/content/plugins/eval-source-map-dev-tool-plugin.md

https://github.com/webpack/webpack.js.org/issues/3890

fix: remove absent options from EvalSourceMapDevToolPlugin

---

src/content/plugins/eval-source-map-dev-tool-plugin.md

Follow-up to remove the remainder of #3890 that was done partially in #3894 (missed)
Closes #3890

docs(plugins) remove non-existant option from plugin example

---

yarn.lock

CVE-2020-13822
high severity
Vulnerable versions: < 6.5.3
Patched version: 6.5.3
The Elliptic package before version 6.5.3 for Node.js allows ECDSA signature malleability via variations in encoding, leading '\0' bytes, or integer overflows. This could conceivably have a security-relevant impact if an application relied on a single canonical signature.

security(elliptic) bump to secure version

---

src/components/SplashViz/SplashViz.scss

macOS Catalina 10.15.6(19G73)
Version: 84.0.4147.105(Official Build) (64 bit)
Before | After
-- | --

fixed centering .splash-viz__modules

---

src/content/api/compilation-object.md

docs(api): add Compilation.deleteAsset

---

repositories/loaders.json
src/content/loaders/index.md

loader: add remark-loader to the list

---

src/content/configuration/module.mdx

The defaults part was moved to https://github.com/webpack/webpack/blob/master/lib/config/defaults.js in this commit https://github.com/webpack/webpack/commit/6477ca56f8046e4642d983f68a68805b83982537#diff-7473dd12403a310ad8cf18d0ab9f10b9

docs(configuration): update link

---

src/content/guides/asset-management.md

It resolves the issue #3846 and I have made changes according to the previous suggestions

changes according to suggestion for issue #3846

---

src/components/Markdown/Markdown.scss

The [`scroll-margin-top`](https://github.com/webpack/webpack.js.org/blob/master/src/components/Markdown/Markdown.scss#L50) we use is [not applied for scrolls to fragment target on safari](https://bugs.webkit.org/show_bug.cgi?id=189265) which causes problem for Safari users.
For example, when we open https://webpack.js.org/concepts/#entry on safari:
While on Chrome we have visible header:
This pull request should fix the problem on safari.

fix header visibility on safari

---

src/content/configuration/externals.md

closes #3806
Related issue #3772

docs(configuration): document external script

---

src/content/plugins/define-plugin.md

docs(plugins) define plugin runtimeValue update

---

src/content/configuration/output.md

docs(output): fix typo

---

src/content/configuration/output.md

closes https://github.com/webpack/webpack.js.org/issues/3922

docs(configuration): document output.charset

---

src/content/concepts/plugins.md

closes https://github.com/webpack/webpack.js.org/issues/3921

docs(concepts): add notice about webpack-sources

---

src/content/api/loaders.md

It's removed in webpack 5 now https://github.com/webpack/webpack/pull/7708

docs(loaders): remove this.exec

---

src/content/configuration/optimization.md

webpack defaults to `production` mode.

docs(configuration): specify default value as part of type information

---

src/content/guides/output-management.md

html-webpack-template is [not compatible with html-webpack-plugin v4](https://github.com/jaketrent/html-webpack-template/issues/84), that means we can't use it in in webpack 5, so there's no need to mention it in the guide.

docs(guides): clean html-webpack-template link

---

src/components/Site/Site.scss

**Current Behaviour**
**Proposed Behaviour**
**Description**
IMO that much blank space from the top is not required.

chore(print): removes top margin in the print mode

---

src/content/loaders/index.md

Missed in https://github.com/webpack/webpack.js.org/pull/3903

chore: fix stylus loader link

---

package.json
repositories/plugins.json
src/content/plugins/index.md
yarn.lock

CI for pull request https://github.com/webpack/webpack.js.org/pull/3963 failed now https://travis-ci.org/github/webpack/webpack.js.org/jobs/730802775#L992, it might be a result of the update here https://github.com/webpack-contrib/eslint-loader/commit/fc94b5d976f3176eba6d1460fba9dde99227ac32 because eslint-webpack-plugin is not existed yet in this repository.
BTW, it's wrong to edit the `plugins.json` or `loaders.json` file like this, they should be generated by `src/utils/fetch-package-repos.js` automatically. But let's fix that later after the webpack 5 branch get merged as there're already multiple manual edits as I found, e.g. https://github.com/webpack/webpack.js.org/pull/3985, https://github.com/webpack/webpack.js.org/pull/3903

add eslint-webpack-plugin to plugins list

---

src/content/guides/asset-management.md

The [asset management guide](https://webpack.js.org/guides/asset-management/) mentions CSV, and includes an example config of how to load CSV, but doesn't actually include loading a real CSV file. This PR updates the [Loading Data](https://webpack.js.org/guides/asset-management/#loading-data) section to include an actual CSV example. 
>To import CSVs, TSVs, and XML you could use the csv-loader and xml-loader. Let's handle loading all three:

Add CSV example to `guides/asset-management`

---

src/content/configuration/other-options.md

Remove other `cache.store` options from other parts of documentation
Similar to #3393 but removes mention of `'idle'` as option of `cache.store` on other lines of the doc
(related to #3325 too)

docs(config): remove other cache.store options from other parts of documentation

---

src/content/migrate/5.md

`output.ecmaVersion` is removed in the release candidate
Documented the target option, through which the same thing can be achieved

Documented target option to revert to es5 syntax

---

src/content/configuration/output.md
src/content/configuration/target.md

Added browserslist output.target and output.environment
closes #4009
* ~The versions allow to infer features of the platform like if arrow functions are supported or not.~
* ~`output.ecmaVersion` has been replaced with `output.environment.*` and a list of boolean flags for features used by webpack (e. g. arrowFunction).~

Added browserslist output.target and output.environment

---

src/content/configuration/target.md

docs(configuration): fix typo

---

.travis.yml

Ubuntu `trusty` (14.04) is EOL, https://docs.travis-ci.com/user/reference/linux/#migration-guides
cc @sokra Any specific reason using Ubuntu [trusty here](https://github.com/webpack/webpack.js.org/pull/4033/files#diff-354f30a63fb0907d4ad57269548329e3) instead of other LTS versions?

use Ubuntu bionic(18.04) to run CI

---

src/content/blog/2020-10-10-webpack-5-release.md

Fix typo in webpack 5 announcement

---

src/content/migrate/5.md

The `optimization.noEmitOnErrors` option has been inverted to `optimization.emitOnErrors`, which I just noticed by accident. This step is currently missing from the migration guide.

Include optimization.noEmitOnErrors in migration guide

---

src/content/configuration/module.mdx

`/\.m?js/` could match `.json` too https://github.com/webpack/webpack/issues/11467#issuecomment-707722067, which is not what we want.

docs(configuration): update rule test

---

src/content/migrate/5.md

fixes https://github.com/webpack/webpack/issues/11649
fixes https://github.com/webpack/webpack/issues/11648

add missing items from user issues

---

src/content/api/cli.md

Ran into this minor inconvenience while trying to copy this example code, sorry for the almost useless PR but hopefully it helps someone else.

Remove extranous backtick in core flag example in CLI docs

---

src/content/configuration/dev-server.md
src/content/guides/development-vagrant.md
src/content/guides/development.md
src/content/guides/hot-module-replacement.md
src/content/guides/production.md

fixes https://github.com/webpack/webpack-cli/issues/1602#issuecomment-715273963
fixes #4095

docs: use `webpack serve` instead `webpack-dev-server`

---

src/content/guides/environment-variables.md

Hello, these days I upgrade my project into webpack 5 (currently 5.3.1), and I found a little change in environment variables.
According to the issue [#1216](https://github.com/webpack/webpack-cli/issues/1216) and [pull request](https://github.com/webpack/webpack-cli/pull/1939), `--env.foo=bar` should be changed to `--env foo=bar`, so I created this pull request.

docs(guides): correct bash command in environment-variables.md

---

webpack.prod.js

closes https://github.com/webpack/webpack.js.org/issues/4083
When we open pages like https://webpack.js.org/concepts/printable/, it would fallback to `/app-shell/index.html` which is wrong as we already have those static html files under `/*/printable/index.html` to be served.

fix bug for printable

---

src/content/configuration/other-options.md
src/content/configuration/stats.md

- `stats.ignoreWarnings` should be `ignoreWarnings`
- See https://github.com/webpack/webpack.js.org/issues/3995

docs: `stats.ignoreWarnings` should be `ignoreWarnings`

---

src/content/contribute/writing-a-loader.md

closes https://github.com/webpack/webpack.js.org/issues/4112
The [Jest testing example](https://webpack.js.org/contribute/writing-a-loader/#testing) of the Loader Writer's Guide needs the following for Webpack5.
* The `stats.toJson()` method now requires `{source: true}` as a parameter in order to populate the `source` property of the `module` object.
* If people create the `example.txt` with a line ending, then the expected output should also have a line ending.
I verified that with these changes the Jest test passes as coded in the document of my pull request.

Corrected Jest code for Loader Writer's Guide.

---

src/content/plugins/hashed-module-ids-plugin.md

This add the `.ids` namespace to the `HashedModuleIdsPlugin`
documentation.

doc: HashedModuleIdsPlugin Namespace

---

src/content/plugins/split-chunks-plugin.md

What kind of change does this PR introduce?
[SplitChunksPlugin.optimization.splitChunks.name: true ](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksname) is not allowed for webpack-5 (see changelog here https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure:~:text=Automatic%20names%20are%20no%20longer%20supported).
Does this PR introduce a breaking change?
No

doc(plugins):  Fix splitChunks.name

---

src/content/contribute/writing-a-loader.md

This PR updates the example code using [schema-utils](https://github.com/webpack/schema-utils) in the `Loader Utilities` section because it no longer works.

docs(contribute): Update usage of schema-utils

---

src/content/guides/asset-modules.md

closes https://github.com/webpack/webpack.js.org/issues/4127
Added a paragraph for using asset modules and old asset loaders

docs: clarify asset handling

---

src/content/api/resolvers.md

closes https://github.com/webpack/webpack.js.org/issues/4121
I've setup a code demo here https://github.com/chenxsan/webpack-repos/pull/1 so you can test when reviewing.

docs(api): update hook usage for resolvers

---

src/content/guides/asset-modules.md

The title speaks for itself ;)

Fix typo 'matro' -> 'metro' in asset documentation

---

src/content/guides/getting-started.md

I found it would be difficult to review all those changes in one pull request like https://github.com/webpack/webpack.js.org/pull/4099, thus I'm splitting it into small ones. Hopefully we can alleviate the pain of reviewing a lot.
Regarding those diff blocks, I'm using Prettier to format code first, and `git show --no-prefix -U1000 > patch.diff` to generate the diffs. It brought quite a lot of changes to the code blocks which is a pain for reviewer at the moment, but I think these changes are beneficial for future as contributors can share the same tools when updating guides with diff blocks. Before this I have to do it manually as there's no guide how to do it, which is inefficient and error-prone.
https://github.com/chenxsan/webpack-demo …

docs(guides): update getting-started against webpack 5

---

src/content/guides/output-management.md

follow-up of https://github.com/webpack/webpack.js.org/pull/4134
https://github.com/chenxsan/webpack-demo/pull/3
https://webpack-js-org-git-feature-update-output-management.webpack-docs.vercel.app/guides/output-management/

docs(guides): update output-management for webpack 5

---

src/content/guides/asset-management.md
src/content/guides/development.md
src/content/guides/getting-started.md
src/content/guides/output-management.md

I've reread those updated guides today and fixed some small issues.
https://github.com/chenxsan/webpack-demo/pull/5

docs(guides): some fixes

---

src/content/guides/code-splitting.md

https://github.com/chenxsan/webpack-demo/pull/6

docs(guides): update code-splitting against webpack5

---

src/content/api/module-methods.md

1. "when using dynamic imports" – "dynamic" is assumed for `import()` isn't it?
2. You have to manually specify which imports are to be bundled, not just tell it not to bundle unused exports.

docs(api): clarify `webpackExports`' function

---

src/content/configuration/stats.md

In previous versions of `webpack-dev-middleware`, the documentation was correct in expecting `stats` to be passed in the options.
Starting with 4.0.0, this is no longer true. Their [changelog](https://github.com/webpack/webpack-dev-middleware/releases/tag/v4.0.0-rc.0) indicates that the `stats` option is now honored from the main configuration. 
In fact, using their latest package will fail to compile in Typescript if you follow the official webpack docs. This PR opts to remove this advice in accordance with modern usage.

Remove `webpack-dev-middleware` note from stats documentation

---

src/content/api/node.mdx
src/content/concepts/loaders.mdx
src/content/configuration/index.mdx

These had previously been introduced for *.mdx files (see #2917) but seem to no longer be needed. As a result, the rendered output includes redundant escapes that would break file matching, e.g.:
```js
module.exports = {
module: {
rules: [
{ test: /\\.css$/, use: 'css-loader' },
{ test: /\\.ts$/, use: 'ts-loader' }
]
}
};
```
See e.g. [this Stack Overflow question](https://stackoverflow.com/q/64882726/3001761) for resulting confusion.

docs: remove excess backslash escapes

---

src/content/configuration/node.md

The contents for `node` page changed a lot in webpack 5, so I refactor some.
For the sake of review, I've added some comments too.
Preview URL: https://webpack-js-org-git-bugfix-update-node.webpack-docs.vercel.app/configuration/node/

docs(configuration): update node page for webpack 5

---

src/content/guides/typescript.md

This adds a warning with some possibly unknown side-effects of `ts-loader`, and adds a note on how Babel can replace it altogether with the right preset or plugin.

feat: update Loader section

---

.travis.yml

I've enabled the github actions for Pull Requests here https://github.com/webpack/webpack.js.org/blob/master/.github/workflows/testing.yml, and we'll monitor it for a while before migrating those travis jobs running against pull requests to github actions.
As you can see in this PR that I'm currently keeping the job of master branch building to travis as it won't run frequently. Hopefully we can migrate it too in near future.

apply travis only for master branch

---

src/content/configuration/watch.md

The `ignored` property of `watchOptions` no longer accepts an array of `anymatch` patterns, and instead accepts an array of string glob patterns.
This PR updates the `watchOptions.ignored` types to reflect this change. Also adds an additional example.
Closes #11903

docs(watch): Update `watchOptions` types

---

src/content/api/parser.md

I believe `expressionAnyMember` hook was removed in this commit https://github.com/webpack/webpack/pull/9203/files#diff-313038f65941a3a6c139ebe61a484045ace246a429e31975f3606afdd95d977fL97

docs(api): clean obsolete hook

---

.github/workflows/deploy.yml

I've merged a pr here https://github.com/webpack/webpack.js.org/pull/4206, and it deployed our built `dist` to target branch https://github.com/webpack/webpack.js.org/tree/deploy-with-github-actions successfully, which means deploying to `gh-pages` branch should work as well.
After this PR, we'll have two deployments running simultaneously, one from travis, another from github actions, I'm going to monitor both for a while before removing all those travis related code.

deploy to gh-pages

---

.github/workflows/deploy.yml
.github/workflows/testing.yml
src/utilities/fetch-supporters.js

closes https://github.com/webpack/webpack.js.org/issues/4211

fix 503 error from opencollective

---

src/content/concepts/entry-points.md

Hi there! I was stuck on an issue related to having multi entries in the same HTML document, until I stumbled on this line in the docs and wonder why. A google search yield a link to [tooling.report](https://bundlers.tooling.report/code-splitting/multi-entry/#webpack), which finally helped me resolve my issue.
It'd be nice to have this link directly in the tip, or alternatively add a few words explain why; or link to another section of the docs. I found [this section in the code-splitting guide](https://webpack.js.org/guides/code-splitting/#prevent-duplication) relevant, but it did not address the issue as directly as tooling.report.

docs: expand on the 'one entry point tip' tip

---

src/content/api/cli.md

Rephrase description for negated flags.

docs(api): rephrase description for negated flags

---

package.json

The minimum supported Node.js version for [webpack 5 is 10.13.0(LTS)](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#minimum-nodejs-version).

update node engine

---

package.json
yarn.lock

`sitemap-static` depends on a lower version `minimist` which has vulnerabilities, fixed with yarn's `resolutions`.

upgrade minimist

---

src/content/api/cli.md

As per https://github.com/webpack/webpack.js.org/pull/4132#discussion_r519162726
seems `cli.md` is the only file using `sh` - https://github.com/webpack/webpack.js.org/search?q=%60%60%60sh

chore: use bash instead of sh

---

src/content/api/cli.md

`--name` can accept only string value.
https://github.com/webpack/webpack-cli/blob/53ed92616bd6050dccbc07a4a77010faceacc508/packages/webpack-cli/lib/utils/cli-flags.js#L235
https://webpack.js.org/configuration/other-options/#name

docs(api): correct type of --name flag

---

package.json
yarn.lock

Seems like 1.0.1 has bug causing issues like below:
By the way, we should consider eliminating those exotic packages as the code are not in control of this repository.

fix custom blockquote

---

src/content/guides/getting-started.md

Specified the version of webpack in webpack cli in `webpack-4` branch, So when v5 will release the v4 documentation will work fine.
```
npm install webpack  webpack-cli --save-dev
``` 
```
npm install webpack@4.x  webpack-cli@3.x --save-dev
```

Fix of Issue #3572

---

repositories/README.md

Fixes #4298
The link mentioned in repositories/README.md is wrong, `utils` is used instead of `utilities`, but `utils` do not exist in the repo

docs: fix link

---

package.json
yarn.lock

The whole point of introducing `size-limit` is to watch size changes between `master` and pull requests, however it won't work against pull requests from fork https://github.com/webpack/webpack.js.org/pull/4268#issuecomment-739945804, which renders `size-limit` useless in our use case.

remove size-limit

---

src/content/blog/2020-10-10-webpack-5-release.md

Docs(blog) : compilation.cache is deprecated now
Related issue https://github.com/webpack/webpack.js.org/issues/3843

Docs(blog) : compilation.cache is deprecated now

---

src/content/guides/getting-started.md

In the getting started guide, I was confused why a file that was written manually would be included in the `dist/` directory. This pull request explains that eventually `dist/index.html` will be generated manually.

docs(guides): explain why index.html is in dist/

---

src/content/migrate/5.md

The watch argument is deprecated & the runtime error doesn't directly tell you to remove it. 
See https://github.com/webpack/webpack/issues/12218 for context.

Suggest removing watch arg from config

---

src/content/migrate/5.md

Link to new Asset Modules guide in appropriate places.  Per the guide,
> When using the old assets loaders (i.e. file-loader/url-loader/raw-loader) along with Asset Module in webpack 5, you might want to stop Asset Module from processing your assets again as that would result in asset duplication
This means that certain configurations can break under 4->5 migration if they aren't aware of the new Asset Module behavior.

Migration guide should link to Asset Modules guide

---

src/content/api/cli.md

Refers https://github.com/webpack/webpack-cli/issues/2258
with the current version, this behavior is not supported. So removing it to avoid confusion.

docs(api): remove <name>=<request> note regarding entry

---

src/components/Site/Site.jsx

When I open two or more pages, clicking `UPDATE` button will only refresh the current page, while I expect all pages to be refreshed. This pull request should hopefully fix it.

fix service worker not refreshing all pages

---

src/components/Site/Site.jsx

Fixes #4364.
Firefox's private browsing mode does not set the serviceWorker property on the Navigator object. Attempting to use that property without checking for its existence first will cause the entire site to fail to load.
I tested this by running the development server locally and checking that it loads in Firefox's private browsing mode after I added this guard.

fix: Gracefully handle browsers that do not support service workers.

---

.github/CONTRIBUTING.md

Fixes #4366.
This updates the setup instructions in CONTRIBUTING.md to use yarn instead of npm, since the npm instructions don't work anyway.

docs(contributing): Change setup instructions to use yarn.

---

src/content/api/cli.md

now `--version` will show the version of `webpack-dev-server` as well.

docs(api): update --version info

---

src/components/Markdown/Markdown.scss
src/styles/fonts.scss
src/styles/index.scss
src/styles/partials/_vars.scss

Currently we have `Geomanist` for headings, `Source Sans Pro` for body texts, and `Source Code Pro` for code, all of the three fonts are sans-serif, which makes the page boring, and there's not enough contrast between body texts and headings.

replace Geomanist with Source Serif Pro

---

package.json
src/utilities/content-tree-enhancers.js
webpack.common.js
yarn.lock

It seems to me that github readme [supports those `:emoji:` syntax](https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/README.md):
While webpack.js.org doesn't:
This pull request should show those emojis. As it's run in the build stage, `remark-emoji` won't be included in the client side.
https://webpack-js-org-git-fork-chenxsan-feature-enable-emoji-support.webpack-docs.vercel.app/plugins/eslint-webpack-plugin/

replace :emoji: with utf-8 emoji

---

.github/workflows/deploy.yml

The api key was introduced in https://github.com/webpack/webpack.js.org/pull/4214, but it's no longer used.

clean up action

---

src/content/migrate/5.md

The current migration guide for webpack 5 is sort of intimidating:
I've made some improvements to it in this pull request:
https://webpack-js-org-git-fork-chenxsan-feature-migrate-5.webpack-docs.vercel.app/migrate/5/

docs(migrate): improve webpack 5 migration guide

---

src/content/api/compiler-hooks.md

From the source code, I believe [`environment`](https://github.com/webpack/webpack/blob/master/lib/webpack.js#L74) and [`afterEnvironment`](https://github.com/webpack/webpack/blob/master/lib/webpack.js#L75) hooks are called before [`entryOptions`](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L247), [`afterPlugins`](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L545) and [`afterResolvers`](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L571). Although it's not a big deal, I still think it's better to keep the order right since user might take it for granted that the former one runs before the latter .

docs(api): update orders of compiler hooks

---

src/components/Site/Site.jsx
src/components/mdxComponents/Link.js

Improve website performance.
Let's take this page for example https://webpack.js.org/api/node/.
Open devtools and click the link in the screenshot below:
Here's the network panel:
Even with service worker, we still have a lot of requests.
Now let's open the preview of this pull request https://webpack-js-org-git-fork-chenxsan-feature-use-react-route-5aabb7.webpack-docs.vercel.app/api/node/, and click the same link:
That's impressive isn't it?
This website is a Single Page React Application with precompiled HTML, but links in body are rendered as `<a>` elements, which would cause browser to load a whole new html page. When we render them as `Link` from `react-router`, it would dynamic load the needed part instead of loading a new html page, and it's possible with `MDX`. Guess this is a …

customize Link for mdx

---

src/components/Support/Support.jsx

There're chances `supporters.length` would be smaller than `random`, which would causing `undefined` value in `supporters` array. For example, I would create an empty `_supporters.json` because I don't want to fetch supporters data when developing locally, which then cause error:

fix bug for Support

---

src/content/api/cli.md

explain the usage of the `--config-name` option.
Open to suggestions.

docs(api): explain --config-name usage

---

src/components/Markdown/Markdown.scss

See the changelog of `sass` here https://github.com/webpack/webpack.js.org/pull/4402:
> Deprecate passing non-% numbers as lightness and saturation to hsl(), hsla(), color.adjust(), and color.change(). This matches the CSS specification, which also requires % for all lightness and saturation parameters. See [the Sass website][color-units] for more details.

fix(app): Deprecated Sass api

---

cypress/integration/pr_4435_spec.js
src/components/SidebarItem/SidebarItem.jsx

If user cmd+clicks (or ctrl+clicks) a link in the sidebar, the linked page opens in a new page, and the current tab should not scroll to the top.

Don't scroll to top if link was opened in new tab

---

src/content/contribute/writing-a-loader.md

fix(docs): expose errors details in loader example

---

src/content/configuration/index.mdx

as-is
```
sourcePrefix: "\t"
// prefix module sources in bundle for better readablitity
```
to-be
```
sourcePrefix: "\t"
// prefix module sources in bundle for better readability
```

docs(configuration): fix a misspelled `output.sourcePrefix`'s description.

---

src/content/guides/production.md

The page still mentioned `-p` and `--optimize.minimize`. `-p` was removed (https://github.com/webpack/webpack.js.org/issues/4465#issuecomment-764782482) and `--optimize.minimize` was renamed to `--optimization-minimize`.

Rewrite old content about `-p` and `--optimize.minimize`

---

src/content/api/compiler-hooks.md
src/content/api/contextmodulefactory-hooks.md
src/content/api/normalmodulefactory-hooks.md
src/content/api/parser.md
src/content/api/plugins.md
src/content/api/resolvers.md

- Add pages NormalModuleFactory Hooks and ContextModuleFactory Hooks.
- Add links to new pages in Compiler Hooks.
- Update Sort values to keep alphabetical order within Plugin sub-menu.
I am ready to work further on any bugs/improvements.

docs(api): add pages for NormalModuleFactory and ContextModuleFactory Hooks

---

src/content/api/cli.md

update commands
Refers - https://github.com/webpack/webpack-cli/pull/2303 https://github.com/webpack/webpack-cli/pull/2357

docs(api): update commands

---

src/components/SidebarItem/SidebarItem.jsx
src/components/SidebarItem/SidebarItem.scss
src/styles/dark.scss

As I mentioned in https://github.com/webpack/webpack.js.org/pull/4413:
> The Bold style can be used for highlighting active menu item later.

highlight current menu

---

src/content/api/module-methods.mdx
src/content/configuration/module.mdx

closes https://github.com/webpack/webpack.js.org/issues/4470

docs(configuration): document webpackIgnore for commonjs

---

src/components/Badge/Badge.scss

The current `Badge` is too large compared to other body texts when we use it a lot:

optimize Badge style

---

src/content/guides/integrations.md

the 5.0.0 release of karma-webpack
requires a framework to be set and
the plugin to be defined. There is
also no support for webpackMiddleware
Fixes N/A

docs(karma-webpack): update for 5.0.0

---

src/content/configuration/output.mdx
src/content/guides/public-path.md

fixes https://github.com/webpack/webpack.js.org/issues/4491
add `output.publicPath: 'auto'`

docs: add output.publicPath: 'auto'

---

src/components/Site/Site.jsx

No need to duplicate `blog` link:

hide blog from sub navbar

---

src/content/configuration/dev-server.md
src/content/guides/development.md

Clarify root path for generated files
Related: https://github.com/webpack/webpack-dev-server/issues/2982

docs(dev-server): clarify root path for generated files

---

src/content/api/loaders.md

According to @sokra `this._compilation` should not be deprecated.
Therefore I moved it into the "webpack specific properties" section

docs: remove deprecation of the loader this._compilation api

---

src/content/api/loaders.md

Follows-up of https://github.com/webpack/webpack.js.org/pull/4557

docs(api): move this._compiler

---

src/content/loaders/index.md
src/utilities/constants.js

It's already deprecated under webpack 5 as per https://github.com/webpack-contrib/json5-loader.

exclude deprecated json5-loader

---

cypress/integration/pr_4435_spec.js
src/components/Page/Page.jsx
src/components/SidebarItem/SidebarItem.jsx

This website is a Single Page React Application with precompiled HTML, but links in sidebar are rendered as [`<a>`](https://github.com/webpack/webpack.js.org/blob/master/src/components/SidebarItem/SidebarItem.jsx#L31) elements at the moment, which would cause browser to load a whole new html page. When we render them as `NavLink`, it would dynamic load the needed part instead of loading a new html page which could load the page faster.

use NavLink for SidebarItem

---

src/content/configuration/configuration-types.md

Refers https://github.com/webpack/webpack.js.org/issues/4587
Add information about the `parallelism` option on the configuration array.

docs: add info about the parallelism with multiple configurations

---

src/content/configuration/configuration-types.mdx

Follows-up of https://github.com/webpack/webpack.js.org/pull/4593 as it's a feature available in webpack 5.22.0.

docs(configuration): add version

---

.eslintrc.js
package.json
yarn.lock

We're likely to have many hook usages, hence enable the[ eslint plugin](https://reactjs.org/docs/hooks-rules.html#eslint-plugin) to catch potential issues.

enable eslint-plugin-react-hooks

---

src/content/configuration/mode.md

fix tip.
`NODE_ENV` can automatically set `mode`.
Reference -  https://github.com/webpack/webpack-cli/blob/4c786e39f342414948c9620f128f67f8b1e821e2/packages/webpack-cli/lib/webpack-cli.js#L1527-L1536

docs(configuration): fix tip for mode option

---

src/content/plugins/internal-plugins.mdx

`SingleEntryPlugin` is deprecated and also renamed to `EntryPlugin`.
https://github.com/webpack/webpack/blob/32bd1a2ff53c6b7fbf99d0e473d6db98f9e3a3f2/lib/index.js#L248

docs(plugin): add EntryPlugin

---

src/content/guides/environment-variables.md

Update environment-variables guide.
Add tip about built-in env variables offered by webpack-cli

docs(guides): add tip about CLI env vars

---

src/content/configuration/output.mdx

1. Refactor the large block of text into list and headings. It's much readable now, and users can link to specific `libraryTarget`.
2. Document `libraryTarget: 'module'`.
Preview url https://webpack-js-org-git-fork-chenxsan-feature-librarytarget.webpack-docs.vercel.app/configuration/output/#outputlibrarytarget

docs(configuration): refactor libraryTarget

---

src/content/configuration/dev-server.md

Use `npx` prefix for commands, as used in CLI docs.

docs(configuration): use npx for CLI usage

---

src/content/configuration/dev-server.md

`--hot only` is not yet supported by CLI.
correct usage `webpack serve --hot-only`

docs(configuration): fix CLI usage for devsServer.hotOnly

---

src/content/api/module-variables.mdx

`__webpack_hash__` can always be used, and runtime code is injected where needed.
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#minor-changes

docs(api): update module variable usage info

---

cypress/integration/pr_4435_spec.js
src/components/Page/Page.jsx

When we click the same menu item on sidebar again and again, the `key` value of `location` changes all the time which would cause the page to invoke unnecessary scroll effect.

reduce scroll effect

---

src/content/api/compilation-object.md
src/content/api/module-variables.mdx

https://webpack.js.org/blog/2020-10-10-webpack-5-release/#other-minor-changes

docs(api): remove stale compilation-object methods

---

src/content/api/compilation-hooks.mdx

https://webpack.js.org/blog/2020-10-10-webpack-5-release/#other-minor-changes

docs(api): add beforeModuleHash compilation hook

---

src/content/configuration/dev-server.md

correct usage - `webpack serve --allowed-hosts host1.com --allowed-hosts host2.com`

docs(configuration): fix --allowed-hosts usage

---

src/content/api/compilation-hooks.mdx

1. Add `afterModuleHash` hook
2. Fix misleading description

docs(api): add afterModuleHash

---

cypress/integration/click-menu-scroll-top_spec.js
cypress/integration/pr_4435_spec.js
src/components/SidebarItem/SidebarItem.jsx

Regression in https://github.com/webpack/webpack.js.org/pull/4613 and https://github.com/webpack/webpack.js.org/pull/4613 combined.
Say we open https://webpack.js.org/concepts/plugins/ and scroll to page end, click the `Plugins` menu item should scroll page to top.
Another case is already handled by `useEffect` in [`Page.jsx`](https://github.com/webpack/webpack.js.org/blob/master/src/components/Page/Page.jsx#L49), i.e., open https://webpack.js.org/concepts/plugins/#usage, and click the `Plugins` menu item should scroll page to top.

fix scroll edge case

---

src/content/configuration/output.mdx

There was a typo. There is no `output.experimentals`. It must be `output.experiments`.

Fix a typo in `output` option

---

src/content/configuration/configuration-languages.md

Improved the example in configuration languages for typescript to include the necessary “import 'webpack-dev-server';”. 
This one line would have saved me some time. I hope it will help someone else.

Added the necessary import 'webpack-dev-server' to configuration-languages for typescript

---

src/content/configuration/dev-server.md

Hi! If you want to use own https certificate for hmr with devServer you should pass cert & key in the devServer.https object not just root devServer object.

Fix https settings for own certs

---

src/content/guides/code-splitting.md

The first sentence in line 410 is missing an article before `ChartingLibrary`.

docs: fix missing article

---

src/components/Markdown/Markdown.scss

We used a hack in this pull request https://github.com/webpack/webpack.js.org/pull/3901 to work around visibility problem of headers' anchor under safari. However I found that it caused a problem when the headings are used inside list under safari:
This pull request introduced a hack to fix the problem.
Preview url: https://webpack-js-org-git-fork-chenxsan-bugfix-fix-safari-list-87fc48.vercel.app/configuration/output/#expose-a-variable

fix position of list marker for safari

---

src/components/Markdown/Markdown.scss

This reverts commit 8b39b6915879603c26ec776a2c1a7eb32de0d7f7.
Unfortunately the latest commit introduced the visibility problem for headings' anchor again. I'll file an issue to track the problem as I don't know how to fix it for safari now. We might have to avoid using headings in list item.

Revert "fix position of list marker for safari (#4713)"

---

src/content/configuration/output.mdx

We used a hack in this pull request https://github.com/webpack/webpack.js.org/pull/3901 to work around visibility problem of headers' anchor under safari. However I found that it caused a problem when the headings are used inside list under safari:
This pull request moves the headings out of list to work around the problem, it's not a real fix, and I don't think there's one until safari fix it.

docs(configuration): avoid using headings in list

---

src/content/configuration/output.mdx

I believe that the leading slash in the `keep` property does not prevent the directory from being deleted. 
I didn't test the *hook* option.

docs(output): remove leading slash

---

src/content/guides/asset-modules.md

Added a missing comma. Used trailing comma to match prior rule.

docs(asset-modules): Fix syntax error

---

src/content/contribute/writing-a-plugin.md

[webpack v5](https://github.com/webpack/webpack/blob/ee09a9609bdebc25e52e785cef56f9698805599d/package.json#L26) uses the latest release of [schema-utils](https://github.com/webpack/schema-utils).

docs(contribute): update schema-utils usage info

---

src/content/configuration/dev-server.md

To be merged after https://github.com/webpack/webpack-cli/pull/2438

docs: add link for serve CLI options

---

src/content/plugins/watch-ignore-plugin.md

Closes https://github.com/webpack/webpack.js.org/issues/4743.

docs(plugins): fix watch-ignore-plugin

---

src/content/api/cli.md

The reference article is no longer present. - https://medium.com/@ahmedelgabri/analyzing-optimizing-your-webpack-bundle-8590818af4df#.hce4vdjs9

docs: remove inactive refernce link

---

src/content/api/cli.md

add documentation for `npx webpack configtest` command

docs(api): add documentation for configtest command

---

src/content/configuration/module.mdx

Document the `emit` added in https://github.com/webpack/webpack/pull/12871.

docs(configuration): document emit

---

src/content/api/node.mdx

The API doc is not very clear regarding the need to call compiler.close() after compiler.run() (only the changelog was).
It seems to me important because persistent cache won't be flushed otherwise. 
Also important to show that the callback takes an error that may be thrown if persistent caching fails.
Preview link: https://webpack-js-org-git-fork-slorber-patch-3-webpack-docs.vercel.app/api/node/#run

Document compiler.run() needs compiler.close()

---

src/content/api/cli.md

link `configtest` command to it's documentation.

docs: add link for configtest command

---

src/content/configuration/dev-server.md

Update documentation for `devServer.allowedHosts`,
I see comma-delimited string was accepted by old cli version.

docs: update devServer.allowedHosts

---

src/content/configuration/module.mdx

Document the new `generator.publicPath` config introduced in webpack 5.28.0 https://github.com/webpack/webpack/releases/tag/v5.28.0, related pull request https://github.com/webpack/webpack/pull/12902

docs(configuration): document generator publicPath

---

src/content/api/cli.md

Added and env var to disable local import
https://github.com/webpack/webpack-cli/pull/2546

cli: add env var doc

---

src/content/api/hot-module-replacement.md

I believe it should be `can't be handled` instead of `can be handled` as we were talking about `decline` of HMR api.

docs(api): fix typo

---

src/content/guides/installation.md

There's a point in the docs about installing Webpack-CLI. I've never installed this nor is it required. It's my understanding this is only required if you're running `webpack` in the command line rather than calling `webpack(config)` directly in Node.js.
As a separate piece, there _is_ a bug where, for every config I pass to `webpack()`, it outputs this message to `stats`:
```sh
-----
CLI for webpack must be installed.
webpack-cli (https://github.com/webpack/webpack-cli)
-----
-----
We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
-----
-----
Do you want to install 'webpack-cli' (yes/no):
-----
```
That's a separate issue.

📝 Clarified point about requiring webpack-cli under Installation

---

src/content/guides/environment-variables.md

This leads to confusion with `process.env` resp env variables, which is not the same

NODE_ENV should not be used for `env`

---

src/styles/index.scss

This reverts commit 9f175182784a08d1f6f8c917657bda48cb6c689c.
Generally I think it's a good idea to differentiate external links from internal ones, however the current solution introduced problems like below:
Hence I'm reverting it at the moment until we figure out a much better solution.

Revert "ui(page): show icon for external links (#4802)"

---

src/content/contribute/writers-guide.md

Rationale: The link is currently rendered including the `)`, see https://webpack.js.org/contribute/writers-guide/#adding-links

doc(writers-guide): linkfix

---

src/content/configuration/dev-server.md

No longer supported in `webpack-dev-server@latest`.
https://github.com/webpack/webpack-cli/issues/2606

docs(configuration): remove --info for dev server

---

src/content/configuration/dev-server.md

`--no-live-reload` is an invalid option. Only `--liveReload` is allowed.

docs(configuration): fix liveReload cli usage

---

src/content/configuration/dev-server.md

Valid - `npx webpack serve --open --open-page different/page1 --open-page different/page2`

docs(configuration): fix openPage usage

---

src/content/configuration/dev-server.md

Refer https://github.com/webpack/webpack-dev-server/blob/v3/bin/cli-flags.js#L67

docs(configuration): fix `--useLocalIp` usage

---

src/content/api/cli.md

docs(api): fix default value for `template` option

---

src/content/api/loaders.mdx

`Inline matchResource` is not a child of `Error Reporting`:

docs(api): fix heading level

---

src/content/api/compiler-hooks.md

Addresses issue #4813 where we identified that a compiler hook example was referencing stale code from a private repository.
As discussed in the issue, it was advised to remove the link from the docs.

Remove outdated example for compiler hook usage

---

src/content/configuration/dev-server.md

Correct usage - `npx webpack serve --inline`

docs(configuration): fix `--inline` usage

---

src/content/api/cli.md

Fix tip.
`webpack --target node ./entry.js` =>  `target: ['node', './entry.js']`

docs(api): fix tip for entry

---

src/content/plugins/define-plugin.md
src/content/plugins/define-plugin.mdx

New DefinePlugin options

---

src/content/configuration/other-options.mdx

`pack` is the only supported mode for `cache.store` since webpack `5.0.x`.
#3393

docs(configuration): remove warning regarding cache properties usage

---

src/content/concepts/entry-points.md

Fix https://github.com/webpack/webpack.js.org/issues/4873
Should we also add some example? Already linked to `output.publicPath` which contains a ton

docs: add public path in entry descriptor

---

src/content/api/cli.md

Fix reference, It's `output-path` and not `output`.
Also, avoid using an alias as `-o` can be easily interpreted as `--output` while is actually `--output-path`.

docs(api): update `--output-path` references

---

src/content/configuration/dev-server.md

Add warning that `liveReload` doesn't work with non-web targets. 
For new webpack users who don't have much idea about the configuration -
https://github.com/webpack/webpack-dev-server/issues/2026#issuecomment-502450338

docs(configuration): add warning for `liveReload`

---

src/content/api/cli.md

Update the example to use `info` instead of `init` as `init` was moved to `@webpack-cli/generators`

docs(api): update example for version command

---

src/content/api/cli.md

Add an advanced usage example. This will clarify --env only split from first `=`

docs(api): add example with multiple `=` for `--env`

---

src/content/guides/typescript.md

This is about the example tsconfig.json file used in the webpack typescript guide.
By default, "moduleResolution" is set to "classic". When using "module": "es6", this does not allow importing lodash (or any module) in the way described in this guide. Setting it to "node" instead fixes the issue (and I double checked - this is compatible with "module": "commonjs" as well). This setting is the industry standard; https://www.typescriptlang.org/docs/handbook/module-resolution.html
P.S. webpack is awesome, and the docs are great, many thanks!

docs(typescript guide) set "moduleResolution" to "node" in tsconfig.json

---

src/content/configuration/other-options.mdx

docs(configuration): use consistent format

---

src/content/migrate/5.md

I tried to make more clear and obvious `browserslist` feature. I did it because after reading the guide I did not remove `target: 'web'` in my config, because I thought, that `browserslist` will apply automatically in this case. But it did not happen and my service crashed in ie11. So I hope that with my tip people will check this setting in their projects.

Make clearer browserslist feature

---

src/content/guides/web-workers.mdx

It's sort of misleading to say `CommonJS is not supported by neither webpack nor Node.js.`. Thanks @QC-L for heads-up.

docs(guides): fix misleading content

---

src/content/configuration/output.mdx

Related PR #4691.
Preview URL: https://webpack-js-org-git-fork-vsn4ik-output-library-umd-named-508c51.vercel.app/configuration/output/#outputlibraryumdnameddefine

docs(configuration): output.library.umdNamedDefine example fix

---

src/content/api/cli.md

`ENV environment variables` here double `env` can be misleading. 
I found `Configuration Environment Variables` more suitable. 
Open to suggestions.

docs(api): improve heading

---

src/components/Markdown/Markdown.scss

closes https://github.com/webpack/webpack.js.org/issues/4388
We no longer have this icon fonts.

fix missing icon

---

src/content/api/cli.md

Fix https://github.com/webpack/webpack.js.org/pull/4881/
Fix #4851

docs(api): add alias for `init` and `serve` commands

---

src/content/guides/asset-modules.md

According to https://github.com/webpack/webpack/blob/c876b0ee4ec9d1e6dbdcc9e3eecf1db9824fbade/types.d.ts#L9637, the type of `not` should be `RuleSetCondition[]`.

docs(guides): fix condition

---

package.json
yarn.lock

We have a problem when using the latest webpack-dev-server v4 beta with react-refresh-webpack-plugin, see https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/391. It's fixed in the next version of `react-refresh-webpack-plugin`.

upgrade react-refresh-webpack-plugin

---

src/content/guides/csp.md

Added Trusted Types section to the Content Security Policies Guide (since Trusted Types restrictions are controlled by CSP, some users might be looking for Trusted Types info in the CSP guide). The section simply refers the users to the `output.trustedTypes` option documentation added in https://github.com/webpack/webpack.js.org/pull/4961.

Added Trusted Types section to CSP guide.

---

src/content/plugins/ignore-plugin.md

Replace invalid IgnorePlugin option `requestRegExp` with `resourceRegExp`.

docs(plugins): fix invalid option in IgnorePlugin

---

src/content/configuration/dev-server.md

v3 still support `setup`. dropped in `v4`
https://github.com/webpack/webpack-dev-server/blob/v3/lib/options.json#L334

docs(configuration): update devServer.setup warning

---

src/content/concepts/module-federation.md

Add tips to the documentation on how to dynamically set publicPath for module federation. 
Credits to @sokra for providing the solution in [#10703](https://github.com/webpack/webpack/pull/10703#issuecomment-617822314)

docs :added tips on dynamic public path use case in module federation

---

src/content/api/cli.md

Add link for `init` - https://github.com/webpack/webpack-cli/blob/master/INIT.md#description-of-questions-asked-by-the-generator.

docs(api): add link for init

---

webpack.ssg.js

Unfortunately the plugin https://github.com/bebraw/redirect-webpack-plugin/blob/master/index.js#L14 won't support redirect from fragment to fragment.

fix redirect

---

src/content/configuration/module.mdx
src/content/guides/asset-modules.md

Closes https://github.com/webpack/webpack.js.org/issues/4996

docs(guides): document data urls support in new url

---

src/content/configuration/dev-server.md

In v4 - https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L233

docs(configuration): update clientLogLevel warning

---

src/content/plugins/index.md

Someone changed the url from `https://github.com/webpack-contrib/npm-install-webpack-plugin` to `https://github.com/webpack-contrib/install-webpack-plugin`, causing [the CI failure](https://github.com/webpack/webpack.js.org/pull/5060/checks?check_run_id=2798702524#step:9:8).

docs(plugins): fix broken link

---

src/components/StackBlitzPreview/StackBlitzPreview.jsx

Fixes the URL of the StackBlitz button.

fix: url for StackBlitz button

---

src/components/Footer/Footer.jsx

The usage of Google Analytics requires a privacy policy. Since webpack is an openjs foundation project, we can just add a link to its privacy policy instead of creating one ourselves.

add a link to privacy policy

---

src/content/api/cli.md

`INIT.md` was moved.
New link - https://github.com/webpack/webpack-cli/blob/master/packages/generators/INIT.md

docs(api): update `init` link

---

src/utilities/process-readme.js

See https://webpack.js.org/plugins/image-minimizer-webpack-plugin/:
Generally I don't think it's necessary to replace [this html](https://raw.githubusercontent.com/webpack-contrib/image-minimizer-webpack-plugin/master/README.md):
```html
<div align="center">
<a href="https://github.com/webpack/webpack">
src="https://cdn.rawgit.com/webpack/media/e7485eb2/logo/icon.svg">
</a>
<h1>Imagemin Webpack</h1>
<p>
Plugin and Loader for <a href="http://webpack.js.org/">webpack</a> to optimize (compress) all images using <a href="https://github.com/imagemin/imagemin">imagemin</a>.
Do not worry about size of images, now they are always optimized/compressed.
</p>
</div>
```

fix process-readme for html code

---

src/utilities/constants.js

`closure-webpack-plugin` doesn't support webpack 5 at the moment as per https://github.com/webpack-contrib/closure-webpack-plugin/issues/161. We can add it back once it's webpack 5 ready.

exclude closure-webpack-plugin

---

examples/module-federation/.stackblitzrc
src/content/concepts/module-federation.mdx
src/content/plugins/module-federation-plugin.mdx

This PR fixes the link when clicking on the StackBlitz button. It will install the dependencies, run the `npm start` command and open a second blank terminal.
I also removed the `.stackblitzrc` because it's covered by the query parameters and allows more flexibility like opening a second or third terminal and what not. So in this case, the `.stackblitzrc` is not needed.

docs(examples): fix StackBlitz example for module federation

---

src/components/Contributors/Contributors.scss

The later one would be much cleaner.

remove shadow from contributor name

---

src/components/Contributors/404.js
src/components/Contributors/Contributors.jsx

Some contributors are 404 on github now, it would be better to hide them from the webpage,
Note that we're still keeping them in the source file.

hide 404 contributors from page

---

cypress/integration/toggle-dark-mode_spec.js
src/components/Navigation/Navigation.jsx
src/components/Site/Site.jsx

There's a bug in the dark mode. Here's how to reproduce,
1. open webpack.js.org in incognito mode
2. click the dark mode toggle button twice
3. now you should see:
Here's the culprit:
`dark` class should be removed on second click.

fix dark mode bug

---

src/content/configuration/output.mdx

The output options are not sorted alphabetically at the moment.
Since the reorder will bring in a lot of changes which would be a pain for downstream (Korean translation repository and the Chinese translation repository) to merge, I'll do it in multiple small pull requests.
I'm listing those options which are moved in this pull request just in case the downstream want to check it:
1. output.assetModuleFilename
2. output.chunkFormat
Just two actually, although it seems a lot from the diff.

docs(configuration): sort output options alphabetically

---

src/content/guides/lazy-loading.md

React documentation has a guide on code-splitting and lazy load. Webpack documentation referring to a different guide. It's always good to use the official React guide like done for the other frameworks.

Changed React code splitting guide to official documentation.

---

src/components/Navigation/Navigation.jsx

Seems the `NavLink` won't work with external url https://github.com/ReactTraining/react-router/issues/1147, although our repository doesn't use any external urls in navigation, the downstream translation repositories might use it. Thus it's better to fix it here.

fix Navigation for external url

---

src/content/configuration/output.mdx

A follow-up of https://github.com/webpack/webpack.js.org/pull/5141.
Two options are moved in this pull request: 
1. `output.clean`
2. `output.crossOriginLoading`

docs(configuration): sort options alphabetically

---

cypress/integration/search_spec.js

Seems the original test [is not stable](https://github.com/webpack/webpack.js.org/pull/5189/checks?check_run_id=3095359165) because of the asynchronous responds from aligolia.

update e2e test

---

src/components/Navigation/Navigation.jsx

Closes https://github.com/webpack/webpack.js.org/issues/4824
Just a workaround as I don't receive any response so far regarding who owns the algolia account for webpack documentation.
The search result won't be redirected to webpack.js.org now, however since the it's searching from webpack v5 document instead of v4, the result might be wrong sometimes. But better than now as far as I see.

transform data for docsearch

---

src/content/plugins/module-federation-plugin.mdx

Fix a wrong reference in MF plugin example.
The example is about sharing react, but refer incorrectly to deps.lodash instead of deps.react.

fix a wrong reference in MF plugin example

---

package.json
src/components/Page/Page.jsx
src/content/api/hot-module-replacement.mdx
src/content/api/loaders.mdx
src/content/api/module-methods.mdx
src/content/api/stats.mdx
src/content/concepts/module-federation.mdx
src/content/configuration/configuration-languages.md
src/content/configuration/output.mdx
src/content/plugins/banner-plugin.md
src/content/plugins/commons-chunk-plugin.md
webpack.common.js
yarn.lock

The original implementation is not reliable. For example, If you have no `contributors` set, it will remove the body content - that's why I'm setting a contributor in this pull request https://github.com/webpack/webpack.js.org/pull/5196/files#diff-d4955ef097d8d259b30b6ad0f4f431329b8c86b4f95973996fc62f23221f2a11. But in that case we don't really want `contributors` field in the front matter section.

remove frontmatter reliably

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

1. upgrade to `actions/setup-node@v2`
2. use its built-in `cache` option which should fulfill our demand without the complexity of `actions/cache@v2`.

upgrade actions/setup-node@v2

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

Node.js 14 is the active LTS https://nodejs.org/en/about/releases/ while 12 enters maintenance stage.

use node 14

---

package.json
src/styles/tailwind.css
yarn.lock

There's no need to set a width now that `docsearch` has fixed the [flash problem](https://github.com/algolia/docsearch/pull/1033).

upgrade docsearch

---

src/content/configuration/stats.mdx

`--colors` is no longer valid. `--stats-colors` is the latest option.

docs(configuration): use `--stats-colors`

---

src/utilities/fetch-supporters.js

We don't use any api key for opencollective at the moment, which means it's easy to hit the api limit defined here https://github.com/opencollective/opencollective-api/blob/main/server/routes.js#L75:
> // 10 requests / minute / ip for anonymous requests
And it's failing the CI now https://github.com/webpack/webpack.js.org/actions/runs/1083925129.
This pull request would query its api less often to avoid hitting the api limit.

fix ci failure

---

.github/workflows/testing.yml

Currently the action would run twice for branches on this repository, one for `push`, another for `pull_request`, the former is not necessary as the latter should fulfill our demand:
Note that it's not a problem for pull requests from forked repositories.

optimize action

---

src/content/configuration/experiments.mdx

closes https://github.com/webpack/webpack.js.org/issues/5274

docs(configuration): document buildHttp

---

package.json

Pages like https://github.com/webpack/webpack.js.org/pull/5275 might have many broken links, we should detect them as well.

detect all broken links

---

package.json

Enabling external links detection would take us [more than 11m](https://github.com/webpack/webpack.js.org/pull/5285/checks?check_run_id=3290319887) to finish the CI, I don't think it's a good idea. We have to manually review the pr https://github.com/webpack/webpack.js.org/pull/5275.

Revert "detect all broken links (#5284)"

---

src/components/Footer/Footer.jsx
src/content/awesome-webpack.md
src/content/loaders/index.md
src/content/migrate/4.md
src/content/plugins/index.md

Fix https://github.com/webpack-contrib/awesome-webpack/issues/188

Add new page for awesome-webpack

---

src/content/configuration/other-options.mdx

Add defaults as per -
https://github.com/webpack/webpack/blob/400a0f94ab45ca20b10f219c8311e87d3d3f108c/lib/config/defaults.js#L1173

docs: add `debug` and `level` default for `infrastructureLogging`

---

src/content/migrate/5.mdx

**Upgrade webpack to 5** is the next step, and we can only use `optimization.moduleIds: 'hashed'` in v4

Fix optimization.moduleIds setting in 5.mdx

---

src/content/configuration/resolve.mdx

docs(configuration): remove `enforceModuleExtension` from resolve and resolveLoader

---

src/content/loaders/index.mdx
src/utilities/constants.js
webpack.ssg.js

Those are deprecated repositories.

Deprecate loaders

---

src/content/configuration/performance.mdx

Sort `performance` options and fix heading levels

docs(configuration): sort `performance` options

---

src/content/configuration/dev-server.mdx

update the link to v4 options.

docs(configuration): update link for `serve` options

---

src/content/configuration/dev-server.mdx

add `devServer.setupExitSignals` to documentation.

docs(configuration): add `devServer.setupExitSignals`

---

src/content/concepts/module-federation.mdx

Closes https://github.com/webpack/webpack.js.org/issues/5308

docs(concepts): close issue #5308

---

src/content/configuration/module.mdx

Due to path.resolve not adding a trailing slash automatically, building a Condition using it might apply to more than the user expects. Modified the example slightly and added some comments to it.

Clarify use of paths in Condition

---

src/content/configuration/dev-server.mdx

Add link for migration guide. 
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

docs(configuration): add link to migration guide for devServer v4

---

src/content/guides/code-splitting.mdx

The **Further Reading** section on https://webpack.js.org/guides/code-splitting/ has a dangling `&gt;`:
Fixing this by converting the HTML entities to the actual angle brackets:
**Note:** The last item in this list completely omits the `<link>` and just mentions `rel="preload"`, so it could also be a good idea to standardize either using a `<link>` or not.

Fix related link format

---

src/content/configuration/dev-server.mdx

Fix typo `--open-aoo-name` to `--open-app-name`

Fix --open-aoo-name typo

---

examples/module-federation/app1/package.json
examples/module-federation/app1/webpack.config.js
examples/module-federation/app2/package.json
examples/module-federation/app2/webpack.config.js
src/content/configuration/dev-server.mdx
src/content/configuration/index.mdx
src/content/contribute/writers-guide.mdx
src/content/guides/development.mdx
src/content/guides/hot-module-replacement.mdx
src/content/guides/production.mdx

`contentBase` has been deprecated by `static`. This changes the docs accordingly so people will be able to read up-to-date docs.

docs: replace contentBase by static

---

src/content/api/hot-module-replacement.mdx
src/content/awesome-webpack.mdx
src/content/configuration/experiments.mdx
src/content/configuration/index.mdx

made corrections to the typos i have found in the documentations.

docs: fix typos in content/

---

src/content/configuration/dev-server.mdx

It should be `server.server.address()`

docs(configuration): fix typo in `devServer.onListening` usage

---

src/content/configuration/dev-server.mdx

Now both accept only one argument `devServer`.
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1024
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1042

docs(configuration): update `onAfterSetupMiddleware` and `onBeforeSetupMiddleware`

---

src/content/configuration/dev-server.mdx

add more commands for CLI usage for webpack-dev-server

docs(configuration): add more commands for CLI usage of devServer

---

.github/dependabot.yml

The default limit is 5, currently we have [5 of them](https://github.com/webpack/webpack.js.org/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies) which can't be merged because of the ESM compatibility problem.

set limit for dependabot to 10

---

src/content/concepts/index.mdx

Added a brief blurb to explain what bundles are. Rewording to indicate the relationship between the dependency graph and bundle generation.
The first warning under Loaders was confusing because it references an ability to import modules as if this was mentioned previously in the article. It wasn't. Rewording to make webpack the subject of the sentence.
Rewording to show that the html-webpack-plugin in the code example injects the bundles into the generated html file. Before, the article made it seem as if injecting bundles was somehow a necessary step to creating an html file. …

Small improvements to readability in index.mdx

---

src/content/guides/hot-module-replacement.mdx

Refers https://github.com/webpack/webpack-dev-server/issues/3698

docs(guides): update HMR guide

---

src/content/api/compilation-hooks.mdx
src/content/api/compiler-hooks.mdx
src/content/api/hot-module-replacement.mdx
src/content/api/loaders.mdx
src/content/api/module-methods.mdx
src/content/api/module-variables.mdx
src/content/api/node.mdx
src/content/concepts/module-federation.mdx
src/content/configuration/dev-server.mdx
src/content/configuration/devtool.mdx
src/content/configuration/entry-context.mdx
src/content/configuration/externals.mdx
src/content/configuration/module.mdx
src/content/configuration/node.mdx
src/content/configuration/optimization.mdx
src/content/configuration/output.mdx
src/content/configuration/plugins.mdx
src/content/configuration/resolve.mdx
src/content/configuration/target.mdx
src/content/configuration/watch.mdx
src/content/guides/code-splitting.mdx
src/content/guides/dependency-management.mdx
src/content/guides/package-exports.mdx
src/content/migrate/3.mdx
src/content/plugins/dll-plugin.mdx
src/content/plugins/environment-plugin.mdx
src/content/plugins/limit-chunk-count-plugin.mdx
src/content/plugins/split-chunks-plugin.mdx

Avoid `code(``)` in heading as it has different font family and also for consistency throughout the docs

docs: avoid code in heading

---

src/content/api/cli.mdx

add troubleshooting with typescript ECMA modules.
Resolve https://github.com/webpack/webpack-cli/issues/2916

docs(api): add troubleshooting with typescript ECMA modules

---

src/content/configuration/dev-server.mdx

Add default for `devServer.historyApiFallback`.
https://github.com/webpack/webpack-dev-server/blob/0ba652a9d8bac9544c85f79dd8aceeb2b74c27c4/lib/Server.js#L499

docs(configuration): add default value for `historyApiFallback`

---

src/content/configuration/dev-server.mdx

add default value for `devServer.hot`.
https://github.com/webpack/webpack-dev-server/blob/79e4bd73655dd20f7ee117091a6762c7f645dac3/lib/Server.js#L509

docs(configuration): add default value for `hot` option

---

src/content/configuration/dev-server.mdx

add the default value for the `bonjour` option.
https://github.com/webpack/webpack-dev-server/blob/d4282dc2f6858b2768658fbc091660bdd704cb05/lib/Server.js#L434

docs(configuration): add the default value for the `bonjour` option

---

src/content/configuration/dev-server.mdx

Move CLI usage close to the related configuration, like the rest of the options.

docs(configuration): update `https` and `historyApiFallback`

---

src/content/configuration/dev-server.mdx

Move CLI usage close to the related configuration, like the rest of the options.

docs(configuration): update `devServer.http2`

---

src/components/Configuration/Configuration.jsx

`className` for `pre` is missing now:
Should be something like `language-diff` etc. I believe it's a bug introduced when migrating to mdx.

fix missing classNames for pre

---

src/content/configuration/dev-server.mdx

add an example configuration for `devServer.headers` as function.

docs(configuration): add example for `devServer.headers` as function

---

src/content/configuration/dev-server.mdx

fix typo in CLI usage, `--https--cert` -> `--https-cert`

docs(configuration): fix `https` CLI usage

---

src/content/configuration/dev-server.mdx

add CLI usage for `devServer.port`

docs(configuration): add CLI usage for `devServer.port`

---

src/content/guides/development-vagrant.mdx

update commands with the latest arguments for webpack-dev-server v4.
Fix https://github.com/webpack/webpack.js.org/pull/5365

docs(guides): update development-vagrant guide

---

src/content/configuration/dev-server.mdx

update `https` docs for `v4.2.0`.
/cc @alexander-akait

docs: update `devServer.https`

---

webpack.dev.js

> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.

clean up HotModuleReplacementPlugin

---

src/utilities/constants.js
webpack.ssg.js

deprecate worker-loader for webpack 5

---

src/content/plugins/internal-plugins.mdx

See https://github.com/webpack/webpack/blob/main/lib/EntryPlugin.js#L20:
> passing a string is deprecated

docs(plugins): update outdated content

---

src/content/plugins/normal-module-replacement-plugin.mdx

Closes https://github.com/webpack/webpack.js.org/issues/5299

docs(plugins): add a note for resourceRegExp

---

package.json
src/scripts/build-content-tree.js
yarn.lock

Closes https://github.com/webpack/webpack.js.org/pull/5460, seems they introduced a breaking change in a minor version.

upgrade directory-tree

---

src/content/configuration/stats.mdx

Add `stats.optimizationBailout` option to the documentation:
https://github.com/webpack/webpack/blob/abd21a27f3ee77f2ad18c051d746690fc9511b56/schemas/WebpackOptions.json#L4332

docs(configuration): add `stats.optimizationBailout`

---

src/content/guides/getting-started.mdx

Remove `buble.js` from the guide because the project has not been maintained for over a year and the website http://buble.surge.sh/ is no longer available.

docs(guides): remove `buble.js` from the guide

---

src/components/Page/Page.jsx

fix: show `Contributors`/`Contributor` correctly

---

src/content/configuration/other-options.mdx

Reference -https://github.com/webpack/webpack/blob/4eb122092d9696ac5286bc2dcf3eacfb901f4fed/schemas/WebpackOptions.json#L1240
`ignoreWarnings` must be an array.

docs(configuration): update `ignoreWarnings` option documentation

---

src/content/api/node.mdx
src/content/guides/build-performance.mdx

parallel-webpack appears to be no longer actively developed
cache-loader has been archived
Resolves https://github.com/webpack/webpack/issues/14386

Deprecate doc refs to parallel-webpack and cache-loader

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/issues/5538

docs(configuration): add warning about `[ext]` and `output.filename`

---

src/content/awesome-webpack.mdx

I added [KeisukeYamashita/chrome-extension-archive-webpack-plugin](https://github.com/KeisukeYamashita/chrome-extension-archive-webpack-plugin), a webpack plugin to create Chrome Extension archives to publish to the Chrome Web Store.

Add chrome-extension-archive-webpack-plugin to awesome-webpack plugin list

---

src/content/configuration/dev-server.mdx

update `devServer.https` documentation.

docs(configuration): update `devServer.https`

---

src/content/configuration/dev-server.mdx

Refers https://github.com/webpack/webpack-dev-server/pull/3940

docs(configuration): add `devServer.server`

---

src/content/api/normalmodulefactory-hooks.mdx

I noticed the callback parameter for other hooks lowercase `resolveData` so I updated this for consistency. Thanks.

Fix `resolveData` casing in `beforeResolve` hook docs.

---

src/content/configuration/output.mdx

This is no longer present in version 5

docs: remove `futureEmitAssets`

---

src/content/api/loaders.mdx

[loader-utils v3 ~~depreciate~~ remove](https://github.com/webpack/loader-utils/releases/tag/v3.0.0) `stringifyRequest` and `getRemainingRequest` in favor of ones from loaderContext.

Replace loader-utils methods by loaderContext alternatives

---

src/content/configuration/entry-context.mdx
src/content/configuration/output.mdx

feat: add docs for asyncChunks

---

src/content/configuration/dev-server.mdx

Add warning for using `spdy` server for node >= v15.
https://github.com/spdy-http2/node-spdy/issues/380

docs(configuration): add warning for spdy server

---

src/content/configuration/module.mdx

Fix https://github.com/webpack/webpack.js.org/issues/5665
-  add `parser.javascript.exportsPresence`
-  add `parser.javascript.reexportExportsPresence`
-  add `parser.javascript.importExportsPresence`
-  deprecate `parser.javascript.strictExportPresence`

docs(configuration): add module parser options

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

use node v16 for CI jobs as it's LTS right now.

chore: use node v16 for CI jobs

---

src/content/configuration/entry-context.mdx

Fix https://github.com/webpack/webpack.js.org/issues/5677

docs(configuration): add `chunkLoading: false`

---

src/content/guides/asset-management.mdx
src/content/guides/caching.mdx
src/content/guides/code-splitting.mdx
src/content/guides/development.mdx
src/content/guides/getting-started.mdx
src/content/guides/lazy-loading.mdx
src/content/guides/output-management.mdx
src/content/guides/production.mdx
src/content/guides/shimming.mdx
src/content/guides/tree-shaking.mdx
src/content/guides/typescript.mdx

Remove the outdated tip regarding `package-lock.json` and update the directory structure throughout the guides.

docs(guides): remove outdated tip regarding `package-lock.json`

---

src/content/configuration/configuration-types.mdx

Added some docs from the other-options page directly to the multiple configuration docs where it makes more sense.
I had this use case where I wanted one webpack config rely upon the output of a previous run, but I was told it wasn't possible and I couldn't see it in the multiple configs docs, so I assumed it was true.

docs(configuration): Added dependencies docs

---

src/content/api/cli.mdx

add more examples for usage of the `info` command

docs(api): add more examples for usage of the `info` command

---

src/content/guides/hot-module-replacement.mdx

Add link for the full documentation of webpack-dev-server Nodejs API.

docs(guides): add link to the docs of webpack-dev-server API

---

src/content/configuration/module.mdx

Removed excess backslash escapes introduced in #2917.
See related #4188 that reverts changes from #2917 but skips the `src/content/configuration/module.mdx` file.

docs(configuration): remove excess backslash escapes

---

src/content/configuration/output.mdx

Resolve https://github.com/webpack/webpack.js.org/issues/5756
added `output.environment.optionalChaining` and `output.environment.templateLiteral`.

docs(configuration):  add `optionalChaining` and `templateLiteral`

---

src/content/configuration/entry-context.mdx

I think this current directory has a ambiguity. Does the current directory refer to the root directory of the project? Or is it the directory where webpack.config.js is located?
After I tested it, I found neither of them, the default should be the directory of the script that starts webpack. For example, I ran the script `webpack --config relativebase` in a non-project root directory. Then, the value of the context at this time is the directory where the script is located.
In order to better illustrate my ideas, I wrote a demo code, but I don’t know how to give the sample code, so I created a warehouse to store the sample code. https://github.com/spicylemonhaha/webpack-demo

Update docs for entry-context

---

src/content/configuration/output.mdx

Resolve https://github.com/webpack/webpack.js.org/issues/5743

docs(configuration): add tip for `output.hashDigestLength` default value

---

src/content/configuration/dev-server.mdx

Refers https://github.com/webpack/webpack-dev-server/pull/4068

docs(configuration): add `devServer.setupMiddlewares` option

---

src/content/configuration/dev-server.mdx

Add deprecated option warning for `onBeforeSetupMiddleware` and `onAfterSetupMiddleware`.

docs(configuration): add deprecation warning for devServer options

---

src/content/configuration/resolve.mdx

Very minor typoe fix in src/content/configuration/resolve.mdx

docs(configuration): fix typo in resolve documentation

---

src/content/configuration/configuration-languages.mdx

I read the article about writing webpack config file in TypeScript. I installed `@types/webpack-dev-server` but it's deprecated:
Since anyone who installs `webpack-dev-server` will get the types, the docs don't need to say "install `@types/webpack-dev-server`"

Remove @types/webpack-dev-server from docs

---

src/content/api/webpack-dev-server.mdx

Documents `internalIP` and `internalIPSync` for webpack-dev-server API with example.

docs(api): add `internalIP` and `internalIPSync` for webpack-dev-server

---

src/content/guides/environment-variables.mdx

Fix https://github.com/webpack/webpack.js.org/pull/5862/

docs(guides): fix link to CLI environment variables

---

src/content/configuration/index.mdx

Fix link. Old link is 404 - https://github.com/webpack/webpack-cli/tree/master/packages/init#cli-via-webpack-cli

docs(configuration): fix link for `init` command

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/pull/5869/

docs(configuration): fix the default value of `devtoolNamespace`

---

src/content/configuration/stats.mdx

When using a relative path for `stats.context`, the build fails:
```shell
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
- configuration.stats.context: The provided value "./src" is not an absolute path!
-> Context directory for request shortening.
error Command failed with exit code 2.
```
Example repo: https://github.com/vio/webpack-stats-context

docs(configuration): fix `stats.context` info & example

---

src/components/Site/Site.jsx

Unfortunately the `/vote` page is not working anymore after https://github.com/webpack/webpack.js.org/pull/5764 according to https://github.com/webpack/webpack.js.org/pull/3019#issuecomment-1013668828. I'm not quite sure what's going on there. Since that Vote App is built with webpack 4, it might be a good idea to redirect v5 vote to v4 because the later is built with webpack 4 as well.

Redirect vote to v4

---

src/content/configuration/watch.mdx

See https://www.jetbrains.com/help/webstorm/system-settings.html
> **Back up files before saving**: Before saving the file, create a backup. If the save operation is successful, WebStorm deletes the backup. If not, it restores the contents of the original file from backup. This behavior is known as "safe write", and it prevents losing your file in case of a faulty save operation.

fix: update WebStorm "safe write" to "Back up files before saving"

---

src/content/concepts/loaders.mdx

Closes https://github.com/webpack/webpack.js.org/issues/5735

docs(concepts): add note about deprecated CLI usage for loaders

---

src/content/configuration/dev-server.mdx

use consistent format as per the writer's guide - https://webpack.js.org/contribute/writers-guide/#configuration-defaults-and-types

docs(configuration): update `devServer` option types

---

src/content/concepts/index.mdx
src/content/concepts/plugins.mdx

added yarn to installation way

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/issues/5941
To be merged after the new webpack release.

docs(configuration): add note for resource name when filename is data URI

---

src/content/configuration/experiments.mdx

For https://github.com/webpack/webpack/pull/15354
closes https://github.com/webpack/webpack.js.org/issues/5994

document for specifying the `buildHttp.proxy` for `HttpUrlPlugin`

---

src/content/api/compilation-object.mdx

sortItemsWithModuleIds Doesn't exist anymore While scanning through the code

docs(api) : Remove sortItemsWithModuleIds

---

src/content/api/module-variables.mdx

fix #6003 
add import.meta.webpackContext

docs: add import.meta.webpackContext

---

src/components/Support/Support.jsx
src/remark-plugins/remark-custom-asides/index.mjs

This PR contains a:
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None

chore: replace deprecated String.prototype.substr()

---

src/content/migrate/5.mdx

Mention the change of the `chunks` parameter of `optimization.splitChunks.cacheGroups.test()`

Update of splitChunks.cacheGroups.test()

---

src/content/configuration/cache.mdx

add cache in CI/CD description
closes #6088

add cache in CI/CD description

---

src/content/plugins/banner-plugin.mdx

Fixes #6077 
There is a plugin we are using for version 4 that does the same thing as BannerPlugin, but it could place the text at the bottom of the file instead of the top. This allows the BannerPlugin to place the banner either as a header or footer. No other changes.
BannerPlugin was updated by https://github.com/webpack/webpack/pull/15617

docs(plugins): add `footer` parameter for `BannerPlugin`

---

src/content/guides/development.mdx

This section of the guide introduces the concept of a dev server for the first time, but has not introduced the concept that multiple endpoints on a single html file served by the webserver is problematic without `optimization.runtimeChunk: 'single'`.
This commit attempts to give new developers a softer landing, and references the Code Splitting section to more deeply understand as well as link to the same pitfall external resource as the Code Splitting section does.
See https://github.com/webpack/webpack/discussions/14873#discussioncomment-2449779 for rationale

docs(development): Mention `runtimeChunk: single` for multi-endpoint dev server

---

src/content/guides/code-splitting.mdx

Hi there,
Noticed a tiny typo while reading the Preloading/Prefetching Modules docs.

docs: correct spelling of streaming

---

examples/module-federation/app1/public/index.html
examples/module-federation/app2/public/index.html

When I jump to [StackBlitz](https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/module-federation?file=app2%2Fpublic%2Findex.html&terminal=start&terminal=) in the [Module Federation chapter](https://webpack.js.org/concepts/module-federation/) of the Webpack documentation , I realized that its HTML template file had some problems:
According to the HTML specification, `div` tags should not be self-closing.
Although on modern browsers it correctly identifies the offending HTML tag (since it happens to be the only tag in the HTML body) and thus happens to render the correct result. But I think it should keep the correct format anyway, so I made a change.
[1]: …

fix(example/html): make HTML tags into the correct format

---

src/scripts/build-content-tree.mjs

fix(scripts/build-content-tree): fix `JSON.stringify` method

---

src/content/configuration/module.mdx

Fix #6139 
To be merged after release.

docs(configuration): add parser options for dynamic import

---

src/content/api/cli.mdx

add `note` about env usage about escaping characters on the terminal, when you want to set a variable to an empty string.
This has come up multiple times https://github.com/webpack/webpack-cli/issues/3284#issuecomment-1151110687

docs(api): add note about `env` usage

---

src/content/guides/getting-started.mdx

Remove a trailing comma in `package.json` in the "Basic Setup" section as they are not allowed in JSON.

docs(guides): remove trailing comma in package.json

---

src/content/api/compiler-hooks.mdx

Fix https://github.com/webpack/webpack.js.org/issues/6187

docs(api): add `shutdown` compiler hook

---

src/content/guides/ecma-script-modules.mdx

- clarify extension resolving
related to https://github.com/webpack/webpack/issues/15517

improve esm docs

---

src/content/guides/csp.mdx

* This PR introduces minor copy updates to correct and clarify the `nonce` overview text

Correcting and clarifying the `nonce` copy

---

src/content/api/module-methods.mdx

- describe critical dependency warning
there was a section about critical dependency [in archived docs](https://github.com/webpack/docs/wiki/context#critical-dependencies) about warning like:
```
Critical dependencies:
158:18-25 require function is used in a way in which dependencies cannot be statically extracted
```
will be great to add this in current docs too. not sure where place this better... 
<!-- Name of the feature(s) and a link to related pull request of the feature implementat

improve require docs

---

src/content/concepts/module-federation.mdx

Fix typo: `boostrap` => `bootstrap`

Fix typo at `module-federation.mdx`

---

src/content/awesome-webpack.mdx

add OWASP's [CycloneDX Webpack Plugin](https://github.com/CycloneDX/cyclonedx-webpack-plugin#readme)
to the awesome webpack plugins list.

docs: add OWASP's `CycloneDX Webpack Plugin` to plugin list 

---

src/content/guides/code-splitting.mdx

remove extra call to createElement method in Dynamic Imports section of the code splitting guide.

docs(guides): refine code-splitting code snippets

---

.github/workflows/deploy.yml
.github/workflows/testing.yml
package.json
webpack.common.mjs
webpack.prod.mjs
webpack.ssg.mjs

Enable webpack persistent cache on CI.
Comparision - https://github.com/webpack/webpack.js.org/pull/6269#issuecomment-1185138320

ci: try webpack cache

---

package.json
yarn.lock

continue https://github.com/webpack/webpack.js.org/pull/6297#issuecomment-1195483721

chore: ensure to run yarn-deduplicate with fewer strategy

---

src/content/configuration/output.mdx

explain default value of output.chunkFormat and output.chunkLoading is inferred from target

---

src/content/loaders/index.mdx

PR adds `esbuild-loader` as a possible option for a transpiling loader as it's gaining a lot of popularity vs using babel-loader.

docs(loaders): add link to esbuild-loader

---

src/content/configuration/externals.mdx

Fix the type declaration for `ctx.contextinfo`  in externals handling callback

Fix type description for ctx.contextInfo for externals callback

---

src/content/configuration/dev-server.mdx

The injected middleware is the first in the array, it makes more sense to call it like that. Also, I'm not sure we should condone violence through fists against JS arrays.

fix(docs): correct typo in the setupMiddlewares example

---

src/content/api/loaders.mdx

syntax fix in Inline matchResource example:
"const match = STYLES_REGEXP.match(source);"  is in the wrong order -> "const match = source.match(STYLES_REGEXP);"
"require.resolve('./getStyle');" is missing the "s" to match with the file getStyles.js

fix(docs): syntax fix in "Inline matchResource"

---

src/components/Configuration/Configuration.scss

fix(Configuration.scss): fix config dialog pre element with block style

---

src/content/configuration/output.mdx

Remove an extra underscore in the documentation.

minor - remove typo extra underscore

---

src/content/configuration/index.mdx

The `name` option was listed under the `output` object which is incorrect.
Move it to top-level configuration object.

docs(configuration): move `name` option to correct place

---

src/content/api/logging.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6384

docs(api): improve logging api

---

src/content/configuration/watch.mdx

Closes https://github.com/webpack/webpack.js.org/issues/5879

docs(configuration): mention default watchOptions.poll value

---

src/content/guides/web-workers.mdx

Closes https://github.com/webpack/webpack.js.org/issues/5714

docs(guides): mention limitation of Worker api

---

src/styles/dark.scss

The background color for `<code />` under dark mode is so lighter at the moment.

fix background color for inline code under dark mode

---

.markdownlint.json
.markdownlintignore
package.json
src/content/api/loaders.mdx
src/content/api/module-variables.mdx
src/content/configuration/experiments.mdx
src/content/configuration/module.mdx
src/content/configuration/output.mdx
src/content/configuration/resolve.mdx
src/content/configuration/watch.mdx
yarn.lock

So we can catch errors like https://github.com/webpack/webpack.js.org/pull/6441#discussion_r991824393

enable markdownlint for mdx

---

src/content/configuration/output.mdx

As explained in https://github.com/webpack/webpack/issues/11277#issuecomment-1277258335, when outputting as a module, one would expect it'll simply work as any other npm module. Currently it doesn't, e.g. it won't work in webpack4-based applications.

docs(configuration/output): Warn about module output being not usable in webpack4

---

.github/workflows/dependency-review.yml

In case someone wants to introduce a malicious dependency through pull requests and we overlook the changed lock file.

add dependency review action

---

src/content/configuration/dev-server.mdx

There's no `console` language for code block https://github.com/wooorm/refractor#data

docs(Configuration): fix lang for code block

---

src/content/migrate/5.mdx

My understanding is that the deprecated `loaders` was removed in https://github.com/webpack/webpack/pull/9138 which was in https://github.com/webpack/webpack/releases/tag/v5.74.0 (should that have been a major version upgrade?)

docs(Migration): `loaders` → `use`

---

src/styles/dark.scss
yarn.lock

Closes https://github.com/webpack/webpack.js.org/issues/6480

optimize blockquote styles for dark mode

---

src/content/configuration/dev-server.mdx
src/content/configuration/externals.mdx

Partially fixes #6485 
Replacing "whitelist" with "allowlist" where possible. There are still 2 places with the word "Whitelist" but they are external article title so I should not change these words.
Contributing to Webpack's efforts of being more inclusive and follow the guidelines from [NIST](https://www.nist.gov/news-events/news/2021/04/nists-inclusive-language-guidance-aims-clarity-standards-publications).

Replace `whitelist` with `allowlist` where possible

---

src/components/Sidebar/Sidebar.jsx

I have spotted that almost everywhere on the docs webpack is referred to as `webpack` (lowercase), when in the sidebar version select the capitalized name has been used, so I have corrected it for the naming consistency.

fix naming in sidebar version select

---

src/content/guides/author-libraries.mdx

https://webpack.js.org/configuration/output/#outputglobalobject
When targeting a library, especially when libraryTarget is 'umd', this option indicates what global object will be used to mount the library. To make UMD build available on both browsers and Node.js, set `output.globalObject` option to 'this'. Defaults to self for Web-like targets.

Add globalObject when type is umd

---

src/content/api/compilation-object.mdx

The `addModule()` method takes a `module` and a `callback`, not a `cacheGroup`:
https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/Compilation.js#L1253-L1261

updating method signature for compilation.addModule()

---

.markdownlint.json
package.json
yarn.lock

A follow-up of https://github.com/webpack/webpack.js.org/pull/6446#discussion_r992198793.

build(deps): upgrade markdownlint

---

src/content/plugins/source-map-dev-tool-plugin.mdx

While implementing the `SourceMapDevToolPlugin` in my project I was following the documentation and noticed it caused an error in the build. I copied this from the documentation:
```javascript
new webpack.SourceMapDevToolPlugin({
append: '\n//# sourceMappingURL=https://example.com/sourcemap/[url]',
filename: '[name].map',
});
```
Ultimately I encountered this error: `Multiple assets emit different content to the same filename`
After some research I noticed it should be set to `[file].map[query]` as specified in this issue https://github.com/webpack/webpack/issues/9732#issuecomment-555461786
I figured this was worth fixing so others don't encounter the same issue I did.

docs(plugins): clarify `SourceMapDevToolPlugin` usage

---

src/components/SplashViz/SplashViz.scss

Seems when `display` set to `table`, Safari won't respect the `max-width` here.
Test under safari 16.2.

fix splash width under Safari

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

Use the [Node.js LTS version syntax ](https://github.com/actions/setup-node#supported-version-syntax)so we don't have to manually update `node-version` in future.

use lts nodejs

---

src/content/guides/production.mdx

docs(guides): improve document

---

.github/workflows/testing.yml
yarn.lock

Noticed another api rate limit in https://github.com/webpack/webpack.js.org/pull/6620, so this is a follow-up of https://github.com/webpack/webpack.js.org/pull/6600.

fix api limit for cypress

---

webpack.common.mjs
webpack.prod.mjs

change: webpack.common.mjs
change webpack hash function to improve speed of hash calculation
set output.hashFunction to 'xxhash64'

!perf: change webpack hash function to improve speed of hash calculation

---

src/content/plugins/split-chunks-plugin.mdx
yarn.lock

Closes https://github.com/webpack/webpack.js.org/issues/6646
Removing `chunk.hash` to avoid confusion due to potential `undefined` `chunk.hash`.

docs(plugins): remove chunk.hash

---

src/components/Markdown/prism-theme.scss

Simple change, but would make guides easier to follow. This would make people easily copy the entire file's content instead of manually making line changes, especially if there are many changes to make in multiple files.

Make .deleted changes non-selectable.

---

src/content/configuration/entry-context.mdx

it seem there no support [ext] placeholder in entery filename
See https://webpack.js.org/configuration/output/#template-strings

docs(configuration): remove [ext] for filename

---

src/content/plugins/watch-ignore-plugin.mdx

Documentation update following https://github.com/webpack/webpack.js.org/issues/6673 which will be then closed
CC: @TheLarkInn 
Before:
After:
Closes https://github.com/webpack/webpack.js.org/pull/6709

Add Deprecation message for WatchIgnorePlugin

---

src/content/guides/code-splitting.mdx

I make a tools for show more detail which existed in webpack. At my work for improve my project performance, I found i need more and more detail content which can help me. so i build it. And i wanna make more people like me known it.
Its copy from my repo:
> Many same webpack analyzer tools can show summary, but as a developer, when i try go deep into, and think why those file bundled into those chunk, those tools make me powerless, because of i cannot get more detail. So i develop this tool, no magic, just plain data. I think i need it.
> This is for in-depth study of webpack chunks composition and for deep website performance optimization
---------

docs: append `webpack-stats-viewer` in code-splitting

---

src/utilities/process-readme.mjs
src/utilities/process-readme.test.mjs

Noticed a bug in https://github.com/webpack/webpack.js.org/actions/runs/4600783997/jobs/8127825773?pr=6734#step:7:9 caused by the readme of https://github.com/webpack-contrib/postcss-loader:
```md
See the file [`./src/config.d.ts`](./src/config.d.ts).
Type:
```
Both matched relative links should be replaced with new one.

fix bug in readme processing

---

src/content/guides/web-workers.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6738

docs(Guides): document Worker limitation in webpack

---

src/content/api/module-variables.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6759

docs(API): add import.meta section

---

src/content/plugins/dll-plugin.mdx

Fix https://github.com/webpack/webpack.js.org/issues/6756

docs: update supported template  paths in DllPlugin's `name` option

---

src/content/configuration/stats.mdx

Fixes https://github.com/webpack/webpack.js.org/issues/6767

docs(configuration): add `stats.errorsSpace` and `stats.warningsSpace`

---

src/content/api/cli.mdx
src/content/configuration/extending-configurations.mdx

Adds docs for the `extends` option added to webpack-cli in PR https://github.com/webpack/webpack-cli/pull/3738
Closes https://github.com/webpack/webpack.js.org/issues/6801

docs: update docs for the extends option

---

.github/CONTRIBUTING.md
src/content/configuration/dev-server.mdx

docs(Configuration): document new devServer.overlay options

---

.github/workflows/deploy.yml
src/utilities/fetch-supporters.mjs

We kept hitting the api limit of opencollective recently.
Let's see if adding a personal token would help a little.
Note that this only targets the `deploy.yml` action at the moment as there're [some limitation of environment secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) stops us from applying to others:
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

fix api limit of opencollective

---

src/utilities/fetch-supporters.mjs

This is a much better version to handle the opencollective api limit.
The code will automatically wait until api limit is lifted then continue, and it supports running fetch simultaneously in different tasks, no more manually restart the failed tasks!

handle api limit automatically

---

.github/workflows/testing.yml
yarn.lock

Currently we ran `yarn build` twice in `testing.yml` which consumes too many resources and hit api limit of opencollective, github, etc. easily.
Thus I reckon we can simplify it and combine two jobs into one to avoid running many `yarn build`, which means less api requests and quicker build.

simplify testing.yml

---

src/content/configuration/experiments.mdx

https://github.com/webpack/webpack/pull/17192 Made Top Level Await enabled by default. Updating the docs for the experiment to add this information

docs: update docs for top level await

---

README.md

add GitHub discussions badge in README, gitter is no longerusd by the team.

docs: add GitHub discussions badge in README

---

src/content/guides/asset-modules.mdx

Change "Asset modules" that was used as singular into "Asset module" (it's singular form)

docs(guides): improve "Asset modules" grammar

---

src/content/plugins/eval-source-map-dev-tool-plugin.mdx
src/content/plugins/source-map-dev-tool-plugin.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6846

docs(plugins): document append function

---

src/content/configuration/experiments.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6909
Add documentation for `experiments.css`

docs: add docs for the css experiment

---

src/content/configuration/configuration-languages.mdx

`import *` not required when `esModuleInterop: true` in `tsconfig.json`.
```json
{
"devDependencies": {
"@types/node": "^20.3.1",
"@types/webpack": "^5.28.1",
"@types/webpack-dev-server": "^4.7.2",
"ts-loader": "^9.2.6",
"ts-node": "^10.9.1",
"typescript": "^5.1.3",
"webpack": "^5.88.0",
"webpack-cli": "^5.1.4",
"webpack-dev-server": "^4.7.4"
}
}
```

docs(config): update typescript setup in configuration-languages.mdx

---

src/content/configuration/module.mdx

Closes https://github.com/webpack/webpack.js.org/issues/6908

docs(Configuration): document css/auto

---

src/content/contribute/debugging.mdx

Since `node --inspect` has been available for 7 years, I think its time to remove `node-nightly` from the docs.

docs(debugging): remove `node-nightly` in favor of `node`

---

src/content/guides/typescript.mdx

The TypeSearch feature is no longer available, as explained [here](https://www.typescriptlang.org/dt/search). Therefore the reference link to the TypeSearch page and related explanation can be removed.

docs(typescript): update typescript guide on using third party libs

---

src/content/configuration/cache.mdx

see https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/config/defaults.js#L414
It's always off by default

fix cache.compression default

---

src/content/configuration/module.mdx

Based on the name in the sidebar, I believe this should be called “Condition”, not “Condition.test”.

docs(configuration): correct Condition reference

---

src/content/contribute/index.mdx

I was unable to find a new documentation team link. As a solution i suggest removing it completely

docs(contribute): remove broken link to the documentation team

---

src/content/plugins/module-federation-plugin.mdx

Hello,
I added a little section on how to specify the package name when using `shared` with module federation plugin. This should fix #5476.

docs: add section on how to specify the package name for module federation

---

.github/workflows/dependency-review.yml
.github/workflows/deploy.yml
.github/workflows/testing.yml

Replace https://github.com/webpack/webpack.js.org/pull/7010 as v4 requires Node.js 20 https://github.com/actions/checkout/pull/1436

bump actions/checkout

---

src/content/api/loaders.mdx
src/content/api/node.mdx
src/content/configuration/module.mdx
src/content/configuration/node.mdx
src/content/configuration/optimization.mdx
src/content/configuration/stats.mdx
src/content/configuration/target.mdx
src/content/license.mdx
src/content/plugins/banner-plugin.mdx
src/content/plugins/commons-chunk-plugin.mdx
src/content/plugins/dll-plugin.mdx
src/content/plugins/progress-plugin.mdx
src/content/plugins/split-chunks-plugin.mdx

The new default branch name of webpack repository is `main`, and the links in the docs still use the legacy branch name `master`.

docs: fix webpack repo links that use legacy branch name

---

src/content/plugins/normal-module-replacement-plugin.mdx

see https://stackoverflow.com/a/56084864/4255158 for more context. There should be info about this in the docs!

Added info about folder separator on windows

---

src/content/api/compilation-hooks.mdx

Add a deprecation notice for deprecated hooks
These hooks are deprecated and deprecation notice exists in code but not in the docs - https://github.com/webpack/webpack/pull/10876

docs: add notice for deprecated compilation hooks

---

src/content/concepts/modules.mdx

This PR addresses a broken link issue in the webpack.js.org documentation. The previous link for the CommonJS specification was leading to a "Not Found" page. I've updated the link to the correct URL (https://wiki.commonjs.org/wiki/Modules/1.1) to ensure users can access the accurate information about CommonJS modules.
Resolves https://github.com/webpack/webpack.js.org/issues/7084

chore(docs): Fix broken CommonJS link in webpack.js.org documentation

---

src/content/guides/asset-modules.mdx

This updates the documentation to better define how `publicPath` interacts with `asset` module types. Specifically, it is poorly documented on how to dynamically set the `publicPath` on the fly for these module types. This is important and useful in an enterprise environment where there may be different upstream CDNs or other locations that the app hosts assets on that aren't the server or a static site.

docs: add note about how publicPath interacts with asset modules

---

src/utilities/__snapshots__/process-readme.test.mjs.snap
src/utilities/process-readme.mjs
src/utilities/process-readme.test.mjs

Fixes https://github.com/webpack-contrib/html-loader/issues/502

fix: don't replace comments inside codeblocks while processing README

---

.github/actions/webpack-persistent-cache/action.yml
.github/workflows/deploy.yml
.github/workflows/testing.yml

Closes #7076 
For each workflow, the webpack persistent caching step is written in the same code:
```yaml
- name: Enable webpack persistent caching
uses: actions/cache@v4
id: build-webpack-persistent-cache
with:
path: node_modules/.cache
key: build-${{ hashFiles('**/webpack.*.mjs') }}-${{ hashFiles('**/yarn.lock') }}
restore-keys: |-
build-${{ hashFiles('**/webpack.*.mjs') }}-${{ hashFiles('**/yarn.lock') }}
build-${{ hashFiles('**/webpack.*.mjs') }}-
```
If requirements change, we'll need to edit it for each workflow. This makes maintenance difficult and can lead to mistakes.
Duplicate workflow steps can be abstracted into [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).
```yaml
- name: Enable webpack persistent caching
uses: …
```

ci: use composite action for webpack persistent caching

---

src/content/plugins/split-chunks-plugin.mdx

Fix https://github.com/webpack/webpack/discussions/17970

fix: splitChunks maxSize/minSize/maxRequest priority

---

src/content/plugins/index.mdx
src/content/plugins/split-chunks-plugin.mdx
src/utilities/fetch-package-readmes.mjs
src/utilities/fetch-package-repos.mjs

This PR adds the `ChunksWebpackPlugin` to the plugins documentation page on the community group. The README is automatically fetched from the [GitHub repository](https://github.com/yoriiis/chunks-webpack-plugin).
With `splitChunks.chunks: 'all'` webpack generates chunks that are not known before compilation.
- In a Single Page Application, there is `html-webpack-plugin` to generate styles and scripts chunks dependencies.
- In Multiple Page Application with multiple entry point (e.g. Symfony) this is possible with `chunks-webpack-plugin`.
History: The plugin was already proposed on the official documentation in 2020 (#3771) and  but there was not yet the community group to separate the contributions from the webpack core team.
Note: The latest version of the package and therefore of the …

doc(plugins): add ChunksWebpackPlugin

---

src/content/configuration/node.mdx

node.__filename and node.__dirname accept 'node-module' as an option, not 'node_module'
Using 'node-module' works, whereas using 'node_module' gives the following error:
```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
- configuration.node.__filename should be one of these:
false | true | "warn-mock" | "mock" | "node-module" | "eval-only"
-> Include a polyfill for the '__filename' variable.
```

Fix typo in __dirname and __filename options

---

src/content/configuration/devtool.mdx

I was trying to avoid `eval` being generated by `devtool` in my local development workflow, but the docs weren't clear on how to disable the `devtool`. The solution was to explicitly set `devtool: false` so that both the development and production modes use `(none)`.

docs(configuration): clarify `devtool` disabling

---

src/content/configuration/output.mdx

`trustedTypes: false` is invalid. [Ref Schema](https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/schemas/WebpackOptions.json#L3392-L3406)

docs(configuration): update `output.trustedTypes`

---

src/content/migrate/5.mdx

Fix https://github.com/webpack/webpack.js.org/pull/3381
Fix https://github.com/webpack/webpack.js.org/issues/2676

docs(migrate): add link to configuration changes

---

src/content/api/compilation-hooks.mdx
src/content/api/compiler-hooks.mdx
src/content/api/parser.mdx

Fix https://github.com/webpack/webpack.js.org/pull/3532/
Fix https://github.com/webpack/webpack.js.org/issues/2411

docs: add note for non extensibility of hooks

---

src/content/configuration/output.mdx

The `libraryTarget` option has a warning that support might be dropped and it's better to use `library.type`.  I left `libraryTarget` in other sections that are marked as maybe dropping support later because that seems consistent for those options.

replace outdated references to libraryTarget with library.type

---

src/content/migrate/5.mdx

As far as I can tell this is so far only mentioned in this issue comment - it seems to have changed after the blog post listing all the changes in config: https://github.com/webpack/webpack/issues/13584#issuecomment-863272803
(I also needed this question and answer to figure it out: https://stackoverflow.com/questions/77951581/webpack-5-builds-for-aws-lambda-with-typescript-runtime-handlernotfound)

add library config changes to migration guide

---

src/content/configuration/module.mdx

docs(configuration): fix typo in UseEntry

---

src/content/contribute/writing-a-plugin.mdx

Fixes a grammatically incorrect sentence found on the [writing-a-plugin](https://webpack.js.org/contribute/writing-a-plugin/) page.

docs: fix incorrect sentence

---

src/content/plugins/banner-plugin.mdx

Fixes https://github.com/webpack/webpack.js.org/issues/7183

docs(plugins): add `stage` option for `BannerPlugin`

---

src/content/configuration/entry-context.mdx

Add `entry[x].runtime` configuration that also align with https://webpack.js.org/concepts/entry-points/#entrydescription-object
Related pr 
https://github.com/webpack/webpack/pull/11235

docs(configuration): add entry[x].runtime

---

src/content/configuration/stats.mdx

`string = 'auto'` means any string is accepted and it has a default value `'auto'`. While the option only accepts `auto` as the valid value.
https://github.com/webpack/webpack/blob/4fda15571d66bb593a1bad69835a6797b2f911c6/schemas/WebpackOptions.json#L4950

docs(configuration): fix stats.entrypoints & stats.errorDetails type

---

package.json
yarn.lock

[upgrade `@octokit/auth-action`](https://github.com/octokit/auth-action.js/releases/tag/v5.0.0)

chore: upgrade `@octokit/auth-action` to v5

---

src/content/api/compilation-hooks.mdx

Fix #2728 
Fix https://github.com/webpack/webpack.js.org/pull/3378

docs(api): add `Compilation.hooks.statsPrinter`

---

src/content/configuration/optimization.mdx

According to https://github.com/webpack/webpack/blob/4baf1c075d59babd028f8201526cb8c4acfd24a0/lib/config/defaults.js#L1415C1-L1416C1, set `optimization.realContentHash` default value. 

docs: optimization.realContentHash default value

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7230

docs(configuration): add `output.environment.nodePrefixForCoreModules`

---

src/content/configuration/module.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7222

docs: add module.parser.css.namedExports

---

src/content/plugins/eval-source-map-dev-tool-plugin.mdx
src/content/plugins/source-map-dev-tool-plugin.mdx

Fix https://github.com/webpack/webpack/issues/17663
Only `SourceMapDevtoolPlugin` supports `false`.

docs(plugins): update append option usage

---

src/content/configuration/output.mdx

docs: add warning for ! usage in `output.path`

---

src/content/concepts/index.mdx

Updated the link to ES5 compatability table in webpack docs.
- **Old Link**: https://kangax.github.io/compat-table/es5/
- **New Link**: https://compat-table.github.io/compat-table/es5/

Replaced correct es5 compat-table link

---

package.json
yarn.lock

In https://github.com/webpack/webpack.js.org/pull/7311, rimraf was upgraded to v6 which dropped support for Node before v20.

bump node engines

---

src/content/api/loaders.mdx

Add an example for `utils.createHash`.

Add an example for utils.createHash

---

package.json
webpack.common.mjs
yarn.lock

Unfortunately we can't use the default `modern` api for sass due to legacy code and it's breaking the build https://github.com/webpack/webpack.js.org/pull/7330

deps: upgrade sass loader

---

src/content/awesome-webpack.mdx

Add [pwa-manifest-loader](https://github.com/autopulated/webpack-pwa-manifest-loader) to the community list, hopefully this is useful for other people?
The PWA manifest references other assets, so it's nice to have a loader automatically handle them.

docs(awesome): add pwa-manifest-loader

---

src/content/plugins/normal-module-replacement-plugin.mdx

The example given in the docs for `NormalModuleReplacementPlugin` uses quite an expensive regex for what it's trying to achieve. This exact regex was the source of a sizeable performance hit in one of our applications. I've updated it to be simpler and more performant.

docs: Replace overkill regex with a much simpler one

---

src/content/concepts/module-federation.mdx

Closes https://github.com/webpack/webpack.js.org/issues/7357

docs(concepts): fix code

---

src/content/api/module-methods.mdx

On the https://webpack.js.org/api/module-methods/ page, the `webpackExports` section was not the right format. It wasn't an actual heading, and as a consequence it didn't have an anchor link.

Fix `webpackExports` section header

---

src/content/guides/package-exports.mdx

Closes https://github.com/webpack/webpack.js.org/issues/7323

docs(guides): update alternatives

---

src/content/configuration/externals.mdx

Update doc for https://github.com/webpack/webpack/pull/18620.
fixes #7348

docs(externals): add `import` and `module-import` external type

---

src/content/configuration/module.mdx

Refers https://github.com/webpack/webpack.js.org/issues/7280
https://github.com/webpack/webpack/blob/09543e7d8e0e7dd1703207193bcc3c3252874636/schemas/WebpackOptions.json#L4400-L4406

docs: add `Rule.assert`

---

src/content/configuration/module.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7280

docs(configuration): add `Rule.with`

---

src/content/configuration/output.mdx

Refers https://github.com/webpack/webpack/pull/18272

docs: add `'modern-module'` value for `output.library.type`

---

src/content/api/module-methods.mdx

Fix https://github.com/webpack/webpack.js.org/issues/6760

docs: add webpackExports warning with destructuring assignments

---

src/content/configuration/module.mdx

[Ref Schema](https://github.com/webpack/webpack/blob/09543e7d8e0e7dd1703207193bcc3c3252874636/schemas/WebpackOptions.json#L4407)
[Ref Usage](https://github.com/webpack/webpack/blob/09543e7d8e0e7dd1703207193bcc3c3252874636/test/configCases/rule-set/compiler/webpack.config.js)

docs(configuration): add `Rule.compiler`

---

src/content/configuration/experiments.mdx
src/content/configuration/module.mdx

- #7392
- https://webpack.js.org/configuration/module/#rulecompiler
module rule.compiler ident fix

docs(configuration) module rule.compiler ident fix

---

src/content/concepts/plugins.mdx

I believe that `caramelized` was just a typo

docs(plugins): replace a typo with a convenient word

---

src/content/api/loaders.mdx

Closes https://github.com/webpack/webpack.js.org/issues/7403

docs(api): document hashDigest etc.

---

src/content/configuration/optimization.mdx

Doc for https://github.com/webpack/webpack/pull/18772.

docs(optimization): add `optimization.avoidEntryIife`

---

.github/workflows/testing.yml

`errata-ai/vale-action` is failing on ubuntu-laltest. Related issue - https://github.com/errata-ai/vale-action/issues/128
Pin version as workaround.
[Reference CI failure](https://github.com/webpack/webpack.js.org/actions/runs/11304327686/job/31442570735?pr=7426)

ci: use `ubuntu-22.04` for `errata-ai/vale-action`

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7422
To be merged after a new release.

docs: update `output.devtoolNamespace`

---

.github/workflows/deploy.yml
.github/workflows/testing.yml

`latest` resolves to v23.1.0 which has a regression https://github.com/nodejs/node/issues/55609
Failing our test & deploy actions.

ci: use Node.js LTS version

---

src/utilities/githubAPI.mjs

Allow developers to use authenticated  API locally to avoid rate limit errors while trying to build locally:

chore: use authenticated GitHub API locally if token is present

---

package.json

We have a lot of `.mjs` files present in the codebase.

chore: run lint-staged on `*.mjs` files

---

src/content/plugins/ignore-plugin.mdx

Refers https://github.com/webpack/webpack.js.org/issues/7430

docs(IgnorePlugin): add note about CSS compatibility

---

src/content/plugins/environment-plugin.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7448

docs(plugins): update EnvironmentPlugin warning

---

src/content/configuration/externals.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7446

docs(externals): update `externalsType.node-commonjs` usage

---

src/content/api/module-methods.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7430

docs(api): add webpackIgnore usage with CSS

---

src/content/configuration/output.mdx

Closes https://github.com/webpack/webpack.js.org/issues/7473

docs(configuration): remove cssHeadDataCompression

---

src/content/configuration/output.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7469

docs(output): remove `fetch-streaming` value for `wasmLoading` option

---

src/content/plugins/source-map-dev-tool-plugin.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7476

docs(plugins): add `debugIds` option for `SourceMapDevToolPlugin`

---

src/content/configuration/module.mdx

Refers https://github.com/webpack/webpack.js.org/issues/7449

docs(module): add `module.parser.css.import` option

---

src/content/configuration/module.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7449

docs(module): add css parser url option

---

src/content/configuration/resolve.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7494

docs(resolve): clarify usage of `...` to retain default conditionNames

---

src/content/api/cli.mdx

Change the cli doc for `create-webpack-app`
- changed the webpack-cli init commands to create-webpack-app commands spec.

doc: update cli documentation for `create-webpack-app`

---

src/content/api/cli.mdx

docs(cli): add --config-node-env option

---

src/content/configuration/resolve.mdx

docs(resolve): and wildcard alias configuration

---

src/content/configuration/module.mdx

Fixes https://github.com/webpack/webpack.js.org/issues/7502#issuecomment-2554810578.
https://github.com/webpack/webpack/pull/19058 introduced one option in v5.98.0. Let we update the docs.

docs: improve FlagDependencyExportsPlugin for large JSON by depth

---

src/content/configuration/externals.mdx

The example `webpack.config.js` in `externalsType.module-import` section is incorrect

fix: example webpack config in `externalsType.module-import` doc is incorrect

---

src/content/configuration/module.mdx

There was an unnecessary space after the backtick in the markdown file for the **Module of Content Configuration** challenge, which caused formatting inconsistencies.
- Removed the extra space before the backtick to maintain consistent formatting in the challenge description.
- Ensured the file aligns with the other markdown files in the curriculum.
- Visually reviewed the markdown content.
- Verified that no other formatting issues were present in the file.
- No errors reported when viewing the file in the curriculum.

docs: remove extra space after backtick in 'module' configuration

---

src/components/Support/Support.jsx
src/components/Support/Support.scss
yarn.lock

The sponsor Section was change where the logo are not aligned properly .
- `Support.jsx`
- `Support.scss`
- Adjusted styling in `Support.scss` to ensure logos are aligned properly.
- Updated `Support.jsx` to maintain a consistent layout.
Please review the changes and let me know if any improvements are needed. 

 Fix Logo Alignment in Sponsor Section

---

src/content/configuration/index.mdx

https://createapp.dev/webpack now resolves to a holding website.  The domain expired on the 1st of March 2025. Until it is back up this is not a helpful tip to have in the docs.

Remove the createapp.dev/webpack link

---

src/utilities/fetch-supporters.mjs

Getting the following error multiple times while fetching locally.
- Fixed "unable to get local issuer certificate" error when fetching supporter data
- Disabled SSL verification in local development only
- Maintained proper SSL verification in CI environments
- Added proper handling of SSL settings with try/finally to ensure restoration

chore: fix ssl verification for fetch-supporters in local development

---

src/components/Support/Support.jsx
src/components/Support/Support.scss

Reverts https://github.com/webpack/webpack.js.org/pull/7568
Reverting because now the Platinum sponsor logo size is same as Gold sponsor logo size () after this change.
This fixes the platinum sponsor size from 100x100 px to 128x128px
I'll fix the alignment in a separate PR.
**Before**
**After**

fix: revert Sponsor logo alignment (#7568)

---

webpack.dev.mjs

Open default browser on configured port (3000) on running `yarn start`

chore: open browser on configured port by default on yarn start

---

src/components/Navigation/Navigation.jsx
src/components/Site/Site.jsx

Add `aria-label` to all navigation links.
https://github.com/user-attachments/assets/18ada613-462b-47c6-8528-84eed1e079dc

fix: add aria-label prop on nav links

---

src/content/migrate/5.mdx

This PR enhances the webpack v5 from v4 migration guide by incorporating codemod integration to streamline the upgrade process for developers. The motivation behind this change is to provide a more efficient and time-saving approach for migrating from v4 to v5, helping the community upgrade with ease.
Key changes include:
1. **Introducing Codemods**: Added a section in the migration guide to highlight the availability of codemods for automating common migration tasks.
2. **Codemod Recipe**: Provided a codemod recipe that runs the following codemods from the Sentry.js Codemod repository:
```
npx codemod webpack/v5/migration-recipe
```
- **webpack/v5/set-target-to-false-and-update-plugins** [Registry Link](https://codemod.com/registry/webpack-v5-set-target-to-false-and-update-plugins)
- …

feat: Added codemods for migrating webpack from v4 to v5

---

src/components/Support/Support.jsx

Fixes: https://github.com/webpack/webpack.js.org/issues/7584
Filtered out individuals who have made no financial contribution to the project from the backers list by ensuring that only users with a positive contribution are shown in the list.
Before: 
After:

fix: excluded zero donation backers

---

src/components/Navigation/Navigation.jsx
src/components/Support/Support.jsx
src/components/Tooltip/Tooltip.jsx

Fix https://github.com/webpack/webpack.js.org/issues/7493
Fix https://github.com/webpack/webpack.js.org/pull/7513

feat: add tooltip component for links & sponsors data

---

src/content/configuration/other-options.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7587

docs(configuration): remove outdated stats-webpack-plugin note

---

src/utilities/fetch-supporters.mjs

SSL verification can be enabled now.

chore: enable ssl verification for fetch-supporters

---

src/content/contribute/index.mdx

Added a working Discord invite link under the "How to Contribute" section to help new contributors easily join the community for discussions and support.
📍 **Updated file**: `/src/content/contribute/index.mdx`  
🔗 **New Discord link**: [https://discord.com/invite/5sxFZPdx2k](https://discord.com/invite/5sxFZPdx2k)
---
Closes #7598

docs: added working Discord link in contribute page

---

package.json
src/content/guides/tree-shaking.mdx

Enhance Tree Shaking Documentation with Full Example
This PR enhances the tree shaking documentation by adding a comprehensive section that explains side effects in more detail with a practical example.
Fixes: #7414 
- Added a new section "Full Example: Understanding Side Effects with CSS Files" that demonstrates:
- A complete directory structure for a fictional UI component library
- Content of key files including CSS files that constitute side effects
- What happens when webpack processes imports with different sideEffects configurations
- The specific impact of incorrectly marking files with side effects
- Added a "Common Pitfalls with Side Effects" section covering:
- Over-optimistic use of `sideEffects: false`
- Issues with re-exports containing side effects
- Problems with nested …

added a more detailed example for tree-shaking clarification

---

src/components/Tooltip/Tooltip.jsx

Seems the tooltip introduced have caused a alignment problem:

fix alignment of navigation icons

---

src/components/Support/Support.jsx

- **Pledged $1000:** The company has _promised_ to give $1000, but has not necessarily given it yet. It's a commitment for the future.
- **Contributed $1000:** The company has _actually given_ $1000 already. The money has been transferred or donated.
In short:
- Pledge = promise (future)
- Contribute = action done (completed)

fix: use "contributed" instead of "pledged" for sponsors

---

src/content/migrate/5.mdx

This PR is part of a routine codemod health check.
This PR fixes found typos and commands for running codemods. Also, the behavior of some codemods has been improved [here](https://github.com/codemod-com/commons/pull/64).

fix: migrate codemod typos and commands

---

src/content/configuration/stats.mdx

Fix https://github.com/webpack/webpack.js.org/issues/7620

docs(configuration): add `stats.errorCause`

---

src/content/guides/lazy-loading.mdx

Update the link for React code splitting to the most recent version of the documentation.

docs: update reference link in lazy-loading

---

src/content/configuration/experiments.mdx
src/content/guides/lazy-loading.mdx

Add docs for https://github.com/webpack/webpack/pull/16567

docs: add deferImport

---

src/content/api/module-methods.mdx
src/content/configuration/module.mdx

This PR update the `fetchPriority` link to point to the `HTMLScriptElement` mdn docs instead of `HTMLImageElement`, which seems more appropriate for codesplitting. Thanks!

docs: update fetchPriority link

---

src/content/api/normalmodulefactory-hooks.mdx
src/content/awesome-webpack.mdx
src/content/configuration/devtool.mdx
src/content/configuration/experiments.mdx
src/content/configuration/module.mdx
src/content/configuration/other-options.mdx
src/content/guides/asset-modules.mdx
src/content/loaders/index.mdx

docs: v5.102.0
