webpack/webpack.js.org

- src/content/api/compilation-object.md
> docs(api): improve info regarding parameters

- src/content/configuration/dev-server.md
- types formatting where missing, wrong
> docs(config) dev server types fixes

- src/content/plugins/dll-plugin.md
> doc for entryOnly DLL plugin

- src/content/guides/lazy-loading.md
- Update outdated vue guide
- add additional resource
- format angular links
> docs(guides) lazy loading guide references updated and added

- src/content/glossary.md
https://webpack.js.org/guides/lazy-loading/
> docs(glossary): Added reference to lazy loading guide

- src/content/concepts/module-resolution.md
> docs(concepts): improve module resolution

- src/content/configuration/externals.md
> docs(configuration): Minor grammatical tweak

- src/content/configuration/externals.md
Added myself to the contributors list in regard to #3482
> doc(configuration): Updated contributors list

- src/content/configuration/mode.md
> Remove "Just"

- src/content/contribute/writing-a-loader.md
Added [`webpack-default`](https://github.com/webpack-contrib/webpack-defaults) note to setup field.
**Screenshot**
> docs(writing-a-loader): added webpack-default description

- README.md
> chore(readme) update readme re webpack 5 lag and v4. subdomain docs

- src/content/contribute/writing-a-loader.md
> docs(contribute): update all instances of memory-fs to memfs

- .github/PULL_REQUEST_TEMPLATE.md
- mention stale PR treatment policy in PR template
> chore(pr-template) mention stale PRs policy

- src/content/glossary.md
https://webpack.js.org/concepts/manifest/
> docs(glossary): Added info about webpack manifest

- src/content/configuration/externals.md
- we dont use blocks for legend
- regex -> RegExp
> docs(config) externals page updated acc to writers guide

- src/content/plugins/eval-source-map-dev-tool-plugin.md
Follow up of #3499 
- `regexp` -> `RegExp`
> docs(plugin): update as per writers guide

- src/content/api/loaders.md
> docs(api) new loader context method: getOptions doc

- src/content/guides/tree-shaking.md
> guides(tree-shaking) document pure annotation

- src/content/configuration/watch.md
> docs(config) - fix watchOptions.ignored documentation

- src/content/configuration/dev-server.md
> docs(configuration): Minor grammatical fixes

- src/content/configuration/dev-server.md
- src/content/plugins/progress-plugin.md
> Improve progress plugin docs

- src/content/plugins/environment-plugin.md
> Docs(plugin): Inform webpack will throw err instead of warn

- src/content/api/compilation-object.md
Remove ApplyModuleIds and Compilation.applychunkids
> doc(api) : removed Compilation.applyModuleIds and Compilation.applyChunkids

- src/content/contribute/plugin-patterns.md
- remove "simply"
- format note block while at it
> docs(contrib) remove simply, format note block

- src/content/configuration/output.md
closes https://github.com/webpack/webpack.js.org/issues/3549
> chore: documented output.hotUpdateChunkFilename cant accept function

- src/content/guides/asset-modules.md
Link to a related article about asset modules
> Link to a related article about asset modules

- src/content/contribute/plugin-patterns.md
fix a small chunk of [#2274](https://github.com/webpack/webpack.js.org/issues/2774)
> doce(plugin): info  are not set

- src/content/contribute/plugin-patterns.md
> docs(contrib) plugin patterns Set and Map

- src/content/guides/build-performance.md
> chore: added note for yarn 2 support for persistent caching

- src/content/configuration/index.mdx
- src/content/migrate/5.md
- remove `serve` option from configuration
- Closes #3565
> docs(config) remove serve option

- src/content/configuration/externals.md
> library type in the externals

- src/content/configuration/entry-context.md
- src/content/guides/code-splitting.md
Add info about entry description, `entry.filename` and `entry.dependOn`
> Entry description, entry.filename and entry.dependOn

- src/content/configuration/index.mdx
- src/content/contribute/writing-a-plugin.md
- point the plugins defaults possibility in configuration
- mention subject in "writing a plugin"
- Closes #3555
> docs(multi) mention that plugins may apply config defaults

- src/content/api/node.mdx
Update example link which is broken.
> docs(api): Update example link

- src/content/concepts/under-the-hood.md
> docs(concepts): add under the hood

- src/content/api/resolvers.md
- shorten the infromation
- simplify english used
- grammar tweak
- fix seo (link should specify name of page or option instead of simply saying documentation)
- move note to a T> block
> docs(api) resolve page tidy up

- src/content/concepts/loaders.mdx
> docs(concepts): use pug loader

- src/content/configuration/node.md
Fixes #3585 
Updated source link.
> docs: Update node.global source link

- src/content/configuration/output.md
Add defaults that we forgot to add in #3359
related to #3313 's fix
> docs(config) ecmaVersion type and default added

- src/content/configuration/output.md
- Closes #3590 
- document `output.uniqueName`
> docs(config) document output.uniqueName

- src/content/configuration/output.md
- document `output.chunkCallbackName` configuration option
> docs(config) document output.chunkCallbackName option

- src/content/configuration/output.md
In view of 
https://github.com/webpack/webpack.js.org/issues/3313#issuecomment-587923993 
#3313 
> Docs(output) : Explictily Add info about deafult values

- src/content/configuration/output.md
> docs(configuration): Minor typographical fix

- src/content/configuration/output.md
Add missing link after #3596 got merged
> docs(config) follow up to link from list to recently merged option docs

- src/content/contribute/writing-a-plugin.md
Fixes #3606  , minor grammar fix
> docs(writing-a-plugin): minor grammar fix

- src/content/api/compiler-hooks.md
> Docs(api) : Add additionalPass hook to compiler

- src/content/api/module-methods.md
> Fixes double double-quote typo

- src/content/configuration/node.md
> Docs(config) : defaults to false in node.js targets

- src/content/api/module-variables.md
- src/content/configuration/output.md
> docs(api): added info about webpack_exports_info

- .github/CODE_OF_CONDUCT.md
chore(code_of_conduct): add jsf conduct link
add jsfoundation code_of_conduct missing link
resolves #3623
> chore(code_of_conduct): add jsf conduct link

- package.json
- yarn.lock
Fix manually, bot still cannot sign cla #3622
> chore(deps) fix security vuln manually

- src/content/api/cli.md
added backtiks to cli table docs
> docs(formatting): added back-ticks for tables

- package.json
- yarn.lock
> chore: update voting app link

- src/content/api/compiler-hooks.md
Add initialize hook to compiler hooks
> Docs(api) : Add initialize hook to compiler hooks

- src/content/configuration/dev-server.md
fixes https://github.com/webpack/webpack.js.org/issues/3630
> fix: corrected the wds https example (fixes #3630)

- src/content/api/compiler-hooks.md
> docs(api): Fix typo

- src/content/guides/scaffolding.md
> docs(guides): rephrase description

- src/content/configuration/stats.md
Added a missing option in stats.
Fixes https://github.com/webpack/webpack.js.org/issues/3638
> chore: add detailed stats option

- src/content/api/loaders.md
> docs(api) remove removed context options

- .eslintrc
- package.json
- src/components/SidebarItem/SidebarItem.jsx
- src/components/SidebarItem/SidebarItem.scss
- src/utilities/content-tree-enhancers.js
- src/utilities/list2Tree/findTopLevel.js
- src/utilities/list2Tree/findTopLevel.test.js
- src/utilities/list2Tree/index.js
- src/utilities/list2Tree/index.test.js
- yarn.lock
The current menus in sidebar are flat, take https://webpack.js.org/guides/development/ for example:
Which is actually misleading. There are four heading 2 with three heading 3. This pull request adds hierarchy to the sidebar:
<del>Currently `remark-extract-anchors` would resolve to my own git repo https://github.com/chenxsan/remark-extract-anchors.git#support-levels-option, I've already submitted a pull request [here](https://github.com/montogeek/remark-extract-anchors/pull/4), will update it when the pull request get merged by @montogeek </del>
> Optimize sidebar navigation

- src/components/Sidebar/Sidebar.jsx
> ui(version) show the actual webpack version from master

- src/content/configuration/externals.md
closes #3503 
Reverts #2100
Added externals array references.
> docs(externals): add array reference

- src/content/guides/build-performance.md
A follow up to show the webpack 5 in the content
> docs(guides) show recommended version in guides/build

- package.json
- yarn.lock
Please see the detail explaination here https://github.com/montogeek/remark-extract-anchors/pull/5
> chore(deps): update remark-extract-anchors

- src/content/configuration/stats.md
https://github.com/webpack/webpack/blob/d00e65529a4c5a4e91843f2d4178c66eff3784ae/declarations/WebpackOptions.d.ts#L1818
> docs(config) : Add moduleAsset to stats

- src/content/configuration/output.md
> fix(configuration): fix filename from webpack.config.js to someLibName.js

- src/content/api/compilation-object.md
https://github.com/webpack/webpack/blob/a5a1c4d5fc5aab1c697fc2fdb953ca37518543e7/lib/Compilation.js#L2648 : Referencing
> Docs(api): Add getPathWithInfo function

- src/content/configuration/target.md
- standardized examples of setting a configuration option
- noticed after #3657
> docs(config) target examples standartized

- src/content/configuration/node.md
Added a note for covering query about global variables required by external modules 
ref https://github.com/webpack/webpack/issues/10668
> docs(node): added note for provideplugin in node global

- src/content/concepts/entry-points.md
Same as that of #3439 . Closed #3439 due to confusions in git.
> solving lint issues.

- src/content/guides/asset-modules.md
Fix url-loader to file-loader.
> fix(asset-modules): fix typo

- src/content/api/hot-module-replacement.md
Fixes #3701 
added `module.hot.invalidate()`
> docs(api): add invalidate to HMR api

- src/content/configuration/optimization.md
Add DeterministicChunkIdsPlugin into docs 
https://github.com/webpack/webpack/pull/10613
> Docs(configs): add infos about DeterministicChunkIdsPlugin

- src/content/api/cli.md
> docs(api) CLI example outdated

- src/content/plugins/banner-plugin.md
I think `(string | RegExp)[]` is accurate than `Array`.
> docs(plugins): update option type

- src/content/configuration/experiments.md
Add more experiments' options according to https://github.com/webpack/changelog-v5#experiments
closes: https://github.com/webpack/webpack.js.org/issues/3697
> docs(configuration): add more experiments' options

- src/content/plugins/internal-plugins.md
I've updated some outdated info. Also added some inline comments for easier review.
> docs(plugins): update internal plugins

- src/content/concepts/module-federation.md
Close https://github.com/webpack/webpack.js.org/issues/3731
> docs(concepts): add module federation

- src/content/concepts/dependency-graph.md
- src/content/concepts/hot-module-replacement.md
- src/content/concepts/manifest.md
- src/content/concepts/module-federation.md
- src/content/concepts/targets.md
- src/content/concepts/under-the-hood.md
- src/content/concepts/why-webpack.md
> docs(concepts) add order to the new page and small corr

- src/content/configuration/entry-context.md
https://github.com/webpack/webpack/issues/10833#issuecomment-624195626
> Info about multiple files per entry using array for dependOn

- src/content/concepts/module-federation.md
A few features added to the description, limitation of initial chunk was not mentioned before, therefore omitted.
Closes #3721
> docs(concepts) module federation updates

- src/content/configuration/dev-server.md
> Docs(config) : add info about node options

- src/content/api/compilation-hooks.md
[webpack 5.0.0 beta 17](https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.17) brings some new hooks. This pull request adds info about them.
Also I've added some inline comments so anyone can review it fast.
> docs(api): add processAssets hook

- src/content/configuration/module.mdx
Fixed bad syntax in a code snippet.
> fix(module): fix syntax of a code snippet in module docs

- src/content/concepts/module-federation.md
> docs(concepts): shared modules allow multiple versions in a single build

- src/content/concepts/under-the-hood.md
> docs(concepts): fix grammar

- src/content/concepts/module-federation.md
Adding common errors and troubleshooting them. These are typically seen when upgrading or implementing module federation
> docs: Troubleshooting Module Federation

- repositories/loaders.json
- src/components/Organization/projects.json
- src/content/comparison.md
> chore: remove transform-loader

- repositories/loaders.json
- src/components/Organization/projects.json
- src/content/api/loaders.md
- src/content/guides/code-splitting.md
> clean deprecated bundle-loader

- src/content/api/module-methods.md
> docs(api): remove deprecation note

- src/content/concepts/module-federation.md
> docs(concepts): remove the instruction that consumes bundle-loader

- src/content/plugins/split-chunks-plugin.md
Fix : https://github.com/webpack/webpack.js.org/issues/3804
> plugins:defaults changed 

- src/content/configuration/output.md
Fix https://github.com/webpack/webpack.js.org/issues/3805
> config: add info about output.scriptType

- src/content/api/logging.md
> docs(api): add plugin/loader example for Logger

- src/content/plugins/split-chunks-plugin.md
Document new option in SplitChunksPlugin
#3836
> feat: add enforceSizeThreshold in split chunks plugin

- src/content/api/module-methods.md
- src/content/configuration/module.mdx
> feat(config) Document Data URI import

- src/content/configuration/resolve.md
> docs(configuration): document resolve.roots

- src/content/configuration/node.md
Follow up of https://github.com/webpack/webpack.js.org/pull/3817
> fix(config) Use relative URLs in links

- src/content/configuration/optimization.md
> docs(configuration): fix misleading description

- src/content/api/loaders.md
- src/content/configuration/optimization.md
> docs: improve cleverMerge to respect byDependency order correctly

- src/content/configuration/resolve.md
Fix https://github.com/webpack/webpack.js.org/issues/3867
>  Backport of resolve.roots for webpack 4

- src/content/configuration/other-options.md
`infrastructureLogging` should be heading 2 instead of heading 3.
> docs(configuration): fix heading level

- src/content/concepts/under-the-hood.md
> docs(concepts): clarify `chunks.__./src/index.js` file extension name

- src/content/configuration/module.mdx
- src/content/configuration/output.md
- src/content/guides/asset-modules.md
> document [query] placeholder

- src/content/configuration/stats.md
fixes https://github.com/webpack/webpack.js.org/issues/3888
> fix: document related assets

- repositories/plugins.json
- src/components/Organization/projects.json
> docs: add css-minimizer-webpack-plugin to official plugins list

- src/content/configuration/experiments.md
- src/content/configuration/externals.md
- src/content/migrate/5.md
> clean experiments.importAwait and experiments.importAsync

- repositories/loaders.json
Fix https://github.com/webpack/webpack.js.org/pull/3903#discussion_r468089470
> fix: postcss repo location

- src/content/plugins/split-chunks-plugin.md
> docs(plugins): set the correct default value for splitChunks.chunks

- src/content/plugins/define-plugin.md
Reoslve : https://github.com/webpack/webpack.js.org/issues/2314
> New api for DefinePlugin

- src/content/configuration/optimization.md
> docs(configuration): add optimization.realContentHash

- src/components/Organization/projects.json
> chore(plugins) Add missing maintainer to css-minimizer-webpack-plugin

- src/content/configuration/module.mdx
Describe : https://github.com/webpack/webpack/blob/542ffa969d2f4c67c309ff711ccf00b27ace9ee5/schemas/WebpackOptions.json#L1030
> config : add info about wrappedContextRegExp

- package.json
- src/styles/index.scss
- yarn.lock
closes https://github.com/webpack/webpack.js.org/issues/3578
<del>Currently the dependency uses github branch of my forked repository, I'll update it after https://github.com/montogeek/remark-refractor/pull/1 is merged.</del>
> optimize diff highlighting

- src/content/plugins/NoEmitOnErrorsPlugin.md
> fix(plugins): Update link syntax

- src/content/concepts/module-federation.md
Updated a formatting issue with a tip on the Module Federation page.
> fix(concepts): Tip formatting

- src/content/configuration/other-options.md
closes https://github.com/webpack/webpack.js.org/issues/3936
> docs(configuration): document snapshot

- src/content/api/module-variables.md
Document [import.meta](https://github.com/webpack/webpack/pull/11075).
> docs(api): document import.meta

- src/components/SidebarItem/SidebarItem.jsx
The page should scroll to top, issue #3933
> Fix : Page not scrolled to top when clicking sidebar menu #3933

- src/content/guides/tree-shaking.md
Removed  webpack 4 related stuff,
> Invalid related as the document is of webpack 5

- src/content/contribute/writing-a-plugin.md
> docs(contribute): code layout fix

- src/content/guides/asset-management.md
closes https://github.com/webpack/webpack.js.org/issues/3943
> docs(guides): add example for importing toml/yaml/json5

- src/content/configuration/module.mdx
close https://github.com/webpack/webpack.js.org/issues/3975
> docs(configuration): document resolve.fullySpecified

- src/content/guides/asset-modules.md
> fixes #3863: document usage of content hashes for assets

- repositories/loaders.json
> loader: make stylus-loader official

- src/content/configuration/stats.md
Fix : https://github.com/webpack/webpack.js.org/issues/3948
> config : add warningsCount and errorsCount in stats

- src/content/api/module-methods.md
- src/content/configuration/experiments.md
closes https://github.com/webpack/webpack.js.org/issues/3966
> docs(configuration): remove experiments.mjs

- src/content/configuration/externals.md
> docs: externalsPresets option

- src/content/configuration/output.md
> docs(config) : Add enabledWasmLoadingTypes and wasmLoading for output

- src/components/Sponsors/Sponsors.jsx
- src/components/Sponsors/Sponsors.scss
**Description**
Removed inline styling
> chore: Removed inline styles

- src/content/configuration/output.md
> docs(configuration): output.chunkFilename can be a function

- src/content/api/compilation-object.md
- src/content/api/parser.md
- src/content/api/stats.mdx
Code layout fix with a **small error**  +  Fix related to UI as document follows
> chore : Minor fixes + code error

- src/content/configuration/stats.md
> docs(config) : Add some options for stats

- src/content/configuration/resolve.md
> docs(configuration): add new options for resolve

- src/content/configuration/module.mdx
> docs(Parser): allow to pass custom worker syntax

- src/components/Configuration/Configuration.jsx
- src/content/configuration/index.mdx
add missing configuration options and descriptions
> improve configuration page

- src/content/migrate/5.md
> Improve migration guide

- src/content/configuration/stats.md
> docs(config): add stats.ignoreWarnings

- src/content/configuration/resolve.md
closes https://github.com/webpack/webpack.js.org/issues/4011
> docs(configuration): document preferRelative

- src/content/guides/asset-management.md
Fixes [#4034 ](https://github.com/webpack/webpack.js.org/issues/4034)
> docs(config): add links

- src/components/Configuration/Configuration.jsx
- src/content/configuration/index.mdx
split details in multiple smaller popover
> fix configuration page: add missing popover tags

- .travis.yml
See issue here https://github.com/webpack/webpack.js.org/issues/4031
> update .travis.yml to fix warning

- src/content/api/module-variables.md
> remove process, explain global

- src/content/configuration/output.md
> improve documentation on placeholders

- src/content/concepts/module-resolution.md
- src/content/configuration/index.mdx
- src/content/configuration/resolve.md
- src/content/guides/package-exports.md
> add package exports guide

- src/content/configuration/optimization.md
- src/content/plugins/split-chunks-plugin.md
> docs: add new options for Runtime based optimization

- src/content/api/cli.md
- src/content/concepts/output.md
- src/content/concepts/under-the-hood.md
- src/content/configuration/index.mdx
- src/content/configuration/output.md
- src/content/guides/asset-modules.md
- src/content/guides/build-performance.md
- src/content/guides/code-splitting.md
- src/content/guides/production.md
- src/content/plugins/banner-plugin.md
- src/content/plugins/dll-plugin.md
> filename and hash improvements

- src/content/configuration/mode.md
- src/content/configuration/optimization.md
> removed obsolete options and update mangleExports option

- src/content/concepts/modules.md
- src/content/guides/asset-modules.md
- src/content/guides/ecma-script-modules.md
- src/content/guides/entry-advanced.md
- src/content/guides/integrations.md
- src/content/guides/progressive-web-application.md
- src/content/guides/public-path.md
- src/content/guides/shimming.md
- src/content/guides/typescript.md
> add ECMAScript modules guide and reference supported module types

- src/content/blog/2020-10-10-webpack-5-release.md
> Spelling change

- src/components/Splash/Splash.jsx
- src/components/Support/AdditionalSupporters.js
- src/components/Support/Support.jsx
- src/utilities/fetch-supporters.js
grab monthly sponsoring from transactions
allow to choose between monthly and total display
> sometimes show sponsors by monthly amount

- src/utilities/constants.js
> fix(loaders) Remove svg-inline-loader

- src/utilities/process-readme.js
- src/utilities/process-readme/index.test.js
> Fixed Link Conversion Error

- src/content/guides/package-exports.md
from discussion: https://twitter.com/AndaristRake/status/1319513676823580672
> Add some examples and improve description

- src/content/guides/tree-shaking.md
> docs(guides) Improve documentation about glob support in sideEffects flag

- src/content/configuration/target.md
It should be browser**s**list, not browserlist
https://github.com/browserslist/browserslist
> Fix typo in browserslist in target.md

- src/content/guides/getting-started.md
The character encoding of the page must be declared.
> add character encoding meta

- src/content/guides/environment-variables.md
> Update environment-variables.md to reflect new syntax

- src/content/configuration/optimization.md
> docs(configuration): add new value for optimization.sideEffects

- src/content/api/cli.md
> docs(cli): update --env usage

- src/content/guides/shimming.md
closes https://github.com/webpack/webpack.js.org/issues/3797
Related code demo see https://github.com/chenxsan/webpack-demo/pull/1
Preview: https://webpack-js-org-git-feature-update-shimming-against-webpack5.webpack-docs.vercel.app/guides/shimming/
> docs(guides): update shimming

- src/content/configuration/output.md
> docs(configuration): fix publicPath default value

- src/content/api/cli.md
add exit-codes and their meanings
> docs(cli): add exit-codes and their meanings

- src/content/guides/asset-management.md
follow-up of https://github.com/webpack/webpack.js.org/pull/4134, closes https://github.com/webpack/webpack.js.org/issues/4090
https://github.com/chenxsan/webpack-demo/pull/2
https://webpack-js-org-git-feature-asset-management.webpack-docs.vercel.app/guides/asset-management/
> docs(guides): update asset-management for webpack 5

- src/content/configuration/devtool.md
add a default value for devtool, source code https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L151
> docs(config): add default value for devtool

- src/content/api/stats.mdx
> Docs(api): add asset info for sourceFilename and javascriptModule

- src/components/Support/Support.scss
closes https://github.com/webpack/webpack.js.org/issues/4119
> set bg color for support item under dark mode

- src/content/guides/development.md
follow-up of https://github.com/webpack/webpack.js.org/pull/4134
https://github.com/chenxsan/webpack-demo/pull/4
https://webpack-js-org-git-feature-update-development.webpack-docs.vercel.app/guides/development/
> docs(guides): update development against webpack 5

- src/content/configuration/optimization.md
Follow-up of https://github.com/webpack/webpack.js.org/pull/4180
> docs(configuration): fix value of moduleIds

- src/content/guides/dependency-management.md
> docs(guides): grammar fix

- src/content/plugins/split-chunks-plugin.md
https://github.com/webpack/webpack/blob/65d653961ac56b54c57bdb52d9050901ca19baad/lib/config/defaults.js#L901
> Docs(plugin): Add default for splitchunks

- src/content/guides/build-performance.md
- src/utilities/constants.js
Fixes https://github.com/webpack/webpack.js.org/issues/4144
> loaders: deprecate cache loader

- src/content/migrate/5.md
Relevant issue https://github.com/webpack/webpack/issues/11631#issuecomment-732051563
> docs(migrate): fix typo

- src/utilities/process-readme.js
closes https://github.com/webpack/webpack.js.org/issues/4175
> remove externalLinkRegex

- .github/workflows/testing.yml
- package.json
- src/utilities/fetch-package-repos.js
- yarn.lock
Increases our API rate limit with authentication.
> use github token for CI

- package.json
- webpack.common.js
- yarn.lock
Use Asset Module for fonts and remove `file-loader` as we don't use it anymore.
> use Asset Module for fonts

- README.md
We've migrated from travis to github actions, hence readme needs updated too.
> docs(readme): fix build status

- src/content/configuration/output.md
https://github.com/webpack/webpack/pull/11817#issuecomment-731119689
> docs(output): Update behaviour for output.library and commonjs2

- src/content/api/stats.mdx
> docs(api): update stats data

- package.json
- yarn.lock
Changelog https://docs.cypress.io/guides/references/changelog.html#6-0-0
> upgrade cypress to v6

- src/content/configuration/output.md
> [runtime] can be used a placeholder in output.hotUpdateMainFilename

- src/content/api/cli.md
Updated default config files read by CLI.
Ref - https://github.com/webpack/webpack-cli/blob/dfe76674d83289bf61377fee437f1bee70744a0e/packages/webpack-cli/lib/webpack-cli.js#L116
> fix: update default cli config files

- src/content/api/cli.md
> docs(cli): add a link to stats data API

- src/content/configuration/output.md
As per https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L644
> docs(configuration): update default value

- src/content/configuration/externals.md
Updated docs to reflect the code changes per https://github.com/webpack/webpack.js.org/issues/4242
> Update externals function args

- src/content/configuration/entry-context.md
Fixes https://github.com/webpack/webpack.js.org/issues/4181
> docs(config): update dependOn option

- src/content/configuration/output.md
Fixes https://github.com/webpack/webpack.js.org/issues/4243
> docs(config): update output.pathinfo

- src/content/api/cli.md
add documentation for `--version`.
> docs(cli): add --version

- src/content/plugins/internal-plugins.mdx
Related issue https://github.com/webpack/webpack.js.org/issues/4212
> docs(plugins): document hook for RealContentHashPlugin

- src/content/api/cli.md
Removed redundant description.
> docs(api): remove redundant description

- src/content/api/cli.md
Added a complex example how env can be used
> cli: add more examples of env flag

- src/content/configuration/optimization.md
> Docs(config): Add note about optimization.sideEffects

- src/content/api/cli.md
for consistency throughout the page.
As suggested in https://github.com/webpack/webpack.js.org/pull/4261#discussion_r537053403
> docs(api): use npx for cli commads

- package.json
- yarn.lock
Get rid of `lodash.throttle` as it's no longer used anywhere.
> remove unused throttle

- src/components/Badge/Badge.js
- src/components/Badge/Badge.scss
- src/components/Site/Site.jsx
- src/index.jsx
So we can server side rendering `<Badge />`.
> move MDXProvider to Site

- package.json
- src/components/Markdown/Markdown.scss
- src/plugins/responsive-table/__snapshots__/responsive-table.test.js.snap
- src/plugins/responsive-table/responsive-table.js
- src/plugins/responsive-table/responsive-table.test.js
- webpack.common.js
- webpack.dev.js
- yarn.lock
closes https://github.com/webpack/webpack.js.org/issues/4200
> make table responsive

- src/content/plugins/split-chunks-plugin.md
Add splitChunks.defaultSizeTypes and hidePathInfo
> Docs(plugin): Add splitChunks.defaultSizeTypes

- src/content/migrate/5.md
closes https://github.com/webpack/webpack.js.org/issues/4318
> docs(migrate): document target change

- src/components/Splash/Splash.jsx
These changes improve a11y of checkbox.
> feat: improve a11y

- src/content/api/cli.md
> docs: fix small typos

- src/content/plugins/split-chunks-plugin.md
closes https://github.com/webpack/webpack.js.org/issues/4348
> docs(plugins): clean up automaticNameDelimiter

- src/content/migrate/5.md
Related issue https://github.com/webpack/webpack/issues/12287
> docs(migrate): fix webpack version

- src/content/plugins/environment-plugin.md
Fixes https://github.com/webpack/webpack.js.org/issues/4299
> Improve docs for EnvironmentPlugin defaults

- src/content/api/cli.md
> docs(api): update --help usage

- src/content/api/cli.md
> docs(api): update cli commands

- src/content/guides/web-workers.mdx
closes https://github.com/webpack/webpack.js.org/issues/4341
> docs(guides): add web workers guide

- src/content/api/cli.md
> docs(api): update cli options link

- src/content/api/cli.md
> docs(api): rephrase description

- src/content/guides/web-workers.mdx
> fix(guides) Update typo

- src/content/configuration/output.md
fixes https://github.com/webpack/webpack.js.org/issues/4376
> docs(configuration): fix output.library warning

- src/remark-plugins/remark-responsive-table/remark-responsive-table.js
I think I've delete the credit by mistake, and sorry about that.
> add credit

- src/content/configuration/entry-context.md
- src/content/configuration/experiments.md
- src/content/configuration/externals.md
- src/content/configuration/module.mdx
- src/content/plugins/split-chunks-plugin.md
> feat: add experiments.layer

- src/content/configuration/module.mdx
closes https://github.com/webpack/webpack.js.org/issues/4392
> docs(configuration): add module.parser and module.generator

- src/content/api/parser.md
> fix(api): Update hooks call method

- src/content/configuration/configuration-languages.md
add markdown code inline to module property in configuration-languages.md
> docs(configuration): add markdown code inline to module property

- src/content/guides/package-exports.md
add new node.js features for exports field
add support table for all general features
add rollup, esinstall and wmr to supported tools
> update exports field documentation

- src/content/configuration/devtool.md
fill holes in the table, add explanations
> improve devtool table

- src/content/configuration/externals.md
- src/content/configuration/externals.mdx
closes https://github.com/webpack/webpack.js.org/issues/4438
> docs(configuration): document new externals feature

- src/content/plugins/profiling-plugin.md
PR for #4448 
Added Absolute paths in Profiling plugin docs. 
closes https://github.com/webpack/webpack.js.org/issues/4448
> docs(Profiling Plugin): Added Absolute Path

- src/content/api/module-variables.mdx
closes https://github.com/webpack/webpack.js.org/issues/4451
> docs(api): document __webpack_is_included__

- .github/workflows/deploy.yml
This makes sure that we show up-to-date OC data.
> Make sure to deploy every day

- src/content/plugins/html-webpack-plugin.md
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');
> doc(plugins): update var to const into html-webpack-plugin.md

- src/content/configuration/index.mdx
[https://webpack-js-org-git-fork-nadeenudantha-patch-1.webpack-docs.vercel.app/configuration/](https://webpack-js-org-git-fork-nadeenudantha-patch-1.webpack-docs.vercel.app/configuration/)
> Fix some syntax errors in configuration/index.mdx 

- src/content/concepts/modules.md
A very minor grammatical error - to -> the
> Fix minor grammatical error in modules.md

- src/content/configuration/resolve.mdx
closes https://github.com/webpack/webpack.js.org/issues/4482
> docs(configuration): document resolve.byDependency

- src/content/api/cli.md
explain the usage of the `--merge` option.
> docs(api): explain --merge usage

- src/content/guides/shimming.md
closes https://github.com/webpack/webpack.js.org/issues/4508
> fix(guides): update against latest exports-loader

- src/content/api/cli.md
to be merged after the new webpack-cli release.
Refers https://github.com/webpack/webpack-cli/pull/2369
/cc @alexander-akait
> docs(api): update --entry usage

- src/content/configuration/other-options.md
Fixes https://github.com/webpack/webpack.js.org/issues/4522
> docs(configuration): update info about 'profile' option

- src/content/api/cli.md
> docs(api): fix input types for configuration options

- src/content/api/cli.md
update `help` and `version` usage
> docs(api): update 'help' and 'version' usage

- src/content/configuration/stats.md
Fix https://github.com/webpack/webpack.js.org/issues/4552
> feat: new errorDetails property

- src/content/api/module-variables.mdx
closes https://github.com/webpack/webpack.js.org/issues/4551
> docs(api): document __webpack_base_uri__

- src/content/configuration/configuration-types.md
update reference link for `--config-name`
> docs: update --config-name link

- src/content/guides/web-workers.mdx
fixes https://github.com/webpack/webpack/issues/12614
> Add info about WebWorkers in Node.js

- src/content/api/compilation-hooks.mdx
Thanks to @QC-L for reporting this.
> docs(api): fix wrongly prettified text

- src/content/guides/getting-started.md
This is to make the text more friendly to newcomers.
> Remove "the observant among you"

- src/content/configuration/output.mdx
> docs(configuration): add output.clean

- src/content/api/module-variables.mdx
closes https://github.com/webpack/webpack.js.org/issues/4575
> docs(api): add example for __webpack_chunk_load__

- src/content/configuration/stats.md
https://github.com/webpack/webpack/blob/afc9b2fcf9bef0831640b3ebb02b73068ba18e17/lib/stats/DefaultStatsPresetPlugin.js#L107-L112
> docs(configuration): add 'summary' preset for stats

- src/content/configuration/devtool.md
> docs: rm source maps warning

- src/content/plugins/normal-module-replacement-plugin.md
Update against the latest `webpack-cli`.
> docs(plugins): fix cli usage

- src/content/configuration/module.mdx
A new feature was introduced in webpack 5.23.0 https://github.com/webpack/webpack/releases/tag/v5.23.0
> docs(configuration): document relative url

- src/content/api/loaders.md
closes https://github.com/webpack/webpack.js.org/issues/4630
> docs(api): add jsdoc for loader interface

- src/content/configuration/optimization.mdx
closes https://github.com/webpack/webpack.js.org/issues/4656
> docs(configuration): update stale content

- package.json
Follow-up of https://github.com/webpack/webpack.js.org/pull/4666
> use prepare for husky install

- src/content/guides/caching.md
- src/content/guides/development.md
- src/content/guides/hot-module-replacement.md
- src/content/guides/output-management.md
- src/content/guides/production.md
- src/content/guides/progressive-web-application.md
Resolve https://github.com/webpack/webpack.js.org/issues/4658
> docs(guides): remove `clean-webpack-plugin` in favor of `output.clean`

- src/content/configuration/other-options.md
closes https://github.com/webpack/webpack.js.org/issues/4685
> docs(configuration): add example for dependencies

- src/content/configuration/optimization.mdx
Removing cache: true from TerserPlugin options.
More info: https://github.com/webpack-contrib/terser-webpack-plugin
> fix(docs): TerserPlugin no longer supports `cache: true`

- src/content/configuration/target.md
> docs: fix usage `JsonpTemplatePlugin`

- src/content/concepts/module-federation.md
> docs(concepts): fix typos in `module-federation.md`

- src/content/configuration/configuration-types.mdx
`--optimize-minimize` was removed, https://github.com/webpack/webpack-cli/issues/624
> docs(configuration): remove mentions of removed flags

- src/content/api/cli.md
the documentation is very large add links to avoid long scrolling
> link commands to their docs

- src/content/configuration/module.mdx
This Pull request aims to fix issue https://github.com/webpack/webpack.js.org/issues/4493
> docs: fix UseEntry function return value

- src/content/api/cli.md
add detailed documentation for `npx webpack info` command.
> add documentation for info command

- src/content/branding.md
See https://webpack.js.org/blog/2020-10-10-webpack-5-release/
> docs(branding): update the name guideline

- src/content/api/cli.md
Allows loading ESM config in CLI
> cli: add env var for esm config

- src/content/api/loaders.md
- src/content/api/loaders.mdx
Related pull request https://github.com/webpack/webpack/pull/12935
> docs(api): document this.utils in loader context

- src/content/api/module-variables.mdx
- src/content/guides/ecma-script-modules.mdx
Introduced in https://github.com/webpack/webpack/pull/11075.
> docs(api): document import.meta.webpackHot

- src/styles/index.scss
> style: show icon for external links

- src/content/loaders/index.md
- src/utilities/fetch-package-repos.js
Closes https://github.com/webpack/webpack.js.org/issues/4799
> remove extract-loader

- src/content/guides/environment-variables.md
Follow up https://github.com/webpack/webpack.js.org/pull/4803
> docs(guides): update environment-variables.md

- src/content/api/module-variables.mdx
Closes https://github.com/webpack/webpack.js.org/issues/4703
> docs(api): document __webpack_runtime_id__

- src/content/plugins/internal-plugins.mdx
- src/content/plugins/module-concatenation-plugin.md
Closes https://github.com/webpack/webpack.js.org/issues/4837
> docs(plugins): add warning

- src/content/configuration/resolve.mdx
Closes https://github.com/webpack/webpack.js.org/issues/4805
> docs(configuration): update default for resolve.extensions

- src/content/configuration/other-options.mdx
> docs(configuration): update infrastructureLogging docs

- src/content/configuration/other-options.mdx
https://github.com/webpack/webpack/blob/49a11ce49d9518333e5f1194c6c506e909c5bc26/lib/config/defaults.js#L296
> docs(configuration): set the correct default value for cache.idleTimeout

- src/content/api/cli.md
Add example usage for the `WEBPACK_PACKAGE` environment variable.
> docs(api): explain usage of `WEBPACK_PACKAGE` env var

- src/content/api/compilation-hooks.mdx
See https://github.com/webpack/webpack.js.org/pull/4812#discussion_r609668667
> docs(api): update misleading part

- src/content/concepts/loaders.mdx
> docs(concepts): fix formatting

- src/content/configuration/other-options.mdx
[https://github.com/webpack/webpack/blob/master/lib/config/normalization.js#L129-L143](https://github.com/webpack/webpack/blob/00f4a82903d99502ffa1eee5c0bfd2fa405d04b8/lib/config/normalization.js#L129-L143)
> docs(configuration): specify cache.type requirement

- src/content/configuration/other-options.mdx
Refers https://github.com/webpack/webpack-cli/issues/1794
> docs(configuration): add warning for bail and watch

- src/content/guides/getting-started.md
Closes https://github.com/webpack/webpack.js.org/issues/4893
> docs(guides): fix misleading content

- src/content/configuration/other-options.mdx
closes https://github.com/webpack/webpack.js.org/issues/4903
> docs(configuration): document cache.allowCollectingMemory

- src/content/configuration/other-options.mdx
Adds new cache option to profile cache timings.
Fix #4920
> add cache profile option

- src/content/api/cli.md
https://github.com/webpack/webpack-cli/pull/2576
> docs(api): update cli subcommands usage info

- src/content/api/cli.md
https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L1026 
To be merged after the new release.
> docs(api): add WEBPACK_CLI_HELP_WIDTH env variable

- src/content/loaders/index.md
- src/utilities/constants.js
- webpack.ssg.js
- [raw-loader](https://github.com/webpack-contrib/raw-loader)
- [url-loader](https://github.com/webpack-contrib/url-loader)
- [file-loader](https://github.com/webpack-contrib/file-loader)
> remove deprecated loaders

- src/content/migrate/5.md
> docs(migration): update usage info

- src/content/loaders/index.md
https://github.com/webpack/webpack.js.org/blob/88ebf00732717f25f356bbe36394c2bfdc2b1331/src/utilities/constants.js#L3
> docs(loaders): remove reference to eslint-loader

- src/content/configuration/other-options.mdx
- src/content/migrate/5.md
Use consistent formatting for the entire page.
> docs(configuration): use consistent formatting

- src/content/configuration/index.mdx
- src/content/configuration/output.mdx
Added a short description of `options.trustedTypes` config setting. Addresses #4960.
> Added options.trustedTypes setting documentation.

- src/content/configuration/output.mdx
See https://github.com/webpack/webpack/releases/tag/v5.37.0
> docs(configuration): add version badge

- src/content/concepts/loaders.mdx
`--module-bind` is no longer supported as far as I know.
> docs(concepts): clean stale content

- src/components/NotificationBar/NotificationBar.scss
See https://github.com/webpack/webpack.js.org/pull/4988#issuecomment-842355931.
> Remove min-height to fix a overlay problem

- package.json
Drop node 10 support as it's end of life.
> drop node 10

- src/content/configuration/dev-server.md
add cli usage for `devServer.serveIndex` -
`npx webpack serve --serveIndex`
> docs(configuration): add CLI usage for serveIndex

- src/content/configuration/mode.mdx
Closes https://github.com/webpack/webpack.js.org/issues/4972
> docs(configuration): clean stale configuration

- src/content/guides/web-workers.mdx
The title is self-explanatory.
> Fix double negative in grammar.

- src/components/Navigation/Navigation.jsx
- Add [Korean translation site](https://webpack.kr/) to the dropdown list
Preview:
> Add Korean translation site to dropdown list

- src/content/concepts/module-federation.md
All code related to overrides was removed - 
https://github.com/webpack/webpack/commit/e78a76b2e00a17c62dcc3ce8a8ffa1b131a6431d#diff-fc7055018e1900b8bb0feffbdfe152f916fd99dec480326df98d54c223ca8ded
> docs(concept): remove OverridablesPlugin

- src/content/api/cli.md
https://github.com/webpack/webpack-cli/pull/2700
To be merged post the release.
> docs(cli): add aliases for options

- src/content/api/cli.md
https://github.com/webpack/webpack-cli/pull/2709
To be merged after release.
> docs(api): add alias for --output

- examples/module-federation/.stackblitzrc
- examples/module-federation/README.md
- examples/module-federation/app1/package.json
- examples/module-federation/app1/public/index.html
- examples/module-federation/app1/src/App.js
- examples/module-federation/app1/src/bootstrap.js
- examples/module-federation/app1/src/index.js
- examples/module-federation/app1/webpack.config.js
- examples/module-federation/app2/package.json
- examples/module-federation/app2/public/index.html
- examples/module-federation/app2/src/App.js
- examples/module-federation/app2/src/bootstrap.js
- examples/module-federation/app2/src/index.js
- examples/module-federation/app2/webpack.config.js
- examples/module-federation/lerna.json
- examples/module-federation/package.json
- src/components/StackBlitzPreview/StackBlitzPreview.jsx
- src/content/concepts/module-federation.mdx
- src/content/guides/getting-started.mdx
- src/content/plugins/module-federation-plugin.mdx
Added Stackblitz example on module federation related pages.
> Added Stackblitz example for module federation

- examples/module-federation/app1/package.json
- examples/module-federation/app2/package.json
- examples/module-federation/app2/webpack.config.js
I believe some dependencies are placed on the wrong place. cc @XiaofengXie16
> docs(examples): fix dependencies

- src/content/plugins/define-plugin.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5087
> docs(plugins): revise DefinePlugin

- src/content/migrate/5.md
This really just fixes a tiny typo that my OCD couldn't cope with.
> Fix tiny typo

- package.json
- webpack.common.js
- yarn.lock
And remove the [`sideEffects` rule](https://github.com/pmndrs/react-spring/issues/1078) which is no longer needed for the stable version.
> update react-spring to its latest version

- src/components/Navigation/Navigation.jsx
- src/components/Site/Site.jsx
Added pathname to keep the consistency of reading while changing language.
Closes https://github.com/webpack/webpack.js.org/issues/5105
> feat: #5105 add pathname at the end of dropdown language url

- src/content/configuration/other-options.mdx
> docs(configuration): add cache.idleTimeoutAfterLargeChanges

- src/content/configuration/experiments.mdx
- src/content/configuration/externals.mdx
- src/content/configuration/output.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5120
> docs(configuration): document esm support improvement

- src/content/configuration/resolve.mdx
closes https://github.com/webpack/webpack.js.org/issues/4101
> docs(configuration): list polyfills

- src/components/Contributors/Contributors.jsx
- src/components/Footer/Footer.jsx
- src/components/Logo/Logo.jsx
Ensure that the browser can allocate the correct amount of space in the document while the image is loading which would avoid sudden layout shifts.
> set width/height for img

- src/content/guides/shimming.md
Closes https://github.com/webpack/webpack.js.org/pull/5155
> docs(guides): fix additionalCode

- src/content/configuration/cache.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5140
> docs(configuration): add cache.compression

- src/components/PageLinks/PageLinks.jsx
The italic style seems too distracting on mobile.
> remove italic style

- .github/workflows/testing.yml
use `actions/setup-node@v2` for workflow
> ci: use `actions/setup-node@v2`

- src/components/Navigation/Navigation.jsx
- src/styles/tailwind.css
Some small improvements to the navigation bar:
1. higher contrast between the active menu and non-active ones
2. update hover color to keep consistency with its active state
> optimize navigation colors

- src/content/plugins/module-federation-plugin.mdx
> docs(plugins): clean up unrelated comment

- src/content/api/hot-module-replacement.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5213
> docs(api): add tip for status handler in HMR API

- src/content/configuration/stats.md
- src/content/configuration/stats.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5203
> docs: add `stats.reasonsSpace` and `stats.groupReasonsByOrigin`

- .github/workflows/deploy.yml
Upgrade to v4 per https://github.com/JamesIves/github-pages-deploy-action/discussions/592
> upgrade deploy action

- src/content/branding.md
We no longer use the font on this site.
> docs(branding): clean up stale content

- src/content/api/node.mdx
Related issue https://github.com/webpack/webpack.js.org/issues/5249
> docs(api): close compiler

- src/content/configuration/output.mdx
See commits for options get moved in this pull request.
> docs(configuration): sort output options alphabetically

- webpack.ssg.js
Added back page button on Desktop PWA.
> [DesktopApp] add back page button ⬅️

- src/content/configuration/dev-server.mdx
Fix serve options link
Fixes https://github.com/webpack/webpack.js.org/issues/5300
> fix: dev server options link

- src/content/configuration/dev-server.mdx
- src/content/configuration/stats.mdx
- src/content/guides/development.mdx
- src/content/guides/progressive-web-application.mdx
> docs(configuration): webpack-dev-server v4

- src/content/configuration/dev-server.mdx
Add `devserver.onListening` documentation.
> docs(configuration): add devserver.onListening

- src/content/configuration/dev-server.mdx
update type for an array of strings.
https://github.com/webpack/webpack-dev-server/blob/d10bcc3aeb973890ac714ccad33adfc417ac84b5/lib/options.json#L526
> docs(configuration): update `static.publicPath` type

- src/content/configuration/dev-server.mdx
update `allowedHosts` CLI usage
> docs(configuration): update `allowedHosts` CLI usage

- src/content/configuration/dev-server.mdx
add `allowedHosts: 'auto'` documentation.
> docs(configuration): add `allowedHosts: 'auto'`

- src/content/configuration/dev-server.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5344
> docs(configuration): update usage of devServer.static

- src/content/configuration/dev-server.mdx
> docs(configuration): add required minimum version of packages for devServer

- src/content/api/cli.mdx
> docs(api): add usage of `build` command

- src/content/api/cli.mdx
> docs(api): add usage of `watch` command

- src/content/concepts/plugins.mdx
Added a link to the plugins list from the introduction.
> Link to plugins list from introduction

- src/content/api/cli.mdx
add `loader` and `plugin` commands usage
> docs(api): add `loader` and `plugin` commands

- src/content/api/cli.mdx
> docs(api): add `serve` command

- src/content/configuration/dev-server.mdx
add types for `client.progress` and `devMiddleWare`.
> docs(configuration): add types for `client.progress` and `devMiddleWare`

- package.json
- src/components/Link/Link.jsx
- yarn.lock
Fix https://github.com/webpack/webpack.js.org/pull/5383
> chore: update `eslint-plugin-react`

- src/content/configuration/stats.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5378
> docs(configuration): add `stats.nestedModules`

- src/content/configuration/dev-server.mdx
> docs(configuration): add `devServer.magicHtml`

- src/content/configuration/cache.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5371
> docs(configuration): fix default value

- src/content/api/loaders.mdx
- src/content/configuration/experiments.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5399
> docs(configuration): remove experiments.executeModule

- src/components/Contributors/404.js
> docs(migrate): hide non-existent contributor

- src/content/configuration/dev-server.mdx
update `devServer.devMiddleware` webpack configuration example.
> docs(configuration): fix `devMiddleware` configuration

- src/utilities/fetch-package-readmes.js
Related issue https://github.com/webpack/webpack.js.org/issues/4430
> set group for loaders

- src/content/configuration/experiments.mdx
- src/content/configuration/node.mdx
closes https://github.com/webpack/webpack.js.org/issues/5451
> docs(configuration): document futureDefaults

- src/content/configuration/stats.mdx
Reference - 
https://github.com/webpack/webpack/blob/20da4b1ef83cd86480abc19206faebfe477b0a15/schemas/WebpackOptions.json#L4235
https://github.com/webpack/webpack/blob/20da4b1ef83cd86480abc19206faebfe477b0a15/schemas/WebpackOptions.json#L4227
> docs(configuration): add `groupAssetsByExtension` and `groupAssetsByPath`

- src/content/configuration/index.mdx
> docs(configuration): update devServer configuration

- src/content/configuration/output.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5491
> docs(configuration): add tip for `xxhash64` algorithm support for hashing

- src/components/Contributors/404.js
> docs(configuration): hide non-existent contributor

- src/content/api/compiler-hooks.mdx
Fix https://github.com/webpack/webpack.js.org/pull/3430
> docs(configuration): fix typo

- src/content/configuration/cache.mdx
- src/content/configuration/experiments.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5492
> docs(configuration): document experiments.cacheUnaffected

- src/content/configuration/dev-server.mdx
Improved the overall document fixing wordings adding necessary punctuations and making it more easier to read.
> docs(configuration): improve `devServer` documentation

- src/content/api/cli.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5477
> fix: use webpack-cli package with npx

- src/content/concepts/why-webpack.mdx
> docs(why-webpack): fix typo

- src/content/concepts/under-the-hood.mdx
> docs(under-the-hood.mdx): fix typo

- src/content/guides/author-libraries.mdx
> docs(contribute): fix link in author-libraries.mdx

- src/content/contribute/writing-a-plugin.mdx
> docs(contribute): Update writing-a-plugin.mdx

- src/content/configuration/dev-server.mdx
Add missing require statement for `fs`.
> docs(configuration): update example configurations

- src/content/configuration/dev-server.mdx
update `devServer.server` type
> docs(configuration): update `devServer.server` type

- src/content/guides/typescript.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5655
> docs(guides): document client types for typescript

- src/content/configuration/experiments.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5664
> docs(configuration): document backCompat

- src/content/plugins/split-chunks-plugin.mdx
closes https://github.com/webpack/webpack.js.org/issues/5654
> docs(plugins): document fallbackCacheGroup.chunks

- src/content/configuration/index.mdx
- src/content/configuration/optimization.mdx
- src/content/guides/development-vagrant.mdx
> chore: fix typo

- src/content/plugins/split-chunks-plugin.mdx
Fixes https://github.com/webpack/webpack.js.org/issues/5593
> docs(plugins): add `splitChunks.minSizeReduction`

- src/content/api/cli.mdx
> fix the plugin name

- src/content/configuration/module.mdx
remove old webpack v2 comment.
> docs(configuration): remove old webpack v2 comment

- src/content/configuration/watch.mdx
Document `watchOptions.stdin` option
https://github.com/webpack/webpack/blob/0065223c4ddac3bf872bc8d660ef1e9a63afa080/schemas/WebpackOptions.json#L4934
> docs(configuration): add `watchOptions.stdin`

- package.json
- yarn.lock
> chore: update  `webpack-dev-server`

- src/content/configuration/resolve.mdx
Document `resolve.useSyncFileSystemCalls`.
https://github.com/webpack/webpack/blob/f1e9221da63ea9ba64e83136da91f4593c5b5b3e/schemas/WebpackOptions.json#L3735
> docs(configuration): add `resolve.useSyncFileSystemCalls`

- package.json
- yarn.lock
bump `postcss` dependency version
> chore: bump `postcss` version

- .github/PULL_REQUEST_TEMPLATE.md
Update CLA link to the latest.
> docs: update CLA link

- src/content/guides/hot-module-replacement.mdx
Now the file dev-server.js runs with an error, including an error in the config part. Modify it to the correct example.
> update Via the Node.js API dev-server.js

- src/content/configuration/dev-server.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5768
> docs(configuration): fix mimeTypes example

- src/content/configuration/dev-server.mdx
add deprecation warning for `server.options.cacert`.
> docs(configuration): add warning for `server.options.cacert`

- .eslintrc.js
- src/components/Navigation/Navigation.jsx
- src/sw.js
> chore: enable `no-duplicate-imports` eslint rule

- src/content/configuration/experiments.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5799
> docs(configuration): document experiments.css

- src/content/guides/shimming.mdx
the hackernoon website version cannot be found by searching, so changed it to the medium article by the person
> update link to medium article

- src/content/awesome-webpack.mdx
Adds `webpack-typescript-directory-compile-plugin` plugin to plugin list.
> Add `webpack-typescript-directory-compile-plugin` plugin

- src/content/configuration/dev-server.mdx
Fix https://github.com/webpack/webpack-dev-server/issues/4129
update `setupMiddlewares` example for `devServer` with migration.
> docs(configuration): update `setupMiddlewares` example

- package.json
- yarn.lock
> chore: update eslint

- src/content/configuration/mode.mdx
update link for webpack default options.
> docs(configuration): update link for webpack default options

- src/components/Configuration/Configuration.scss
Fix https://github.com/webpack/webpack.js.org/issues/3990
Fix https://github.com/webpack/webpack.js.org/pull/3991
> fix: popover functionality

- src/content/configuration/output.mdx
> docs(configuration): add new `commonjs-static` output type

- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5891
> docs(configuration): add `module.generator.asset.outputPath`

- src/content/configuration/output.mdx
> docs: avoid `Badge` in heading

- src/content/configuration/externals.mdx
Fix #5927 
References-
https://github.com/webpack/webpack/blob/4bc61504b2f2d11e08615d8dc670c55aed4f9841/schemas/WebpackOptions.json#L1024
https://github.com/webpack/webpack/blob/4bc61504b2f2d11e08615d8dc670c55aed4f9841/schemas/WebpackOptions.json#L928
> docs(configuration): update `externals` option types

- src/content/api/module-variables.mdx
Fix https://github.com/webpack/webpack.js.org/issues/5918
> docs(api): add `__webpack_module__` and `__webpack_module__.id`

- src/content/configuration/output.mdx
> fix link to Node.js docs

- src/content/api/cli.mdx
Update description to include `server` command/alias as well.
> docs(api): update description for `WEBPACK_SERVE` env variable

- src/components/Site/Site.jsx
- src/content/vote.mdx
Fix Vote page, see https://github.com/webpack/webpack.js.org/pull/5900 and https://github.com/webpack/webpack.js.org/pull/6016.
> fix Vote page

- src/content/configuration/module.mdx
fix #6004 
add parserOptions.importMetaContext
> docs: add parserOptions.importMetaContext

- src/content/configuration/dev-server.mdx
> docs(configuration/dev-server): Fix wrong typo

- src/components/Page/Page.jsx
- src/utilities/fetch-package-readmes.mjs
- tailwind.config.js
Closes https://github.com/webpack/webpack.js.org/issues/6030
> add disclaimer for third-party packages

- src/content/configuration/output.mdx
Fix https://github.com/webpack/webpack.js.org/issues/4924 
https://github.com/webpack/webpack/blob/770dea1fb46c7c5e04016dbab1f0854037b00d81/lib/config/defaults.js#L780-L785
> docs(config) : Change default value output.globalObject

- src/content/api/cli.mdx
udpate description for `--force` option
> docs(api): udpate description for `--force` option

- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/issues/6087
> docs(configuration): add `module.parser.javascript.importMeta`

- src/content/plugins/split-chunks-plugin.mdx
Fix https://github.com/webpack/webpack.js.org/issues/3998
> docs: add info about moving modules to parent chunks

- src/content/guides/asset-modules.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6095
> docs(guides): mention outputPath and publicPath

- src/content/api/hot-module-replacement.mdx
> docs(api): fixed a typo in Hot Module Replacement Page

- src/components/SidebarItem/SidebarItem.jsx
- src/scripts/concatenate-docs.mjs
> fix(scripts/concatenate-docs & compoents/SidebarItem): replace equal to strictEqual

- package.json
- yarn.lock
> chore: update webpack-cli to v4.10.0

- src/components/Navigation/Navigation.jsx
The subnav item should be highlighted when we are visiting its child sections.
> fix highlighting for current subnav

- src/content/configuration/other-options.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6205
> docs(configuration): add new type

- package.json
Node 12 was end of life on 30 April 2022.
> drop node 12

- src/content/api/module-variables.mdx
Closes https://github.com/webpack/webpack.js.org/issues/5966
> docs(api): document canMangle

- src/content/concepts/index.mdx
- small grammatical fix to improve readability
> fix(concepts): small grammatical edit

- src/content/configuration/resolve.mdx
Fix https://github.com/webpack/webpack.js.org/issues/6254
> docs(configuration): add `resolve.extensionAlias`

- src/content/plugins/module-concatenation-plugin.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6286
> docs(plugins): fix stale content

- package.json
- yarn.lock
close #6297 
See also https://github.com/scinos/yarn-deduplicate#deduplication-strategies
> chore: upgrade `eslint-plugin-mdx`, run `yarn-deduplicate --strategy fewer` for fewer `acorn` versions

- src/content/guides/progressive-web-application.mdx
Update broken link to PWA resource
> Update broken link to PWA resource

- src/content/configuration/externals.mdx
Explain the externals string syntax specifying externalsType
Fixes #4148
Fixes #5928
> Explain the externals string syntax specifying externalsType

- src/content/configuration/dev-server.mdx
Path to invalidate the bundle is incorrect.
> Update path to invalidate

- src/content/api/plugins.mdx
Resolve https://github.com/webpack/webpack.js.org/issues/5583
> docs(api): update custom hooks API for plugins

- src/content/guides/asset-modules.mdx
See https://github.com/webpack/webpack/issues/12474#issuecomment-1250249790
> docs(guides): add emit section for asset modules

- .github/workflows/testing.yml
- package.json
- yarn.lock
E2e tests [failed with the default electron](https://github.com/webpack/webpack.js.org/pull/6397), let's see if using Chrome would fix it.
> CI: running e2e tests with Chrome

- src/styles/tailwind.css
- tailwind.config.js
According to https://tailwindcss.com/docs/upgrade-guide
> upgrade tailwindcss configuration

- .github/CONTRIBUTING.md
Update Note to use node v14.
https://github.com/webpack/webpack.js.org/blob/0527e459f13e4b426837c459466a944e5889c62f/package.json#L24
> docs: update Node version note in CONTRIBUTING.md

- src/content/configuration/target.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/4130
> docs(configuration): add a note about runtime code and user code

- src/content/api/loaders.mdx
> fix: fix wrong Conditional Operator

- src/content/plugins/source-map-dev-tool-plugin.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6541
> docs(plugins): update filename example

- src/content/guides/web-workers.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6535
> docs(guides): document magic comments for web worker

- src/content/api/cli.mdx
Update doc per https://github.com/webpack/webpack-cli/pull/3514
> docs(api): update cli

- src/content/concepts/module-federation.mdx
- src/content/plugins/module-federation-plugin.mdx
Added a few useful pointers to the module federation plugin docs and also fixed a few grammatical errors
> docs(module federation): improve module federation docs

- src/content/configuration/optimization.mdx
Close https://github.com/webpack/webpack.js.org/issues/6586
> docs(Configuration): explain ... for optimization.minimizer

- src/content/configuration/other-options.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6380
> docs(configuration): add example for managedPaths

- .github/workflows/testing.yml
- debug.js
- package.json
- src/utilities/githubAPI.mjs
- webpack.common.mjs
- yarn.lock
Follow-up of https://github.com/webpack/webpack.js.org/pull/6659 as the bug in react-spring has been fixed, hence we can remove the `fullySpecified` rule in `webpack.config.js`.
Closes https://github.com/webpack/webpack.js.org/pull/6662
> upgrade react-spring

- src/content/awesome-webpack.mdx
🚀 Focus on improving the first screen loading speed of applications and providing the best user experience, inspiration comes from [the preloading of NextJS](https://web.dev/route-prefetching-in-nextjs/). 
- Split modules loads as needed, improving the first screen loading experience of your App. 
- Minimize dynamic component loading time and providing the best user experience.
- Support manually to preloading.
- Support automatic the preloading of resources ( JS / Component /  Module-Federation / UMD / Svg / Png , Etc) by route and providing the best user experience.
- Support typescript.
> commit webpack plugin form route-resource-preload

- src/content/guides/tree-shaking.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6677
> docs(guides): mention devtool for tree shaking

- src/content/configuration/output.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6711
> docs(Configuration): add output.workerPublicPath

- src/content/configuration/output.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6742
> docs(Configuration): document amdContainer

- package.json
- src/utilities/fetch-package-readmes.mjs
- src/utilities/fetch-package-repos.mjs
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/pull/6751
> build(deps-dev): bump mkdirp

- src/content/configuration/output.mdx
Fix `amdContainer` description
> docs(Configuration): fix document amdContainer

- src/content/configuration/output.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6777
> docs(Configuration): document output.ignoreBrowserWarnings

- src/content/contribute/writing-a-loader.mdx
https://github.com/webpack/loader-utils/blob/master/CHANGELOG.md#-breaking-changes
> loader-utils > 3.0.0 version has removed stringifyRequest method

- src/content/api/normalmodulefactory-hooks.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6778
> docs(API): document createModuleClass hook

- src/content/awesome-webpack.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6614
> docs(Awesome): add transpile-webpack-plugin

- src/content/configuration/module.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6822
> docs(Configuration): update document to use asset modules

- src/content/configuration/output.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6803
> docs(Configuration): document onPolicyCreationFailure

- src/content/api/compilation-hooks.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6827.
Will convert it into `ready for review` once the new webpack version released.
> docs(api): document afterChunks

- src/components/Sidebar/Sidebar.scss
Closes https://github.com/webpack/webpack.js.org/issues/6838
> show scrollbar for sidebar

- src/content/api/loaders.mdx
- src/content/configuration/output.mdx
- yarn.lock
Closes https://github.com/webpack/webpack.js.org/issues/6868
> docs(API): document this.environment for loader context

- src/content/plugins/progress-plugin.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6877
> docs(plugins): document createDefaultHandler

- src/content/plugins/split-chunks-plugin.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6882
> docs(plugins): document regexp for splitChunks.chunks

- src/content/api/module-methods.mdx
- src/content/configuration/module.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6907
> docs: document dynamicImportFetchPriority and webpackFetchPriority

- src/content/configuration/cache.mdx
Closes https://github.com/webpack/webpack.js.org/issues/6867
> docs(Configuration): document cache.readonly

- .github/dependabot.yml
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> group dependencies update

- package.json
- src/utilities/fetch-supporters.mjs
- yarn.lock
Use Node.js built-in `fetch` instead.
> remove node-fetch

- src/content/awesome-webpack.mdx
- yarn.lock
> feat: add webpack manifest plugin to awesome list

- src/content/configuration/experiments.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7098
> docs: update `Server` types

- src/content/configuration/experiments.mdx
- src/content/configuration/module.mdx
Document all support options in the latest release.
> docs(module): update generator option

- src/content/configuration/experiments.mdx
- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7097
> docs(configuration): add css generator & parser options

- src/content/configuration/node.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7095
> docs(configuration): update node options

- src/content/concepts/plugins.mdx
Fix https://github.com/webpack/webpack.js.org/pull/3601
Fix #3321
> docs(plugins): update plugin name note

- src/content/configuration/other-options.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7092
> docs(configuration): add `snapshot.unmanagedPaths`

- src/content/configuration/output.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7121
> docs(configuration): add `output.environment.asyncFunction`

- src/content/configuration/optimization.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7129
> docs(configuration): update optimization.removeAvailableModules

- src/content/configuration/output.mdx
[Ref Schema](https://github.com/webpack/webpack/blob/651b3d66d10d54da31d4cb7123ea74d10f1f5456/schemas/WebpackOptions.json#L134-L146)
> docs: update output.assetModuleFilename type

- src/content/configuration/output.mdx
[Ref Schema](https://github.com/webpack/webpack/blob/651b3d66d10d54da31d4cb7123ea74d10f1f5456/schemas/WebpackOptions.json#L3245-L3250)
> docs: add `output.cssFilename` & `output.cssChunkFilename`

- .github/CONTRIBUTING.md
- package.json
- yarn.lock
- minimum supported Node.js version is 18.12.0
- Update dev server to v5
> ci: minimum supported Node.js version is 18.12.0

- src/content/configuration/dev-server.mdx
> docs(configuration): dev-server v5 changes

- src/content/configuration/output.mdx
[Ref Schema](https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/schemas/WebpackOptions.json#L3339)
> docs(configuration): add `output.importMetaName`

- src/content/configuration/output.mdx
- [Ref Schema](https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/schemas/WebpackOptions.json#L3424)
- [Default value](https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/lib/config/defaults.js#L906)
> docs(configuration): add `output.webassemblyModuleFilename`

- src/content/configuration/stats.mdx
Fix https://github.com/webpack/webpack.js.org/pull/3226
> docs(configuration): update stats.mdx

- src/content/api/loaders.mdx
- src/content/api/module-methods.mdx
- src/content/api/plugins.mdx
- src/content/branding.mdx
- src/content/concepts/index.mdx
- src/content/configuration/experiments.mdx
- src/content/guides/code-splitting.mdx
- src/content/guides/hot-module-replacement.mdx
- src/content/guides/shimming.mdx
- src/content/guides/typescript.mdx
Refs https://github.com/webpack/webpack.js.org/issues/5015
> docs:remove insensitive wordings

- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7162
> docs(configuration): add css generator exportsConvention and localIdentName

- src/content/plugins/dll-plugin.mdx
Add warning about this PR: [18203](https://github.com/webpack/webpack/pull/18203)
> docs(dll-plugin): Add warning to dll-plugin.

- src/content/configuration/node.mdx
update `node` option type & remove v3 mention.
> docs: update `node` option type

- src/content/configuration/optimization.mdx
dd `optimization.checkWasmTypes`
> docs: add `optimization.checkWasmTypes`

- src/content/configuration/resolve.mdx
[Reference Schema](https://github.com/webpack/webpack/blob/4fda15571d66bb593a1bad69835a6797b2f911c6/schemas/WebpackOptions.json#L3938-L3940)
> docs(configuration): add `resolve.cache`

- src/content/configuration/resolve.mdx
[Reference Schema](https://github.com/webpack/webpack/blob/4fda15571d66bb593a1bad69835a6797b2f911c6/schemas/WebpackOptions.json#L4023)
> docs(configuration): add `resolve.fullySpecified`

- src/content/configuration/stats.mdx
Sort stats options on the page
> docs: sort `stats` options

- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/pull/4908
> docs(configuration): update `module.noParse`

- src/content/configuration/stats.mdx
> docs(configuration): update stats.colors type

- src/content/api/compilation-hooks.mdx
Refers https://github.com/webpack/webpack.js.org/issues/2728
> docs(api): add `Compilation.hooks.statsPreset`

- src/content/api/compilation-hooks.mdx
> docs(api): add `Compilation.hooks.statsNormalize`

- src/content/plugins/module-federation-plugin.mdx
Fixes https://github.com/webpack/webpack.js.org/issues/6802
> docs(ModuleFederationPlugin): update requiredVersion description

- src/content/contribute/writing-a-loader.mdx
Fix https://github.com/webpack/webpack.js.org/pull/3526
> docs(contribute): add data sharing info among chained loaders

- src/content/api/compilation-hooks.mdx
> docs(api): add `Compilation.hooks.statsFactory`

- src/components/NotificationBar/Notification.mdx
> Update webpack 5 notification message

- src/content/api/cli.mdx
Fix https://github.com/webpack/webpack.js.org/pull/7080
> docs(api): update `--define-process-env-node-env` usage

- src/content/configuration/module.mdx
- src/content/guides/code-splitting.mdx
Fix https://github.com/webpack/webpack.js.org/issues/6418
> docs(guides): clarify SplitChunksPlugin behavior

- .github/dependabot.yml
Already upgraded through https://github.com/webpack/webpack.js.org/pull/7289.
> clean up dependabot

- src/content/index.mdx
I added a comma in "Awesome, isn't it? [...]" because I felt it would fit.
> add a comma

- src/content/configuration/resolve.mdx
Close https://github.com/webpack/webpack.js.org/issues/6748. Related https://github.com/webpack/webpack/issues/7976#issuecomment-820706796
> docs(configuration): update resolve.unsafeCache

- src/content/configuration/module.mdx
Close https://github.com/webpack/webpack.js.org/issues/7306
Do not merge until a new version webpack is released.
> docs(configuration): document overrideStrict

- src/content/configuration/output.mdx
Per https://github.com/webpack/webpack/issues/3559#issuecomment-268965473. Close https://github.com/webpack/webpack.js.org/issues/7081
> docs(configuration): document commonjs-module

- .husky/pre-commit
Per https://github.com/typicode/husky/releases/tag/v9.1.2
> clean up pre-commit

- .github/CONTRIBUTING.md
Update Node requirement.
https://github.com/webpack/webpack.js.org/blob/5b14579a5c630043ecf61c69d6a4a9795b0628bf/package.json#L23-L25
> docs: update required Node.js version in CONTRIBUTING.md

- src/content/configuration/module.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7286
> docs(configuration): add `binary` option for module.generator

- .husky/pre-commit
- package.json
- yarn.lock
References - 
- https://github.com/typicode/husky/releases/tag/v9.1.1
- https://github.com/typicode/husky/releases/tag/v9.0.1
> chore: update husky configs

- src/content/api/module-methods.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7355
> docs: add `webpackIgnore` for `new URL()`

- src/content/plugins/normal-module-replacement-plugin.mdx
Fix https://github.com/webpack/webpack.js.org/pull/5995
Fix https://github.com/webpack/webpack.js.org/issues/5059
> docs(plugins): update NormalModuleReplacementPlugin example

- src/content/plugins/split-chunks-plugin.mdx
Fix https://github.com/webpack/webpack.js.org/issues/7082
> docs(configuration): update `splitChunks.cacheGroups.{cacheGroup}.name` note

- package.json
- src/components/Navigation/Navigation.jsx
- yarn.lock
> chore: update @docsearch/react to v3

- package.json
- yarn.lock
Upgrade `react-helmet-async` to the latest release.
> chore: update `react-helmet-async` to v2

- .github/workflows/testing.yml
Fix https://github.com/webpack/webpack.js.org/pull/7443
> ci: update errata-ai/vale-action

- src/content/api/cli.mdx
Update minimum requirements to use webpack-cli v6
> docs(cli): update the requirements note

- src/content/api/loaders.mdx
See https://github.com/webpack/webpack/discussions/19208#discussioncomment-12126100.
> docs(loaders): update async loader API documentation

- repositories/README.md
Fix the fetch package file path specified in README.md
> docs: fix fetch package file path

- .github/workflows/testing.yml
Docs- https://vale.sh/docs/formats/mdx
> ci: fix vale action

- src/components/Footer/Footer.jsx
> fix: remove gitter link from footer

- src/content/plugins/virtual-url-plugin.mdx
[webpack/pull/19508](https://github.com/webpack/webpack/pull/19508)
> feat: Add VirtualUrlPlugin
