content/concepts/core-concepts.md
content/concepts/index.md

This document is the landing page for the "Concepts" section in our docs page. This is most likely going to be one of the first things a first-time user (or any user reads) and should expose to them some abstract/high-level terminology and webpack definitions that will be tossed around throughout the rest of the docs. And will segue into a Core Concepts page. (Which is stubbed for now). 
This corresponds to #38

newdoc(concepts): intro to webpack 

---

content/concepts/targets.md
styles/components/_blockquote.scss

Gotten started on the targets section. Work in progress.

docs(concepts): added new targets section

---

content/how-to/develop-using-vagrant.md

I documented how you can use webpack-dev-server with Vagrant.
I know it may be not the most important aspect, seeing how much still needs to be done, but I also wanted to get some practice with documenting a how-to. There will be more!
The part I'm not sure about is whether to show a full working `Vagrantfile`. At the moment I show only one config thingy from the `Vagrantfile`.
Related: #26
Sidenote: the contributing guidelines say to create an issue first when creating a new page, but this was already discussed in #26. Is this good enough?

Documentation for how to develop using Vagrant

---

content/how-to/hmr/hot-module-reload-with-react.md
content/how-to/hot-module-reload.md

Add documentation for a basic How Module Replacement (HMR) setup. The example uses Babel, React, and CSS modules, and explains how to edit webpack.config, what dependencies are needed, and how to structure the source code.

Content howto hmr

---

content/api/cli.md
content/how-to/install-webpack.md

Not sure of the content. Please treat as first draft. Will work on any feedback.

Adds HOWTO for webpack installation

---

.markdownlintrc
package.json

* Markdown lint added. There are a variety of rules we can choose from. I selected some defaults.
* Tests should fail on this commit. I will cleanup all documents afterwards.

feat(lint): implement markdownlint

---

.alexrc
package.json

* Adds alex social sensitivity linter
*  Upon using social insensitive language, one will receive lint errors and warnings. 
Although this isn't entirely dire in the context of what we are writing, it's simple and super helpful for keeping people in-check/aware just in case.

feat(lint): add alex social sensitivity linter

---

.travis.yml

I was noticing that all recent travis builds were still running against node 4 as the config. Am curious if this is related to the invariant issues. Going to try this out.

chore(travis): update the node_js version on travis config

---

content/concepts/output.md

with @joshq00
used [WebpackOptionsDefaulter](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js) as reference
Need more detail for the following options 
Need to review for changes in webpack 2

output options with webpack 1 definitions - wip

---

content/concepts/entry-points.md

The links on entry page were pointing to wrong place and now they are fixed.

Update links entry point page 

---

content/configuration/dev-server.md

I added much more documentation to the DevServer configuration page. Some of my additions are inspired by the existing docs, but most of it is completely rewritten.

Add more configuration documentation for DevServer

---

content/how-to/develop.md

I'm planning to write the whole "how to develop" page soon, but I would like to see first what you guys think of the structure.
I'm not even sure if explaining the three ways to develop (dev-server, dev-middleware, webpack watch) is the best way to go here. We could also explain the most common and easy use case with dev-server here, and explain the other two ways in a subpage.
I really would like some feedback on this.

Extend stub for "how to develop"

---

content/how-to/upgrade-from-webpack-1.md

Added code-splitting guide from "Whats new in webpack 2 old doc" into new one.
I noticed that @addyosmani was linking https://gist.github.com/sokra/27b24881210b56bbaff7 in his newest Medium publications, its probably best we just add this content to the new page which is more comprehensive and detailed for webpack 2.x. 
cc// @bebraw

feat(migration-guide): added System.import

---

content/configuration/dev-server.md
content/configuration/watch.md

Added some more docs to WatchOptions.
Moved duplicate documentation from DevServer about WatchOptions to there. Added link back to WatchOptions.
Also added how to disable `contentBase` while I was at it :).
PS: Still working on the "how to develop" page.

Improve WatchOptions docs

---

content/how-to/cache.md

This dependency helped me to retrieve my chunk unique hashes while rendering my views on the server side. My view wasn't an html file so I couldn't simply use `html-webpack-plugin`. I thought this worth mentioning and save people's time.

Suggesting `webpack-isomorphic-tools` for server-side rendering.

---

content/concepts/entry-points.md
content/concepts/index.md
content/concepts/output.md
content/concepts/plugins.md
content/concepts/targets.md
content/how-to/cache.md

Fixes #228 
- Moves `module.exports` to syntactically valid positions (e.g. after `const config = {...}` is defined).
- In some cases, removes `module.exports` line entirely when it has already been written at least once in the doc (as per @timdorr 's suggestion)

Move module.exports to syntactically valid positions

---

content/how-to/develop.md

This is my first try at the "How to develop" page.
According to the stubs I made earlier, I should also include how to use the Node.js API for the watch mode and dev-server. On second thought, this should really be a separate page. For beginners this will be even more confusing. We already teach them 3 ways to develop, with the API variants that would essentially mean 5 ways.
I'm curious to your feedback!

Add content for "how to develop"

---

content/configuration/resolve.md

Updated the resolve documentation to be compatible with webpack v2. Also improved some explanations and added an introduction.
Before we can close #220, the `resolveLoader` option should also be properly documented.

Update resolve docs to webpack v2

---

content/configuration/dev-server.md
content/configuration/stats.md

As described in #226, this moves the documentation I wrote about `devServer.stats` to a separate page, because it also applies when using webpack itself.
Fixes #226

Move stats documentation to separate page

---

content/configuration/dev-server.md

In this PR, documentation for the new `--watch-content-base` feature of `webpack-dev-server` has been added.

Add devServer.watchContentBase documentation

---

content/configuration/resolve.md

* mentions default value for mainFields, and then specifies alternate default for targets that are not `web` or `webworker`.

feat(config/resolve): add target information for mainFields section

---

components/site/site.jsx
components/splash/splash-style.scss
components/splash/splash.jsx
styles/index.scss

This adds an open collective banner (minimalist) and navigation link to "DONATE". We are now apart of the open collective organization. Am open to additional styling but wanted to get the base content in ASAP.

feat(donate/open_collective): add open collective content

---

package.json

Adding the `http-server` package and a simple script to test the site after doing a build. Down the road once there are less discrepancies between the dev-server and build this will probably will become unnecessary, but for now I find it useful.

Adding a script to test production builds

---

content/how-to/upgrade-from-webpack-1.md

This fixes a little typo in the upgrade guide, no biggie :)
Thanks for writing this doc, helped me to understand some of the differences of Webpack 2 to Webpack 1. Will definitely give it a try in a project now. Thank you all for your hard work!

doc: fix typo in upgrade guide

---

content/how-to/set-up-hmr-with-react.md

Spent an hour debugging why my devserver wasn't working. Turns out /dist would try to serve from a root folder name 'dist' on my filesystem!

Consistent use of resolve()

---

components/page/page.jsx
components/sidebar-item/sidebar-item-style.scss
components/sidebar-item/sidebar-item.js
components/sidebar/sidebar.jsx

This PR is based on #256 . The only thing that I found out that is was not yet implemented is
> When you click on menu with sub-menu, sub-menu should open
Some more things that I found:

Desktop Sidebar

---

content/how-to/code-splitting/splitting-css.md
content/how-to/code-splitting/splitting-require.md
content/how-to/code-splitting/splitting-vendor.md
content/how-to/split-code.md

Trying to tackle #3 with this.

How to split code?

---

content/get-started.md

**Context/problem:**
I like the content on the 'get started' page, it's a nice quick overview. However, there's a few options in the conclusion for what to do/read next. This could create some 'choice paralysis' for the user. It also means the learning journey doesn't have a linear flow which may mean users don't know what they *should* read next. 
**Solution:**
Linking to the next logical section (concepts) with a main call-to-action link at the bottom should solve this. I've added the link as part of this PR. If you think this is a good idea we can change wording/styling to suit.

link from get started to concepts

---

content/configuration/index.md

Pointed out the speed/detail diff between source-map and eval. Shows that there is plenty of reason to evaluate which devtool to use, depending on the needs. At least in prod/dev environments

Speed/detail diff between source-map and eval

---

content/configuration/index.md

As per @bebraw's great tip, I pointed users to the webpack 1 upgrade guide so they know that -loader suffix is not mandatory for clarity purposes

Loader suffix tip to the upgrade guide

---

content/how-to/upgrade-from-webpack-1.md

Mentioned that `react.ensure` is still needed when custom chunk names are required

Note on custom chunk names w/ System.import

---

content/concepts/output.md

`bundle.js` is a better example than `blah`, also, it is the same example used in the introduction page.
`false` is the default value.

Slightly improved wording

---

content/get-started/index.md

Ref: https://github.com/webpack/webpack.js.org/pull/293#discussion_r87222508

get-started: Fix and clarify usage of two dashes in npm scripts

---

content/api/node.md

Fixes `stats.toJSON()` -> `stats.toJson()`.
I'm pretty sure the correct method is `toJson()`: https://github.com/webpack/webpack/blob/ac340bce1d7239c0e6c0d0cf93dbb6c26dddde1f/lib/Stats.js#L21. However, I'm definitely not an expert on webpack core, so I could be wrong. Certainly in webpack@2.1.0-beta.25 it is.

Fix stats.toJson() naming

---

content/concepts/configuration.md
content/concepts/entry-points.md
content/concepts/index.md
content/concepts/loaders.md
content/concepts/output.md
content/concepts/plugins.md

added fixed and todo from review

---

content/concepts/entry-points.md

I guess this is the first time `entry` is mentioned.
I don't know why `T> As a rule of thumb: for one HTML use exactly one entry point.` is highlighted as change? I didn't change something.

fixed link

---

content/guides/migrating.md

Hot-fix to section: Automatic -loader module name extension removed
Added example to opt-in to the old behavior with the resolveLoader.moduleExtensions configuration option.

Hot-fix to section: Automatic -loader module name extension removed

---

.eslintrc

This tells ESLint not to extend any config up the directory tree, which (for example) makes it easier to be used as a submodule.
Let's say that I'm building a Dash docset from new Webpack docs, _hipothetically_, 😜 and I'm including this repo as a submodule, this repo's ESLint config will inherit my docset's config.

Define the ESLint config as root

---

antwar.config.js
content/api/plugins.md
content/pluginsapi/compilation.md
content/pluginsapi/compiler.md
content/pluginsapi/dependency.md
content/pluginsapi/examples.md
content/pluginsapi/index.md
content/pluginsapi/module-factories.md
content/pluginsapi/parser.md
content/pluginsapi/resolver.md
content/pluginsapi/tapable.md
content/pluginsapi/template.md

This directory structure allows contribs like @pksjce and myself to independently work on different sections of the plugin api with little friction. I'm going to close the existing PR I have open and we can start from here.

feat(pluginapi): implement separate directory structure for plugins api

---

content/configuration/devtool.md

In https://github.com/webpack/webpack/issues/3270#issuecomment-260578258, sokra described a valid use case for hidden-source-maps. This PR documents that. The whole source map page should be refactored some time soon, but at least this information is now in there...
Fixes https://github.com/webpack/webpack/issues/3270

Document use-case for hidden-source-map

---

components/navigation/navigation-style.scss

The mobile menu button appears in a place it shoulnd't on Chrome (at least using the Desktop version with a small viewport).
That margin is the cause. Also, to let the logo be center aligned the best way is to absolute positioning the menu button and take it out of flow.

Fixed mobile menu alignment

---

content/concepts/loaders.md
content/loaders/index.md

This PR splits the loader documentation in two parts: a concept page and a configuration page.
It also adds most of the content @manekinekko has written in #249 + my own content.

Improve loader docs

---

components/navigation/search-style.scss

In continuation with #285, here are some improvements for how search looks.

Improved spacing and color scheme of search

---

content/concepts/targets.md
content/configuration/target.md

This PR removes the duplicate target options (see #373), fixes various typo's and adds an intro text.
Fixes #373.

Deduplicate target options and improve descriptions

---

content/get-started/index.md

The script tag in `get-started/index.md` is incorrectly placed. If someone tries to execute the code to demonstrate how browsers load global variables, they're going to get an error that the browser can't read `appendChild` of undefined because `document.body` won't exist yet. 
The script tag should be placed at the bottom of the body so that they don't get confused (although this is a pretty inconsequential thing and the whole point of this part of the tutorial is to tell people not to code this way lol).

Getting Started Clarifications

---

content/get-started/index.md

Adds missing comma in webpack.config.js sample code and a word in ## Using webpack with npm section.

Fixes some typos in Get Started with Webpack

---

content/get-started/index.md

Added a missing comma in `module.exports`

Fixed small typo in get started guide

---

content/configuration/resolve.md

The resolve docs were somewhat inconsistent and sometimes wrong. I fixed most of the issues I think.
I also compared the documented options to the table in https://github.com/webpack/webpack.js.org/issues/68#issuecomment-242033413 and added some descriptions.
@TheLarkInn, I'm not sure if #68 can be closed after this?

Improve resolve docs

---

.travis.yml

If you're making a PR from a branch on the same repo (only possible if you're a collaborator / admin), Travis CI does a build twice. This can take a looong time. This PR fixes that.

Only let Travis build on the master and develop branch

---

components/sidebar-mobile/sidebar-mobile.jsx

`element.style = '';`
does _NOT_ clear up inline styles on safari.
Need to target specific property we are trying to remove.
`element.style.transform = '';`
in our case.
Closes #412

fix mobile sidebar from getting stuck on iOS safari.

---

components/contributors/contributors-style.scss
components/contributors/contributors.jsx

Higher res contributor images with nick name

Contributor heads

---

styles/index.scss
styles/markdown.scss
styles/prism-theme.scss

- Use `chevron` icon for summary-details marker whenever possible.
- Make the focus style for summary details subtle.
- Easier to identify code links in object properties or in comments.
- A new dark prism theme (forked from the previous one) taking into account the new color scheme.

New dark prism theme

---

components/sidebar-mobile/sidebar-mobile-style.scss
components/sidebar-mobile/sidebar-mobile.jsx
template.ejs

- Sidebar open is a _pull_ transition rather than a linear one.
- New styles for sidebar to indicate active state, use colors from scheme.
- Added a theme color meta tag for chrome.
|  Before | After  |
|---|---|
| <img src="https://cloud.githubusercontent.com/assets/8946207/20642265/99eea528-b430-11e6-9c1e-dd032a9772f4.png" width="300"> |  <img src="https://cloud.githubusercontent.com/assets/8946207/20642260/83641298-b430-11e6-81cc-b3d55926c17b.png" width="300"> |

Mobile enhancements

---

CONTRIBUTING.md

I noticed that some people commit with an email that is not coupled to GitHub, causing issues with the CLAbot. Hopefully by documenting this, people will be reminded to link Git <-> GitHub.

Document CLA bot in contributing section

---

content/guides/code-splitting-libraries.md

All `filename` properties in `code-splitting-libraries.md` are using quotation marks for open their filename string and «closing» them with backticks. Yeah, is a silly edit, but I'm just reading the documentation and it disturbes me ^_^U.

Fix mixed quotation marks and backticks

---

content/concepts/index.md

The word should be "its" since the intention is to convey possession, not a contraction of "it is".

Remove incorrect apostrophe usage in "it's".

---

content/configuration/target.md

They seem unnecessary to me and might cause confusion.

Remove unclear qoutes in configuration/target/ around "node"

---

content/get-started/index.md

Removing the double title in the get-started index page.

Remove Double Title in Get-Started

---

content/configuration/other-options.md

I tried using the debug option and got an Invalid configuration object error message so it seems strange to keep this Webpack 1 config in the v2.1 documentation.  I see there are some details about how to properly specify debug here: https://webpack.js.org/guides/migrating/#debug so I figured that's sufficient.

The 'debug' property was removed in webpack 2.

---

components/splash/splash-style.scss

improve homepage styling

---

components/splash-viz/splash-viz-style.scss

Hey, i found while browsing front-page in landscape mode there is glitch with logo:
And after fix:
It's little bit smaller but it works on every tested device in chrome simulator

Fix landscape size of logo on front page

---

content/index.md

I find it confusing (as I'm sure others will) that the import is `bar` but the file is `foo.js`. This goes against standard practices ASFAIK so I propose keeping names consistent.

Rename example import file to match import name

---

content/guides/hmr-react.md

The current code doesn't work with `react-hot-loader@3.0.0-beta.6`, following this discussion https://github.com/gaearon/react-hot-loader/issues/243 I could fix my own code with the changes on how the hot module replacement api was called.

hmr-react: Update code on project config

---

content/concepts/index.md

`path` is required for the examples to work as is.

Add path module to examples

---

content/guides/lazy-load-react.md

Use import() to lazy load files as it is now supported in webpack 2 as opposed to previously using System.import

Use import() for lazy-loading

---

content/guides/migrating.md

Also added deprecation note. I think describing it with `import()` instead of just `import` will cause less of a headache for newcomers who don't know the difference between `import from` and `import()`.

Migration docs: Changed `System.import` to `import()`

---

content/guides/migrating.md

Under "Code Splitting with ES2015," the function inside `then()` should _return_ `module.default`.
Addresses https://github.com/webpack/webpack.js.org/issues/502

Update migrating.md: code-splitting section typo

---

content/configuration/index.md

Add a simple callout at the beginning of the docs directing any newbies to the concepts page. See #505

Add concepts link to documentation

---

content/concepts/loaders.md

There was a typo in the documentation for loaders. This is a quick correction.

correct grammatical typo

---

content/concepts/index.md

I think it is more appropriate to link to [output configuration](https://webpack.js.org/configuration/output/) instead of [configuration](https://webpack.js.org/configuration/). Feel free to discard it though.

Update output configuration link

---

content/configuration/index.md
content/configuration/performance.md

docs(performance): Add performance config documentation

---

components/sidebar-item/sidebar-item.jsx

This fix prevents full page refresh for anchor links in sidebar.
Closes webpack/webpack.js.org#530

Use html anchor tag for sidebar anchor links

---

content/guides/hmr-react.md

Sorry, looks like the site only recognizes the heading if it has a space.

Fix Heading

---

content/plugins/loader-options-plugin.md
content/plugins/source-map-dev-tool-plugin.md

This PR adds docs for the loader options plugin (as well as a placeholder for SourceMapDevToolPlugin https://github.com/webpack/webpack.js.org/issues/494  ).
The docs may well be inaccurate - that's fine; set me straight!

Added docs for loader options plugin (and placeholder for sourcemap)

---

content/guides/migrating.md

Should we be mentioning https://github.com/airbnb/babel-plugin-dynamic-import-webpack separately as well?

add note about use with Babel [skip ci]

---

content/get-started/index.md
content/get-started/install-webpack.md

This makes the installation instructions work before version 2 is stable.
See #486.  Fixes #367.

Update instructions for installing webpack 2

---

content/guides/hmr-react.md

Change the dependency version of Webpack to beta 25 - earlier versions don't support rules.use, so they aren't compatible with code presented in the guide.

Update HMR guide - dependency fix

---

content/api/cli.md

Running `webpack --optimize-dedupe` with latest release doesn't work either.

Removed --optimize-dedupe option as it was removed from webpack

---

components/sidecar/sidecar-style.scss

Resolves #382
@skipjack What do you think?
I see two fixes for this problem:
1. Increase break point (implemented in this PR)
2. Add padding to the content so that we can still display sidecar to the 1024px break point
I think that first option is better, that's why it's also part of this PR :smiley:

Fixed sidecar overflowing content

---

content/api/cli.md

To access the page when searching for "cli"
> Adding (CLI) to the header tag on that page should make it a top match for the short CLI
https://github.com/webpack/webpack.js.org/issues/557

added (CLI) to CLI page title following discussion in #557

---

content/guides/production-build.md

Apparently https://webpack.js.org/guides/production-build/ did not render correctly
because spaces where missing in between hashes and headings.

Fix markdown headers by adding spaces

---

components/splash-viz/splash-viz.jsx
components/text-rotater/text-rotater-style.scss

See #540 
Setting `flex-shrink: 0;` fixes the text overlapping problem on safari. Used `* >` in case someone uses the component with something else than `<span>` as children.
Also set an initial delay on the text rotator, because the first transition did not work on safari if none was set.

Fix scrolling marquee text overlapping on safari

---

content/concepts/module-resolution.md

Just a fix for small typo, the link text says `mainFiles` but the link URL points to `mainFields`.
The fix is obvious: `s/mainFiles/mainFields/`

Fix link text on module resolution page

---

content/guides/production-build.md
content/plugins/define-plugin.md

- Copy over docs of DefinePlugin from webpack 1
- Add `webpack -p`
- Clarify `NODE_ENV` and the role of DefinePlugin
Addresses #353.
Incorporates parts of @markerikson's blog post https://www.packtpub.com/books/content/building-better-bundles-why-processenvnodeenv-matters-optimized-builds

production-build: enhance documentation

---

bootstrap.js

Allow bootstrap.js to be run directly

---

content/configuration/module.md
content/guides/migrating.md

Clear examples of how loaders are chained, and also mention that `!` chaining is legacy.
Idea for added docs came from https://github.com/webpack/webpack.js.org/issues/569 and https://github.com/webpack/webpack/issues/3713.

Loader chaining config

---

content/index.md

Add one sentence to the home page, to make it clear that you need to run a webpack command to actually build the thing.

Mention running the command on home page

---

content/configuration/index.md

The example did not work since the `assetFilter` function was passing in `assetFilename` but was using `assetName` within the function body instead.

Fixing configuration performance example

---

content/guides/migrating.md

I _think_ it currently says the opposite of what it means because of a one letter typo - figured it would quicker to just submit a PR than an issue 🚀

Fix typo in migration guide

---

content/configuration/other-options.md

In the distant past, long before React, ES Modules, fancy bundlers, or
even bower, the web was a very different place. Some might say, it was,
simpler.
Back in those days, to include a dependency in your project you had
primarily had two options:
- Download the required files and place them into a vendor directory.
- Hotlink the JavaScript from another source.
In either case, script tags had to be added to your site's HTML in the
correct order—manually handling dependency order—and the scripts
modified the window scope.
As web pages were beginning to become more complicated, this method of
doing things presented two major issues: it was common to include
resources that weren't being used, and errors attempting to use
a resource that hadn't yet been loaded.
AMD, the Asynchronous Module …

config: tales of jQuery and the early days of modules

---

content/concepts/output.md

Fix output example to use output.filename instead of assigning file to output object.

DOCS: Fix output example to use object.filename

---

content/configuration/resolve.md

Non-existent prop resolve.resolveToContext should be removed.

config:remove none-existent resolveToContext prop description. fix #634

---

content/guides/hmr-react.md

The node API for `babel` has been moved to `babel-core`.

Babel package is no-op in babel 6.*

---

content/configuration/index.md

If you're going to use the path library in the configuration sample, it ought to be included. Otherwise newb readers (points to self) will get confusing errors.

Include path library in sample configuration

---

CONTRIBUTING.md
package.json

This is a _required_ change based on the usage of `let` without `use strict` [here](https://github.com/webpack/webpack.js.org/pull/607/files#diff-454cc7d35544d042a685f267fef1f668R234).
Obviously this is not the only way to resolve this issue (add `use strict` or avoid `let`), but either way I would suggest adding the node engine version requirement to the `package.json` – let me know how you would like to proceed and I can provide a follow-up PR if necessary. 
**edit** 
I just noticed the Travis configuration uses `node` at `6` so this might, in fact, be the desired change set.

Specify NodeJS version for contributing to documentation.

---

content/index.md
styles/homepage.scss
styles/index.scss
utilities/markdown.js

Resolves #350
Now you can write HTML directly into the markdown files.

Added split code blocks to home page

---

content/configuration/output.md

The following snippet in https://github.com/webpack/webpack.js.org/blob/master/content/configuration/output.md#outputlibrarytarget makes use of "output.name" where it should be "output.library":
```
But, require([ _what?_ ])?
output.library!
output: {
name: "MyLibrary",
libraryTarget: "amd"
}
```

correct a typo

---

content/guides/lazy-load-react.md

Refactor LazilyLoad.js example to use latest React recommendations to be more defensive for Fiber rendering. This moves side effects into different lifecycle hooks. 
I actually jumped on to update the documentation to `import()` away from `System.import` but open source is awesome and others have already done that! So instead I made it more React-future friendly.
cc @TheLarkInn

update(guides/lazy-load-react): fiber friendly side-effects

---

content/guides/lazy-load-react.md

Redoing the merge against master.

update(guides/lazy-load-react): refactor LazilyLoad.js example to use fiber friendly side-effects

---

content/guides/code-splitting-require.md

`RequireJS` in the title is misleading ( confused with [RequireJS](http://requirejs.org/) ). It should be just `require.ensure`

`RequireJS` in the title is misleading.

---

content/guides/migrating.md

`BannerPlugin` no longer accept two parameters but rather only a single options object

Added section on BannerPlugin

---

components/page/page.jsx

Append `/index` to the Edit link to `index` pages like Getting started

Fixes #624, append index to index URLs

---

content/guides/production-build.md

[The manual way: Configuring webpack for multiple environments](https://webpack.js.org/guides/production-build/#the-manual-way-configuring-webpack-for-multiple-environments) example have syntax error.
This is  what the page show:
**dev.js**
```javascript
module.exports = function (env) {
devtool: 'cheap-module-source-map',
output: {
path: path.join(__dirname, '/../dist/assets'),
filename: '[name].bundle.js',
publicPath: publicPath,
sourceMapFilename: '[name].map'
},
devServer: {
port: 7777,
host: 'localhost',
historyApiFallback: true,
noInfo: false,
stats: 'minimal',
publicPath: publicPath
}
}
```
It should be like this as i think:
**dev.js**
```javascript
module.exports = function (env) {
return {
devtool: 'cheap-module-source-map',
output: {
path: path.join(__dirname, …
```

Docs: Bugfix/production build

---

content/guides/code-splitting-css.md

Replaces `modules.exports` in first webpack.config.js snippet with
`module.exports`.

Fix Typo in `code-splitting-css.md`

---

content/guides/migrating.md

The docs mention `use` to be a property on `module` while this is incorrect. `rules` should be used instead.
Closes: #668

fix(migrating): Incorrect migration docs regarding 'rule'

---

components/vote/app-style.scss

In smaller screen sizes of Safari (e.g. Mobile) the user and score sections were overlapping the content. Which made the it harder to read the copy. Move the position to be medium on up. 
This wasn't an issue in Chrome or Firefox. Confirmed this still looks as expected in Safari medium on up, Chrome medium on up and Firefox medium on up.
**Before**
**After**

[Vote Style] fix issue in Safari mobile

---

content/plugins/commons-chunk-plugin.md

Was reading about CommonsChunkPlugin and found a typo in code sample that would throw practitioners of copy-and-paste off.

fix typo in commons-chunk-plugin.md

---

content/pluginsapi/compiler.md

Typo: `comfiguration` -> `configuration`

Update compiler.md - typo fix

---

content/get-started/index.md

Previous example returned `Hello ,webpack ` rather than `Hello webpack`.

fix example js

---

content/guides/webpack-and-typescript.md

I think it makes sense to have it there, because people will pretty quickly run into `Module not found: Error: Can't resolve` and it is not easy to figure out the cause of this error by searching since it is very generic.
Besides, I've extended second configuration example with additional rule; it is easier to copy paste it that ways, which people will likely do.

Adding resolve.extentions to configuration sample

---

content/guides/caching.md

Updated description for long-term caching with Webpack 2
* Describes scenario for long-term caching, where manifest is separated into entry where chunk manifest is extracted into own file
* Does not describe the option of using recordsPath
* Does not describe into detail what causes hash changes
Addresses issues: https://github.com/webpack/webpack.js.org/issues/652 and https://github.com/webpack/webpack/issues/1315

Long-term caching with Webpack 2

---

components/splash/splash.jsx

😅 Although its manual work its satisfying to need to bump our sponsorship counts and backer counts on the homepage. I profiled load speed and everything looks alright still. 😅

feat(splash): bump sponsor and backer counts

---

content/guides/development.md

Just a simple addition to the list of instructions on how to disable safe write in WebStorm

Added instructions to disable safe write in the WebStorm IDE

---

content/guides/webpack-and-typescript.md

Hi, 
This fixes duplicate module rules.
The intention I suppose was to have a rule for `.js` and one for `.ts(x)`
Cheers!

Fix in webpack-and-typescript.md code example

---

content/guides/code-splitting-require.md

Read this here: http://survivejs.com/webpack/building-with-webpack/code-splitting/#-require-ensure- and used it myself. Thought it would be useful information.

`require.ensure` needs Promise polyfill

---

content/guides/production-build.md

1. Fixing the code snippet on [building for production](https://webpack.js.org/guides/production-build/) page.
In given below code snippet only function reference should be returned.
```
module.exports = buildConfig(env);
```
should be
```
module.exports = buildConfig;
```
2. Fixing typo from 'you' to 'your'.

Fixing code snippet and typo for production build guide

---

content/api/loaders.md

As documented in the [migration guide](https://webpack.js.org/guides/migrating/#cacheable), loader results are cacheable by default. This change clarifies this fact in the loader API docs.

Clarify that loaders are cacheable by default

---

components/cube/cube.jsx

`setInterval()` execute regardless of whether a page or tab is visible or the browser window has been minimized, potentially resulting in wasted drawing calls.
`requestAnimationFrame()` was designed to solve this problem.
- https://hacks.mozilla.org/2011/08/animating-with-javascript-from-setinterval-to-requestanimationframe/
- [requestanimationframe](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
- [Performance.now()](https://developer.mozilla.org/en/docs/Web/API/Performance/now)

cube setInterval -> requestAnimationFrame

---

components/splash/splash-style.scss
components/splash/splash.jsx

I love what the homepage has turned into! It's really looking great. I have just a couple tweaks to the intro section that I think make it look a bit more fluid:
1. Adding a darker background to separate it visually from the 'support' section
2. Removing out of place 'webpack' title
Before/after preview:

Homepage cleanup

---

components/vote/app-style.scss

I think the votes were very hard to read especially on mobile. It was hard to figure out, if some points are for the feature above or below the points. I added some margins as a a quick fix.
**Old**
**New**

quick fix to make votes more readable

---

content/guides/hmr-react.md

As mentioned at [here](https://github.com/gaearon/react-hot-boilerplate/blob/9609a8e567b940ff341176638fb1169f70efd461/src/index.js) and  [here](http://localhost:3000/guides/hmr-react#code), just re-render the component works properly and re-require() then use a new component doesn't work as long as I tried.

require() for components is no longer needed after hot-update.

---

content/guides/author-libraries.md

This is no longer required in webpack 2, JSON files are loaded by default.

Remove JSON loader

---

content/get-started/index.md
content/get-started/install-webpack.md

Since we do not recommend a global webpack installation, do not rely on
it in the getting started guide
Relates to item 2 from #486.

Get started: do not rely on global installation

---

content/api/cli.md

Remove `--optimize-occurence-order` as `OccurrenceOrderPlugin` is now enabled by default. Remove the comma after `--define`.

Update description for -p parameter

---

package.json

Looks like the new version broke things. There should be yarn lockfile etc.

Fix preact-compat version

---

content/guides/code-splitting-libraries.md

From the [Stack Overflow answer](http://stackoverflow.com/questions/30329337/how-to-bundle-vendor-scripts-separately-and-require-them-as-needed-with-webpack/38733864#38733864
) I gave a while back.
I updated the example to use `module.context` since it's more reliable than `module.userRequest`.
@bebraw you might want to [update](http://survivejs.com/webpack/building-with-webpack/splitting-bundles/#loading-dependencies-to-a-vendor-bundle-automatically)
Where I have this example and then seeing
https://webpack.js.org/plugins/commons-chunk-plugin/#explicit-vendor-chunk
I am starting to think that maybe this and all examples in this area should migrate to the plugin example section to have one area for all related common chunk info.

Adding documentation for implicit common vendor chunk

---

content/configuration/resolve.md

In Webpack 2+ this would throw an invalid configuration object error.

Empty extension isn't valid anymore

---

content/configuration/dev-server.md

Noticed that this option was missing in the docs while writing docs for grunt-webpack.

Add hotOnly option for devServer

---

content/api/loaders.md
content/concepts/hot-module-replacement.md
content/development/how-to-write-a-loader.md
content/guides/code-splitting-css.md
content/guides/migrating.md
content/guides/shimming.md
content/guides/webpack-and-typescript.md
content/plugins/banner-plugin.md
content/plugins/commons-chunk-plugin.md
content/plugins/define-plugin.md
content/plugins/environment-plugin.md
content/plugins/html-webpack-plugin.md
content/plugins/index.md
content/plugins/loader-options-plugin.md
content/plugins/provide-plugin.md
content/plugins/source-map-dev-tool-plugin.md
content/writers-guide.md
scripts/fetch_package_files.js

* loaders are enclosed in backticks and kebab-cased
* plugins are enclosed in backticks and CamelCased
#794 is meant to be merged first. I'll rebase afterwards.

Consistent typesetting for loaders and plugins

---

styles/markdown.scss

Add prefix to info/warning/todo tips via CSS

---

content/guides/code-splitting-libraries.md

Added hint about hashing policy used to achieve long-term caching in libraries code splitting section.

Code splitting libraries - hashing policy hint

---

content/concepts/loaders.md
content/loaders/index.md

* Move all loader documentation to /concepts/loaders
* List various loaders at /loaders, partially based on https://github.com/webpack/webpack/blob/2ed6448/README.md#loaders

/loaders: add index of important loaders

---

antwar.config.js
content/guides/comparison.md
content/guides/task-test-runner.md

Rationale: The title "why webpack" is a vague. The content "webpack vs. task runners" and "webpack vs. other bundlers" is not directly related.

Split why-webpack into task-runner and comparison

---

content/guides/code-splitting-css.md

Focus on the relevant points. Link to corresponding loaders/plugins for
details. Consistent typesetting for loaders/plugins.

code-splitting-css: rewrite guide in a concise way

---

content/configuration/environment.md
content/guides/production-build.md

* Using `--env`
* Using environment variables
Fixes #790.

Document how to specify environment in config

---

content/plugins/commons-chunk-plugin.md

Added `new webpack.optimize.CommonsChunkPlugin` instead of `new CommonsChunkPlugin`

Typo fix, makes cleaner for beginners

---

components/splash-viz/splash-viz-style.scss

Preventing abnormally large illustration on large screen sizes (e.g. desktops). Stretching the illustration starts to look a bit funny past a certain point.
Before:
After:

Minor Fix for the Landing Page

---

content/plugins/index.md
content/plugins/normal-module-replacement-plugin.md

My humble contribution to that great project. Refs #814 
I tried to keep the same structure used on other plugin documentations but it doesn't look like there is a template to follow. Please advise me if changes are needed.

normal-module-replacement-plugin: add documentation

---

content/configuration/dev-server.md

Just to make it clear how developers can use the dev server through the node api instead of the CLI 😁✨🤖

Add nodejs api example to webpack dev server docs

---

utilities/markdown.js

Removed `section` variable from `renderer.image` in file markdown.js because it will fail to load resource ( jpg, gif, svg, mp4 )
url with failed resources can be found here.
https://webpack.js.org/plugins/npm-install-webpack-plugin
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

Fixed 404 fail resource in plugins page

---

content/api/plugins.md

As per current version of 'enhanced-resolve', in Resolver.js https://github.com/webpack/enhanced-resolve/blob/master/lib/Resolver.js, the signature has changed to have a 'message' parameter.

update signature of doResolve method

---

content/guides/migrating.md

Hi! Two small typo fixes in the migration guide, related to the new `module.rules` syntax.

Fix typos related to rules in migration guide

---

content/configuration/plugins.md

Remove minimize option usage here.  According to the [migration guide](https://webpack.js.org/guides/migrating/#uglifyjsplugin-minimize-loaders), it should be passed via `new webpack.LoaderOptionsPlugin`

Remove minimize option

---

content/guides/production-build.md

It's choppy and superfluous. The article ends stronger on the previous paragraph.

Remove closing line in production-build.md

---

components/footer/footer-style.scss
styles/index.scss
styles/partials/_mixins.scss
styles/prism-theme.scss

This (semi-opinionated) commit adds CSS font anti aliasing on devices that support it.
I added a mixin `fontantialias` that will add anti aliasing properties or not. The mixin is applied to the body element and disabled on code and the footer (the text becomes too small/thin). 
*Open in fullscreen!*

Font anti aliasing

---

content/configuration/dev-server.md

copied directly from the old site, formatted suitably.

devServer.setup() documentation

---

content/api/plugins.md

Following the existing docs results in this deprecation warning:
> webpack: Using compiler.parser is deprecated.
> Use
> compiler.plugin("compilation", function(compilation, data) {
>   data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
> });
> instead.

Update docs on parser access

---

content/guides/production-build.md

This suggests using `"production"` (instead of `"prod"`) everywhere for the value of `NODE_ENV`.

Consistent use of NODE_ENV "production"

---

content/guides/migrating.md

"loaders" is string of Array.
https://webpack.github.io/docs/configuration.html#module-loaders
Example
The following code will cause an error.
`Module not found: Error: Cannot resolve 'file' or 'directory'`
```javascript
module: {
loaders: [
{
test: /\.css$/,
loaders: [
{
loader: 'style-loader',
},
{
loader: 'css-loader',
query: {
module: true
}
}
]
}
]
}
```

fix(migrating): An array of loaders as string

---

content/guides/code-splitting-import.md
content/guides/code-splitting-require.md

Closes #589.
Related: https://github.com/webpack/webpack/issues/4265

Document code splitting using `import()`

---

components/navigation/navigation.jsx
content/api/cli.md
content/plugins/limit-chunk-count-plugin.md
content/plugins/min-chunk-size-plugin.md

- Add many links
- Clarify usage patterns with/without config file
- Add CLI link to sub-navigation (adding `/cli` causes the sidepanel to not contain any headers. This is the default for any `index.md`)
Closes #826. Supersedes #820.

Improve CLI reference

---

content/guides/code-splitting-import.md
content/guides/migrating.md

* Add more example links
* Link from migrating to code-splitting-import
* Change title to "Code Splitting - Using import()"
* Consistent typesetting "syntax-dynamic-import"

Improvements to code-splitting-import

---

components/vote/app-style.scss

Android handles \2666 as the emoji "diamonds" (:diamonds:) and displays it with a different font-size and color.
Also influence and gold-influence are now different (filled/empty).
Cheers @sokra Thanks again for your talk at #frankenjs.

fix(vote): changed influence icons to be better displayed on android

---

content/configuration/output.md

`output.jsonpFunction` is string according with [old documentation](https://webpack.github.io/docs/configuration.html#output-jsonpfunction).
There are [source code](https://github.com/webpack/webpack/blob/29ed4c3d6f5f7be89fbfc29d5c42f67c1cee7ee8/lib/JsonpMainTemplatePlugin.js#L126) that profs that `output.jsonpFunction` have to be string;
Maybe we need to rename this option. Into `output.jsonpFunctionName`, for example.

Fix output.jsonpFunction type

---

components/sidebar-item/sidebar-item.jsx

When we have active sidebar, the arrow toggler it does't work, this PR is fixing this issue.

Active arrow toggles the list

---

styles/markdown.scss
utilities/markdown.js

Added mobile friendly tables.
Resolves #246

Mobile friendly tables

---

content/guides/development.md

The package `serve` is incorrectly linked to the repository [tj/serve](https://github.com/tj/serve).
This is because @tj transferred ownership of the `serve` package on the
npm registry to [zeit/serve](https://github.com/zeit/serve). Thus, the link and the installation command
correspond to two different packages.
The link now points to zeit/serve, which has similar functionality to
tj/serve, in addition to an option for effectively serving single page
apps.
Additionally, the instructions have been improved to instruct readers to
install the package locally and run it using an npm script as opposed to
installing it globally.

Improve watch mode development section and fix incorrect link

---

content/guides/webpack-and-typescript.md

fixes issue with 'bundle.js' put to the root of the file system (and causing error) rather than project folder.

fix bundle path

---

content/guides/hmr-react.md

The purpose of this line is to allow copying the entire example into code and conveniently also denote the appropriate file name.
Unfortunately, a single-line comment here breaks the next CSS selector and thus post-css aspect of the tutorial. Running the tutorial as-is, the header appears to ignore all styles in `.app`.
Single-line comments are not supported by run-of-the-mill CSS. Replace with a multiline comment.

Fixed CSS that breaks tutorial

---

content/guides/get-started.md

In this patch, the webpack command is called using the relative path because it wouldn't work otherwise (unless the user installed webpack globally, which was not suggested in this guide).

Call webpack using relative path

---

components/gitter/gitter.jsx

This prevents issues on small pages where the gitter
was overlapping the footer.

Fix Gitter Button Overlapping Footer

---

content/configuration/watch.md

Add missing "work" word in watch documentation.

---

content/guides/code-splitting-import.md

use the original config in this doc, I got :
```
throw new Error(RuleSet.buildErrorMessage(rule, new Error("options/query provided without loader (use loader + options)")));
```

use webpack2.0 config for code-splitting-import

---

content/configuration/dev-server.md

In webpack-dev-server 2.3.0, `overlay` was introduced. I forgot to document this, but better late than never.

Add documentation for `overlay` in devServer

---

content/guides/get-started.md

All statements in the code snippet are using single quote to denote strings. Assuming this is the default style, the quotes around the webpack module name were also converted from double to single.

fix: Use consistent quotation marks

---

content/concepts/loaders.md

This clarification is necessary because users might try to copy and paste the below code, and will run into bugs that do not have an obvious solution. If users set `modules: true` without meaning to, they will run into an issue where the classes will be replaced with generated ones, but this isn't made clear by the documentation. 
This PR also fixes some grammar mistakes for clarity.

docs(loaders): Clarify how to include CSS modules and fix grammar. 

---

components/sidebar-item/sidebar-item.jsx

Based on #924, I compared the `currentPage` props to the `url` props, to determine what should be the `href` value of the Sidebar anchor links. 
It works! :dancer: :smile:

Fix #924 - Make Sidebar anchor links not reload/refresh page. 

---

content/configuration/output.md

Fixes #796 
My first PR, I hope everything's all right with it :)

Documented `output.strictModuleExceptionHandling`

---

content/guides/comparison.md
styles/markdown.scss
utilities/markdown.js

Based on #911 I added basic table css for desktop version. 
Because the comparison table is just to big I added option to display scroll for table on desktop and then mobile version for mobile devices.

Added scroll table for desktop

---

content/api/cli.md
content/concepts/loaders.md

I found probrem in the loader sample.
This sample was allowed in webpack 1.x, but there was a sample that was not allowed in 2.x.

Fix CLI sample mistake.

---

content/guides/lazy-load-react.md

Assuming the lazy-loaded component is used as:
```js
render() {
return (
<div>
<LazilyLoad modules={{
TodoHandler: () => importLazy(import('./components/TodoHandler')),
}}>
{({TodoHandler}) => (
<TodoHandler />
)}
</LazilyLoad>
</div>
);
}
```
The previous equality check called `this.load` each time the parent-component re-rendered, which remounted all the lazy-loaded components. Comparing the actual promise references instead of the modules object fixes this.

Fix equality check for lazy-loading example

---

content/configuration/devtool.md

When seeing it for the first time and without a clear concept of the source map options, I tough that the `+++` implied a longer build and rebuild time, instead of faster.

Added quick note about source map speed table

---

content/guides/comparison.md

Fix link for `rollup-plugin-amd`

Fix link for rollup-plugin-amd

---

content/configuration/module.md

The `Rule.resourceQuery` property can be used to match different loader pipelines depending on the query string, like this: https://github.com/webpack/loader-utils/issues/69#issuecomment-284725071
---
@sokra @bebraw Was this omitted intentionally? Is it ok to document it as a public API?

Add Rule.resourceQuery property to module.md

---

content/api/cli.md

There is a typo in the CLI documentation.
`-v` displays webpack's version. 
It is not a shorthand for `--verbose`.

Remove -v shorthand

---

antwar.config.js
template.ejs

Added the description meta tag to the `<head>` section.
The content is taken from the old webpack website ([webpack.github.io](webpack.github.io)), feel free to suggest edits.
When googling "webpack" I currently get this:
This change should hopefully fix that problem.

add meta tag description to website

---

content/guides/migrating.md
content/writers-guide.md

Walked through this guide as I was porting a project from webpack 1 to 2 - and spotted a few typos.

Fix a few typos

---

content/loaders/index.md

The [typescript-loader is deprecated](https://github.com/andreypopp/typescript-loader). I've spent a long time getting the older loader to work with TS 2.0+ because of this. I've updated it with links to the githubs of two TS 2.0+ loaders

update typescript-loader to ts-loader etc

---

content/api/cli.md

```
webpack --module-bind /\.js$/=babel-loader
```
`test` value will be `/\.\/\\\.js\$\/$/`

Fix module-bind usage

---

content/configuration/dev-server.md

Grammar fix:  the `index.html` page will likely have **to** be served in place of any `404` responses. Enable this by passing:

updated "to be served" in historyApiFallback descr

---

content/guides/get-started.md

unified diff format, starting with a +/-/` ` character at the beginning of the line.
before
after

Fixed red lines that not deleted.

---

content/plugins/commons-chunk-plugin.md

Adding a link and tweaking the wording in the CommonsChunkPlugin `children` documentation.
Resolves #1018.

Edit CommonsChunkPlugin Doc

---

content/configuration/entry-context.md

This tripped me up when I was working on making a project use vendor chunking when it previously used an array of strings as the value for the `entry` key. It wasn't clear which key that array should move to in the object syntax.

Add a section on naming

---

content/guides/code-splitting-libraries.md

Added a case which combines an implicit vendor bundle and a separate manifest bundle.

Extended last example in code-splitting-libraries.md

---

content/configuration/stats.md

Add the stats options which are used in [webpack/lib/Stats.js](https://github.com/webpack/webpack/blob/4b9b660e8c4fe8ab6425014cb24dcec2d5df194b/lib/Stats.js#L51-L81) but were missing from the stats documentation.
- cachedAssets
- depth
- entrypoints
- exclude
- maxModules
- performance
- providedExports
- usedExports
Fixes #899

Document missing stats options

---

content/configuration/entry-context.md

I looked at the code and it seems that if entry is a function it can return an array or an object too.
https://github.com/webpack/webpack/blob/028c51301733836abbedc88be7483af2623f5943/lib/DynamicEntryPlugin.js#L40..L46
https://github.com/webpack/webpack-dev-server/blob/master/lib/util/addDevServerEntrypoints.js#L20
As simply adding more return types made the type ambiguous I added parens around the function type, but can also remove it again if desired.

Clarify that dynamic entries can return array and object

---

content/api/loaders.md
content/concepts/loaders.md

- Remove deprecated features like `this.options` and `this._compilation` that make it heard to implement a multi-process pipeline
- Add `this.callback`
- Add `this.async`
- Add some explanatory comments
- Prepend `this` to all properties to make it obvious that these properties are accessible via `this` inside the loader
@sokra do you agree with these changes?

Rework loader api documentation

---

content/configuration/index.md

seems to have been a missing comma in the example

adding missing , to config example

---

components/navigation/navigation.jsx

Looks like the way docsearch is being bundled has changed. Better adapt
to that.
Closes #1055.

fix: Fix docsearch

---

content/configuration/resolve.md

This part is outdated, c.f.
- https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L98
- https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L38
- https://github.com/webpack/webpack/issues/2532

Fixed resolveLoader defaults

---

components/page/page-style.scss
components/sidebar-item/sidebar-item-style.scss
components/sidebar-item/sidebar-item.jsx
components/sidebar/sidebar.jsx
content/configuration/configuration-languages.md
content/configuration/configuration-types.md
styles/partials/_mixins.scss

Redesigning the sidebar to match @pastelsky's comp (see #438).
This is phase one of two for getting everything discussed in #438 (and things mentioned in some other issues like #1039) knocked out. My next task is updating the structure of the `/content` directory, the antwar config, etc to match our actual hierarchy in the site. This should allow us to map the banner links more dynamically and to allow grouping in the sidebar (with a few more tweaks).
Changes:
- Changing webpack version in sidebar to an image shield
- Updating sidebar design to come closer to the comp
- Doing some code cleanup/refactoring
Here's a gif of the updates:

Sidebar Redesign

---

content/guides/hmr-react.md

Changes:
- Fixed some grammatical mistakes
- Removed babel-preset-stage-2, because it had no material impact on the tutorial
- Moved react-hot-loader install to `save` since it's used in App code
- Moved section on es2015 modules to `.babelrc` section for better flow

Editing the React HMR guide

---

components/sidebar-item/sidebar-item.jsx

I discovered an issue on this [page](https://webpack.js.org/plugins/commons-chunk-plugin/#components/sidebar/sidebar.jsx) on the production site where the Example link in the sidebar would continually duplicate itself as you scrolled down the page.
This [tweet](https://twitter.com/ryandrewjohnson/status/847083931094659078) has a screen cap of the issue.
When running the site locally I could see that there was a React error complaining that there were duplicate `key` attributes being used on elements in the sidebar. I have updated the sidebar-item component to use lodash uniqueId to generate key which prevented the error.

Fix issue with sidebar-item with duplicate key attributes

---

content/branding.md
styles/markdown.scss

Fixing, sorting, and cleaning up the color palette section of `branding.md`.
From:
to this:
@NejcZdovc I'll still be following up with another more targeted table styling PR (at some point 😆 , i know i said that a while ago too but it will come!). I wanted to check with you to make sure that padding I removed wouldn't break anything you did (I did check the mobile view which looked fine as far as I could tell).
@rouzbeh84 feel free to take a look, I know you worked on this file as well.

Color palette cleanup

---

components/sidebar-item/sidebar-item-style.scss
content/plugins/min-chunk-size-plugin.md

Minor fix for the sidebar item titles wrapping to the next line.
From:
to this:

Sidebar overflow fix

---

content/guides/production-build.md

The comment was implying that a switch-case exists.
Checking the history, the switch-case was phased out on this commit: {7b83c190339395ee8d9a944e91d017b1ce03df5e}

Update production-build.md (#1)

---

components/sidebar/sidebar.jsx

Currently, we specify webpack v2.2.1 in the docs:
Meanwhile, [v2.3.3](https://github.com/webpack/webpack/releases/tag/v2.3.3) has been released. Shall we update the documentation?

Specify webpack v2.3.3

---

content/guides/public-path.md

Hi guys, 
as many users may struggle on this issue I think it's worth mentioning it in the doc.
ie: https://github.com/webpack/webpack/issues/2776#issuecomment-233208623
Thx

Add warning about dynamic public path when using ES6 imports

---

content/guides/hmr-react.md

ERROR in ./~/css-loader?modules!./~/postcss-loader!./src/components/App.css
Module build failed: Error: No PostCSS Config found in: example/src/components
at Error (native)
at example/node_modules/postcss-load-config/index.js:51:26
@ ./src/components/App.css 4:14-126 13:2-17:4 14:20-132
@ ./src/components/App.js
@ ./src/index.js
@ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./index.js

guides: hmr-react: remove failing postcss dependency

---

content/configuration/dev-server.md

Add a warning in `dev-server.md` regarding exporting multiple configurations, since only the first is passed to the `webpack-dev-server` CLI.

Multiple configurations in dev-server.md

---

content/plugins/commons-chunk-plugin.md

This PR focuses on improvements to `CommonsChunkPlugin`.
There currently is no description of what shape the `module` argument provided by `minChunks` takes - which makes it hard for new users to understand how to use it for custom common chunks. (This is mentioned in #902)
This PR adds a description of two particularly important properties for this use case (`context` and `resource`), and links to the `NormalModule` class definition that the `module` argument takes the shape of. 
It also adds an additional advanced implicit common chunks example that shows how to use the `resource` property to prevent specific files (such as stylesheets needed in a separate file with `ExtractTextWebpackPlugin`) from being moved to the common chunk.
---
Fixes #902

Explanation of module argument in CommonsChunkPlugin & add advanced implicit common vendor chunk example

---

content/guides/code-splitting-async.md

This is an attempt to resolve #1083 and could also potentially address #1099, however #1099 is in relation to `require.resolve`. Maybe this can be tweaked somehow to accommodate both cases.
This will conflict with some other PRs that are currently open but I'd be happy to rebase once those are merged. In the meantime, hoping someone can give this a quick review to make sure I have everything right.

Clarify Dynamic Import Limitations

---

content/api/plugins/compiler.md

https://github.com/webpack/webpack/blob/ab2270263e9af5b0dd83e454c20ab3aa1797424a/lib/Compiler.js#L94
```js
if(this.stats)
this.compiler.applyPlugins("done", this.stats);
else
this.compiler.applyPlugins("failed", this.error);
```

Compiler event hook is `failed`, not `fail`.

---

content/guides/production-build.md

no need to pass here since we have commonConfig(), useless params

remove useless env param

---

content/configuration/output.md

Fixes #796 and incorporates information from https://github.com/webpack/webpack.js.org/issues/796#issuecomment-282655528

Clarify output.strictModuleExceptionHandling

---

.travis.yml
content/api/node.md
content/guides/code-splitting-css.md
content/guides/development-vagrant.md
content/guides/development.md
content/guides/installation.md

Let's have a consistent typesetting for `npm install`s.

Consistent `npm install --save-dev`

---

content/api/plugins/compiler.md

Fixed spelling.

---

content/guides/code-splitting-css.md

add style-loader to tutorial "Code Splitting - CSS"

---

content/api/plugins/compiler.md

The `before-compile` event was documented as `sync`.
If I got it right, the fact that is executed with `applyPluginsAsync ` (as seen [here](https://github.com/webpack/webpack/blob/ab2270263e9af5b0dd83e454c20ab3aa1797424a/lib/Compiler.js#L476)) makes it `async`.
Is that correct? I'm just starting to dig through the documentation, learning something about the internals.

Correct wrong documented synchronicity of Compiler's `before-compile` event

---

components/contributors/contributors-style.scss
content/guides/production-build.md

Rework and simplify the production build guide to address some of the issues discussed in #1100 as well as just doing some general cleanup of titles and whatnot.
Also sneaking a UI/UX fix for the contributors section in here...
to...
This puts some space between rows and prevents them from being overlapped by the gitter button.

Update Production Build Guide

---

content/guides/migrating.md

Added a warning instead that points to the v2 version in which this option
became obsolete. We could also reference an older version of the docs if
necessary for people to jump back to, though that may be overkill.
Fixes #1150

Remove Obsolete `ident` Section

---

content/guides/author-libraries.md

Added some info about a pitfall mentioned in webpack/webpack#4771 which is good to keep in mind until the issue is fixed.

Added info about pitfall for externals

---

content/plugins/context-replacement-plugin.md

Loosely based on:
* https://github.com/webpack/docs/wiki/list-of-plugins#contextreplacementplugin
* https://stackoverflow.com/a/25426019/205629
* https://medium.com/@kudochien/a-react-webpack-optimization-case-27da392fb3ec
* https://github.com/webpack/webpack/issues/2783#issuecomment-233752248
Addresses #43.

Add ContextReplacementPlugin documentation

---

scripts/fetch.sh

Recently I needed this and I think it's generic enough to deserve a spot in the official docs. 
This loader basically takes an output from css/html/other loader that return the output as a JS module and execute it to return it as a raw string during the compile step.

Document extract-loader.

---

content/guides/production-build.md

Template literals must be enclosed by backticks

Fix syntax error in per-env configuration example

---

.babelrc
components/splash/splash.jsx
components/support/support-additional.json
components/support/support-style.scss
components/support/support.jsx
package.json

Cleaning up the support component by... 
- updating the way sponsors are retrieved using the method mentioned in #411 
- abstracting the additional sponsors into a separate json sheet that follows the same model
- concatenating the additional sponsors on to those fetched from open collective
This gives us full control over styling and allows us to...
- easily add new additional sponsors, not from open collective, without bloating the component file
- refactor how we display sponsors, e.g. using one of the methods discussed in #411 
I think this should resolve #411 as it has been inactive for a while __and__ with this in place changing the display algorithm should be a piece of cake as we have more data to key off.
Thanks to @rafaelrinaldi for pinging opencollective to find out about the …

Support Cleanup

---

content/configuration/devtool.md

This adds links to the source map plugin and loader as well as the examples from the webpack repository (via https://github.com/webpack/webpack/issues/4698).
Relates to #971

Devtool: add links to plugin, loader, examples

---

.eslintrc
components/dropdown/dropdown-style.scss
components/dropdown/dropdown.jsx
components/navigation/navigation-style.scss
components/navigation/navigation.jsx

Some follow up code-style and styling tweaks for #1148.
cc @lcxfs1991 
Preview of styling tweaks:

Touch Up Language Dropdown

---

content/guides/code-splitting-async.md

As described in #772 in `require.ensure`'s callback users cannot use other than `require` argument name.
Resolves #772

docs(guides): adds warning about `require.ensure`

---

.gitignore
components/support/support-additional.json
components/support/support-style.scss
components/support/support.jsx
content/api/plugins/tapable.md
content/configuration/devtool.md
content/plugins/limit-chunk-count-plugin.md
package.json
scripts/check-links.js
scripts/fetch.sh
scripts/fetch_supporters.js

Still a WIP...
Re-implementing the reverted refactor/fix of the `Support` component. 
@bebraw moving the conversation from #1168 to here, my attempts so far have failed. Please let me know any suggestions, if we don't get this in somehow we'll likely have to re-open #1167 and #411.

Support Refactor

---

package.json
scripts/deploy.sh

Add `npm run fetch` to build scripts so all content exists prior to building.
Fixes #1182

Add Fetch to Scripts

---

content/guides/tree-shaking.md

Lower case w on Webpack was breaking the link.

Fix for broken link on tree-shaking.md

---

content/configuration/output.md

One would naturally look to the `publicPath` documentation when searching for solutions to setting  it at runtime.

add __webpack_public_path__ docs

---

package.json
scripts/check-links.js

* Ignore failures on sponsor/backer images/links
* Do not allow any other failure to not miss broken links such as https://github.com/webpack/webpack.js.org/pull/1188 or https://github.com/webpack-contrib/less-loader/pull/194

Improve lint:links - exclude support images/links

---

content/guides/output-management.md

Add a best practices and advice guide for managing built files (aka webpack's output).
Resolves #949

Output Management

---

content/guides/code-splitting-async.md

The examples on the page show usage with commonjs modules but not ES2015 modules, which was confusing for me when I tried to import ES2015 modules.
See https://github.com/webpack/webpack/issues/3829. My provided examples could probably use some work, though I was trying to come up with something generic that doesn't introduce too many concepts at once. My personal use case is for HMR with a React component and Redux reducers:
```js
if (module.hot) {
module.hot.accept('./root', async () => {
mount((await import('./root')).default);
});
module.hot.accept('./reducers', async () => {
store.replaceReducer((await import('./reducers')).default);
});
}
```

Clarify use of `import()` with ES2015 modules.

---

antwar.config.js
components/page/page.jsx
content/api/cli.md
content/guides/code-splitting-async.md
content/guides/tree-shaking.md
content/plugins/dll-plugin.md

Allow a `related` section in the yaml frontmatter of any markdown file to add a __Further Reading__ section containing the `related` links.
Example:
Resolves #94

Further Reading / Related Links

---

content/guides/asset-management.md
content/loaders/index.md
scripts/fetch.sh
scripts/fetch_package_files.js

Add postcss-loader to the loaders documentation. Did a few things:
- Added a new `fetch` line to pull in the readme (similar to the others)
- Had to drop html comments as that seems to be another thing not supported by our markdown process 😢  (just for reference #178)
- Updated and added some links to the new page
Fixes #1202

Add postcss-loader

---

utilities/markdown.js

Fix issue with escaped `|` not being taken into account.
This is allowed in GFM but not supported by marked. See this issue:
https://github.com/chjj/marked/issues/595
Fixes #1187
cc @Alex1990 @NejcZdovc

Fix Markdown Issue

---

content/api/node.md

Add warning about watching in the node api doc.
Fixes #1096

Node API Warning

---

package.json

Reduces hyperlink memory footprint and speeds up external link checks. This should make link linting run correctly again

Update to hyperlink 2.8.0. Refs #1210 refs Munter/hyperlink#117

---

content/loaders/index.md

Add link to react-markdown loader list

---

content/concepts/loaders.md

docs(concepts): remove obsolete `moduleTemplates` reference

---

content/guides/caching.md

set inlineManifest: true cause the default value is false.

fix the options of ChunkManifestPlugin

---

content/plugins/banner-plugin.md

This adds the documentation for https://github.com/webpack/webpack/pull/4693.

BannerPlugin: add doc on placeholders

---

content/guides/code-splitting-async.md
content/guides/code-splitting.md

Update code splitting titles for consistency.

docs(code-splitting): Rename to code-splitting for consistency

---

content/plugins/index.md

This adds the `IgnorePlugin Link` at Plugins List Page
It will affect the Plugins Page:
https://webpack.js.org/plugins/
It complements #1014
It is the second try to #1232

Added IgnorePlugin at Plugins Index Page

---

content/configuration/dev-server.md

I suspect that this should probably go into its own section, but I'm not too sure, especially since the content is so thin.
I realize that this may seem like an unnecessary tip to experts, but I found it helpful - in my case, I had put a screwy output.filename in a quick project which had messed it up, so the logged output of `webpack output is served from /` wasn't quite right. Discovered this trick at http://stackoverflow.com/a/42592398/4200039
Hopefully a troubleshooting section can be expanded which in the long run will reduce the load of new issues opened.

Add webpack-dev-server troubleshooting tip

---

content/guides/code-splitting-async.md

fix webpack config in async/await with dynamic imports to include the `babel-plugin-syntax-async-functions` babel plugin.

add required babel plugin for async functions

---

content/guides/asset-management.md

The loader order will cause https://github.com/webpack-contrib/css-loader/issues/362

Fix style-loader and css-loader order

---

content/configuration/output.md

This adds documentation for https://github.com/webpack/webpack/pull/4860.

Document `output.chunkLoadTimeout`

---

content/guides/code-splitting-async.md

This adds the documentation for the not yet released https://github.com/webpack/webpack/pull/4818. The docs is largely based on @sokra's https://github.com/webpack/webpack/issues/4807#issuecomment-300443876.
Resolves #1243

code-splitting-async: document webpackMode

---

README.md

The link to the CONTRIBUTING.md file in this project's README currently returns a 404. This PR corrects the href.

README: fix the href to CONTRIBUTING.md

---

components/notification-bar/notification-bar.jsx
utilities/test-local-storage.js

Addresses https://github.com/webpack/webpack.js.org/issues/1247
- Adds a utility function to test for `localStorage` via https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js
- Tests for `localStorage` everywhere it may be accessed in `components/notification-bar/notification-bar.jsx`
- If `localStorage` is disabled, the notification bar is rendered without the icon to close it. This means that users with `localStorage` disabled will have no way to dismiss the notification bar (which seems like a fair compromise).

Test for Local Storage

---

content/guides/code-splitting-async.md

fix(docs): Fix cut out text

---

.gitignore
antwar.config.js
components/starter-kits/starter-kits-style.scss
components/starter-kits/starter-kits.jsx
package.json
scripts/fetch.sh
scripts/fetch_starter_kits.js
scripts/fetch_supporters.js
styles/markdown.scss
utilities/markdown.js

Adds a starter kits guide fetched from @ahfarmer's [tool-list package](https://github.com/ahfarmer/tool-list). Just working on a better display for the tags column and then this should be good to go.
Resolves #45

Starter Kits

---

content/concepts/manifest.md
content/guides/output-management.md

Add a concepts manifest page and more details on extraction plugins and how to use them in `/guides/output-management`.
Resolves #80

Manifest Docs

---

content/api/module-methods.md

Add warning about mixing module syntaxes in _Module API - Methods_.
Resolves #552

Mixed Module Syntaxes

---

content/plugins/commons-chunk-plugin.md
content/plugins/context-replacement-plugin.md
content/plugins/define-plugin.md
content/plugins/dll-plugin.md
content/plugins/ignore-plugin.md
content/plugins/limit-chunk-count-plugin.md
content/plugins/loader-options-plugin.md
content/plugins/min-chunk-size-plugin.md
content/plugins/no-emit-on-errors-plugin.md
content/plugins/normal-module-replacement-plugin.md
content/plugins/provide-plugin.md
content/plugins/source-map-dev-tool-plugin.md

Add lead-in descriptions (#1161) and clean up content. Most of these changes were to the local plugin docs in this repo but I also opened a few prs on external repos where necessary like [this one](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/517). Also adding documentation for #815.
Resolves #1161
Resolves #815

Improve Plugin Documentation

---

content/guides/hmr-react.md

Make react-hot-loader@next a devDependency.

---

content/api/node.md

the `mkdirp` and `join` are also needed by [`outputFileSystem`](https://github.com/webpack/webpack/blob/efc576c8b744e7a015ab26f1f46932ba3ca7d4f1/lib/node/NodeOutputFileSystem.js).

Points out that outputFileSystem needs of methods

---

content/configuration/index.md
content/configuration/output.md
content/guides/author-libraries.md

Removes the `commonjs-module` option (#545) and cleans up some of the surrounding docs.
Resolves #545

Improve LibraryTarget Docs

---

content/guides/hot-module-replacement.md

Current documentation is importing a module called `Lib`, but is being used as `Library` later on in the code example. I simply changed `Lib` to `Library` to better clarify.

Fix import typo in code example.

---

content/guides/code-splitting-libraries.md
content/guides/production-build.md

The current guide throws an error : 
```
Config did not export an object or a function returning an object.
```
When exporting the merged object instead of a function it works.

In merge example, export the merged object.

---

content/concepts/index.md

"The goal is **to have** .... **to be**"
should be
"The goal is **to have** ... **be**"

Fix typo in docs

---

content/configuration/dev-server.md

related webpack-dev-server PR: https://github.com/webpack/webpack-dev-server/pull/899

Add documentation for devServer.allowedHosts

---

content/guides/getting-started.md

Because of the mistakes, the "hello webpack" doesn't show up.

Fix some mistakes in the tutorial

---

antwar.config.js

Noticed a broken link to `production-build` in the react documentation, and there are probably others out there as well.

Add Redirect to Production Guide

---

content/guides/getting-started.md

* Removed the `bundle.js` in the file structure, so that people don't think they need to create that themselves.
* Also added example bash command + output for the `npm run build` step.
* Changed the folder structure in the last step to correctly reflect what people will see after following this guide.

Small tweaks to Getting Started

---

content/api/cli.md

updated to add the new 3.0 scope hoisting flag

---

content/configuration/output.md

Docs for https://github.com/webpack/webpack/pull/4987

docs(config/output): add libraryExport option

---

content/configuration/node.md

Docs for https://github.com/webpack/webpack/pull/4995

docs(config/node): add `false` for `node` option

---

content/api/cli.md
content/configuration/stats.md

Docs for https://github.com/webpack/webpack/pull/4143
I will rebase and fix the table after #1309 is merged.

docs(stats, cli): add new stats options

---

content/guides/code-splitting-async.md
content/guides/migrating.md
content/plugins/loader-options-plugin.md

To comply with https://webpack.js.org/writers-guide/#typesetting

docs: consistent typesetting of webpack versions

---

content/plugins/define-plugin.md

See these issues for references:
https://github.com/egoist/poi/pull/193
https://github.com/chentsulin/electron-react-boilerplate/pull/245/files
Basically using something like the below example will break the process object compatibility that webpack includes. This just gives a warning about that. 
```javascript
new webpack.DefinePlugin({
process: {
env: {
NODE_ENV: JSON.stringify('production')
}
}
})
```

Adding warning about overwriting process

---

content/concepts/configuration.md
content/configuration/configuration-languages.md

- Move all configuration languages to the corresponding configuration page, away from the concepts page
- Reduce TypeScript example to a minimal working example

docs(config): conflate configuration languages

---

content/plugins/dll-plugin.md

this is for #1306 
Unless I'm missing something Usage links but the Examples subheaders are being pulled into sidebar when they shouldn't be?
[screen recording of `Usage` working as expected](https://cl.ly/lIGm)
closes #1306

swapping `Usage` content to not be header links

---

content/configuration/output.md

Running webpack without an `output.filename` produces the following error and causes the command to fail
```
Error: 'output.filename' is required, either in config file or as --output-filename
```
Thus, stating there is a default value is incorrect. This removes that statement from the docs.

Remove inaccurate information and fix spelling/grammar

---

content/glossary.md

It's still not perfect but I think this is the best we can do for now. We can always loop back to it down the road if it comes up again.
Resolves #970

docs(glossary): try to clarify the relationship between chunks and bundles

---

content/api/loaders.md
content/api/plugins/compilation.md
content/api/plugins/module-factories.md
content/api/plugins/resolver.md
content/concepts/index.md
content/concepts/loaders.md
content/concepts/output.md
content/concepts/plugins.md
content/configuration/module.md
content/configuration/output.md
content/guides/caching.md
content/guides/hot-module-replacement.md
content/guides/typescript.md

> In resolving #569, I had to grep through much of the docs to look for loader usage inconsistencies. In doing this I noticed a variety of other minor (and some not-so-minor) things that needed fixing so I'm addressing them here as well. This should probably have been split into multiple PRs but if the reviewers just view the commits instead of the full diff it shouldn't be so bad (sorry it's late and I'm tired 😞).
A bunch of cleanup including...
- Resolving some formatting inconsistencies
- De-duplicating content between `/concepts/output` and `/configuration/output`
- Clarifying loader usage and configuration (see #569)
Resolves #569
cc @dmitriid (see [this commit][1] in particular)
[1]: https://github.com/webpack/webpack.js.org/pull/1339/commits/9171a0a9fceaeaea6bdced3f8ada50215317d587

Miscellaneous Edits

---

content/api/cli.md

The sample output that was previously shown for `--profile` will not appear unless `--progress` is also used. This change spells this out, and also describes the per-module timings that `--profile` produces by itself.

Improve documentation for --profile

---

content/guides/output-management.md

Solving the following error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.output.path: The provided value "dist" is not an absolute path!
```
Now it also uses the same output path as the "Getting started"  >  "Using a Configuration" guide.

Path fix for output managment guide

---

content/guides/output-management.md

Solving the following error: 
```
ERROR in Entry module not found: Error: Can't resolve './index.js' in '/home/peteruithoven/Projects/www/webpack/webpack3/output-managment'
```

Fixing output managment entry config

---

content/configuration/externals.md

To make it easier to discover use case reported by webpack/webpack#4665 
from the documentation, as the existing array example only convey/imply 
that only modules are supported by this construct.

An example for using an array in the object form.

---

content/guides/production.md

fix definition of `webpack -p` command line option expansion, at the top of this page its missing the needed single quotes which are present down below. this caused me some grief ;)
incidentally `--optimize-minimize --define process.env.NODE_ENV="'production'"` *doesnt* produce the same result as `-p` for me, only the first correctly causes react to build in production mode without the attedent warnings. this is with webpack 1.15.0 and react 15.6.1. I assume this is a doc issue rather than something i need to create as an issue on either react or webpack but let me know if im wrong here.

fix definition of `webpack -p`

---

content/configuration/output.md

docs(config): add `auxiliaryComment` documentation to output.md

---

content/writers-guide.md

I think the guideline is missing this important part.

Update Writer's Guide

---

content/guides/author-libraries.md

The note from #1158 are now obsolete since webpack/webpack#4771 has been fixed.

docs(guides) Reverted the changes from #1158

---

content/guides/typescript.md

Unnecessary lingering comma @ the end of the exclude line. This just removes the comma.

Remove hanging comma from exclude in rules

---

content/configuration/output.md

Appears to have been a clip-n-paste error from output.hashFunction's description.

Fix output.hashDigest Description

---

content/configuration/configuration-types.md

Documentation for https://github.com/webpack/webpack/pull/5196
Part of #1388

docs(configuration-types): multiple functions

---

content/configuration/resolve.md

Documentation for https://github.com/webpack/webpack/pull/5178, https://github.com/webpack/enhanced-resolve/pull/92
Part of #1388

docs(resolve): document cacheWithContext option

---

content/guides/code-splitting.md

updating [code-splitting](/guides/code-splitting/#components/sidebar/sidebar.jsx) to link/mention explicit vendor splitting per #1366

Code Splitting Guide Update

---

components/dropdown/dropdown.jsx
components/footer/footer.jsx
components/logo/logo.jsx
components/notification-bar/notification-bar-style.scss
components/notification-bar/notification-bar.jsx
components/splash-viz/splash-viz.jsx

When using the site I noticed a few accessibility issues that I thought would be easy enough to fix, so I did so.
in this PR I changed the 'close' icon that shows up in the notification bar to a button so that it can be accessed with a keyboard and then triggered with the enter key... of course in doing so I needed to change some of the styling.  Currently the appearance of the button is identical to the original.
I also added some alt-texts to the images that are on the front page of the website.  Without these texts a screenreader will humorously read the filenames of the images: `cd0bb358c45b584743d8ce4991777c42.svg` (one letter at a time of course)
There is some more similar work that can be done on the site if this type of thing is appreciated, and I'd be glad to do it as I get time.

A11y fixes

---

antwar.config.js

See https://github.com/webpack/webpack.js.org/pull/1338#issuecomment-313519967
cc @Krinkle

docs(guides): add redirects for old code-splitting guides

---

content/configuration/output.md

Documentation for https://github.com/webpack/webpack/pull/4883
Part of #1388

docs(output): library names for UMD since 3.1.0

---

content/writers-guide.md

Adds a warning to use Node 6+ to run the site locally (`Running the Site`), as otherwise `npm start` will fail.

docs(guides): Add minimum Node version

---

components/organization/organization.jsx
components/shield/shield.jsx
components/sidebar/sidebar.jsx
content/guides/installation.md

Obtain latest webpack version from npm instead of the latest GitHub release.
Fixes #1420.

fix(shield): webpack version from npm

---

content/guides/lazy-loading.md

Hi @TheLarkInn, as you told me on Twitter, here's my PR.
For context, I've just written an article ["Lazy loading in Vue using Webpack's code splitting"](https://alexjoverm.github.io/2017/07/16/Lazy-load-in-Vue-using-Webpack-s-code-splitting/) and asked @TheLarkInn to take a quick look. Actually anyone, feedback is appreciated, it should be less than 5 min reading.
And thought it could be useful for the frameworks section on https://webpack.js.org/guides/lazy-loading/

docs(guides): Add vue example to lazy loading

---

content/guides/development.md

Also adds some words to make sentence flow a little better and removes backticks for non code-related words.

docs(guides): Fix typos in development.md

---

content/plugins/prefetch-plugin.md
content/plugins/watch-ignore-plugin.md

Port documentation for the `WatchIgnorePlugin` and `PrefetchPlugin` from here:
https://github.com/webpack/docs/wiki/list-of-plugins
Resolves #126 
Resolves #1378

Port Plugin Documentation

---

content/guides/development.md

`CleanWebpackPlugin` was missing from the examples.
Also fixed name in `package.json`.

fix(guides): Added missing plugin in config

---

content/guides/getting-started.md
content/loaders/index.md

* bring together related sentences
* add links to further documentation

docs(getting-started): refine module section

---

content/configuration/output.md

Really keen for some feedback on the examples I used and whether they are technically correct. Have only used `libraryExport` very briefly for my own purposes, but thought I'd get the ball rolling on some better docs for it.
What is the correct default value for this config?
Are there any libraryTarget combinations which produce inconsistent results?
Anything else someone may need to know about using this config?
cc: @skipjack @mbraint @sokra 
Resolves #1379

docs(config): add output.libraryExport description (#1379)

---

content/guides/asset-management.md
content/guides/getting-started.md
content/guides/output-management.md

**const** for path instead of **var** to ensure consistency in webpack config file
build output use **print** instead of **vendor** for asset and chunk name

docs(plugins): use const in webpack config and correct build output

---

content/api/stats.md

Add page to document the output of...
``` bash
webpack --profile --json > compilation-stats.json
```
We still need to go through and fill in the blanks before this can be merged.
Resolves #491 
cc @dmitriid @walfly

docs(api): begin work on stats json documentation

---

content/guides/hot-module-replacement.md

Fix for snippet in the _Gotcha_ section of [_Hot Module Replacement Guide_](https://webpack.js.org/guides/hot-module-replacement/#gotchas).
Resolves #1461

docs(guides): fix HMR Gotcha section snippet (#1463)

---

content/development/how-to-write-a-loader.md

This PR fixes a small grammar mistake in the `how-to-write-a-loader.md` file.

Improve grammar of how-to-write-a-loader.md

---

content/guides/caching.md

previous source code use `chunkhash`, the second example should use `chunkhash` too no?

Replace contenthash with chunkhash

---

content/guides/integrations.md

Populate the __Integrations__ guide with concise sections on each of the popular task runner integration utilities. IMO this page should essentially give readers a rough idea of what the integration would look like, and then send them to the respective repository for more information. It also notes that you can get pretty far with webpack and npm alone as many users can probably get by without complicating their setup with another build tool.
As I've mentioned before, I think we should avoid going too in depth with third-party stuff on this site as it's been tough just to document webpack itself.
Resolves #53

Integrations Guide

---

content/configuration/dev-server.md

Originally was just adding documentation for the allowedHosts cli option https://github.com/webpack/webpack-dev-server/pull/1012.
However, because there was no documentation for other CLI options I went ahead and added those too.

Add documentation for devServer cli options

---

content/configuration/stats.md

Like @sokra asked me, I'd like to provide the new excludeAssets and excludeModules within the Stats-Documentation.
Please see this PR:
[https://github.com/webpack/webpack/pull/5377](https://github.com/webpack/webpack/pull/5377)

excludeAssets in stats

---

components/splash/splash.jsx
components/support/support-style.scss
components/support/support.jsx
scripts/check-links.js

Categories: Platin, Gold, Silber, Bronze
Logos have different sizes

Display sponsors in categories

---

content/configuration/dev-server.md

Add an example of proxying to the same target from multiple contexts. A similar example was in the Webpack 1.x docs, I just tried it in Webpack 3.4.1 and it still works.

Add documentation to devServer.proxy

---

content/guides/tree-shaking.md

Idea for #1473 (also see #1331). Opener for discussion - feedback welcome.

Add note about --optimize-minimize is not required for tree shaking

---

content/configuration/externals.md

The currently deployed documentation indicates that there are 4 module contexts you can specify under the externals config - `global`, `commonjs`, `commonjs2`, and `amd`, which contradicts both the examples that surround it, and the actual library functionality. 
This just changes the word "global" to "root" in the section that lists the module contexts.

Change externals module contexts documentation from `global` to `root`

---

content/configuration/dev-server.md

The current docs say HotModuleReplacementPlugin "must" be included, but after inspecting the source, my conclusion was that webpack [adds HotModuleReplacementPlugin automatically](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L400-L404) if you specify `--hot`, so adding this to webpack.config.js ought to usually be unnecessary. We are successfully using HMR with `webpack-dev-server` without adding the plugin explicitly, so that seems like further evidence.
I think the docs should specify that HMRPlugin doesn't need to be added explicitly if you're using the `--hot` option.

Clarify that HMRPlugin is added automatically by --hot

---

content/configuration/module.md

I think this wording might clarify the text mentioned in #1484.

Clarify the meaning of Rule.parser options

---

content/api/cli.md
content/configuration/configuration-types.md

This adds a table of possible `--env` arguments and how they translate into  the `env` parameter.
It also mentions the second parameter, `argv`, and gives an example of detecting if `-p` or `--optimize-minimize` was given.

Explain the possible parameters when webpack.config.js exports a function

---

components/splash/splash-style.scss
components/support/support-style.scss
components/support/support.jsx
content/index.md

This is both a follow up to #1466 and resolves #1300. The index page now contains short descriptions for each sponsor/backer section:
cc @sokra @xdamman @joshmosh

Update Index Page

---

content/configuration/devtool.md

A tiny wording fix found in the source maps documentation.

Fix small typo

---

content/guides/caching.md

I've filled in one of the two missing bash outputs.
However I don't actually get the expected output when running the command `npm run build` multiple times... 
``` bash
npm run build
> webpack-docs-stuff@1.0.0 build /Users/danny/tmp/webpack-docs-stuff
> webpack
clean-webpack-plugin: /Users/danny/tmp/webpack-docs-stuff/dist has been removed.
Hash: f7a289a94c5e4cd1e566
Version: webpack 3.5.1
Time: 579ms
Asset       Size  Chunks                    Chunk Names
main.7e2c49a622975ebd9b7e.js     544 kB       0  [emitted]  [big]  main
index.html  197 bytes          [emitted]
[0] ./src/index.js 216 bytes {0} [built]
[2] (webpack)/buildin/global.js 509 bytes {0} [built]
[3] (webpack)/buildin/module.js 517 bytes {0} [built]
+ 1 hidden module
Child html-webpack-plugin for "index.html":
1 asset
[2] …
```

Add missing bash output to caching.md

---

content/api/plugins/compiler.md

In #1493, it wasn't clear what the "watch mode" section was describing. Since this is documentation for plugin writers, I added the information they'd be interested in: The new events that will be emitted.
I also added links to the Node.js API and the CLI options, in case the reader wants to see how watch mode is invoked.

Clarify what 'watch mode' is in the plugin documentation

---

content/guides/build-performance.md

Add a page with build performance tips

add build performance page

---

content/configuration/target.md

An extra '|'  is causing an extra table cell which causes the table to overflow into the margin at https://webpack.js.org/configuration/target/

docs(target): fix a small typo 

---

content/plugins/index.md

This should fix the errors found in some other PRs' CI builds.

fix(plugins): babili has been renamed to babel-minify

---

content/plugins/dll-plugin.md

Fixes #1513: Clarify that manifest parameter can also be an absolute path string.
This was added in commit [530fad](https://github.com/webpack/webpack/commit/530fad43b418dbf78c484eda78b5b22fba086ee9)

Fix issue #1513: Clarify that manifest parameter can also be a string

---

.github/CONTRIBUTING.md

docs(contributing): Mention Python dependency

Mention Python dependency in contribution guide

---

content/api/module-methods.md

0 as the ID of a module does not tell it is an entry point because the ID can be affected by `optimize-module-order` plugins.

Remove description about module ID 0

---

src/scripts/deploy.sh

The location of certain files changed in fd37f672/#1490 .
cc @pierreneter

fix(deploy): fix deploy script after restructuring

---

src/content/api/stats.md

Fix: typo in link

---

src/content/guides/asset-management.md

Respected Sir,
import _ from 'lodash';
import './style.css';
import Icon from './icon.png';
function component() {
var element = document.createElement('div');
// Lodash, now imported by this script
element.innerHTML = _.join(['Hello', 'webpack'], ' ');
element.classList.add('hello');
+   // Add the image to our existing div.
+   var myIcon = new Image();
+   myIcon.src = Icon;
+   element.appendChild(myIcon);
return element;
}
document.body.appendChild(component());
Here in the above code. We are appending a new child <img> which adds the image after 'Hello webpack' not behind it

Loading Images

---

src/content/concepts/targets.md

Removed the example of a Webpack setup for building to both electron and web because it uses an old plugin for electron-renderer support even though Webpack has native support for target.
Added example boilerplate which contains good examples of configuration files for both electron-main and electron-renderer

Update target resources

---

src/content/guides/shimming.md

Add a short guide about how to load polyfills only when needed to not penalize users on modern browsers. 
Resolves #938

Add polyfills on demand section to shimming page

---

src/content/configuration/dev-server.md

The console messages produced by webpack dev server differ slightly from when the docs were written. This commit changes the console snippet to match the current messages being logged.

Update console output snippet

---

src/content/configuration/node.md

Per [WebpackOptionsDefaulter][1], the default value of `node.__filename` and `node.__dirname` are `"mock"`, not `true`. This is correctly listed earlier in the file, but the listed defaults under the individual option sections were incorrect.
[1]: https://github.com/webpack/webpack/blob/aaa6eea68f42517ac8af0f4aa454951cddfcef62/lib/WebpackOptionsDefaulter.js#L77

Fix incorrect stated default of __filename/__dirname

---

src/content/guides/development.md
src/content/guides/production.md
src/content/guides/tree-shaking.md

This continues our work #1258 and resolves most of the issues mentioned in #1331. It is a WIP though, we still need to populate the `TODO` code blocks and I'm currently working on updating the 
__Production__ guide which may take a bit longer.
Resolves #1331 
Related #1258 
cc @jakearchibald

Guides - Tree Shaking and Production Rewrites

---

src/content/configuration/module.md

- Add explanation of mutually exclusive `Rule` options (either supply a `resource` or supply `test`|`exclude`|`include`)
- Fix broken links to `Rule.resource` documentation

Clarify Rule documentation and fix broken links

---

src/content/guides/typescript.md

Begun typescript rewrite according to other guide.

Rework typescript guide

---

src/content/guides/tree-shaking.md

The `uglifyjs-webpack-plugin` plugin was installed on previous step, so
it should be marked as added line.

mark line requiring uglifyjs-webpack-plugin as new

---

src/content/api/hot-module-replacement.md

In webpack 2 `check` and `apply` return Promises.
There are more options.

fix(hot-module-replacement): Fix and improve HMR management API

---

src/content/guides/production.md

At the [Production - Source Mapping guide](https://webpack.js.org/guides/production/#source-mapping), there's a suggestion to use a *devtool style* not supposed for production use, as the [Devtool guide explains](https://webpack.js.org/configuration/devtool/#devtool).
Suggest a *devtool style* suited for production, based on the [Devtool guide](https://webpack.js.org/configuration/devtool/#devtool).

Wrong devtool type at Production>Source Mapping guide

---

src/content/guides/production.md

In the "Specify the Environment" section, the line `const webpack = require('webpack');` has no plus sign before it, even though it's a new line of code for that code snippet.

Add plus sign on `require('webpack')` line

---

src/content/guides/production.md

To make the 'source-map' setting work in webpack.prod.js file, we must provide the `sourceMap: true` option to UglifyJSPlugin, as described in the Webpack documentation at https://webpack.js.org/configuration/devtool/#production

Fix source-map configuration in webpack.prod.js

---

src/styles/markdown.scss

Prevent stretch images with defined sizes in smaller breakpoints.
**Before**
**After**

Make sure images are responsive

---

src/content/api/cli.md
src/content/guides/build-performance.md
src/styles/markdown.scss

Minor formatting clean up and updated certain `devtool` examples to just use `cheap-module-eval-source-map` instead of other variations (resolves #1577).

Miscellaneous Fixes and Cleanup

---

src/content/plugins/dll-plugin.md

Fix typo in sourceType example from `commonsjs2` to the correct one `commonjs2`
There was a typo in the sourceType example, trying to run a build with that configuration will throw an error.
Fix the value to the correct name `commonjs2`.

Fix typo in sourceType example.

---

src/content/plugins/source-map-dev-tool-plugin.md

Try to resolve the confusion from #1556. Also update the options
section to clean things up a bit both for readability and grammar.
Resolves #1556

docs(plugins): clarify and simplify `SourceMapDevToolPlugin` docs

---

src/content/guides/author-libraries.md

Text below this sample code makes reference to "library" not "dependency". Very subtle and small contribution, but hope it's welcome!

Updated example for "external limitations"

---

src/content/guides/shimming.md

Rewrite the _Shimming_ guide to synchronize with the others. This is the last core guide we identified in the list from #1258. Once this is done we can close that out, finish the guides structuring in #1519, and begin cleaning up the other sections as well.
Closes #1258

Shimming Rewrite

---

src/content/configuration/configuration-languages.md

The @types/node type definition module already declares `__dirname` type:
https://git.io/v5Dr9
Thanks!

Remove local type def from TypeScript snippet

---

src/content/guides/code-splitting.md

Suggest solutions to the problem right away seems to be a better approach.
PS. Used similar text as was used in [Module API - Methods # import](https://webpack.js.org/api/module-methods/#import-).

Improving Code Splitting docs

---

src/content/configuration/module.md

`pre` loaders run at the beginning, `post` loaders run at the end.

Swap ordering of pre/post loaders

---

src/scripts/fetch_package_files.js

The previous regex was a simpler approach to the lead in content
issue in fetched plugin/loader readmes, however it wasn't targeted
enough to correctly remove all lead in content. The new approach
should be a bit more stable but honestly the real fix here would be
so better standardize/enforce the readme template before including
these packages in the documentation site. I also think we can simplify
the template a bit to make the parsing of these readme easier.
Resolves #1600

fix(fetch): fix some issues when parsing remote content

---

src/content/configuration/dev-server.md

CMIW, but when `inline` is `false`, HMR will not work at all.

`inline: true` is `required` rather than `recommended` for HMR

---

src/content/configuration/dev-server.md

Added info for newly added `before` and `after` hooks, and deprecation of `setup` in webpack-dev-server

devserver: add before, after hook info

---

src/content/guides/development.md

> Everytime should be written as two separate words: every time. While some compound words like everywhere, everyday, and everyone have become commonplace in the English language, everytime is not considered an acceptable compound word. 
Via [grammarly](https://www.grammarly.com/blog/everytime-every-time/)

Fix typo  (everytime > every time)

---

src/content/guides/production.md

from `--optimize-minize` to `--optimize-minimize`

Fixing small typo in `src/content/guides/production.md`

---

src/utilities/markdown.js

I've noticed that table's row in [UglifyjsWebpackPlugin documentation](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#options) was broken:
I've tried to fix the source file, but it appeared to be correct. After further investigation the problem was related to this issue: https://github.com/chjj/marked/issues/595.
I've found the piece of code, which was responsible for fixing it in this repo and rewritten it to handle more broad use cases (it was working only for the single pipe in the table cell and was failing for multiple pipes). I've used finite state machine approach to implement table row parser, which fixes this issue.
The result:
I hope the implementation is correct, but please verify it.
Thanks.

Introduced better fix for pipes escaping in Markdown table cells

---

src/content/guides/hot-module-replacement.md

Second argument of `server.listen` is the hostname, in this context, `'localhost'`.
Third argument of `server.listen` is the success callback.
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L552
Currently the success callback is never called to print `'dev server listening on port 5000'` because it is given as the second argument and `fn` is undefined at:
```
600    if (fn) {
601      fn.call(this.listeningApp, err);
602    }
```

Update hot-module-replacement.md, second argument missing in server.listen call

---

src/content/configuration/index.md

Added default config file name _(webpack.config.js)_ to the documentation.

Show default config file name in the documentation

---

src/content/guides/hot-module-replacement.md

Original discussion reference: https://github.com/webpack/webpack-dev-server/pull/1129
**Summary**
Define the `host` property of the options object and set it to `'localhost'`.
When `host` is not specified, `host` is defaulted to `'localhost'` when using the webpack-dev-server CLI, but is left `undefined` when using the webpack-dev-server Node.js API with `addDevServerEntrypoints`.
Because of this, the code example will throw `Uncaught SyntaxError: The URL 'http:/sockjs-node' is invalid` in the browser.
There are differences between the CLI and Node.js API as discussed here: https://github.com/webpack/webpack-dev-server/issues/616
**Details**
When using webpack-dev-server with the Node.js API in the following scenario:
1. using `addDevServerEntrypoints` to inject webpack-dev-server into …

Set options.host to 'localhost'

---

src/components/Splash/Splash.jsx
src/components/Support/Support.jsx
src/components/Support/Support.scss

Show the latest sponsors on the sponsors page for 14 days.

feature(sponsors): highlight latest sponsors/backers

---

src/content/guides/typescript.md

Configure TypeScript to compile modules to ES2015 module syntax,
enabling webpack to resolve the `import` / `export` syntax on it's own.
With this included, the only thing necessary to enable _tree shaking_
is the inclusion of the `UglifyJSPlugin` (which I'm not adding to this
article as it is just centered on getting started with TypeScript).
Resolves #1627

docs(guides): update typescript.md

---

src/content/guides/hot-module-replacement.md
src/content/guides/production.md

In the guides, `production.md` under the **NPM Scripts** section, the listing `package.json` _devDependencies_ is missing modules require to run `npm run build` and `npm start`.When I follow the example in the page and execute `npm run build` the following error will shown:
`$ npm run build`
> Error: Cannot find module 'webpack-merge'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
...
> Error: Cannot find module 'clean-webpack-plugin'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
...
`$ npm start` 
> webpack-dev-server --open --config webpack.dev.js
sh: webpack-dev-server: command not found
npm ERR! Darwin 16.7.0 …

docs(guides): update production.md

---

src/content/guides/hot-module-replacement.md

The first listing (webpack.config.js) on `hot-module-replacement.md` section have no import for `clean-webpack-plugin` module, while the module is used in the `plugins` section of the example config.

docs(guides): update hot-module-replacement.md

---

src/content/configuration/module.md

These options were a bit ambiguous and linked back to section that didn't explain
them too much further in detail. We could likely clean this section up even further
but this should at least remove the confusion around these two options.
Resolves #1645
Resolves #1646

docs(config): clarify `issuer` and `resourceQuery` documentation

---

src/content/contribute/index.md

Corrects broken links for 'Writing a Loader' and 'Writing a Plugin' on Contribute page.

docs(Contribute): correct broken links in Contribute

---

src/content/plugins/hashed-module-ids-plugin.md

Broken URL got replaced with a working one.

Fix broken link for "crypto.createHash" doc

---

src/components/Vote/Vote.jsx

`page.url` was different, probably due to refactoring

fix vote page

---

src/content/contribute/debugging.md
src/content/contribute/plugin-patterns.md
src/content/contribute/release-process.md
src/content/contribute/writers-guide.md
src/content/contribute/writing-a-loader.md
src/content/contribute/writing-a-plugin.md

Add a debugging guide that contains information on using `stats` data and debugging webpack via Chrome's _DevTools_ (#90). This should be a good home for any other common debugging tips and tricks.
Resolves #90 
cc @bebraw @TheLarkInn @pksjce wanted to knock #90 off the list but please feel free to submit follow up PRs with any modifications, enhancements, corrections, etc.

Debugging Walkthrough in the Contribute Section

---

src/content/api/stats.md

They all follow ~~the~~ a similar Structure to `They all follow a`

Typo on the API Docs Page

---

src/content/guides/tree-shaking.md

https://github.com/webpack/webpack/issues/4784 and https://github.com/webpack/webpack/issues/2867 are serious issues that show that tree-shaking in Webpack is completely broken in certain (common!) situations. 
This change adds a small section to the introduction of tree-shaking explaining what happens and how tree-shaking actually works in Webpack.

Update information on how tree-shaking may be ineffective

---

src/content/plugins/module-concatenation-plugin.md

Just noticed a 'dependency' typo.

docs: Fix typo

---

src/content/plugins/module-concatenation-plugin.md

This adds a link between “this concatenation behavior” and “scope hoisting” terms. Without this, a new person might be confused what exactly “scope hoisting” is (because it appears without any visible connection to the previous content).

Add an introduction for the “scope hoisting” term

---

src/content/api/loaders.md

In actual fact the parameters passed to emitWarning/emitError must be an instance of Error.

docs(loaders api): fixed some method signatures

---

src/content/guides/typescript.md

The quote usage in the config file was inconsistent. With this change it should be single where possible.

Consistent quote use

---

src/content/api/cli.md
src/content/guides/production.md

This adds documentation for the new `--concatenate-modules` CLI flag (see https://github.com/webpack/webpack/pull/5914).
Additionally, this documents `ModuleConcatenationPlugin` in the Production guide. I believe it’s reasonable to do this because the `--concatenate-modules` flag is included under the `-p` umbrella.

A new --concatenate-modules flag

---

src/content/guides/hot-module-replacement.md

Add small tip to the "Hot Module Replacement" guide for `webpack-dev-middleware` users.
Resolves #1682

docs(guides): add middleware tip to the hmr guide

---

src/content/contribute/writing-a-loader.md

When using an arrow function, `this` is undefined.
When using a normal function, `this` is the loaderContext.
(tested using the tutorial on this page)

Use normal function to fix scope in loader

---

src/content/api/loaders.md

Add some lead in descriptions to the `Examples` section and clarify that meta
data can be passed along via the fourth parameter to `this.callback` and accepted
as the third parameter to a loader function.
Resolves #1607
cc @NeekSandhu

Loader API Revisions

---

src/content/guides/production.md

Shorten form for `DefinePlugin` example.

Use shorten form for `process.env.NODE_ENV`

---

src/styles/markdown.scss

Changes:
File ```src/styles/markdown.scss```
This PR changes the css ```white-space:normal``` for ```<code></code>``` tag to avoid overflowing the content wrt to the parent div.

website(css): changed the css to fix the text inside code tag which was overflowing the parent div

---

src/content/configuration/dev-server.md

Just fixed the link, nothing to add. 🙃

Fix dead link to webpack-dev-server example

---

src/content/concepts/loaders.md

This is just a quality of life adjustment that updates the list of ways to use loaders with fragment links to the relevant section in the docs.  In their current state, the section feels like a dead end, abruptly cutting off with three bullet points and no examples. While one can read on and figure it out, there is a break in focus that is quite distracting. No one like to have a "wtf" moment when reading docs so this hopefully reduces that friction and helps people connect the dots.

Updated Usage Instructions with Fragment Links

---

src/content/guides/getting-started.md

`./node_modules/.bin/webpack --config webpack.config.js` command does not work at windows 7 with webpack 3.8.1. 
Correct way to run it is  `./node_modules/.bin/webpack.cmd --config webpack.config.js`. 
This page is the first step of the guide for newbies and this omission can be discouraging for windows users that wants to learn Webpack. I want to add this information so that other windows users can proceed without experimenting.

Adding windows command for build

---

src/content/configuration/plugins.md

The final code block was missing a semicolon from the end of the first line; added it in to match the other require statements.

docs(configuration): added missing semicolon for consistency in plugins.md

---

src/content/plugins/commons-chunk-plugin.md

Really minor update to the plugin docs but I think `.includes()` is more readable that `.indexOf()` for people less familiar with javascript.

Update CommonsChunkPlugin Docs

---

src/content/contribute/writing-a-plugin.md

While authoring plugins the list of hooks is essential knowledge, so link to hooks documentation page should be accessible in the top of plugins authoring guide.
The exact location is not very important, but it should be easy to find.
(for newcomer like myself it was not easy to realize the link between compiler api and plugins at first)

Linking compiler docs on plugins page

---

src/content/guides/production.md

The webpack.prod.js code example in the 'Specify the Evironment'
section shows 'cheap-module-source-map' for the devtool field which is
not recommended for production. This section should show 'source-map'
to be consistent with the webpack.prod.js in the previous
'Source Mapping' section.

docs(guides): fix `source-map` discrepancy in production.md

---

src/content/guides/caching.md

Preserve CommonsChunkPlugin boilerplate naming consistency as
referenced in the [CommonsChunkPlugin manifest file][1] 
documentation when extracting webpack runtime and manifest
boilerplate.
[1]:https://webpack.js.org/plugins/commons-chunk-plugin/#manifest-file

docs(guides): rename 'runtime' to 'manifest' in caching.md

---

src/content/guides/getting-started.md

The changes in this PR include the Terminal logs for the latest Webpack version 3.9.1

Updated output for Webpack 3.9.1 across the file

---

src/content/api/loaders.md

Resolves #449
Resolves #116
Refactored and enhanced the existing section using much of @sokra's
explanation from:
https://github.com/webpack/webpack/issues/360

docs(api): clarify the `pitch` method and how it can be used in loaders.md

---

src/content/configuration/devtool.md

I believe this is a mistake. As far as I know, `devtool: false` is completely appropriate for production use – but I just talked to a friend who was tempting to enable it because the docs say “Production use: no”.

Update devtool production recommendations

---

src/content/api/cli.md

`--save` option has been removed from webpack's CLI.
See https://github.com/webpack/webpack/pull/3896 and https://github.com/webpack/webpack/issues/6090

Remove --save option

---

src/content/concepts/index.md

@c-johnson I wanted to get this started as we're in the middle of a push to hit the remaining issues on this repo. Please feel free to discuss more here or submit a follow up pull request to elaborate after this one is merged.
Resolves #1736

docs(concepts): add warning about incompatible `import` statements

---

src/content/configuration/configuration-languages.md

issue #1735 
Update how to write the webpack configuration with typescript. Current configuration is wrong.
ts-node dosenot  support the module syntax of other than commonjs module. 
So, if module in compilerOptions in tsconfig.json is not commonjs, webpack getting error. like this.
```bash
(function (exports, require, module, __filename, __dirname) { import * as path from "path";
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:588:28)
at Module.m._compile (/Users/hogefuga/webpack-config-with-typescript/node_modules/ts-node/src/index.ts:392:23)
```
I have a two solution.
1. modify tsconfig.json
1. install tsconfig-paths
edit module in compilerOptions in tsconfig.json. please setting commonjs. …

 docs(config) update how to write the webpack configuration with typescript

---

src/content/contribute/writing-a-loader.md
src/content/guides/integrations.md
src/content/guides/shimming.md
src/content/guides/tree-shaking.md

Most of the guides use the full command, so follow that.
Also it's clearer for beginners who is not familiar with npm.

Use full "npm install" command instead of abbreviated "npm i"

---

src/content/guides/output-management.md

Resolves #1743
Fixed the first diff display for webpack.config.js in the [Output Management](https://webpack.js.org/guides/output-management/) guide.
In the guide, the addition of an additional entry point is shown but the change from a string ([from the previous tutorial](https://webpack.js.org/guides/asset-management/)) to an object is not made clear.

docs(guides): fix diff display for webpack.config.js entry object

---

src/content/guides/progressive-web-application.md

To resolve https://github.com/webpack/webpack.js.org/issues/1145
This is a work in progress - not yet ready for merging.  I've opened the PR to create visibility as to what I'm doing.  I'll notify when I think this is ready for review proper.
cc @skipjack

Add Progressive Web Application guide

---

src/content/configuration/output.md

added docs for new `output.devtoolNamespace` option and [namespace] placeholder.

Document new `output.devtoolNamespace` option

---

src/content/plugins/commons-chunk-plugin.md

Recently usage of `.indexOf` was replaced by `.includes` in the CommonChunksPlugin docs but there were still two instances of `.indexOf`

Remove usage of `.indexOf` in CommonChunksPlugin docs

---

src/components/Site/Site.jsx

Resolve #1758 add missing sort for mobile sidebar. (copy logic from:  [/src/components/Page/Page.jsx#L19-L26](https://github.com/webpack/webpack.js.org/blob/ab2d8ffa05d07d6bc06d784bd548c15b9f95367b/src/components/Page/Page.jsx#L19-L26))

Add sort for mobile sidebar

---

src/components/NotificationBar/NotificationBar.jsx
src/components/StarterKits/StarterKits.jsx
src/content/guides/migrating.md

`&nbsp;` shouldn't be used as they are wider than normal spaces. In some cases, the `&nbsp;`s aren't necessary. The rest can be replaced with `{' '}` instead.
Note the spacing between (`can` and `be`) and (`learn` and `different`) is wider than usual.

docs: Fix formatting

---

src/content/concepts/loaders.md

When one starts to learn about loaders it's very confusing.
[This](https://webpack.js.org/contribute/writing-a-loader/#complex-usage) explains the behaviour much better.

Loader order changed from chonological to reverse

---

src/content/guides/development.md

Remove `--progress` option that wasn't introduce in previous `package.json` snippets in order to prevent confusion.

Keep `guides/development.md` more consistent

---

src/content/contribute/debugging.md

Learn and Debug webpack with Chrome DevTools!
It doesn't work, unless you remove the trailing "b" from the URL.

Typo(?) in URL for related

---

src/content/guides/tree-shaking.md

Tiny thing, but this made more sense to me with `imported` rather than exported. 
I could be wrong though 🙂

Typo: Should this be import not export?

---

src/content/guides/tree-shaking.md

according to my test and this issue https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/43, babel minify webpack plugin does not support tree shaking.

docs(guides): remove plugins that does not support tree shaking

---

src/content/concepts/index.md
src/content/concepts/modules.md

Added a direction to learn about JS modules when reading the concepts page, meant mostly for new-comers. Because the modules doc page does not discuss the JS module systems, I also added a further reading link on this subject.
This is after a colleague of mine had an issue understanding what and why about webpack when reading the docs. What he was missing is an understanding of JS modules. You can't understand a *module* bundler without knowing modules.

docs(concepts): Direct new-comers to read about JS modules

---

src/content/configuration/module.md
src/content/configuration/resolve.md

From discussion in https://github.com/webpack/webpack/issues/811#issuecomment-309797397.
Adds a few notes about how `resolve.symlinks` and `npm link` play together (I assume `npm link` to be the most common tool for symlinking packages). Specifically, turning off `resolve.symlinks` may solve some problems users have with modules not resolving properly in their symlinked packages.

docs(configuration): add details on resolve.symlink and npm link

---

src/content/plugins/module-concatenation-plugin.md

Adds more information about why the plugin may cause no effect in case Babel
Related:
- https://github.com/webpack/webpack/issues/5199#issuecomment-354348034

docs(plugins): Clarify the case of ModuleConcatenationPlugin + Babel

---

src/content/concepts/index.md

docs(concepts): Simplified the Loaders section to be clearer for complete beginners like me.

docs(concepts): Simplified the Loaders section

---

src/content/plugins/eval-source-map-dev-tool-plugin.md
src/content/plugins/index.md

Adds information about existing class as well as an example of usage for `sourceUrlTemplate` which is introduced in PR: https://github.com/webpack/webpack/pull/6272

Adds documentation on EvalSourceMapDevToolPlugin

---

src/content/guides/code-splitting.md

Adds links to additional requirements to make `await import` example work. 
Just using babel and `babel-loader` is not enough.
You need the [Syntax-Dynamic-Import Babel Plugin](https://babeljs.io/docs/plugins/syntax-dynamic-import/#installation) installed as a devDependency and added to .babelrc as a plugin
Instructions on the linked page should allow anyone familiar with `babel-loader` to get the example running no problem.
There are a lot of outdated solutions floating around that mislead or push to older `require` syntax,. Referencing the current required packages to see the example in action is helpful.
In the [comments of the babel plugin page](http://discuss.babeljs.io/t/syntax-dynamic-import-babel/799/7?u=kcolton), I have a [working …

docs(guides): link required babel plugin for async

---

src/content/api/index.md

Some assistive technologies such as screen readers have options to list links in a page to allow rapid browsing and navigation. These links are listed without their surrounding context, making them sometimes hard to understand.
This pull-request qualifies “learn more” links to make them self-explanatory so that a screen-reader user can easily figure out which link points to which documentation.
---
I didn’t manage to do a screenshot with the links list from VoiceOver open (as keyboard shortcuts control the rotor) but I did snap a picture so you see what it looks like.

Make “learn more” links self-explanatory

---

src/content/configuration/watch.md

After accidentally getting onto @sokra and @gaearon discussion of old docs missing page on twitter, i decided to send a PR with troubleshooting section for webpack watch. This makes it easier to find and to make people link to our docs website instead of old wiki page.

Update docs with troubleshooting information: watching section

---

src/content/guides/code-splitting.md

'is use to' replaced by 'is to use'.

docs(guides): fix typo in code-splitting

---

src/content/configuration/watch.md

The link to `feedback.livereload.com` is 404, but the original document in GitHub still exists. This PR simply changes the URL to point to the original Markdown file.

Fix broken link in watch.md

---

src/content/concepts/plugins.md

Added Mozilla Docs link for Function.prototype.apply text. It has been mentioned above, but would good to have on this place as well.

Update Function.prototype.apply link

---

src/content/plugins/profiling-plugin.md

Add docs for the new `ProfilingPlugin`
Linked PR: webpack/webpack#6482

ProfilingPlugin: add to the docs

---

src/content/configuration/stats.md

Doc incorrectly states the default value is `true`, but it is `false`. See https://github.com/webpack/webpack/blob/master/lib/Stats.js#L512

Update docs for default value for stats.toString({colors})

---

src/content/guides/author-libraries.md

This fixes #1832 with the suggested text from that issue.

Fix missing text in Author Libraries guide

---

src/content/plugins/commons-chunk-plugin.md

Updated CommonsChunkPlugin examples links to point to latest available versions of the examples.
Fixes #1834

docs: update CommonsChunkPlugin example links

---

src/content/configuration/watch.md

Add the newly added `info-verbosity` to the docs. Reference to addition: webpack/webpack-cli#200

Update docs with info-verbosity option

---

src/content/guides/csp.md

Add basic nonce documentation.
Fixes #1802

Start adding Nonce documentation

---

src/content/plugins/source-map-dev-tool-plugin.md

Added a dependency section to mention that a source map will not be generated if the user is also using the `UglifyJsPlugin` and has not set the `sourceMap` property to `true`.

 Add reference to UglifyJsPlugin dependency

---

src/content/guides/getting-started.md

One of the commands wasn't working properly as I was going through the Getting Started Guide.  I checked the `--help` and found that, without configuration, the `--output` or `-o` flag was required.  Without it, I was getting:
```
▶ npx webpack ./src/index.js ./dist/bundle.js
Hash: 4f8eb0312946d804aad5
Version: webpack 4.0.0
Time: 3564ms
Built at: 2/25/2018 8:57:00 AM
1 asset
Entrypoint main = main.js
[1] (webpack)/buildin/module.js 519 bytes {0} [built]
[2] (webpack)/buildin/global.js 509 bytes {0} [built]
[3] ./src/index.js 215 bytes {0} [built]
[4] multi ./src/index.js ./dist/bundle.js 40 bytes {0} [built]
+ 1 hidden module
WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.
ERROR in …
```

Documentation: Fix error in Getting Started Guide

---

src/content/guides/getting-started.md

* Changes the guide so it reflects webpack 4 output.
* Changes some wordings here and there and adds some clarifications.
* Adds `webpack-cli` install which is required with v4

Updated getting-started.md

---

src/content/guides/asset-management.md
src/content/guides/author-libraries.md
src/content/guides/development-vagrant.md
src/content/guides/getting-started.md
src/content/guides/output-management.md
src/content/guides/shimming.md
src/content/index.md

As pointed out in Issue #1866, this should be added for valid HTML.

docs(all): add doctype for valid HTML in all documentation

---

package-lock.json
src/content/configuration/stats.md
src/content/guides/asset-management.md
src/content/guides/author-libraries.md
src/content/guides/development-vagrant.md
src/content/guides/getting-started.md
src/content/guides/output-management.md
src/content/guides/shimming.md
src/content/index.md
src/content/plugins/index.md
src/scripts/fetch.sh

According to the source code there must be the `builtAt` option specified which is defaulted to `true`.
https://github.com/webpack/webpack/blob/f6e366b4be1cfe2770251a890d93081824789209/lib/Stats.js#L125

Add the `builtAt` option

---

src/content/plugins/index.md

it's in the plugins navigation menu already but absent from the table.

docs(plugins): adding CopyWebpackPlugin to table

---

src/content/guides/getting-started.md

* Adds `<!doctype html>` to HTML snippets

docs(guides): add doctype to Get Started

---

src/content/api/loaders.md

`this.callback` is called with `sourceMaps` instead of `map`.

Fix typo in the synchronous loader code example

---

src/content/guides/production.md

Minor fix of missing line in diff and semicolon

Fixed missing line in diff and missing semicolons

---

src/content/guides/tree-shaking.md

updated the treeshaking documentation for webpack 4

update tree shaking guide for webpack 4

---

src/content/concepts/index.md
src/content/concepts/mode.md

- Added a small note regarding `NODE_ENV` and `mode`
- Uppercased cli to be consistent with the rest of the docs, also added a link to it.
- Worded `output` description.

docs(concepts) Clarification about NODE_ENV and mode

---

src/components/SidebarItem/SidebarItem.scss

Ensure that sidebar items has proper height even when emoticon is used.

style(sidebar): fix vertical spacing when option has an icon

---

src/content/guides/progressive-web-application.md

`workbox-webpack-plugin` [exports](https://github.com/GoogleChrome/workbox/blob/ed2a847baf34c17c0f019d11cdfb1464fe3a9e19/packages/workbox-webpack-plugin/src/index.js#L20) an `object` now:
```
module.exports = {
GenerateSW,
InjectManifest,
};
```
So this doc is updated according to https://github.com/google/WebFundamentals/blob/f64420d4fdb3a7dd8796577c7683e81e69d2305e/src/content/en/tools/workbox/guides/generate-service-worker/webpack.md#setup-your-webpack-config

docs(guides): fix config

---

src/content/configuration/configuration-languages.md

This PR changes the TypeScript configuration sample slightly trying to simplify the code - and make it on the same level as any ES6/ES2015 module based code.
The TS 2.7 allows - with simple configuration change in `tsconfig.json` - to unify use of imports in vanilla JavaScript module and TypeScript module source code. This remove needs of using `* as` in source code.
The text of the note has been extended to add note about these compiler additional configuration properties - which should be helpful for users with some TypeScript background. The unfortunate outcome is that the entire length of the section is slightly increased.
Here is a quick demo project that was setup based on existing (and this one) configuration notes to show that it is working setup: …

Update TypeScript configuration example to TS 2.7

---

.gitignore
src/components/SidebarItem/SidebarItem.scss
src/content/api/stats.md
src/content/configuration/configuration-languages.md
src/content/guides/production.md
src/content/guides/progressive-web-application.md
src/content/guides/tree-shaking.md

The webpack 4 documentation PR #1856 currently has conflicts with `master` branch.
---
This PR contains the auto-merge change as well as conflicts resolution.

Resolve conflicts on next branch

---

src/content/guides/getting-started.md

The path for including bundle.js is not correct. index.html is already inside /dist folder, the correct path should be 'bundle.js' or '../dist/bundle.js'

Fix a bug in getting-started.md

---

src/content/index.md

As mentioned on #1870 homepage doesnt say that webpack can compile without config
* Mention on the homepage about 0cjs capability
P.S. im not really sure we should make the examples more complicated to match our 0cjs setup, maybe just mention it in other way?
P.P.S Should i add `mode: "production"` to the config snippet?

content(homepage) Mention 0CJS capability

---

src/content/guides/installation.md

[As suggested here](https://github.com/webpack/webpack-cli/issues/318#issuecomment-371333504)

Installation guide: Add note to install webpack-cli on v4 or higher

---

src/content/concepts/configuration.md
src/content/configuration/configuration-languages.md
src/content/configuration/configuration-types.md
src/content/configuration/index.md

1. dont say that its the simplest configuration because simplest is 0cjs now
2. update snippets
Fixes #1869

docs(configuration) Update snippets to comply with webpack v4+

---

src/scripts/fetch_package_names.js
yarn.lock

We are hitting GH Rate limit (60 request/hr) very quickly, this will increase it to 5000.

Added GitHub token for authenticated GitHub API calls

---

src/content/api/resolvers.md

The link is [currently broken](https://webpack.js.org/api/resolvers/#configuration-options) because of an additional space.

Removed invalid space between [label] and (link)

---

src/components/Footer/Footer.jsx
src/components/StarterKits/StarterKits.jsx
src/content/api/cli.md
src/content/api/loaders.md
src/content/api/module-variables.md
src/content/branding.md
src/content/comparison.md
src/content/concepts/hot-module-replacement.md
src/content/configuration/devtool.md
src/content/configuration/output.md
src/content/configuration/target.md
src/content/configuration/watch.md
src/content/contribute/index.md
src/content/guides/caching.md
src/content/guides/code-splitting.md
src/content/guides/hot-module-replacement.md
src/content/guides/migrating.md
src/content/guides/production.md
src/content/guides/shimming.md
src/content/loaders/index.md
src/content/plugins/commons-chunk-plugin.md
src/content/plugins/dll-plugin.md
src/content/plugins/html-webpack-plugin.md

Automatically replaced all external urls that had redirects pointing them to a different location.
Automated replacements based on output from hyperlink in #1582

Evaluate all http redirects of outgoing links

---

src/content/guides/getting-started.md

`npx webpack` creates an output file as`main.js` instead of 'bundle.js`. We need to point to `main.js` in the `index.html'

Changing the output file to `main.js`

---

src/content/configuration/module.md

> It can have a `options` property
↓
> It can have an `options` property

Fixed an a/an error in `/configuration/module`

---

src/content/api/cli.md

`-o` is required in my test for webpack 4.5.

docs(api): fix command

---

src/content/configuration/stats.md

For better readability. Most of the WebPack users are beginners. Using spaces above comments will increase readability and helps to catch it quickly.

Add space above comments

---

src/scripts/fetch_package_files.js

The relative link resolution was accidentally reversing the work done a few lines up where absolute links to repositories with `webpack` or `webpack-contrib` where converted into relative hrefs
This was a regression from https://github.com/webpack/webpack.js.org/pull/2006/commits/462145063c68e5e1300a40d1ce0080e7936c4076 merged in https://github.com/webpack/webpack.js.org/commit/1489e7bfc28783e17b254f6b02597a43a62a37fe

Move resolving of external README.md relative hrefs up

---

src/content/configuration/output.md
src/scripts/fetch_package_files.js

Fixes broken links to nodejs documentation (fragments were renamed).
Stops resolving local fragment anchors in imported plugin/loader README's to `https://raw.githubusercontent.com`
Closes #2023

More link fixes

---

antwar.config.js
src/components/Navigation/Links.json
src/content/migrate/3.md
src/content/migrate/index.md
webpack.config.js

Create "Migrating" section and move content from Guides.
Fixes #1933

Issue/1933 Create "Migrating" section and move content from Guides

---

.travis.yml
antwar.bootstrap.js
antwar.config.js
src/components/Support/Support.jsx
webpack.config.js

Local build time ~540 seconds. Consequent builds for some reason take much less with a random difference varying from 82 seconds to 110 seconds per build using default `yarn run build` cmd
UPD:
* local build time is unstable, subsequent builds take less time (down to 82 seconds from 540 seconds) for unknown reason, antwar needs more profiling, dropping this work to not waste time
* this branch seems to build 20-25% faster than others due to node.js version bump
* this branch renders contributors only clientside, will finally fix error event not firing for 50X/40X image responses from OC
* redirects fixed, antwar.config.js redirects dont work at all in latest antwar version

fix(config) Fix build time issue using defaut config

---

src/content/guides/asset-management.md
src/content/guides/production.md
src/content/plugins/index.md
src/scripts/fetch.sh
webpack.config.js

* remove extract-text-webpack-plugin
* add mini-css-extract-plugin
* add redirect from extract-text-webpack-plugin to mini-css-extract-plugin
* fix guides asset management
* fix guides production
fixes #2016

docs(plugins) Add mini-css-extract-plugin

---

src/content/concepts/index.md

Initially this PR solves https://github.com/webpack/webpack.js.org/issues/2035 issue.
I also change some parts and code snippets that are not valid with v4 release.
FInally, I encounter a lot of issues with code snippets and content in each section. There were lots of sentences saying exactly the same thing over and over, probably tangling more the understanding an entry user needs on what each concept means in webpack.
Would your words on my changes, the intention was to summarize and simplify the content to be a little more consumable.
You can check the formatted version of the concepts page [here](https://github.com/webpack/webpack.js.org/blob/762a338f28e361d70ae494d1ff12b330441b4a1b/src/content/concepts/index.md) which might help review the content.

fix: various fixes on concepts for v4 and some rephrasing

---

src/content/configuration/output.md

* mention default values for `output.pathinfo`
Fixes #2014

fix(docs) Document output.pathinfo default values

---

src/content/contribute/writing-a-loader.md

Update the loader testing example to check for runtime errors as mentioned [earlier in the docs](https://webpack.js.org/api/node/#webpack-).
> The err object will not include compilation errors and those must be handled separately using stats.hasErrors()

Update loader testing docs to catch compiler errors

---

package.json
src/components/Markdown/Markdown.scss
webpack.common.js

Src code patched until
https://github.com/ben-eb/remark-autolink-headings/pull/41 is merged, if
ever, we should probably use a fork.

chore(rebuild): re-incorporate header links

---

src/content/api/module-methods.md

I modified some of the notes about how magic comments work. 
The explanation was out of date for Webpack 4.

Update magic comments explanation

---

src/content/configuration/optimization.md

Fixes #2138 
Tackles one off #1968

Document optimization.nodeEnv

---

src/utilities/fetchSupporters.js

Currently fetch command creates `__supporters.json` instead of `_supporters.json` because an underscore was added in both filename and file path string literal.
This patch fixes it, if you do a git clean and fetch currently dev server errors on trying to read non existent `_supporters.json` because it was fetched with two underscores.

fix(fetch) done add two underscores for supporters.json

---

src/components/Gitter/Gitter.jsx

Fixes #2131 
Open for discussion:
We could move gitter to `Site.jsx` to have cleaner implementation and stop worrying about hiding and showing the chat toggle button but that would result in gitter widget on all pages of the website vs what we currently have only on documentation pages (`Page.jsx`)

chore(rebuild): don't load gitter twice

---

src/content/api/hot-module-replacement.md

add self accept and decline documentation
add some details
separate module and management api

Improve HMR documentation

---

src/content/plugins/split-chunks-plugin.md

Updating the docs based on discussed in [webpack#7217](https://github.com/webpack/webpack/issues/7217)
- adding info about providing function for `chunks`
- also fixing wrong indents in a code snippet
Ideally, where it says
> (your function is given the chunk object as a parameter)
it would link to the documentation for the schema of that chunk object. If someone could link me to that (if it exists), I can add it here as well

SplitChunksPlugin: cleanup and organization

---

src/content/configuration/optimization.md

Document behavior when multiple runtimes are present on a page.
Discussion: https://github.com/webpack/webpack/issues/7375

docs(optimization): module initialization with multiple runtimes

---

src/content/guides/tree-shaking.md

The hint for --optimize-minimize is appearing twice in [the guide to tree shaking][1]. This change will keep the one added in [6c2ab16][2].
[1]: https://webpack.js.org/guides/tree-shaking/#minify-the-output
[2]: https://github.com/webpack/webpack.js.org/commit/6c2ab166853738fbd09993d99b72d1f11381bc63#diff-8152e1597fc1acfff8849d4b494f4915R155

docs(guide): Remove redundant hint

---

src/content/api/compilation-hooks.md
src/content/api/parser.md
src/content/api/plugins.md

- `tapName` was missing in several code examples
- add an example using `async`/`await`

Update API documentation about hooks

---

.gitignore

Since we're using `yarn`, add `yarn-error.log` file to `.gitignore`.

gitignore: add yarn-error.log

---

src/content/guides/tree-shaking.md

in my version of webpack 4.10.2 bundle comes already minified by default. I need to set the development mode

docs(tree-shaking): bundle minified problem

---

src/content/contribute/writing-a-plugin.md

* Update the docs to use the new Tapable API
* Add the “Under the hood” section
* Remove the “Hook types” section and link to the Tapable docs instead (depends on https://github.com/webpack/tapable/pull/63)
* Put sections talking about compiler and compilation next to each other
* Do some minor tuning
Depends on https://github.com/webpack/tapable/pull/63.

Update the “Writing a plugin” docs for the new plugin API

---

package.json
yarn.lock

feature: pre-commit hooks

---

src/content/plugins/split-chunks-plugin.md

Title says what it does, also Fixes #2166

docs(plugins) Link split chunks example from the plugin page

---

src/content/configuration/configuration-languages.md

This changes the content of sample `tsconfig-for-webpack-config.json` configuration file to include
settings for  '--allowSyntheticDefaultImports' for better typesystem compatibility
fixing issues like:
` error TS1192: Module '"path"' has no default export.`
Thanks!
Full output of error fixed by configuration update:
```bash
/Users/piotrblazejewicz/git/angularjs-typescript-webpack/node_modules/ts-node/src/index.ts:250
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
webpack.config.ts(1,8): error TS1192: Module '"path"' has no default export.
webpack.config.ts(2,8): error TS1192: Module '"/Users/piotrblazejewicz/git/angularjs-typescript-webpack/node_modules/@types/webpack/index"' has no default export.
```

Update TypeScript configuration for Webpack config

---

.travis.yml
src/scripts/env.sh
src/scripts/fetch.sh
src/scripts/fetch_package_names.js

Follow up of https://github.com/webpack/webpack.js.org/pull/1963 that actually works.
Travis scripts runs in a child process which doesn't inherit environment variables, so you have to re export them.
See https://travis-ci.org/webpack/webpack.js.org/builds/392673634?utm_source=github_status&utm_medium=notification for logs regarding rate limits, it says 5000 instead of 60. I hope this will solve our constant failed builds.

Add GitHub token to GitHub API calls

---

src/content/configuration/optimization.md

* adds `namedChunks` and `namedModules` options to the docs
Tackles two off #1968

Docs optimization

---

src/content/guides/getting-started.md

There was some inconsistency between referring to main.js in the html file, and bundle.js on other places. I assume that the default in previous versions was bundle.js, however following the examples with console output, webpack uses main.js, so I have updated the examples to reflect this, as it reflected quite badly that the getting started instructions followed exactly as examples presented wouldn't actually work. Happy to have my name removed as a contributed if deemed necessary, it's only a small change after all.

Making the examples consistent.

---

src/content/configuration/module.md

Updated the example in configuration doc to put noParse as a child of module in config.

docs(config): updated module.noParse example

---

src/content/configuration/stats.md

This option is picked up here:
https://github.com/webpack/webpack/blob/4de3ce05/lib/Stats.js#L145-L148
And used here:
https://github.com/webpack/webpack/blob/4de3ce05/lib/Stats.js#L474-L476
This controls the addition of `namedChunkGroups` in the stats output.

Add chunkGroups option to stats config docs

---

src/components/Dropdown/Dropdown.jsx
src/components/Navigation/Navigation.jsx

Here is a PR for #2244 .
- adds a navigation landmark
- adds a search landmark
- adds some labels to links

fix(accessibility) Improve landmarking of the site

---

src/content/configuration/module.md

The actual behavior is that "inline" loaders are invoked after "normal"
fixes https://github.com/webpack/webpack/issues/7576

Fix the order of loaders

---

package.json
src/components/Sidebar/Sidebar.jsx
src/components/Site/Site.jsx
src/utilities/content-tree-enhancers.js

Pages sidebar order was incorrect in all pages, this PR fixes it.
We are using `directory-tree` to get a JS Object representation of our content, at this moment it returns `index.md` files as any other page, but we have to use it as our main anchor in the sidebar.
I tried to change how `sort` function works on  `content-tree-enhancers.js`, without success, as last resort I manually moved the item to the beginning of the array. It works but it is a hack.
We should think in a better structure for our content, or at least create a different representation between system files and site content structure and navigation (sidebar).

Fix Sidebar order alphabetically

---

src/content/configuration/watch.md
src/content/guides/getting-started.md

This uses the official casing for the Windows and macOS names.

fix(docs): Capitalize Windows and macOS

---

src/content/api/cli.md

`entry` should begin with `./`, or we'll get error:
> Entry module not found: Error: Can't resolve 'src/index.js' in ...
Because webpack will try to resolve it from `node_modules` directory.

docs(api): fix cli example

---

src/components/NotificationBar/NotificationBar.jsx

Removed link to unixstrickers, since it's not possible to buy webpack stickers anymore after they changed to only selling sticker packs.

(NotificationBar) Removed link to unixstickers

---

src/content/api/node.md

Not the biggest PR, but I like to help out where I can :)
It looked like the link for `WebpackOptionsDefaulter` was chopped in half to keep to a line length of 80, but markdown doesn't preserve links across new lines. I couldn't find a line length policy on the website or this repo, but since the line below it goes to 102 characters, I'm assuming you're willing to make an exception for links.  This brings line 77 up to 106 characters, but it's still safely below 120.

Fix a broken markdown link in node.md

---

src/content/guides/development.md

The advice for WebStorm applies to all JetBrains IDEs, so the IntelliJ-specific advice can be removed (it does the same thing anyway).

docs(guides): Simplify instructions for disabling IDE safe write

---

src/content/plugins/split-chunks-plugin.md

First of all, I wanted to congratulate everyone on the great job of maintaining docs! Really useful.
For the splitChunks page, it took me a while to figure out what does the size represent (unit of measurement). I didn't find any reference on it, but hopefully I got this right since the rules are based on 30kb and the default value is 30000.
Cheers!
Alex

Added explanation for splitChunks.minSize

---

src/content/guides/caching.md

I don't see any valid link for `NamedModulesPlugin`, so I removed it at all.

Remove 404 link for NamedModulesPlugin

---

src/content/contribute/writing-a-loader.md

“Depending the type of module” -> “Depending on the type of module”

Fix a typo: Depending type -> Depending on type

---

src/content/plugins/profiling-plugin.md

There is no "Profile" tab in Chrome devtools. After trying this out,
this seems to work with the "Performance" tab.

Fix ProfilingPlugin instructions

---

src/content/api/compilation-hooks.md

`dependencyReference`
Fixes #2319

docs(api) document dependencyReference compilation hook

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/Dropdown.scss
src/components/Navigation/Navigation.jsx

- make it focusable
- allow navigation using arrow keys
- dismiss on escape
This is a rework of #2325

fix(a11y) Make Dropdown more accessible

---

src/content/guides/environment-variables.md

environment-variables.md - added missing `require('path')`
config was not usable as given without this line.

guide example config - add missing require('path')

---

package.json
src/scripts/fetch_starter_kits.js
yarn.lock

Update starter kits guide fetched from @ahfarmer's [javascriptstuff-db package](https://github.com/ahfarmer/javascriptstuff-db).
Now the list will be consistent with that present in this file: data/source/react-starter-projects.js.

update Starter Kits

---

src/content/api/parser.md

Fix example in parser api section (it's a hook map, so `for` is needed).

docs(api) correct get parser example

---

src/content/guides/output-management.md

I see the pattern of `npm install <option> <package_name>` being used across the guides, but this npm command has the option part at the end.
It would look more consistent if this line kept the same pattern although the result is the same.

Update output-management.md (Minor)

---

src/content/guides/code-splitting.md

Changed a sentence to what I think it was meant to be.

fix(guides) Fix typo in code-splitting.md

---

src/content/guides/author-libraries.md

Proper JSON syntax should not use single quotes, see http://www.json.org/.
Changes in this commit:
* Use json instead of javascript for codeblock language.
* Change single quotes to double quotes.
* Remove semicolon.
* Apply default formatting with prettier.

fix(guides) Use proper JSON in author-libraries

---

src/content/guides/progressive-web-application.md

The plugin `workbox-webpack-plugin` generates a service worker with name `service-worker.js` (see https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-webpack-plugin/src/generate-sw.js#L54).
Replaced all instances of `sw.js` with `service-worker.js`.

fix(guides) Update generated filename in PWA

---

src/utilities/fetch-package-files.js

` console.log('utilities/fetch-package-piles', error);`  -->  ` console.log('utilities/fetch-package-files', error);`

typo - piles to files

---

src/content/guides/production.md

Add explanation to [Specify the Environment](https://webpack.js.org/guides/production/#specify-the-environment) section in production guide, which is no longer effective with webpack v4. See advice here https://github.com/webpack/webpack.js.org/issues/2387.
P.S. I think it's better adding an instruction than removing the whole section, for there're users of previous major versions. If there's a separate branch and url for v3 docs, I'll add changes and remove the whole section in master.

fix(guides): update production guide, fix #2387

---

src/content/guides/caching.md

Hi! 👋 This PR fixes https://github.com/webpack/webpack.js.org/issues/2296
Following is a list of removed resources and a brief explanation of the reasons behind:
- [Predictable Long Term Caching](https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31)
Based on webpack 3 (i.e. code snippets use CommonsChunkPlugin)
- [Webpack & Caching](https://gist.github.com/sokra/ff1b0290282bfa2c037bdb6dcca1a7aa) 
While some of the recommendations might still be useful, some other make use CommonsChunkPlugin. Maybe the reference could be updated and then kept in the docs?
- [Advanced Webpack Presentation](https://presentations.survivejs.com/advanced-webpack/)
Based on webpack 3 (i.e. code snippets use CommonsChunkPlugin)
- [Issue …

Update references to webpack 4

---

src/content/concepts/loaders.md

added example of sass loader and explanation of why it goes at the end in order to work

added sass loader

---

src/components/Site/Site.jsx

"migrate" added to:
` isActive: url => /^\/(api|concepts|configuration|guides|loaders|migrate|plugins)/.test(url),`

Fix issue: Sub-Navigation disappears when sub-menu entry "Migrate" is clicked

---

src/content/plugins/hashed-module-ids-plugin.md

According to the code, the default hashFunction is md4, not md5.
https://github.com/webpack/webpack/blob/482ff200/lib/HashedModuleIdsPlugin.js#L18

Fix default hashFunction for HashedModuleIdsPlugin

---

src/content/concepts/output.md

As seen in the `WebpackOptionsDefaulter`, the `output.path` value defaults to `path.join(process.cwd(), "dist")` (and `process.cwd()` and `""`, before that 🤔).
https://github.com/webpack/webpack/blob/3366421f1784c449f415cda5930a8e445086f688/lib/WebpackOptionsDefaulter.js#L152

Update output.md to match the default options

---

src/server.jsx

* twitter card
* opengraph
Fixes #1984

feat(misc) Add OG and Twitter metadata

---

src/content/guides/code-splitting.md

This PR remove a duplicate warning on the code-splitting page
https://webpack.js.org/guides/code-splitting/#prevent-duplication

remove duplicate warning

---

src/content/guides/tree-shaking.md

Added a mention about ModuleConcatenationPlugin in the tree shaking, because it will not run without it.

fix(docs) Added a mention about ModuleConcatenationPlugin in the tree shaking (#2440)

---

src/content/api/parser.md

* Rename `Parser` page into `JavascriptParser` 
* Fixes #2332 
P.S. i did not change the URL intentionally, it is not clear if we are getting any new parsers just yet.

docs(api) rename parser page into JavascriptParser

---

src/components/Sidebar/Sidebar.scss

fix(ux) Set max width to sidebar to avoid overflow text

---

src/content/api/cli.md
src/content/guides/installation.md

* remove webpack-command mentions

docs(cli) remove webpack-command

---

src/content/guides/code-splitting.md

* Remove duplicated warning
* Rename `SplitChunksPlugin` mentions to correspond to its name and not to configuration option.
* Various linking improvements
* Remove outdated `CommonChunksPlugin` reference

docs(guides) updates to code splitting guide

---

package.json
src/utilities/process-readme.js

Marked known false negatives from hyperlink as TODO and added a url rewrite mechanism for old urls while fetching README's
This should put the `rebuild` branch in the green again

Fix regressions from #2451

---

src/content/guides/tree-shaking.md

Update tree shaking guide
Update code to have consistent single quote in js examples

docs(guides) update tree shaking guide, make syntax consistent

---

src/content/plugins/split-chunks-plugin.md

Update defaults for SplitChunks on:
https://webpack.js.org/plugins/split-chunks-plugin/#defaults
https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks
Fixes #2323

docs(plugins) SplitChunks defaults update

---

src/content/configuration/plugins.md

Issues/2424 Update plugins configuration example

---

src/content/configuration/module.md

Remove array from possible values of Rule.sideEffects

---

src/content/api/plugins.md
src/content/plugins/index.md
src/content/plugins/progress-plugin.md

To address #2289, add a "Reporting Progress" section to the Plugin API doc, and an article for `ProgressPlugin`.

docs: add ProgressPlugin + progress reporting

---

src/content/configuration/dev-server.md

When trying to use the `router` feature in [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) in our `webpack-dev-server` config, I was having trouble and couldn't find any documentation as to why it hadn't worked. I ended up looking in the source code and realized that I hadn't been including a `target` key. It hadn't been clear that that was required, since the `router` function overrides the `target` key. I figured others might run into the same issue and wanted to clarify.

Add caveat for using http-proxy-middleware options

---

src/content/concepts/why-webpack.md

removed double title from start

fix: Update why-webpack.md

---

src/content/concepts/why-webpack.md

Removed a duplicate sentence : 
Before : 
"When script files are wrapped by an IIFE, you can safely concatenate. When script files are wrapped by an IIFE, you can safely concatenate or safely combine files without concern of scope collision."
After : 
"When script files are wrapped by an IIFE, you can safely concatenate or safely combine files without concern of scope collision."

Removed a duplicate sentence

---

src/content/guides/typescript.md

Readability improvement in a sentence:
Before
"Now we tell webpack to extract these source maps and into our final bundle:"
After
"Now we tell webpack to extract these source maps and include in our final bundle:"

Minor wording change

---

src/content/guides/production.md

fix: The main entry in package.json has incorrect settings. As the previous sections of the tutorial, I think it should be point to "src/index.js" instead.

Correct main entry in package.json

---

src/content/plugins/split-chunks-plugin.md

From [this comment](https://github.com/webpack/webpack.js.org/issues/1956#issuecomment-417346913):
> The documentation (https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-cachegroups-test) shows a code example defining splitChunks.test (which I dont believe exists?) instead of splitChunks.cacheGroups[yourGroup].test.

fixing invalid splitChunks example

---

src/content/guides/development.md

In the Development guide, add a warning about the dev server not writing any output files.
I was recently using webpack for a new project, and had a little trouble setting up the dev server because of some misunderstandings about how it works. If the dev server says that it compiles files, I'd expect an output to be written somewhere, just like when you run webpack from the terminal. 
However this is not the case and it left me puzzled for a while. It seems [a lot of people](https://github.com/webpack/webpack-dev-server/issues/24#issuecomment-44366325) also find this not so obvious so I decided to try help a little with this PR. Let me know what you think.

docs(development): Add warning about dev server

---

src/content/concepts/targets.md

The original link (`/concepts/output`) leads to an empty page.

Fixed link to `output` property

---

src/content/contribute/writing-a-plugin.md

This PR resolves https://github.com/webpack/webpack.js.org/issues/2494 - the plugin name used in the initial code snippet is an event name and is confusing whether it's of significance or not. This PR uses the plugin's name which is consistent with the other code snippets on the page. https://webpack.js.org/contribute/writing-a-plugin/
/review @iamakulov @jeremenichelli @montogeek

Use consistent plugin name in code snippet

---

src/components/SidebarMobile/SidebarMobile.jsx
src/components/SidebarMobile/SidebarMobile.scss
src/components/Site/Site.jsx
src/components/SplashViz/SplashViz.scss

- Fixed broken urls in section headings
- Fixed active marker of the section and avoided marking a sections index page as active when a sub page was active
- Hooked close button up
- Made drag-to-open work
- Made outside click to close menu work

Rebuild: Make mobile sidebar work again

---

src/content/configuration/output.md

Fixes a small typo on `output.md`

Fix typo on output.md: adds "be" before "exposed"

---

src/content/concepts/manifest.md

Small updates and corrections for manifest concepts page

docs(manifest) corrections and small update to concept manifest page

---

src/content/concepts/dependency-graph.md

* provide links to new page
* link example for aggressive splitting plugin
* use common formatting
* move older article from *best optimization* reference into further reading secion

docs(concepts) Update dependency graph concepts page

---

src/content/configuration/externals.md

Update the external docs with an example on how to combine the different syntaxes. 
I felt it was not clear how to achieve this from the existing docs.

Update externals.md - Combining syntaxes example

---

src/content/api/cli.md
src/content/comparison.md
src/content/configuration/configuration-languages.md
src/content/configuration/devtool.md
src/content/configuration/optimization.md
src/content/guides/integrations.md
src/content/guides/production.md
src/content/plugins/index.md
src/content/plugins/internal-plugins.md
src/content/plugins/source-map-dev-tool-plugin.md

Since as of webpack 5, the default `options.minimizer` is now `terser-webpack-plugin`:
https://github.com/webpack/webpack/pull/8036
I've also:
* updated the custom `minimizer` example to include all of the default options, to reduce the chance people forget to enable them.
* removed the `optimize/UglifyJsPlugin` reference, since it's no longer included in the webpack repository.
* removed the "Here are a few more popular ones" mention, since it's not accurate (they aren't more popular).
* removed manual plugin configuration from `configuration-languages.md` since the defaults for `minimizer` make it unnecessary.
Fixes #2520.

docs(config): Replace UglifyJSPlugin references with TerserPlugin

---

src/content/concepts/entry-points.md

fixes webpack/webpack#6647
see https://github.com/webpack/webpack/issues/6647#issuecomment-422288194
> > You should not have a entrypoint for vendor. It's not an entry.
> This advice is in direct contradiction to official documentation: https://webpack.js.org/concepts/entry-points/

Using vendors as entry is not recommended

---

src/content/api/cli.md

Change wording from "bind an extension" to "bind a file extension" in order to distinguish from a webpack extension.

Clarify module section

---

src/content/plugins/html-webpack-plugin.md

Update broken links in htmlwebpackplugin docs

docs(plugins): update links in htmlwebpackplugin

---

src/content/plugins/split-chunks-plugin.md

* Fix title nesting, reside in cachingGroups.cacheGroup.option
* add example

docs(plugins) scp reuseExistingChunk title nesting fix

---

src/content/guides/caching.md

import webpack needs to be highlighted since we are adding webpack.HashedModuleIdsPlugin()

import needs to be highlighted with '+' mark

---

src/content/configuration/optimization.md

Re-create PR #2533 against master as it belongs to `master`.
Ground to fix #2528

docs(config) optimization moduleIds option

---

src/content/configuration/module.md

Added documentation and an example around a Module's `Rule.type` configuration property. Fixes #1994

docs(config) add comments and values for rule.type

---

src/content/concepts/index.md

webpack supports different file types and extensions by default out of the box. `.js`, `.mjs` and `.json` files. but in the old docs, it's been written as it only supports Javascript files.

Update docs: adds JSON file to out of the box supported files

---

src/utilities/process-readme.js

Fix(utilities): Convert github raw links to rendered page links

---

src/content/plugins/source-map-dev-tool-plugin.md

I noticed a discrepancy between the typescript definitions and this documentation, and assumed the definition to be correct.
This changes doc to show that a boolean is possible for the lineToLine option

Add boolean as possible type for lineToLine

---

src/content/migrate/4.md

The link to [optimization.splitChunks](https://webpack.js.org/configuration/optimization/#optimization-splitchunks) anchor was broken.

Fix webpack 4 migration guide link to split chunks docs

---

src/content/api/module-methods.md

`require.context`, accepts an extra forth argument, but this is not described in documentation.
Information is based on replies from this issue https://github.com/webpack/webpack/issues/7283

Extend documentation for require.context

---

src/content/guides/tree-shaking.md

@babel/preset-env is extremely popular, but unless an additional configuration was added to it, it will break Webpack's tree shaking. It's worth mentioning it in the docs, I think.

Mention @babel/preset-env transforming ES modules to CommonJS by default

---

src/content/configuration/output.md

This adds a section to the Output configuration page for the "amd-require" library target that was added in webpack/webpack#8093.
Fixes #2562.

docs(config): Add section for output.libraryTarget: "amd-require"

---

src/content/plugins/hashed-module-ids-plugin.md

I was wondering what is the behavior in case of potential collisions, I think it's worth documenting.
See https://github.com/webpack/webpack/blob/91e9dd77062797e3e716485f295d32a5cab57042/lib/HashedModuleIdsPlugin.js#L50
(This doesn't handle the potential collisions of the hashing algorithm itself, only the collisions due to truncating the hash -- though the first type should virtually never happen in case of the input type being a module name / path string, so I think that's fine).

docs(plugins) More info on HashedModuleIdsPlugin#hashDigestLength

---

src/content/configuration/stats.md

Added possible values for `assetsSort`, `chunksSort` and `moduleSort` according to the [sources](https://github.com/webpack/webpack/blob/cec5bfb01c025a28062646e18467293e4d6b93ab/lib/Stats.js#L489).
Before this change it was impossible to straight up guess all the possible sorting fields for statistics.
I see this as a critical drawback for projects with a large amount of chunks and assets (I work on one with ~100 chunks). Lack of relevant field sorting documentation means hours wasted on trying to align the records in console statistics.
Like it was for me.
After 2 hours of googling and rereading webpack documentation I had to dive into the source-code.
This PR is here to make webpack docs another tiny bit better and to ensure that nobody will have to forcefully scan the sources in order …

docs(config): clarify `stats.md` sort fields

---

src/content/plugins/split-chunks-plugin.md

Fixes #1956 
See https://github.com/webpack/webpack.js.org/issues/1956#issuecomment-417346913
In comments people also asked for examples, i think that is a separate to the original issue request, it is time to close this one as if syntax on test function is now correct.

docs(plugins) update scp test info

---

src/content/concepts/mode.md

_One of maxAsyncRequests properties in webpack.development.config.js should be maxInitialRequests._

Mistake in Mode Doc corrected

---

src/content/configuration/other-options.md

Added `name` field docs. I found it accidentally in the error message. And this is exactly what I needed in my work 🙂
Also added missing field types for sibling fields.

Add 'name' field docs & minor fixes

---

src/content/configuration/resolve.md

`/guides/migrating#automatic-loader-module-name-extension-removed` is broken link.
I think that the current link is `/migrate/3/#automatic-loader-module-name-extension-removed`.

Fix broken link

---

src/content/configuration/target.md

- atom and electron no longer allowed via schema
- outdated link and example

docs(config) target updates to current webpack state

---

src/content/plugins/split-chunks-plugin.md

- document `splitChunks.cacheGroups.{cacheGroup}.filename` configuration option
- Fixes #2611

docs(plugins) split chunks cache group filename option

---

src/content/guides/getting-started.md

Unless I am mistaken, no CLI options were used earlier in this guide to run webpack.

Remove reference to CLI options not used before

---

src/content/api/plugins.md

Matches documented parameters with [`webpack/tapable` docs](https://github.com/webpack/tapable#usage):
```javascript
myCar.hooks.calculateRoutes.tapPromise("GoogleMapsPlugin", (source, target, routesList) => {
// return a promise
return google.maps.findRoute(source, target).then(route => {
routesList.add(route);
});
});
myCar.hooks.calculateRoutes.tapAsync("BingMapsPlugin", (source, target, routesList, callback) => {
bing.findRoute(source, target, (err, route) => {
if(err) return callback(err);
routesList.add(route);
// call the callback
callback();
});
});
// You can still use sync plugins
myCar.hooks.calculateRoutes.tap("CachedRoutesPlugin", (source, target, routesList) => {
const cachedRoute = cache.get(source, target);
if(cachedRoute)
routesList.add(cachedRoute);
})
```

Updates plugins.md

---

src/content/contribute/writers-guide.md

When I first read the writers guide, it took me a while to realize that the "Same goes for tables" was referring to the fact that they must be in alphabetical order (or at least... I'm pretty sure that's what it is referring to 😅)
In my opinion, it would be better to give it its own context, especially because people can link directly to the Tables section.

Small clarification in Tables section of writers-guide.md

---

src/content/plugins/internal-plugins.md

After the arrival of webpack 2, `OccurenceOrderPlugin` has been [renamed](https://github.com/webpack/webpack/issues/1964#issuecomment-177661869) to `OccurrenceOrderPlugin`. This PR updates this to internal-plugin docs.

docs(plugins): rename OccurenceOrderPlugin to OccurrenceOrderPlugin

---

package.json
yarn.lock

Bumping version since `eslint-plugin-markdown` got a release. 
See [this tweet](https://twitter.com/brandontmills/status/1056292345052884992)

chore(eslint-plugin-markdown) bump version to release candidate

---

src/content/guides/development.md

- Development guide's config snippet was missing `mode: development`
- remove minor formatting inconsistencies

docs(guides) add mode development to config in the dev guide

---

src/content/api/cli.md

Document `--no-color` option, and clarify colours are enabled (for TTY output only) if no options are given. See [supports-color](https://github.com/chalk/supports-color) for details.

docs(cli): document --no-color option

---

src/content/configuration/optimization.md

Add a link to the mode concept. Although there is a link further down in the document, I didn't realize it and I started searching for what was meant by mode. The `mode` been linked on its first instance on this page, I wouldn't have gone off trying to figure it out on my own.

Add Link to Mode Concepts

---

src/content/guides/tree-shaking.md

In last PR #2426 the `mode` was changed from `production` to `development` and it broke the tree shaking behavior because [`usedExports`](https://webpack.js.org/configuration/optimization/#optimization-usedexports) is `false` in `development` mode.

docs(guides) update tree shaking guide

---

src/content/guides/author-libraries.md

I really tripped over the original version because I read it as if the *consumer* was required to use `externals`. Obvious in hindsight but maybe this change will spare someone else a few minutes of confusion 😊

Recast this sentence about `externals`

---

src/content/configuration/other-options.md

Adds documentation to configuration of cache for webpack v5
Fixes #2605

docs(config) document configuration cache for webpack v5

---

src/content/configuration/stats.md

- explain on how to "extend" one of the stats pre-defined behaviours.
Fixes #2616

docs(config) stats pre defined template extension

---

src/content/concepts/configuration.md

Removed 'following' from 'The following examples below' as it kind of seems redundant.

docs(concepts) Remove redundant word in configuration.md

---

src/content/loaders/index.md

Reverts webpack/webpack.js.org#2653
Reasons behind revert are:
- not readable source code on parse.js (https://github.com/leecjson/ref-loader/blob/master/parse.js)
- no auto tests
- no current usage statistics, potentially suspicious
@leecjson the functionality looks very useful! Can you please add auto tests and refactor your source code to make it easily readable before re-submitting this to webpack.js.org please.

Revert "Add ref-loader to loader's introduction page"

---

src/content/configuration/index.md

The link `https://webpack.js.org/guides/migrating` described in [https://webpack.js.org/configuration/#options](https://webpack.js.org/configuration/#options) is broken. Changed link to [migrate/3/#automatic-loader-module-name-extension-removed](migrate/3/#automatic-loader-module-name-extension-removed).

docs(config): fix broken link

---

src/content/guides/development.md

devtool: 'inline-source-map' is added in "Using source maps" section
which comes after the "Development" section

docs(dev): remove devtool from mode section

---

src/content/configuration/externals.md

- add a note about using object for externals
- use `javascript` for code example blocks to continue general `*.md` tidying and maintainability
- fixes #2668

docs(config) Externals as object note about umd library target

---

src/content/configuration/resolve.md

There was an extra word. Now there isn't.

docs(config): fix typo by removing extraneous 'which'

---

src/components/Support/Support.jsx

Donating seem to be abused for advertising. This PR limits the number of "latest" sponsors and limits the number of backers to 100 randomly chosen ones.

Limit number of displayed sponsors and backers

---

src/content/api/cli.md
src/content/comparison.md
src/content/concepts/mode.md
src/content/configuration/configuration-languages.md
src/content/configuration/configuration-types.md
src/content/configuration/devtool.md
src/content/configuration/optimization.md
src/content/guides/build-performance.md
src/content/guides/integrations.md
src/content/guides/production.md
src/content/guides/tree-shaking.md
src/content/plugins/index.md
src/content/plugins/internal-plugins.md
src/content/plugins/source-map-dev-tool-plugin.md

UglifyJS was replaced by Terser in the documentation https://github.com/webpack/webpack.js.org/issues/2656.

Replace UglifyJS with Terser (#2656)

---

src/content/configuration/output.md

Dont advertise AggressiveSplittingPlugin since its getting deprecated, partially fixes #2696

docs(config) remove AggressiveSplittingPlugin mention

---

src/content/contribute/writers-guide.md

Currently we are using sub-sections using group property for `MODULES` and `PLUGINS` on `/api/` page.
This PR adds information about how to add sub-section.

docs: add group prop in writer's guide

---

src/content/loaders/index.md

Currently, loaders are discoverable by hyperlinks on the loaders page, but there are some loaders which do not have a hyperlinks.
This PR adds hyperlinks for rest of the loaders.

docs: add missing links to loaders

---

src/components/Splash/Splash.scss

Dont let splash's content overlap links.
Fixes #2637

ux(splash) fix splash overlapping with links on low heights

---

src/content/plugins/split-chunks-plugin.md

Hi people!
This adds a note about what `splitChunks.name = false` means and that it is probably a good setting for production. This (hopefully) is an easy win, as it was recommended by sokra: https://github.com/webpack/webpack/issues/8426#issuecomment-442375207
Thanks!

Adding a note about splitChunks.name = false functionality

---

src/content/plugins/split-chunks-plugin.md

Fixes #2705 partially, the rest is for migration guide
- remove name: true and automaticNamePrefix from splitChunks
- add idHint option to splitChunks to provide a hint for the named ids

docs(plugins) SCP idHint and removal of name and automaticNamePrefix

---

src/utilities/process-readme.js

Implements https://github.com/webpack/webpack.js.org/pull/2693 to `rebuild` branch.

fix(fetch-packages): remove only titles from loaders and plugins docs

---

src/content/plugins/ignore-plugin.md

- Describes changes merged in webpack/webpack#7827
- small reformat

docs(plugins) IgnorePlugin new syntax and options

---

src/content/plugins/split-chunks-plugin.md

Here's where `cacheGroup.name` get invoked, being passed chunks and cacheGroup: https://github.com/webpack/webpack/blob/master/lib/optimize/SplitChunksPlugin.js#L470

docs(plugins): specify all inputs to `cacheGroup.name`

---

src/content/concepts/index.md

When specifying a test in `module.rules`, webpack accepts either a regex or string. However it's easy to mistakenly qoute the regex which will cause webpack to not use the specified loader. I added this warning to help newcomers like me who might  stumbled into this situation save themselves frustrations and wasted time.

Add a warning note for common errors when specifying rules

---

src/content/guides/caching.md

Most of us are reading the docs because we don't know how to do something, and it's not fun to hear that the concept we're having a hard time understanding is "simple" or "easy". I'd love you to show me how simple it is instead. 
A great reference: https://css-tricks.com/words-avoid-educational-writing/
Updated some language around `contenthash` as well, hopefully it's a little more direct. Let me know what you think.

Small readme improvements, remove the word "simple"

---

src/content/api/module-methods.md

docs: added title of Magic Comments so it can be found in the search bar. Added preload and prefetch as although they are in the guide I feel it would be beneficial to have all the magic comments in the one place and a link to the guide for more. Any suggestions just let me know

docs: added more info for magic comments

---

src/content/plugins/split-chunks-plugin.md

Reverts webpack/webpack.js.org#2227

Revert "cacheGroups"

---

src/content/guides/author-libraries.md

Now that ExtractTextWebpackPlugin is no longer recommended since webpack 4, I think it's better to update the link.

docs(guides): Update author-libraries.md

---

src/content/plugins/ignore-plugin.md

There's no requestRegExp option for IgnorePlugin in the source code

Change requestRegExp to resourceRegExp IgnorePluginOptions in docs

---

src/content/configuration/resolve.md

d3 doesn't supply a browser field in its [`package.json`](https://github.com/d3/d3/blob/3e2bbb506b536fdf13bfdf6a106d1c16b4859666/package.json#L18-L21) anymore.
this small change updates the section that describes the order of precedence for module resolution to make it more generic.

make d3 pkg.browser example more generic

---

src/content/configuration/module.md

Adds some documentation for using a function for `Rule.use` configuration.
For the object passed to the function, I'm not surewhat `realResource`, `compiler` & `resourceQuery` are for, and I'd appreciate some help to explain them succinctly , thank you
Fixes #2691

Add documentation for `Rule.use` as a function

---

src/content/configuration/stats.md

Fixes #2734 
Document new stats option which is off by default.

 docs(config) add new stats option is off by default

---

src/content/guides/installation.md

In the follow-up steps in the guide, `npm run build` is always referenced, not `npm run start`. It seems like in the initial installation section `build` should be the name of the npm task vs. `start`.

Update installation.md to reference `npm build` vs. `npm start`

---

src/components/Organization/Organization.jsx

Fix unencoded star character in img src url (`https://img.shields.io/github/stars/webpack/memory-fs.svg?label=✭&style=flat-square&maxAge=3600`)
Caused `npm run linkcheck` to break.
This is a hopefully nicer alternative to disabling the link check: https://github.com/webpack/webpack.js.org/pull/2759
We'll look into making `hyperlink` either tolerate this kind of invalid url (if browsers tolerate it), or throw a specific error message instead of an internal error.

Fix unencoded ✭ character in img src

---

src/content/guides/asset-management.md

Added instruction for `npm build` on the `guides/asset-management`.
This change would prevent reader from confusion if they forgot to build module before check upon `dist/index.html`.

docs(guides): Add "npm build" instruction on "Loading Data" section

---

src/content/concepts/index.md
src/content/configuration/index.md

Grammar correction in Line 401 changing "with few clicks away" to "with just a few clicks away".

Grammar correction in Line 401 of the configuration page

---

src/content/plugins/split-chunks-plugin.md

Adding a description for `maxAsyncSize` and `maxInitialSize`, in response to https://github.com/webpack/webpack.js.org/issues/2723 (based on https://github.com/webpack/webpack/pull/8484).
EDIT: Fixes #2723

docs(config): Describe maxAsyncSize and maxInitialSize

---

src/content/configuration/resolve.md

- add correct function signature
- move types and their defaults to the right place
- format configs accordingly to docs style
- remove redundant default texts

docs(config) resolve page tidy up and improvements

---

src/content/api/compiler-hooks.md

Fixes a typo in the `afterEnvironment` hook

docs(compiler-hooks): fixes typo in afterEnvironment

---

src/content/guides/shimming.md

URL encode Wikipedia polyfill link.  Closing parenthesis in previous link was dropped in most browsers.

Fix Wikipedia polyfill link

---

src/content/concepts/mode.md

Redundant words removed.
Seems like someone forgot to delete them in some previous edition.
Similar phrases can be found several lines above:
>Possible values for mode are: none, development or production(default).

docs(concepts) Remove redundant words in mode.md

---

src/content/guides/build-performance.md
src/content/guides/environment-variables.md

I'm just trying out webpack and the installation and environment variables sections threw me off a bit. Hopefully these minor changes will help others avoid my confusion.
1. The installation section explains that you need to install the cli for webpack 4 but could be clearer that this is in addition to the `webpack` package. I added "also".
2. The environment variables section does not make clear that webpack's environment variables are separate from the environment variables I might set in `bash`, `fish`, `zsh`, etc... I added a tip to that effect.

Adding minor getting started clarifications

---

src/components/Support/Support.jsx
src/components/Support/Support.scss

Changes method of creating green outline around Open Collective backers from an extra dom element with quirky positioning to a CSS box shadow.
**Before**
**After**

Fix wrong alignment of green outline on Open Collective backers

---

.travis.yml

https://github.com/webpack/webpack.js.org/pull/2806 disabled **all** link checking.
The slowest task we wanted to avoid was the external link check, which was allowed to fail anyway. But not the internal link check, which ensures we don't have any broken links internal to the documentation page.
This change brings back the internal checks. This is also the faster of the two link checks

Bring back linting of internal links

---

package.json
src/content/configuration/output.md

The `output.globalObject` is useful for UMD build, which should be documented.
Ref: https://github.com/webpack/webpack/issues/6522

docs(configuration): add a missing option

---

src/content/api/loaders.md
src/content/configuration/module.md

Fixes https://github.com/webpack/webpack.js.org/issues/2804
Update: Turns out that the docs do already talk about the overrides [here](https://webpack.js.org/configuration/module#ruleenforce), but this PR attempts to make this information more obvious.
@EugeneHlushko If you find that it's not necessary, we can close this PR

Add info about loader overrides

---

src/content/configuration/optimization.md

Correct typo (incorrect reference) in: [Configuration: optimization.chunkIds](https://webpack.js.org/configuration/optimization/#optimizationchunkids).
The last bullet point currently reads
"if none of the above, `optimization.namedChunks` will be defaulted to `'natural'`"
which should have been
"if none of the above, `optimization.chunkIds` will be defaulted to `'natural'`"

docs(Config.Optimization): correct typo namedChunks -> chunkIds

---

src/content/guides/hot-module-replacement.md

fixing a typo removing function's parenthesis, as we are assigning the function reference rather than its call return value

fix a little typo

---

src/content/guides/author-libraries.md

Remove extra spaces before parentheses on the `guides/author-libraries`.

docs(guides): remove extra spaces before parentheses

---

src/components/Markdown/Markdown.scss

Currently, tables that are too wide aren't displayed completely. See https://webpack.js.org/comparison, for example.
The CSS already had overflow-x and overflow-y values in place, but they weren't doing much as the tables weren't rendered as a block.

Enable horizontal scrolling for wide tables

---

src/content/concepts/targets.md

The missing space causes the first letter of the line to disappear.

docs(concepts): add missing space in targets.md

---

src/content/configuration/index.mdx

Mention internal config generation capability

docs(config) mention cli config generator

---

src/content/guides/output-management.md

CleanWebpackPlugin released  v2.0.0 and the API has a breaking change: No configuration is needed for standard usage (cleans webpack's output.path).
`new CleanWebpackPlugin(['dist/*'])` with the new version clean-webpack-plugin installed above will cause an error:
"Error: clean-webpack-plugin only accepts an options object. See: https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional "

docs(guides): change CleanWebpackPlugin arguments usage

---

src/content/guides/shimming.md

Update links to babel-preset-env docs in shimming guide

Update babel-preset-env links in shimming guide

---

src/content/guides/hot-module-replacement.md

The currently linked module is no longer maintained.
This works in conjunction with https://github.com/elm-community/elm-webpack-loader

Update Elm HMR reference

---

src/content/guides/development.md

new CleanWebpackPlugin() | requires a config object than an array

CleanWebpackPlugin | Requires a config object

---

.eslintrc
src/components/Configuration/Configuration.jsx
src/components/Dropdown/Dropdown.jsx
src/components/Organization/Organization.jsx
src/components/Support/AdditionalSupporters.js
src/utilities/content-tree-enhancers.js
src/utilities/fetch-package-repos.js
src/utilities/markdown.js
src/utilities/test-local-storage.js

- force single quotes for strings in js?x for consistency reasons
- fix current occurence

infra(eslint) force single quote for js?x

---

src/content/guides/development.md
src/content/guides/output-management.md

As a follow up to recent clean-webpack-plugin 's update, we want to reflect all the necessary changes
Related to #2884

docs(guides) updates due to recent plugin update

---

src/content/guides/code-splitting.md

While looking at #2790 
I've noticed a few things to do:
- Grammar
- broken links while in dev

docs(guides) code splitting grammar and fix local links

---

src/content/index.md

Fixes https://github.com/webpack/webpack.js.org/issues/2854
Before:
After:
cc @Ajacmac

Fix clipped header on homepage

---

src/content/concepts/index.md

sentence is using a "former/latter" construction

corrected typo later->latter

---

src/content/api/node.mdx
src/content/concepts/loaders.mdx
src/content/configuration/index.mdx
src/content/configuration/module.mdx

This PR fixes several not escaped backslashes in `.mdx` files. Without a second escaping backslash they are either not visible or interpreted as special character (e.g. `\n`)

Escape backslashes in mdx files

---

src/components/Cube/Cube.scss
src/components/Footer/Footer.scss
src/components/Markdown/Markdown.scss
src/components/Markdown/prism-theme.scss
src/components/SidebarItem/SidebarItem.scss
src/components/SidebarMobile/SidebarMobile.scss
src/components/Splash/Splash.scss

- format scss files for maintainability

docs(infra) format scss files for maintainability

---

src/content/api/compilation-hooks.md

Change `finishModules` hook to be `AsyncSeries`.
Resolves #2924

Convert finishModules hook to be an AsyncSeries

---

src/content/configuration/dev-server.md

Issue: https://github.com/webpack/webpack.js.org/issues/2922
I documented the new `devServer.http2` option.
- Included API/CLI examples for self-signed and custom certificates
- Detailed relations of this with `https` option

docs(dev-server): New http2 option

---

src/content/guides/code-splitting.md

Fragments in the links were not matching the actual anchors.

Fix links to API methods in the code splitting article

---

src/content/configuration/dev-server.md

Closes: #2932 
This PR adds documentation for the new `mimeTypes` option. The option was introduced in https://github.com/webpack/webpack-dev-server/pull/1714

docs(dev-server): Add documentation for `mimeTypes` option

---

src/content/configuration/other-options.md

- fixes #2934 
- minor fixes (types, rephrase `simply`)

docs(config) correct caching default, fix minors

---

src/content/license.md

Found another occurrence where sort was in menu, i hope i didnt miss any other this time.

docs(license) fix up markup to not render sort attribute in the menu

---

src/components/Splash/Splash.scss

Heading were all aligned left on homepage splashes, probably we broke it when merged rebuild.

ui(homepage) fix heading alignment

---

src/content/configuration/configuration-types.md
src/content/configuration/entry-context.md
src/content/configuration/externals.md
src/content/guides/author-libraries.md
src/content/plugins/dll-plugin.md

fix(links): fix anchor links to `/configuration/output`
related to #2929
Fixed broken anchor links:
* `/configuration/output#output-librarytarget` -> `/configuration/output#outputlibrarytarget`
* `/configuration/output#output-library` -> `/configuration/output#outputlibrary`
Some takeaways (also answering @montogeek 's [question](https://github.com/webpack/webpack.js.org/pull/2929#issuecomment-482023800))
> Why this wasn't catch by the link checker?
* on travis only `lint:links` runs, which executes `hyperlink` with `-i` flag. Looks like in this case fragment links are not checked at all
* `hyperlink` [does not correctly check fragment links](https://github.com/Munter/hyperlink/issues/150) pointing to folders having `index.html` inside.

fix(links): fix anchor links to /configuration/output

---

src/content/configuration/dev-server.md

add documentation for `serveIndex` option in this PR 
https://github.com/webpack/webpack-dev-server/pull/1752

docs(dev-server): Add documentation for `serveIndex` option

---

src/content/api/module-methods.md

The "Magic Comments" section applies to the `import()` (level-3) sub-section of the `ES6` (level: 2) section.
Changing to level-4 will make it clear that the magic comments apply to `ES6` > `import()`.

Change Heading Level of "Magic Comments" Section

---

src/content/contribute/writing-a-loader.md

This PR fixes an uncaught error in a compiler example code in a document about writing a loader.

fix(contribute): Uncaught error in a compiler example.

---

package.json
src/index.jsx
webpack.common.js

- Fixed a case when`npm run start` command to possibly serve old `./dist/index.html` after working with `npm run build-test` command for example
- simplified rendering logic (tested, vote works)
- cleanup unused vars in config

site(misc) simplify rendering logic, clean dist on dev, clean config

---

src/content/plugins/html-webpack-plugin.md

Use real tag as opposed to the next similar reference to `<link>` tag...

docs(plugins) Correct tag
