webpack/webpack.js.org

- styles/index.scss
A better solution that preserves the semantics as a response to https://github.com/webpack/webpack.io/pull/75/files/c4d390c86024d9f7263bfca2e2fada9764a89b10#r76234847
> Capitalize text for all headers

- content/how-to/long-term-caching.md
Based on https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.1ow59wp12
> Added Long-term caching page

- content/how-to/generate-production-build.md
Please feel free to review and amend the copy if necessary.
Talking with @TheLarkInn we both agreed that it would be great if we could later append additional references:
- How to manage multiple configurations
- Splitting configuration between prod and dev
Cheers 🍻
> Add initial content for how-to/generate-produciton-build

- .eslintrc
- package.json
> lint(markdown): add eslint for markdown js codeblocks

- utilities/highlight.js
- utilities/markdown.js
This allows markdown like in #157
> add special code lang which allows links in code

- .markdownlintrc
- CONTRIBUTING.md
- README.md
- content/api/cli.md
- content/concepts/index.md
- content/concepts/targets.md
- content/how-to/cache.md
- content/how-to/develop-using-vagrant.md
- content/how-to/generate-production-build.md
- content/how-to/hot-module-reload.md
- content/how-to/set-up-hmr-with-react.md
- content/how-to/upgrade-from-webpack-1.md
- content/how-to/use-with-docker.md
- package.json
- utilities/markdown.js
Also changed rules to fit with antwar (ie #header doesn't have to be top etc.)
> chore(lint): cleaned all linting errors added from new linting

- utilities/markdown.js
enalbed by adding `-with-details` to the code language
> allow details/summary blocks in code blocks

- content/organization.md
Not sure if this order is generated before or after.
> chore(loader-list): added angular2-template-loader

- components/Footer.jsx
> Fixed links in footer

- antwar.config.js
- components/Sidebar.jsx
- styles/components/_sidebar.scss
- utilities/markdown.js
This PR adds nested anchors to the Sidebar for easier navigation.
@bebraw @oliverturner had some time to fiddle around with this... it's still a WIP but this should do the trick until we get something more solid in place. I should be able to put some final touches on the styling tomorrow.
> Sidebar Anchors

- components/Navigation.jsx
- components/Sidebar.jsx
- components/Site.jsx
- template.ejs
Adds minimal inline JS to template sufficient to restore navigation.
In-browser testing required removal of React functionality, so the sooner this branch can be reverted and die a fiery death the better ;)
> Temporary branch: restores nav functionality. To be reverted ASAP

- content/configuration/devtool.md
I believe it 'al' was suppose to be 'eval'
> rename 'al' to 'eval'

- content/how-to/lazy-load/react.md
I offer my humble strategy for lazily loading React. 
Heavily inspired by my friend @ryanflorence
> add: how-to/lazily-load/react

- components/Footer.jsx
- styles/components/_footer.scss
Stretching the footer back out while retaining the breakpoint.
cc @oliverturner
> Footer Cleanup

- content/configuration/entry-context.md
> Fixed typo

- CONTRIBUTING.md
Added note to encourage developers to include their name in the docs they edit.
> chore(contributor): update contributor.md

- components/Splash.jsx
- content/index.md
- styles/components/_splash.scss
This obviously isn't complete, but I'm curious what other people think. I think it's really important to start right out of the gate with a full, simple, example to demonstrate how easy it is to setup.
Once a developer is familiar with the core concept (which this is), **then** you can start slowly introducing things like plugins, CSS bundling, etc.
> Simple Intro

- content/how-to/upgrade-from-webpack-1.md
> Fix migration guide resolving links.

- content/how-to/set-up-hmr-with-react.md
The `contentBase` value should be relative instead of absolute in the example.
> Changing the devServer contentBase value

- antwar.config.js
- content/concepts/index.md
- content/concepts/plugins.md
- content/how-to/hot-module-reload.md
- content/how-to/set-up-hmr-with-react.md
- content/how-to/shim.md
- content/how-to/upgrade-from-webpack-1.md
- webpack.config.js
Aligns with breaking change introduced with https://github.com/webpack/webpack/pull/3102
See https://github.com/webpack/webpack/issues/2986
> Add `-loader` to every loader name

- components/container/container.jsx
- components/logo/logo-style.scss
- components/navigation/navigation-style.scss
- components/navigation/navigation.jsx
- components/search-results/search-results-style.scss
- components/search-results/search-results.jsx
- components/site/site.jsx
- package.json
cc @bebraw @dzello
Still a WIP, adding the interface bits for search:
Still need to add another search bar in SidebarMobile for searching on screens under 768px, but we should probably take it one step at a time and first merge this so someone else can start playing around with actually displaying search results (see #184).
I'll add some gifs tonight...
> Search Interface

- components/navigation/navigation-style.scss
- components/splash/splash.jsx
- components/support/support.jsx
A fix for a couple build issues, see #305 for related discussion. @SpaceK33z I gotta run to work, but if you could test and get this merged when you have a chance that'd be awesome. I guess we'll also have to do another deployment once this gets merged.
cc @bebraw @TheLarkInn
> Fixing Build Issues

- content/concepts/targets.md
- content/configuration/index.md
- content/configuration/node.md
- content/configuration/resolve.md
- content/configuration/target.md
- content/how-to/author-libraries.md
- content/how-to/cache.md
- content/how-to/generate-production-build.md
the official site writes it this way
> Replace node.js with Node.js

- content/configuration/externals.md
Not very confident of the material.
Looked through [this readme](https://github.com/webpack/webpack/tree/54aa3cd0d6167943713491fd5e1110b777336be6/examples/externals) and code for [ExternalModules](https://github.com/webpack/webpack/blob/54aa3cd0d6167943713491fd5e1110b777336be6/lib/ExternalModule.js) and [ExternalModulesPlugin](https://github.com/webpack/webpack/blob/54aa3cd0d6167943713491fd5e1110b777336be6/lib/ExternalModuleFactoryPlugin.js)
> Docs about externals usage

- content/how-to/upgrade-from-webpack-1.md
Summary:
----
Was going through a migration from v1 to v2 and saw a few things that could be improved in the migration docs. Hope this helps.
> Improve grammar and details in upgrade-from-webpack-1.md on loaders & UglifyJsPlugin

- content/configuration/resolve.md
Ref https://github.com/webpack/webpack/issues/3296
> Move resolve.moduleExtensions into resolveLoader.moduleExtensions

- components/vote/api.dev.js
- components/vote/app.jsx
- components/vote/slider/slider.jsx
As discussed in #292 I implemented slider for the voting. For now I didn't add any styling to the page only slider functionality, so that you can check it out if this is ok first and after that I will add styling.
Note to @sokra:
- added step in the vote settings
- added color in the vote settings
- instead of infinity I set max to 100 with step amount to 10
> Voting slider

- antwar.config.js
- components/vote/api.dev.js
- components/vote/api.js
- components/vote/app-style.scss
- components/vote/app.jsx
- components/vote/list-style.scss
- components/vote/list.jsx
- components/vote/slider/slider.jsx
This PR adds an page to vote for todo items of the core team. There are two currencies:
* Influence: granted to everyone depending on how long you are github member
* Golden Influence: granted by donations (importing of the open collective data WIP)
It's in a prototype stage. It would be great if someone takes care of the design (I can't do that).
Here is a screenshot:
You authenticate with the Github API. This means login only works on webpack.js.org host. A developer emulated version is used if not deployed. See code comment in api.js for more info.
Other ideas:
* Auction stuff
* Distribute a part of the money to ecosystem authors
* Add your own ideas
> added voting app

- content/index.md
The example had a small issue :)
> fix homepage example

- content/guides/migrating.md
I will be contributing more soon, but reading the docs I found a real small typo so figured I'd push it.
> Hotfix: minor typo

- components/navigation/navigation-style.scss
- components/page/page-style.scss
- components/sidebar-item/sidebar-item-style.scss
- styles/index.scss
- styles/markdown.scss
- styles/partials/_vars.scss
- utilities/markdown.js
A implementation of #291 .
**What's new**
- Navigation color is a shade of webpack colors
- Link Color consistent across different places and matches webpack colors
- Tips / Warnings use more soothing colors, aligned to webpack colors
> Webpack colors for the site

- content/loaders/index.md
> Initial Loader Documentation

- components/splash-file/splash-file-style.scss
- components/splash-viz/splash-viz-style.scss
- components/splash-viz/splash-viz.jsx
Leftover from #374 - I merged too early.
> Finishing temporary cleanup for SplashViz

- components/sidebar-mobile/sidebar-mobile-style.scss
- components/sidebar-mobile/sidebar-mobile.jsx
Re-opening from a new branch based on #366...
> Swipable Menu (From #366)

- package.json
This fixes a bug with the voting app
> update antwar version

- content/configuration/devtool.md
This PR adds more `devtool` docs. I'm still not happy about this page and it definitely needs more work. I spent a few hours tracking down what each option does, and at least the page has more information now.
> More devtool docs

- components/vote/app.jsx
- package.json
> add support for browsers without native fetch

- README.md
I think that link should to point to this.
@TheLarkInn Sorry, dude. I closed the [previous PR](https://github.com/webpack/webpack.js.org/pull/417) by mistake. Hope your review.
> Posible wrong link

- content/guides/code-splitting-libraries.md
> modules is not defined

- components/splash/splash.jsx
- components/support/support.jsx
and removed the buttons to avoid duplicate
> extended the number of sponsors and backers to show

- content/configuration/target.md
Proofreading and formatting of markdown
> Proofread target documentation

- content/index.md
This PR fixes issue number #355
It is blocked by https://github.com/antwarjs/antwar/pull/116
> Fixes #355, page titles

- content/guides/code-splitting.md
Removed repetitive explanation, reorganised content, improved grammar and general tone.
> Proofreading code splitting guide

- content/concepts/configuration.md
- content/configuration/index.md
- content/configuration/module.md
- content/configuration/target.md
- content/get-started/index.md
- content/get-started/why-webpack.md
- content/guides/author-libraries.md
- content/guides/code-splitting-require.md
- content/guides/hmr-react.md
- content/guides/shimming.md
- template.ejs
> Remove not needed type="text/javascript"

- content/guides/migrating.md
If https://github.com/webpack/webpack/pull/3374 gets merged, we can pull this in :)
> Add section on JSON support to migrating.md

- components/splash/splash-style.scss
From #471 
Recommended to use "Squash and Merge" to get rid of the merge commits in this PR.
> improve homepage styling (develop)

- content/configuration/output.md
Taken from [my post](http://tomasalabes.me/blog/_site/web-development/2016/04/30/Webpack-Series-Part-1.html) explaining this property among others. Suggested by Sean Larkin [tweet](https://twitter.com/TheLarkInn/status/790547583965863936).
Let me know what you think and what changes should we make to it.
: )
Replacement for PR #302 .
> Changes to output.libraryTarget

- content/configuration/devtool.md
> Adds a line about nosources

- content/guides/public-path.md
As requested by @TheLarkInn [here](https://github.com/rafaelrinaldi/til/issues/1), I'm adding some tips on how to take advantage of the `publicPath` feature. Hopefully users enjoy it!
Please, let me know if this is the proper place to add it. I can change if needed.
Thank you.
> Add docs about `publicPath`

- content/guides/hmr-react.md
Unless I'm mistaken, that's the new approach to use.
> Use the new config parameters

- content/concepts/loaders.md
> grammatical suggestion to loaders.md

- content/concepts/module-resolution.md
Changed 'comprising' to 'comprised' and added a space after 'Every' in second sentence under Unsafe caching.
> two slight typo corrections

- content/configuration/index.md
Add the bail config option to webpack config
> Document the bail option in webpack config

- content/guides/hmr-react.md
Without adding the index, the example doesn't work :)
> Add index.html to guide

- content/concepts/index.md
Added module.exports line to Loader Example
> Updated Concepts Index

- content/configuration/output.md
Changing name to library seems to work though
> This was giving me validation errors

- content/api/cli.md
- content/guides/dependency-management.md
I'm not a Webpack guru, so let me know if my change to the `require.context()` explanation is incorrect!
> Fix grammar issues and make require.context explanation more clear

- content/configuration/resolve.md
See [#3043](https://github.com/webpack/webpack/issues/3043#issuecomment-249314455) for reference.
> Fix note about default extensions

- content/concepts/plugins.md
I saw #563 which states that a link is broken
I pointed to a specifc commit message instead of the branch. Sorry for the PR snipe @kennyjacob, but it was quick and I was already forked and cloned repo this morning to check out the new site setup. 
see it live here http://typist-minimums-31187.netlify.com/concepts/plugins/
> Updates link to be commit specific

- content/guides/production-build.md
A simple approach to have Splitting configurations for the application and manage for different environments
> Update production-build.md - split configurations

- components/page/page.jsx
discussed here: https://github.com/webpack/webpack.js.org/issues/561
> Fixing the 'Edit this page' link

- components/sidebar-item/sidebar-item.jsx
> Fixed anchor url's

- content/guides/lazy-load-react.md
The anchor was wrong and didn't work.
> Fix HOC reference link

- content/concepts/module-resolution.md
Proofread concepts and revisited the "how resolution happens if a folder is specified" section to include information about `resolve.mainFields` and `resolve.mainFiles`
> Proofread module resolution

- content/guides/production-build.md
@bebraw,
The last pull got too clumsy. It was closed. Creating a new one. See if it looks good.
Thanks.
> Add contributor && update file titles

- CONTRIBUTING.md
CC @simon04, @skipjack. Please have a look.
Closes #587.
> Simplify contributing docs

- scripts/fetch_package_files.js
> fetch_package_files: adapt to new README styling

- content/guides/shimming.md
- content/plugins/provide-plugin.md
Loosely based on https://github.com/webpack/docs/wiki/list-of-plugins
> provide-plugin: add documentation

- README.md
> README: we develop in master branch

- content/get-started/index.md
Added text enhancements to help clarify steps for users (mainly those new to webpack).
PR is in reference to: https://github.com/webpack/webpack.js.org/issues/486
> Update: Getting Started Page - Small Clarification Text for Examples

- content/guides/webpack-and-typescript.md
This PR relates to issue #196 
This PR is based upon difficulties I experienced setting up a project with webpack 2 and typescript (mainly the non code imports).
Please note that english is not my native language so this may include grammar and various mistakes.
> Webpack and typescript guide

- README.md
- components/cc/cc-style.scss
- components/cc/cc.jsx
- components/footer/footer-style.scss
- components/footer/footer.jsx
- content/license.md
- package.json
> Attach license to the project

- content/api/node.md
- content/configuration/stats.md
The stats config does not have any effect in the Node.JS API
I added a warning on configuration/stats
And also mentioned it on the Node.JS API page
> Notice about stats config

- content/api/cli.md
Adds a brief section about the new CLI as well as the new option for the CLI.
> Add -save to CLI option and CLI section

- package.json
update gh-pages to fix yarn install errors
> update gh-pages to fix yarn install errors

- content/guides/production-build.md
See https://github.com/facebook/react/issues/7032
> Fix production string literal

- content/get-started/index.md
Unless I am wrongly interpreting the example code, the output should have no commas.
> fix small typo

- content/guides/lazy-load-react.md
Reverts webpack/webpack.js.org#641
> Revert "update(guides/lazy-load-react): fiber friendly side-effects"

- components/sidebar/sidebar.jsx
The next webpack release will be version 2.2
> Version 2.2

- content/guides/production-build.md
change ` loader: 'file'`
to `loader: 'file-loader'`
> fix in Building for Production docs

- content/plugins/commons-chunk-plugin.md
Feel free to help me clarify this. I really wanted to get the knowledge on paper to be refined.
> docs(CommonsChunkPlugin): Add minChunks fn usage

- styles/markdown.scss
> Increase line-height for headings

- content/configuration/entry-context.md
added short description for the entry and context configurations
> docs(Entry-Context): added short description

- content/concepts/hot-module-replacement.md
- content/concepts/modules.md
- content/concepts/output.md
- content/concepts/plugins.md
- content/concepts/targets.md
Adding handle to contrib tables and noticed a couple formatting shifts. 
Thanks to @chiplay who caught one of my mislabels on [concepts/output.md](concepts/output.md)!
As well as my sincerest apologies to any annoyances this may have caused @bebraw
> formatting fixes and adding handle to contrib table

- content/concepts/configuration.md
- content/concepts/entry-points.md
- content/concepts/output.md
- content/get-started/why-webpack.md
- content/guides/author-libraries.md
- content/guides/code-splitting-libraries.md
- content/guides/dependency-management.md
- content/guides/development-vagrant.md
- content/guides/lazy-load-react.md
- content/guides/migrating.md
- content/guides/production-build.md
- content/guides/public-path.md
small spelling and syntax changes.
> Spellcheck Updates For Concept and Guides Pages

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
This should help with CLAs etc.
> Add templates

- content/configuration/devtool.md
Updated the grammar on the DevTools page
> updated grammar

- content/concepts/loaders.md
> break the sentence to make it easier to read

- scripts/fetch.sh
- scripts/fetch_package_names.js
This adds the documentation of the following plugins (as of today):
compression-webpack-plugin, npm-install-webpack-plugin,
uglifyjs-webpack-plugin.
> Fetch also webpack-contrib plugins

- antwar.config.js
> Antwar: sort list of loaders/plugins

- content/guides/shimming.md
Small PR here.
P.S. I absolutely love Webpack, so I'd like to take this opportunity to thank all you superheroes from the bottom of my heart.
> Proofing + fixed small typo

- content/plugins/commons-chunk-plugin.md
> Add description to the CommonsChunkPlugin docs.

- CONTRIBUTING.md
Minor edits in the Contribution Recognition section of CONTRIBUTING.md for increased readability/clarity. I also fixed a typo where 
> PR's
becomes
> PRs
> Edited contribution recognition section of CONTRIBUTING.md

- content/concepts/index.md
- content/concepts/plugins.md
- content/concepts/targets.md
- content/get-started/index.md
- content/guides/author-libraries.md
- content/guides/code-splitting-css.md
- content/guides/code-splitting-libraries.md
- content/guides/code-splitting-require.md
> resolves #727

- content/get-started/index.md
> adding in tip for output for #578

- content/concepts/loaders.md
- content/loaders/index.md
* Start from the textual example, and add usage instructions (`npm install`, `webpack.config.js`).
* Sketch the different configuration options.
* Clarify loader resolution.
> concepts/loaders: improve, add code example

- content/configuration/entry-context.md
> Updated entry-context.md typo

- components/sidebar/sidebar.jsx
> adding in get started to Guides page for #743

- bootstrap.js
This will terminate deploy script etc. if the build process throws an error.
> fix - Fail hard if build fails

- content/concepts/output.md
- content/development/how-to-write-a-loader.md
- content/development/how-to-write-a-plugin.md
- content/guides/build-performance.md
fixes #732 as well as updating [content/development/how-to-write-a-plugin.md](content/development/how-to-write-a-plugin.md) to change `instanceable` to `instantiated`
> Addressing issue #732

- content/pluginsapi/index.md
Small typo fix, hander -> handler
> Fix typo in pluginsapi/index.md

- content/get-started/index.md
I hope I'm right but I think `@beta` is not needed anymore.
> no need for `@beta` anymore

- components/vote/app.jsx
1. Set title with a minor change in the return of the app.jsx in the Vote folder. 
2. Will submit styling in a separate PR.
Fixes #720
> Title for vote html

- content/get-started/index.md
> get-started: document ES6 modules with webpack

- content/guides/tree-shaking.md
> Add tree shaking guide

- content/plugins/banner-plugin.md
Based on https://github.com/webpack/docs/wiki/list-of-plugins/f6e4155c1befc4fb5e7763bf8953c8567869a1f6
> Add banner-plugin documentation

- content/guides/author-libraries.md
I did nothing more than adding a single space. Like, for formatting.
> Add missing space

- content/plugins/environment-plugin.md
> Clarify documentation of EnvironmentPlugin

- content/guides/production-build.md
> Correct reference of the `devtool` object

- content/guides/production-build.md
> Typo fixed on production-build

- components/vote/api.dev.js
- components/vote/api.js
- components/vote/app-style.scss
- components/vote/app.jsx
- components/vote/button/button.jsx
more options for the admin interface.
lock/unlock
archive/unarchive
edit title and description
> allow to configure vote item

- content/guides/build-performance.md
- content/guides/code-splitting-require.md
- content/guides/compatibility.md
- content/guides/development-third-party.md
This marks open TODOs very clearly.
> guides: add TODO markers

- content/configuration/index.md
- content/configuration/output.md
- update configuration index page with missing libraryTargets
- add documentation of missing libraryTargets to output documentation
- slightly adjust inconsistencies
- correct grammar in libraryTarget documentation
> Update targetLibrary documentation

- components/page/page-style.scss
- components/sidebar/sidebar-style.scss
- components/sidebar/sidebar.jsx
Using `position: fixed` to prevent lagginess caused on certain displays.
Before:
After:
> Updating the fixed sidebar behavior

- content/configuration/stats.md
> add `stats.colors` option

- content/guides/caching.md
> Consistent typesetting for loaders and plugins

- content/configuration/entry-context.md
- content/guides/caching.md
> merge from master

- content/guides/tree-shaking.md
> Typo fixes in tree-shaking.md

- content/plugins/define-plugin.md
Credits: http://tomasalabes.me/blog/_site/web-development/2017/01/03/Useful-Webpack-Define-Plugin-Usages.html
> define-plugin: document some use cases

- content/guides/production-build.md
> Fixed spelling error, repeated word

- content/configuration/target.md
Reflects https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L117
> Fix descriptions for electron target

- content/guides/hmr-react.md
Missing backtick for highlighting.
> Fix highlighting

- utilities/markdown.js
> markdown.js: remove unused variable

- components/notification-bar/notification-bar-style.scss
- components/notification-bar/notification-bar.jsx
- components/site/site.jsx
- components/splash/splash-style.scss
- components/splash/splash.jsx
This is intended to address #777. Added the bar as discussed there...
Mobile:
Desktop/laptop:
> Notification Bar

- content/configuration/index.md
Added module.exports for the code to be syntactically correct
> module.exports added

- content/configuration/index.md
Added more information for the `stats` section
> Added more stats information

- components/notification-bar/notification-bar.jsx
Link to the installation guide from the docs instead of npmjs.com
> notification-bar: link to install documentation

- content/development/how-to-write-a-loader.md
> Minor capitalization change

- content/configuration/output.md
I extracted the information from the linked souce files. Please review carefully!
Closes #490.
> output: document filename templates

- content/configuration/target.md
> Clarify atom/electron* targets

- content/guides/code-splitting-require.md
> code-splitting-require: formatting, link examples

- content/guides/code-splitting-require.md
I thought these changes could clarify the documentation. If any of my terminology is off, please let me know!
Closes #873.
> Suggested edits to require.ensure docs

- content/configuration/output.md
Information taken from
* https://github.com/webpack/webpack/blame/master/lib/Compilation.js
* https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js
> Document output.hash* configuration

- content/concepts/index.md
Use both var and const in same file feel like a mess.
> use const instead of var

- content/configuration/passing-a-config.md
Config can return a promise documentation added
> Config can return a promise

- content/guides/author-libraries.md
I recently faced an issue with updating one of my packages for webpack 2. So I believe that it should be clearly mentioned in the documentation.
> add important note about module usage

- content/guides/get-started.md
Added `var webpack = require("webpack");` to the example webpack.config.js
> Added var webpack = require("webpack");

- components/notification-bar/notification-bar-style.scss
- components/notification-bar/notification-bar.jsx
- components/site/site.jsx
- yarn.lock
This adds a little Call to Action for our apparel store and open collective page at the top. Will track with analytics to see conversion to our apparel store.
> feat(splash): add additional sponsorship info in banner

- content/guides/lazy-load-react.md
> babel-preset-2015 => babel-preset-es2015

- content/loaders/index.md
> Added link to sass-loader

- content/concepts/index.md
`but` definition: "used to introduce something contrasting with what has already been mentioned."
It doesn't seem to me the sentence "Webpack will yell at you when doing this incorrectly" is adversative of previous lines.
> Minor wording change

- content/configuration/plugins.md
Added link to plugin development guide on plugin configuration page.
> link to plugin development guide

- content/plugins/commons-chunk-plugin.md
This renames countOfHowManyTimesThisModuleIsUsedAcrossAllChunks to count in the example.
> docs(common chunks): fix count sample example

- content/configuration/index.md
> Add commas

- content/guides/get-started.md
This reverts commit 4d46128e551b2feb0866a4f8d18c4f4bb4364751.
See https://github.com/webpack/webpack.js.org/pull/915#issuecomment-281183640, https://github.com/webpack/webpack.js.org/pull/915#issuecomment-281193573
> Revert "Added var webpack = require("webpack");"

- components/vote/api.js
- components/vote/app.jsx
> Check result of vote API for errors

- content/concepts/index.md
Hello! These are just a couple of grammatical fixes I came across as I was reading your documentation. Please let me know if making these fixes is helpful to you, and I will continue to do so. Otherwise, I will stop!
> Make grammatical fixes to index.md

- components/notification-bar/notification-bar.jsx
> Fix typo in sponsor notification

- content/guides/production-build.md
> Update example code to webpack verion 2.

- content/configuration/module.md
> Make a note about symlink resources

- content/guides/tree-shaking.md
> Add new Weblink to a tree-shaking post

- content/configuration/devtool.md
Forgot to include it in PR #973
> Added missing contributor

- content/configuration/output.md
> Fix markdown syntax for hyperlinks; fix broken link.

- content/plugins/commons-chunk-plugin.md
> commons-chunk: "implicit chunks" vs "manifest"

- content/configuration/dev-server.md
adjust prior to previous pr - sort option name alphabetically
> update dev server doc

- content/guides/code-splitting-import.md
> add note about import() paths

- content/guides/code-splitting-css.md
Pretty self-explanatory, just removing an unnecessary comma.
> Remove unnecessary comma

- content/configuration/index.md
> Changed `var` to ES6 syntax `const` for path

- content/guides/migrating.md
> FIX a missing bracket in old documentation

- content/configuration/output.md
> Fix a few grammar/spelling errors.

- content/configuration/plugins.md
[4476](https://github.com/webpack/webpack/issues/4476)
> Update documentation to match the source code

- content/guides/hmr-react.md
Added a small note about configuring `babel-preset-env`
> Add note about `babel-preset-env`

- content/plugins/define-plugin.md
- content/plugins/index.md
alphabetized the plugin index list at [plugins](/plugins) and added `DefinePlugin to it
> adding define-plugin to list of plugins

- content/configuration/entry-context.md
https://github.com/webpack/webpack/issues/4456
> docs for dynamically entry

- content/configuration/externals.md
- content/plugins/environment-plugin.md
- content/plugins/index.md
- content/plugins/limit-chunk-count-plugin.md
adding environment-plugin info to plugin index with a snippet of what it does.
> adding environment-plugin to list of plugins

- content/plugins/index.md
- content/plugins/limit-chunk-count-plugin.md
This one I'm _very_ iffy on as I basically ported over webpack1 info on this over and hope it's the same. The code looks very similar in the commit history for the file within the last year or so but please take an extra second on this one as I'd really hate to mislead folks
> adding limit-chunk-count-plugin page

- content/plugins/index.md
> update index.md (remove duplicate)

- content/configuration/dev-server.md
- content/configuration/devtool.md
- content/configuration/externals.md
- content/configuration/other-options.md
- content/configuration/plugins.md
Hitting some of the outstanding configuration TODO's that were left hanging around. Added a call to action on the "Other Options" page to try to draw contributors who might be more familiar with some of the undocumented options there than I am.
> Configuration TODOs

- content/api/cli.md
- content/development/how-to-write-a-plugin.md
- content/guides/development.md
- content/guides/tree-shaking.md
just getting familiar with the docs to see what's been updated. Saw some `Webpack` that needed adjustment
> Webpack => webpack, nothing crazy.

- content/guides/comparison.md
Closes https://github.com/webpack/webpack.js.org/issues/1049
> Add rollup-watch, browserify watchify to comparison table

- content/guides/migrating.md
Refer to:
https://github.com/webpack/webpack/issues/1964#issuecomment-177661869
> "OccurenceOrderPlugin" has been renamed to "OccurrenceOrderPlugin"

- components/sponsors/sponsors-style.scss
- styles/partials/_vars.scss
> Hide Sponsors Bar on Smaller Screens

- content/guides/code-splitting-import.md
well, I forgot to add my name in my last contribution. Can I add it now, I would be grateful about it.
> add my name

- content/guides/code-splitting-import.md
Otherwise YAML fails to parse -> no page.
> fix: Replace non-breaking space with a regular one

- content/concepts/index.md
Explicitly state the four concepts early.
Stop referring to "we", it just adds clutter to the sentences and conveys no useful information.
> Make intro sentence more concise and useful.

- components/support/support.jsx
This displays also one-time sponsors, not only sponsors that donate regulary.
> Also display inactive sponsors and backers

- content/guides/hmr-react.md
Remove erroneous "/" in code snippet under Project Config.
> Update hmr-react.md: Remove erroneous "/" in code snippet.

- content/configuration/module.md
> Update module.md phrasing

- content/configuration/node.md
The Node configuration page was still basically a stub, so I fleshed it out.
> Significantly expanded the node options docs

- content/configuration/stats.md
document warningsFilter as introduced in https://github.com/webpack/webpack/pull/4381
> document warningsFilter 

- README.md
Add Translation part in Readme
> Add Translation part in Readme

- content/support/index.md
I started just fixing the outstanding "and" in "Donations are always welcome and Open Collective" and ended up cleaning the list of bullet points (make sure each point starts with a verb, etc.). It's all writing style so no offense taken if changes not accepted ;-)
Love this page btw!
> Update "How Can I Help?"

- content/guides/code-splitting-css.md
stumbled upon this as a webpack-newbie
> instructions to install css-loader in "Code Splitting - CSS"

- content/api/plugins/compilation.md
> Add a missed callback

- scripts/fetch_package_files.js
*    Keep introduction for fetched content
*    Rewrite loader/plugin links
> Improve fetching of loader/plugin READMEs

- content/concepts/index.md
When I first read this tutorial I didn't completely understand what webpack is, and the first section (Concepts) didn't clarify it. I think that's because of the laking of information about what a 'bundle' and 'dependencies' are. Later, in other sections, they were described and I got the whole idea.
Hope this helps :)
>  added extra info to first paragraph

- components/sidebar-item/sidebar-item.jsx
- utilities/markdown.js
Fix #1126 
Remove markdown syntax and link content from ID...
and title...
Also including some cleanup like moving all anchor parsing to a single function, so when the regex needs updating, we won't have to add it in two places.
> Resolve Anchor Issue

- content/plugins/environment-plugin.md
Inspired by https://github.com/webpack/docs/wiki/list-of-plugins#dotenvwebpack-
> Add DotenvPlugin documentation

- content/configuration/module.md
Some fixes to minor grammatical errors
> Fix minor typos

- content/api/node.md
- content/guides/hmr-react.md
- content/guides/migrating.md
Minor grammar and formatting fixes.
Includes fixes for:
#800 
#649
> Minor corrections

- content/guides/shimming.md
Add note to shimming guide about polyfilling node.
Fixes #153
cc @wearhere @jrvidal
> Shimming Node Functionality

- content/plugins/provide-plugin.md
Updated the content of the following PR
https://github.com/webpack/webpack/pull/3597
> Update ProvidePlugin usage

- content/configuration/index.md
> Fix typo in configuration/index.md

- content/guides/hmr-react.md
> Fixing clerical issue

- content/guides/asset-management.md
Added the basic scaffolding and introductory content for this guide. Still need to flesh out the rest of the content.
Resolves #615
> Asset Management

- components/gitter/gitter-style.scss
- components/sidebar/sidebar-style.scss
> Fix Scrolling Issues

- components/notification-bar/notification-bar.jsx
> Added link to new webpack stickers

- content/configuration/output.md
- content/guides/output-management.md
- content/plugins/dll-plugin.md
- package.json
- utilities/markdown.js
Fix `lint:links` script with a temp hack and patch some broken links.
Thanks @papandreou for the suggestion... hopefully this will do until Munter/hyperlink#117 is fixed in a more stable way.
> Fix Link Linting

- content/guides/asset-management.md
> Fix missing slash

- components/page/page.jsx
- components/sidebar/sidebar.jsx
- components/sponsors/sponsors.jsx
For some weird reasons the ad was invisible. This PR fixes it.
> fix(ad): make logo visible again

- components/splash/splash.jsx
- components/support/support-additional.json
- components/support/support.jsx
- scripts/fetch_supporters.js
show all sponsors, even one-time
update additional sponsors list
show donation amount
insert additional sponsors at correct location
provide fallback values
> Update sponsors list

- content/guides/webpack-and-typescript.md
Add "Enabling tree-shaking" section as discussed in #995.
Resolves #995.
> Add "Enabling tree-shaking" section

- content/api/module-methods.md
> fix some syntax errors in module-methods.md

- content/guides/production-build.md
`webpack --optimize-minimize --define process.env.NODE_ENV="'production'"`
update to
`webpack --optimize-minimize --define process.env.NODE_ENV="production"`
> fixed a typo

- content/configuration/node.md
> Clarify Available Options in `node` Configuration

- content/api/plugins/compiler.md
> Adding Example for emit event

- antwar.config.js
- content/guides/installation.md
Fix some minor issues related to #1273 
Resolves #1287
> Minor Fixes

- content/configuration/externals.md
> Minor typo

- content/configuration/resolve.md
Improve formatting and correct an issue in the `resolve.alias` docs.
Resolves #1282
> Correct Issue in Resolve Configuration Docs

- content/configuration/configuration-languages.md
Document the need to install dependencies in `configuration-languages.md`.
Resolves #1286
> Update Configuration Languages

- content/plugins/hot-module-replacement-plugin.md
Docs for https://github.com/webpack/webpack/pull/4907
> docs(hmr): add requestTimeout option

- content/concepts/output.md
Add [contenthash] since webpack 3.0.0
Docs for https://github.com/webpack/webpack/pull/4972
> docs(output): update sourceMapFilename

- content/configuration/module.md
Docs for https://github.com/webpack/webpack/pull/4992
> docs(config/module): add function option for noParse

- content/guides/getting-started.md
* Made the diffs line up better
* Small spelling mistakes fixed
* Edited minor wording
> Updated getting-started.md

- content/api/module-variables.md
> Correct typo

- content/configuration/configuration-languages.md
> docs(config): update config-languages and add a warning

- content/concepts/loaders.md
It just fixes a tiny typo error on loaders concept content.
> Fix a tiny typo

- content/api/node.md
- content/api/plugins/compiler.md
Elaborate on how one passes a custom file system and mention that this is do-able for the `inputFileSystem` as well.
Resolves #141
> Custom File Systems

- content/api/node.md
> docs(api): add note about `MultiStats` to prevent any confusion

- content/writers-guide.md
Resolve some minor linting and prism errors introduced by 76cd022100a.
> docs(writers-guide): resolve some minor issues caused by 76cd022100a

- content/guides/index.md
> docs(guides): add warning about varying output as discussed in #1356

- content/api/hot-module-replacement.md
> Fixes typo

- components/dropdown/dropdown.jsx
- content/comparison.md
fix(dropdown): convert all tabs to spaces
> Fix Build Issues

- content/guides/output-management.md
docs(guides): add diff part and src/index.html codes
> docs(guides): add diff part and src/index.html codes

- content/guides/hot-module-replacement.md
Sometimes, using language which says things are simple might be condescending towards beginners. 
HMR has been amazing for my productivity, but It took me a while to get it right the first time I tried to set it up 😄 
```diff
- Enabling this feature is actually fairly simple.
+ This feature is great for productivity
```
Thanks to @supreetpal for pointing this out.
> Improve language in HMR docs

- content/guides/code-splitting.md
- content/guides/environment-variables.md
- content/guides/migrating.md
- content/guides/typescript.md
Do some sorting, a little cleanup, and add a lead in paragraph to the `migrating.md` guide. Also added links to analyzers in `code-splitting.md`.
Resolves #1385  
Related #1425
> Minor Guides Work

- content/plugins/index.md
One of my changes in #1381 broke the table's formatting... this resolves that issue.
> docs(plugins): fix formatting on index page

- content/guides/development.md
Add missing const CleanWebpackPlugin in example code.
> fixes missing const CleanWebpackPlugin

- content/configuration/module.md
Adding some examples. 
Hopefully this saves some precious hours of somebody else's life.
> resourceQuery and oneOf examples

- content/guides/code-splitting.md
> Grammatical error fix on code-splitting.md

- content/configuration/output.md
- content/plugins/context-replacement-plugin.md
- yarn.lock
Fixes #1467
Fixes  Furthuer Reading Section in ContextReplacementPlugin (https://webpack.js.org/plugins/context-replacement-plugin/)
Update `yarn.lock`
> docs(conf,plugins) Fixes #1467 and Fixes Furthuer Reading in ContextReplacementPlugin

- content/guides/development.md
webpack.config.js is in the current folder, not parent folder
> Wrong path used in guide

- content/guides/code-splitting.md
Corrected link text to reflect current section heading text.
> Corrected link text

- content/guides/development.md
Corrected typo in the guide "Development"
> Corrected a typo

- content/guides/development.md
Changed highlight sections from bash/json to diff where required.
> docs(guides): Fixes highlight sections

- content/plugins/banner-plugin.md
- content/plugins/module-concatenation-plugin.md
Resolves #1318 
I'm also going to add a note to #1331 so that we note this in the _Production_ guide when we rewrite it.
> Add ModuleConcatenationPlugin

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- content/writers-guide.md
- scripts/check-links.js
This PR contains a few general updates:
- Update the README and CONTRIBUTING files to remove duplication and reflect current progress.
- Add CODE_OF_CONDUCT.md file (cc @TheLarkInn).
- Improve ISSUE_/PULL_REQUEST_ TEMPLATEs to encourage usage and deletion.
- Ignore `img.shields.io` links as they fail constantly due to timeouts and are not used frequently in the core documentation.
> General Updates

- content/configuration/index.md
- content/configuration/other-options.md
add `parallelism` option
https://github.com/webpack/webpack/pull/5502
> add `parallelism` option

- content/guides/caching.md
Correct this error in `output` configuration.
Fixes #1512
> docs(guides): contenthash => chunkhash in caching

- .github/PULL_REQUEST_TEMPLATE.md
> Fix link to writer’s guide

- content/configuration/dev-server.md
More details: https://github.com/webpack/webpack-dev-server/issues/1038
> Remove incorrect note on clientLogLevel

- content/development/release-process.md
> docs(development): add link to releases page

- src/content/plugins/context-replacement-plugin.md
Make some minor grammatical improvements and elaborate on certain
sections of this plugin's usage.
Related: #140
> docs(plugins): update context-replacement-plugin

- src/content/configuration/output.md
> Fixed spelling of "substitution"

- src/content/guides/typescript.md
Fix path to entry file to match project structure.
> Fix entry path to match project structure

- src/content/guides/production.md
> Fix typos in production.md.

- src/content/api/node.md
> add note about correct concurrent usage

- README.md
Updated typos in README.md file, signed CLA.
> Updated typos in README.md file.

- src/content/guides/caching.md
> I think here is native event, not react's one

- src/components/Support/Support.jsx
- src/components/Support/Support.scss
- src/components/Support/support-additional.js
- src/scripts/fetch_supporters.js
opencollective api changed again...
I also added a validation this time so build will fail instead of leaving an empty sponsors list.
> fix(sponsors): opencollective api changed, add validation

- src/content/plugins/commons-chunk-plugin.md
updated documentation for this pull request: https://github.com/webpack/webpack/pull/5764
> Add deepChildren to commons-chunk-plugin.md

- src/styles/markdown.scss
so part of long line will not be hidden outside paragraph (#1633)
> fix(style): add code line wrap

- src/content/guides/asset-management.md
Fix small typo excluding closing brace
> Fix small typo excluding closing brace

- src/content/guides/hot-module-replacement.md
Maintain consistent code from previous guide
> Maintain consistent code from previous guide

- src/content/guides/production.md
> Maintain consistent code

- src/content/configuration/dev-server.md
Add devServer.index Option to config documentation
See https://github.com/webpack/webpack-dev-server/blob/1af8f0e508e08b4e8f036311ae6c72b77f77600f/lib/optionsSchema.json#L318
> Add devServer.index

- src/content/api/node.md
> Add missing semicolon

- src/content/index.md
This will make it simpler to copy-paste and extend the init config
> lint code styling

- src/content/contribute/writing-a-loader.md
This pr attempts to...
- Clean up the grammar
- Better organize the document
- Elaborate on loading a local loader
- Add information on testing
Resolves #1240
> Update "Writing a Loader"

- src/content/guides/code-splitting.md
> A little tweak

- src/content/contribute/writing-a-loader.md
> docs(contribute): improve write-a-loader testing section

- src/content/api/loaders.md
- src/content/api/resolver.md
Minor tweaks in the _API_ section.
Resolves #1268
> API Tweaks

- src/content/configuration/resolve.md
Minor tweaks to the `resolve` page.
Resolves #1677
> Config Tweaks

- src/content/concepts/index.md
Attempt to make the Introduction a bit more beginner friendly by explaining concepts a little more.
Wait with a review until I give the heads-up ;)
Resolves #1416
> docs(concepts): beginner friendly introduction (WIP)

- src/content/api/cli.md
- src/content/guides/production.md
Reverts webpack/webpack.js.org#1686
> Revert "A new --concatenate-modules flag"

- src/content/configuration/dev-server.md
we should state the ability to open in specific browser
> update devserver open option guideline

- src/content/plugins/html-webpack-plugin.md
change output.path to an absolute path
> output.path must receive an absolute path

- src/content/concepts/index.md
Add "static" to "module bundler". Some feedback here was given to me on twitter to make sure we are clear with what these terms mean.
> Update concepts wording

- src/content/guides/build-performance.md
> Fix grammatical error

- src/content/api/index.md
> Remove inadvertent double verb

- src/content/contribute/writing-a-plugin.md
> Fix sentence

- .github/CONTRIBUTING.md
> docs(contributing): add note of debian OS

- src/content/guides/shimming.md
Add build output example over `TODO`.
> Update shimming doc with build output example

- src/content/contribute/writers-guide.md
In a section which states the properties must be sorted alphabetically, sort the examples alphabetically.
> Edit configuration properties section

- src/content/configuration/output.md
- src/content/guides/author-libraries.md
Add details on how `library` plays with the `entry` configuration. Make some recommendations for stylesheets and how to configure the `entry` option when building a library.
Resolves #1703
> Library Entry Points

- src/content/configuration/externals.md
> docs(config): improve formatting and clarify the string usage in externals

- src/content/guides/asset-management.md
- src/content/guides/production.md
Resolves #1741
@slurps-mad-rips feel free to submit a follow-up pr if you feel more is needed.
> docs(guides): highlight css splitting in production

- src/content/configuration/stats.md
https://github.com/webpack/webpack-dev-server/blob/master/lib/optionsSchema.json#L292-L298
> Omit invalid "detailed" option.

- src/components/Site/Site.jsx
This causes HTML to be really huge
reported by @lcxfs1991
> Remove unneeded file property

- src/content/configuration/output.md
make libraryTarget's Module-Definition-Systems part consistent with others parts.
and change the code to be the same as real code
> optimize libraryTarget part

- src/content/configuration/output.md
> Add docs for output.jsonpScriptType

- src/content/guides/getting-started.md
"As you may already know" may could discourage the reader.
> Don't make assumptions about what the reader knows

- src/content/configuration/output.md
Docs for feature pending this PR https://github.com/webpack/webpack/pull/6144
> document functions as valid output.filename type

- src/content/contribute/writing-a-plugin.md
> docs(contribute): fix typo

- src/content/guides/lazy-loading.md
Hi there,
In [this article](https://medium.com/@var_bin/angularjs-webpack-lazyload-bb7977f390dd), I’d like to show you how to realize lazyLoad modules for AngularJS app using Webpack, [UI-Router](https://ui-router.github.io/ng1/), and [ocLazyLoad](https://oclazyload.readme.io/). All behind-the-scene magic will be done with the help of ocLazyLoad tool. Last, but not least in the last part of the article I've shown how to use [Dynamic imports](https://github.com/tc39/proposal-dynamic-import).
P.S. Feedback is appreciated, it should be less than ~7 min reading.
Best regards,
Vitalii
> AngularJS + Webpack

- src/content/plugins/commons-chunk-plugin.md
> docs: update commons-chunk-plugin.md

- package-lock.json
- src/content/plugins/index.md
- src/scripts/fetch.sh
Remove archived repository component-webpack-plugin from the plugins page.
> remove component-webpack-plugin

- package-lock.json
- src/content/api/cli.md
- src/content/guides/asset-management.md
- src/content/guides/author-libraries.md
- src/content/guides/development-vagrant.md
- src/content/guides/getting-started.md
- src/content/guides/output-management.md
- src/content/guides/shimming.md
- src/content/index.md
- src/content/plugins/index.md
- src/scripts/fetch.sh
- src/utilities/markdown.js
Add missing config options to cli.md.  I executed a `webpack --help` and then copied the information into this md.  I wish this was automatic eh?
> Add missing config options to cli.md

- src/content/guides/development.md
> fixed line 62 spelling 'cosnole' -> 'console'

- src/content/api/stats.md
- src/content/configuration/stats.md
Doc updates for https://github.com/webpack/webpack/pull/6405
> Documentation update for output path in Stats object

- src/content/guides/tree-shaking.md
Fixed capitalization of plugin name.
> Update UglifyJsPlugin -> UglifyJSPlugin

- .gitignore
It was annoying always seeing these as `Untracked files` in `git status`
> misc(gitignore) Add .idea (IDE) and .DS_Store to .gi

- .alexrc
Added per suggestion from: https://github.com/webpack/webpack.js.org/pull/1978
> fix(site) Add kill word to .alex

- src/content/concepts/index.md
Elaborated on the output property and briefly described the path module and what it is used for.
> Updated the Output Property

- antwar.config.js
- src/content/api/parser.md
- src/content/api/plugins.md
- src/content/api/resolvers.md
- src/content/branding.md
- src/content/configuration/output.md
- src/content/guides/migrating.md
- src/content/plugins/source-map-dev-tool-plugin.md
- src/scripts/fetch_package_files.js
Yet more broken link fixes based on local hyperlink runs
> Fix broken links

- src/components/Navigation/Navigation.jsx
Fixes https://github.com/webpack/webpack.js.org/issues/2019
> fix(site) Missing second navigation

- antwar.config.js
- src/components/Support/Support.jsx
- webpack.config.js
- yarn.lock
- Added back `page-loader` to antwar config,.
- Remove `page-loader` it from webpack configuration.
- Remove Supports component conditional rendering on client.
Tested locally successfully after 10 mins.
We should put our efforts on `rebuild` branch, I am actively working on it, mean while we have to suffer these long builds.
> Partially revert #2026

- src/content/configuration/optimization.md
Start adding `optimize` section to the configuration
Tackles first four from #1968 
Suggest we merge this one with those few checkboxes tackled, so more people could contribute to the new page and finish #1968 quicker
> docs(optimization) Add optimization section to configuration docs

- src/content/concepts/modules.md
- src/content/guides/code-splitting.md
* mention prefetch and preload
* add simple examples
* add differences
* add link to source article
> content(modules) prefetch/preload in webpack

- src/content/configuration/optimization.md
I was late to the PR that added the page so I'm proposing some changes here. thanks @EugeneHlushko for adding it 😊
> fix: code correction and rephrasing on optimization page

- src/content/configuration/index.md
> mention defaults in config example

- src/content/plugins/split-chunks-plugin.md
Added a forward slash to complete the regular expression definition in Example 2.
> Add forward slash to the regex in Example 2

- src/content/guides/getting-started.md
Fixes #2094
Linked PRs (thx @montogeek ):
#2106
#2050
#2030
> docs(guides) Fix getting started output filename mismatch

- src/content/api/module-methods.md
> docs(module) document webpackInclude and webpackExclude otpions

- src/content/concepts/index.md
- src/content/index.md
* mention browser support (on the homepage or other place To be discussed)
Fixes #2000
> feature(homepage) mention browser support of webpack

- src/content/index.md
Fix broken indentation in the homepage example
> fix(homepage): fix code formatting in the example

- src/content/api/cli.md
- src/content/guides/installation.md
Mention `webpack-command`
Fixes #2157
> feat(cli) mention webpack-command

- src/content/guides/code-splitting.md
> Update code-splitting.md - Fixing grammar

- src/content/plugins/index.md
- webpack.config.js
Fixes #2185 
- adds redirect to removed plugin page (in case there are external links pointing that removed page)
- update the link which i missed during implementing #2112
> fix(redirect) Add a redirect to removed plugin page. Update link.

- src/content/configuration/index.md
I spotted this tweet this week https://mobile.twitter.com/AdamRackis/status/999293514637807619 and notice we don't mention the fact that user can switch to other config file via CLI on the configuration docs.
> feat: add cli config flag option

- src/content/plugins/split-chunks-plugin.md
Fixes #2122. Based on description given in [this comment](https://github.com/webpack/webpack.js.org/issues/2122#issuecomment-388609306)
CC @jeremenichelli
> updating reuseExistingChunk description

- src/content/loaders/index.md
Add Twig loader to the list of templating loaders
> Add Twig loader

- src/content/concepts/index.md
Current default output is main.js and not bundle.js
> Readme Update

- src/content/api/compiler-hooks.md
Depends on https://github.com/webpack/tapable/pull/63
> Tune the hooks description a bit

- src/content/configuration/index.md
Docs (config): clarify intro re: requiring a config file.
> Config index.md edit

- src/content/guides/getting-started.md
> By default it uses 'main.js' instead bundle.js

- src/components/NotificationBar/NotificationBar.jsx
- src/components/NotificationBar/NotificationBar.scss
- src/styles/index.scss
Notification bar won't close on production.
This PR fixes it in a React way.
> Fix Notification bar wont close

- src/content/concepts/output.md
> Combine duplicative sentences in output.md

- .github/CONTRIBUTING.md
- .gitignore
- .npmrc
> chore: add package-lock to gitignore, add note about yarn

- src/content/configuration/optimization.md
* document removeAvailableModules option
* add missing examples
Also takes one off from #1968
> docs(config) document removeAvailableModules option

- src/components/Navigation/Navigation.scss
Hello. PR #2274 introduced a regression, so that search input looks a bit different on Safari. This PR fixes it.
> fix(site) Fix search input appearance so it looks consistent 

- src/content/configuration/optimization.md
* document removeEmptyChunks and mergeDuplicateChunks optimizations
Takes two off #1968
> docs(config) document removeEmptyChunks and mergeDuplicateChunks

- src/content/configuration/optimization.md
* document flagIncludedChunks optimization option
Takes one off #1968
> docs(config) document flagIncludedChunks optimization option

- src/content/concepts/index.md
Module bundlers, and especially webpack (can) do a ton of stuff which would seem like magic to newcomers. I added a reference in the README to several resources that would contribute to the understanding of what webpack does under the hood and hopefully remove unbased fear and feeling of "magic".
I placed the links at the top because it seemed like the best fit. Let me know if it should be placed elsewhere.
> Concepts - Add "Bundling Fundamentals" resources

- src/content/plugins/banner-plugin.md
Should evidence the import of webpack on examples.
> Add better description to use BannerPlugin

- src/content/configuration/stats.md
Change default value for `source` stats option. Fixes #2354
> docs(config) Update stats source default

- src/scripts/fetch.sh
> infra(site) Fix sh unexpected token

- src/scripts/fetch.sh
Last time I forgot to add the `SOURCE_BRANCH` variable.
> infra(site) Fix fetch script

- package.json
> infra(site) Add cross-env to build script

- package.json
- src/content/guides/production.md
* Finish updating production guide to v4
* Small auto formatting in package.json
> Finish updating guides: production

- src/content/guides/csp.md
Changed the word _enable_ to _enabled_.
> fix(guides) Fix typo in CSP

- src/content/configuration/optimization.md
as per title
Takes one off #1968
> docs(config) document optimization.sideEffects

- src/content/concepts/mode.md
changing variable to property and grammar from
```according the ```
to
```according to the ```
> Minor grammar changes to the concepts mode readme

- src/content/plugins/banner-plugin.md
Close https://github.com/webpack/webpack/issues/7848
> Update doc for BannerPlugin

- src/content/configuration/output.md
Updated webpack `output.filename` docs
> update the output.filename docs

- src/content/configuration/optimization.md
> minimizer only accepts an array

- src/utilities/process-readme.js
We forgot to return :D
Fixes https://github.com/webpack/webpack.js.org/pull/2382/files#r210910668
> fix(infra) Add return to actually replace readme links

- src/content/guides/installation.md
> removing webpack-command

- src/content/concepts/loaders.md
sorry just a small thing but only just learnt how to add my name to the contribution that I made 2 weeks ago. hope thats ok to add it in here, if not no worries
> added name to the contribution

- src/content/configuration/optimization.md
* document `optimization.portableRecords`
* Fixes #1968 🎉 🎉 🎉
> docs(config) optimization portableRecords doc

- src/content/guides/code-splitting.md
Fixed some grammatical errors on the code-splitting page
> Simioluwatomi patch 1

- src/content/guides/installation.md
Fixes a typo in word `Pre-requisites`
> docs(installation): fix typo

- src/content/configuration/optimization.md
> docs(config) optimization moduleIds

- src/content/configuration/optimization.md
> docs(config) deterministic option for moduleIds

- src/content/contribute/writing-a-plugin.md
> fix(guides): Fixed example code typo

- src/content/plugins/provide-plugin.md
This is a simple fix for the typo in the description.
> Fix typo in description

- src/content/guides/caching.md
https://github.com/webpack/webpack.js.org/pull/2536
> Adding myself to contributor list as PR approved

- src/content/concepts/index.md
Contributed to the documentation 6 months ago but forgot to list myself as a contributor
> Added name to contributors

- src/content/configuration/module.md
- update some of the types
- use common formatting
- small updates
> docs(config) Update configuration module page

- src/content/configuration/output.md
> docs(config) output libraryExport updates, md formatting

- src/content/configuration/dev-server.md
- actualize parameters and types
- small text updates
- useful links added for quick nav
- related content linked
- updating formatting
- Fixes: #2610 
Useful for reviewing:
https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js
> docs(config) dev server guide updates

- src/content/configuration/configuration-languages.md
- Add link to DefinitelyTyped
- Add @types/webpack-dev-server
> doc(configuration): extend TypeScript

- src/content/guides/shimming.md
Add Link to useBuiltIns at Babel.
> Add Link to useBuiltIns at Babel

- src/content/api/cli.md
Fix broken table
Before: 
After:
> docs(api) fix cli table

- src/content/configuration/configuration-types.md
Add Link to CLI Config Options Section.
> Add Link to CLI Config Options Section

- src/content/concepts/entry-points.md
- add missing webpack config name
> docs(concepts) add missing code snippet filename

- src/content/loaders/index.md
Github: https://github.com/leecjson/ref-loader
> Add ref-loader to loader's introduction page

- src/content/plugins/limit-chunk-count-plugin.md
Update LimitChunkCountPlugin page
> docs(plugins) refactor LimitChunkCountPlugin page

- src/content/loaders/index.md
> ReSubmit: Add ref-loader to loader's introduction page

- src/content/concepts/why-webpack.md
A couple of small grammatical corrections.
> docs(concepts) Fix grammar in why-webpack.md

- src/content/configuration/entry-context.md
- src/content/plugins/define-plugin.md
I've used dynamic entries to collect entry points from external files and when I was implementing this, docs were not clear about some details (how dynamic entry works) and I was forced to dig webpack source code.
> Additional info about Dynamic entry

- src/content/guides/asset-management.md
> docs(guides) asset management bundle finalename

- src/content/guides/getting-started.md
> indent devDependencies

- src/content/configuration/module.md
correct regex for loader usage.
> correct the regex

- src/content/plugins/split-chunks-plugin.md
Added a period to the end of the first paragraph.  Didn't add myself to the contributors list because this particular change is formatting and insignificant, but can do that if it's required even for changes of this size.
> add period to end of first paragraph in SplitChunksPlugin article

- src/content/guides/progressive-web-application.md
- remove extra `up`
- align code
> docs(guides) format pwa guide

- src/content/plugins/ignore-plugin.md
> Update ignore plugin docs

- src/content/configuration/node.md
> fix(docs) Do not polyfill node bindings by default

- src/content/plugins/internal-plugins.md
> docs(plugins) fix NodeEnvironmentPlugin exposition

- src/content/plugins/split-chunks-plugin.md
> docs(plugins) splitChunks enforce doesnt make maxSize ignored anymore

- src/content/configuration/optimization.md
> docs(config) document optimization.chunkIds

- src/content/configuration/stats.md
Added information on setting stats colors using ANSI escape sequences.
> Added information on settings stats colors

- src/content/configuration/externals.md
- src/content/configuration/index.md
> docs(config) update externals function signature

- src/content/configuration/devtool.md
I replaced `is` with `it` because it made more sense.
> Fixed a single word

- src/content/configuration/dev-server.md
docs(devServer): add `writeToDisk` option
> docs(devServer): add `writeToDisk` option

- yarn.lock
- Fix yarn install on node v10+
> fix(misc) Fix yarn install on node v10+

- src/content/configuration/node.md
> docs(config) node.global is true by default again, small tidy up

- src/content/api/loaders.md
- src/content/configuration/watch.md
> docs(api) loaders inline matchRequest

- src/content/api/stats.md
Updating the sample stats file in response to #2745
> docs(stats): Set stats.assetsByChunkName[x] to arrays

- src/content/configuration/module.md
I discovered this earlier this week buried on a github comment somewhere, so wanted to add this into the docs.
I'm not massively happy with the wording here, there weren't any notes about how best to document function arguments or return values in the writing guide, so I figure I'd post this up as-is for feedback.
> Note that `Rule.use` and `UseEntry` can be functions

- src/content/configuration/plugins.md
- fix an old url
- update type and add example file name
- reword `list` to `array`
> docs(config) fix url and update format in plugins page

- src/content/api/stats.md
> docs(stats): fixed typo in analogous

- src/content/guides/shimming.md
> Fix footgun advice re loading polyfills

- src/content/concepts/entry-points.md
> docs(concepts): fix typo in `entry-points` part

- src/content/configuration/stats.md
In response to #2728 
It only takes one bit. So doesn't close the huge doc request issue itself.
> docs(config) stats preset extension and overrides

- src/content/configuration/optimization.md
- Documents new optimization option as per title
- Fixes #2792
> docs(config) document optimization.mangleExports option

- .travis.yml
- package.json
as per title, to cut build times
> infra(lint) make links check manual

- src/content/guides/getting-started.md
Missing comma for package.json in getting-started.md.
> Updating getting-started.md

- src/content/configuration/dev-server.md
webpack/webpack-dev-server#1508
webpack/webpack-dev-server#1630
> docs: add note

- src/components/Sidebar/Sidebar.scss
> fix(styles): don't let sidebar crossover footer

- src/index.jsx
- webpack.common.js
> site(vote) fix vote landing url

- src/content/concepts/index.md
Add hyphen to "concept specific".
> Fix grammar in index.md

- src/content/configuration/index.mdx
I have changed the URL to the webpack config tool so this PR reflects the new URL. I also added a better description.
> update URL to webpack configurator

- src/components/Sidebar/Sidebar.scss
Fixes #2858 
Demo -> [here](https://drive.google.com/file/d/1i1hGrZxvBkYY-LULQNcUg7q43Mre_-d_/view?usp=sharing) :movie_camera:
> Fixes the unscrollable sidebar

- .gitignore
Add links checker artifact to .gitignore
> infa(ignore) ignore links checker artifact

- src/content/guides/production.md
add correct reference for closure-webpack-plugin
> Add correct reference for closure-webpack-plugin

- src/content/configuration/other-options.md
> docs(config) add new possible value of amd option

- src/content/configuration/dev-server.md
Despite not being able to reproduce the claim from the Issue i was able to shape up the related section in this small pr.
- Fixes #2869
> docs(config) shape up devServer.open in response to issue 2869

- src/content/api/node.mdx
> docs(api) fix broken link and apply consistent formatting (sq in js)

- src/content/guides/scaffolding.md
As promised, a follow up to #2860
- fix formatting
- fix links, remove redundant
- reorder sections
> docs(guides) fix formatting, fix links, re-organize list

- src/components/Scaffolding/Scaffolding.jsx
- src/components/Scaffolding/Scaffolding.scss
- src/content/api/automation.md
- src/content/api/cli.md
- src/content/concepts/loaders.md
Attempts to fix css in https://github.com/webpack/webpack.js.org/pull/2718
> Fixed some css, click on card to open repo

- src/content/configuration/resolve.md
> Fixed anchor id

- src/content/configuration/resolve.md
I [was confused](https://github.com/webpack/webpack.js.org/issues/2899) about the behavior of resolve.extensions. This is my attempt to clarify the docs.
Please only accept this PR if you believe what I wrote is accurate.
EDIT: 
Fixes #2899
> Clarify behavior of resolve.extensions.

- src/content/api/loaders.md
Fixing link anchors on api loaders page
> docs(api) fix links on api loaders page

- src/content/guides/caching.md
Small grammar correction. Should be either "content has changed" or "contents have changed". 'Content has changed' sounds more appropriate.
> Grammar correction

- src/content/api/resolvers.md
> docs(api) fix up markup to not render sort attribute in the menu

- src/server.jsx
- Looking through reports it seems we can fix this trivial html markup error
- add DOCTYPE to our html
> markup(html) add missing required attribute lang

- repositories/loaders.json
- src/utilities/fetch-package-repos.js
> infa(fetch) add hide option to the fetch script, hide deprecated package

- package.json
- yarn.lock
> infra(wp) update webpack and lockfile for latest acorn

- src/content/plugins/dll-plugin.md
Update quotation for consistency reasons
> docs(plugins) dll plugin inline quotation

- src/components/Contributors/Contributors.scss
- src/components/Dropdown/Dropdown.scss
- src/components/Footer/Footer.scss
- src/components/Logo/Logo.scss
- src/components/Markdown/Markdown.scss
- src/components/Markdown/prism-theme.scss
- src/components/Navigation/Navigation.scss
- src/components/Navigation/Search.scss
- src/components/Organization/Organization.scss
- src/components/Placeholder/Placeholder.scss
- src/components/SidebarItem/SidebarItem.scss
- src/components/SidebarMobile/SidebarMobile.scss
- src/components/Splash/Splash.scss
- src/components/Support/Support.scss
- src/styles/fonts.scss
- src/styles/index.scss
- src/styles/partials/_functions.scss
- src/styles/partials/_mixins.scss
- src/styles/partials/_vars.scss
Makes the file name to align left 
Closes #2951 
_Desktop_
_Mobile_
> ui(homepage): improves text alignment

- src/components/Gitter/Gitter.scss
> fix unclickable links under gitter button container

- src/content/guides/caching.md
- src/content/guides/development.md
- src/content/guides/hot-module-replacement.md
- src/content/guides/production.md
- src/content/guides/progressive-web-application.md
> docs(plugins): add < v2 CleanWebpackPlugin caveat to guides

- src/content/contribute/writers-guide.md
Mention quotes in the contributor guide
> docs(contrib) Quotation in contributors guide

- src/content/glossary.md
> fix: minor formatting updates to glossary

- package.json
- src/components/Contributors/Contributors.jsx
- src/components/Support/Support.jsx
- src/index.jsx
- yarn.lock
> fix(safari) polyfill IntersectionObserver for safari

- src/content/guides/production.md
Following #2984 found another occurence
> docs(guides) update wp version as follow up to #2984

- src/components/SidebarMobile/SidebarMobile.scss
Sidebar in Mobile looks much better now. Just improved some padding and top.
> fix(ui): Reduced mobile sidebar padding

- src/content/concepts/loaders.mdx
- src/content/guides/production.md
Document inline import prefixing
Fixes #2966
> docs(loaders) document prefixing inline imports

- src/content/configuration/output.md
As per title and fixes #2991
References:
- https://github.com/webpack/webpack/releases/tag/v4.29.0
- https://github.com/webpack/webpack/pull/8642/files
> docs(config) document new temporary option for output

- src/content/configuration/resolve.md
> docs(resolve): Remove outdated '*' string comment

- src/utilities/find-files-in-dist.js
- webpack.prod.js
OG image wasn't known to SW as its emitted during SSG phase, this fixes it.
Currently og:image 404s
> fix(pwa) fix versioned assets from SSG run 404-ing via SW

- src/content/license.md
- src/content/vote.md
Added vote option in sidebar for mobile site
Closes #3020
> feat(sidebar): adds vote option in sidebar for mobile site

- src/components/Sidebar/Sidebar.jsx
Fixed import of scss in `Sidebar` component
> chore(import): minor fixing in import statement

- README.md
Improved URL macros in README.md
> chore(docs): improves URL macros in README.md

- src/styles/fonts.scss
Partially takes one off #1400
Will finish off when this is available: 
https://twitter.com/addyosmani/status/1126370518347608065
> feat(FOIT) add font-dispaly for our font

- src/styles/index.scss
fix foit using font-display now available also for google fonts
> feat(foit) use font display for google fonts

- README.md
Fixes writers-guide URL in README.md
Closes #3034
> fix(URL): invalid URL in README.md

- src/content/configuration/index.mdx
- fixed broken [link](https://webpack.js.org/concepts/mode)
> docs(config): fixed broken link

- src/content/api/node.mdx
- moved markdown to comment area.
> fix(docs) fix broken link on node.mdx

- src/assets/PWA/manifest.json
Update application name to be displayed on PWA to comply with branding guidelines of webpack
> fix: update name in manifest

- src/components/SidebarMobile/SidebarMobile.jsx
- src/components/SidebarMobile/SidebarMobile.scss
Added margin to improve UX and speeds navigation
Closes #3032 
**Current Behaviour**
**Proposed Changes**
> feat(sidebar): improves sidebar section layout

- src/content/configuration/stats.md
The contributor **renjithvk** has changed name to **renjithspace** 
Related to: #2003
> Update renjithspace nickname

- package.json
- repositories/plugins.json
- src/utilities/fetch-package-repos.js
- yarn.lock
The plugin at question is not maintained since2014, time to remove it from the docs
ref: https://github.com/webpack-contrib/component-webpack-plugin/commits/master
> docs(plugins) remove unmaintained outdated plugin

- src/content/guides/asset-management.md
I learn about this page, find this doc readable issue,
its better to read after add this sentence,
anyway, this is my first PR, if your guys had any standard issues about it, 
just feedback to me, thanks
> docs（GUIDES）（Asset Management）improved

- package.json
- sitemap-ignore.json
- Remove unwanted entries from sitemap and introduce a way to filter more entries in future.
- Fixes #3107
> fix(sitemap) remove unwanted pages from sitemap

- README.md
- Mention the work on webpack 5 milestone where contribution is really needed
- Remove outdated issue link
> contrib(readme) mention webpack 5 progress lag

- src/content/api/plugins.md
Remove's the last mention of the apply method.
Fixes #2300
> docs(api) remove mention of the apply method

- src/content/configuration/configuration-languages.md
This PR removes the reference to the tweet as it seems it was deleted.
> docs(configuration languages): remove reference to deleted tweet

- src/content/plugins/split-chunks-plugin.md
> allow filename as function for SplitChunks plugin

- src/content/plugins/split-chunks-plugin.md
> docs(plugins) SplitChunks plugin minRemainingSize option

- src/components/Markdown/Markdown.scss
- src/components/StarterKits/StarterKits.jsx
- src/components/StarterKits/StarterKitsTable.jsx
Improves starter kit layout -> https://webpack.js.org/starter-kits/
Visual Diff
https://github.com/webpack/webpack.js.org/pull/3146#issuecomment-506752218
> refactor(starter-kit): improves UX of starter kit and fixes layout

- src/content/api/module-methods.md
- src/content/guides/code-splitting.md
> docs(api) dynamic expressions in import()

- src/content/configuration/dev-server.md
Addresses https://github.com/webpack/webpack.js.org/issues/3168
> fix(site): correction on proxy config

- src/content/configuration/resolve.md
Closes #3170 
I decided to not remove the description of them just yet, it might be useful to keep for some time therefore PR is against `master` branch
> docs(config) warnings about configuration removal

- src/content/plugins/split-chunks-plugin.md
> docs(plugins) mention specifics of minRemainingSize option

- src/content/configuration/experiments.md
- src/content/configuration/other-options.md
- Add new page for experiments option
- Document experiments option
- Change sort for other options page to keep it the last in the list
Closes #3097
> docs(config) document configuration experiments option

- src/content/api/compilation-hooks.md
> docs(api) clarify record* hooks behaviour

- src/content/contribute/index.md
Scaffolds are like project starters that made on top of the scaffolding system provided by at webpack-cli. These scaffolds will also be supported by [webpack-ui](https://github.com/webpack-ui/webpack-ui) Currently, there are not so many scaffolds so this might help to get more scaffolds to npm.
- To get an idea of how scaffolds would be working (kind of PoC) [rishabh3112/webpack-ui](https://github.com/rishabh3112/webpack-ui)
- Add [webpack-scaffold-starter](https://github.com/rishabh3112/webpack-scaffold-starter) under `writing a scaffold` section (if it makes sense).
- Adding available webpack scaffolds under [Starter Kits](https://webpack.js.org/starter-kits/) section.
cc @evenstensberg
> docs: improve visibility of scaffolds

- src/content/configuration/output.md
> docs(config) output jsonpFunction clarified

- .github/CONTRIBUTING.md
> docs: grammar

- src/content/guides/getting-started.md
> dosc(guides) mention unstable node caveat in the guide

- src/content/guides/hot-module-replacement.md
> docs(guides) correct HMR guide

- src/content/plugins/extended-api-plugin.md
> docs(plugins): add ExtendedAPIPlugin doc

- src/content/contribute/writing-a-plugin.md
_the introduction of Async Series Bail is duplicate.now remove one of them._
> docs(writing-a-plugin.md): fix duplicate content

- src/content/api/compilation-object.md
Takes a bit off #3148 
Part of the methods dont have types and descriptions yet.
Reference: https://github.com/webpack/webpack/blob/master/lib/Compilation.js
> docs(api) document compilation object

- src/content/api/plugins.md
- src/content/configuration/other-options.md
- document plugin logger usage
- forgot to add myself as a contributor of other options... not fair, fixed.
Takes a bit off #3205
> docs(api) document plugins logger api usage

- src/content/configuration/output.md
- add `contenthash` to the table
- fixes #3209
> docs(config) improve documentation about [contenthash]

- src/content/api/compilation-hooks.md
- src/content/api/compilation-object.md
- src/content/api/compiler-hooks.md
- src/content/api/logging.md
- src/content/api/module-methods.md
- src/content/api/module-variables.md
- src/content/api/parser.md
- src/content/api/plugins.md
- src/content/api/resolvers.md
- Create a logger api page
- Correct order for pages
- Write an intro to the webpack logger
- Document logger methods
- Almost finishes off #3205 
CC @sokra
> docs(api) document logger api

- src/content/configuration/optimization.md
This is very minor but caught my eye when checking config pages
> docs(config) fix up inconsistency

- src/content/api/loaders.md
- As per title
- Takes one of last items in #3205
> docs(loaders) document loaders logging usage

- src/content/guides/development.md
Closes #3253 
- sync package.json files
- add missing deps in dev guide after installing dev server
> docs(guides) sync package.json files in guides

- package.json
Fixes https://github.com/montogeek/remark-extract-anchors/issues/2
> chore(site): Upgraded remark-extract-anchors

- src/content/guides/index.md
add a link to create an issue in the markdown file
> add: link to create new issue

- src/content/guides/dependency-management.md
updated the line to match the api docs
> updated require.context to use the correct default

- src/content/contribute/writing-a-plugin.md
The code shows an example of a JS `class` while in the description only suggests a JS `named function`, I know this sounds pedantic but for the sake of completeness I think it's good to list both options.
> [MDF] Creating a plugin steps.

- src/content/api/compilation-object.md
- document new methods on available on compilation object
- takes a bit off #3280
> docs(api) document new compilation methods for assets

- src/content/guides/asset-management.md
- src/content/guides/author-libraries.md
- src/content/guides/build-performance.md
- src/content/guides/caching.md
- src/content/guides/code-splitting.md
- src/content/guides/development-vagrant.md
- src/content/guides/development.md
- src/content/guides/entry-advanced.md
- src/content/guides/environment-variables.md
- src/content/guides/getting-started.md
- src/content/guides/hot-module-replacement.md
- src/content/guides/integrations.md
- src/content/guides/output-management.md
- src/content/guides/production.md
- src/content/guides/progressive-web-application.md
- src/content/guides/public-path.md
- src/content/guides/scaffolding.md
- src/content/guides/shimming.md
- src/content/guides/tree-shaking.md
- src/content/guides/typescript.md
guides: correct diffs to account for adding a comma before the last item when appending items to an object
> guides: add trailing commas to last items in js objects/arrays

- src/content/concepts/modules.md
- src/content/loaders/index.md
- mention elm in concepts
- mention elm loader in loaders
> docs(loaders) mention elm loader which is pretty popular

- src/content/guides/caching.md
Updated 3 broken links with hash routes that were not pointing on the right section of the page
> docs(caching) : Update broken links

- src/content/concepts/modules.md
- Remove webpack 1 note
- html -> HTML
- remove unnecessary parenthesis
> docs(concepts) Modules page actualization

- src/content/concepts/module-resolution.md
- change `main fields` to an actual field name to make sense
> docs(concepts) correct main fileds title in the text to make sense

- src/content/contribute/plugin-patterns.md
related issue: https://github.com/webpack/webpack/issues/9955
> fix code error

- .travis.yml
This makes sure that sponsors list is updated regularly
> chore(ci): page need to deploy on cron jobs

- src/content/api/stats.mdx
- src/content/configuration/optimization.md
- src/content/configuration/other-options.md
> docs(links) fix broken anchors after next branch merge into master

- src/content/api/stats.mdx
- src/content/configuration/output.md
Adds new output option and adds a warning. Closes #3341
> docs(config) document new output option, add warning

- src/content/configuration/resolve.md
> docs(config): fix incorrect example in `resolve.alias`

- src/content/configuration/module.mdx
Some info about custom JSON parser
Closes #3376
> docs(configuration): custom json parser

- src/content/guides/asset-management.md
Stumbled upon this, lets fix it
> docs(guides) fix up phrasing

- src/content/configuration/module.mdx
> docs(config): Updated word usage error

- src/content/plugins/dll-plugin.md
Handles : [2192](https://github.com/webpack/webpack.js.org/issues/2192)
> docs(plugin):Add entryOnly option in DllPlugin, also type

- src/content/configuration/other-options.md
> docs(config):remove cache.store option from documentation

- .github/CONTRIBUTING.md
> meta: minor grammatical fix

- src/content/plugins/split-chunks-plugin.md
> fix(plugins): Fixed typo

- src/content/configuration/experiments.md
- src/content/configuration/output.md
> Document new experiments option and finish off #3312

- src/content/configuration/module.mdx
A follow-up to improve doc added in #3377
> docs(config) module.rule.parse option grammar improved, formatting fix

- src/content/configuration/output.md
> docs(config) output formatting fix

- src/content/configuration/optimization.md
Small grammar fix as a follow up on #3384
> docs(config) optiomization moduleIds grammar

- src/content/plugins/dll-plugin.md
> docs(plugins) new dll plugin options markup fixed

- src/content/configuration/stats.md
A small follow up to #3362 https://github.com/webpack/webpack.js.org/pull/3362/files#r357783625
> docs(config) stats.orphanModules doc improved slightly

- src/content/migrate/5.md
Change pnp-resolver-plugin to pnp-webpack-plugin.
Fixes #3410
> Issues/3410 Fix plugin name

- src/content/api/module-methods.md
> docs(api) clarify module ID type and value origin, link related option

- src/content/configuration/stats.md
Extend the option documentation that was added in #3387
> docs(config) stats.preset option extended according to codebase

- src/content/plugins/split-chunks-plugin.md
> docs(plugins) split chunks automaticNamePrefix doc

- src/content/guides/scaffolding.md
After reading the scaffolding guide again i wanted to improve the readability of it
> docs(guides) scaffolding guide small rephrasing to improve readability

- src/content/plugins/split-chunks-plugin.md
- explain `[\\/]` in examples
- more info about what is available in `test` callback and how to get it
> Add more info on splitChunks.{cacheGroup}.test

- src/content/plugins/split-chunks-plugin.md
> docs(plugins) SplitChunks cacheGroup.test changes follow-up
